### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotFramework-Emulator#1]
I really liked the previous versions of emulator which used to auto update on start. Is it still the case or do I have to uninstall old and install new version?

**Comment by tomlm** [comment]
We love that feature too, which is why the new emulator auto updates as well. Enjoy!

**Comment by eanders-MS** [comment]
The update experience is a little bit different in the new emulator. It downloads the new version in the background and let's you know when it completes. It will update the next time you start the app.
