### ISSUE TITLE
Crash when reading a HeroCard

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotFramework-Emulator#10]
The following red text appears in the bot window when my bot returns a HeroCard ....

`[err-client] Uncaught TypeError: Cannot read property 'url' of undefined C:\Users\Alien\AppData\Local\botframework\app-3.5.18\resources\app\node_modules\@reactivex\rxjs\dist\cjs\Subscriber.js 227 13 {}`

Bot Framework Emulator version 3.5.18

Here is the response JSON that causes the error ...

```
{
  "type": "message",
  "from": {
    "id": "56800324",
    "name": "Bot1"
  },
  "conversation": {
    "id": "8a684db8",
    "name": "Conv1"
  },
  "recipient": {
    "id": "2c1c7fa3",
    "name": "User1"
  },
  "text": "Did you want to file an expense?",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "buttons": [
          {
            "type": "imBack",
            "value": "#!fileexpense",
            "title": "File an expense"
          }
        ],
        "images": []
      }
    }
  ],
  "channelData": {
    "common": {
      "inputType": "",
      "isLastInBatch": true,
      "displayText": false,
      "buttons": [
        {
          "type": "cmd",
          "value": "#!fileexpense",
          "title": "File an expense"
        }
      ],
      "images": [],
      "textMetaData": [],
      "followUpMessageMetaData": []
    },
    "custom": {
      "showSearchResults": true,
      "searchQuery": "file expense"
    }
  }
}
```

**Comment by eanders-MS** [comment]
@brendanarnold Thanks for reporting this. A fix has been made and will be available in version 3.5.20.

**Comment by eanders-MS** [comment]
Commit https://github.com/Microsoft/BotFramework-Emulator/commit/652af23b1624d3243d1864ab97892c0875bc7dfe

**Comment by eanders-MS** [comment]
Hi @brendanarnold, Release 3.5.20 is now available. Please let us know if it doesn't resolve this issue for you.

**Comment by brendanarnold** [comment]
Works great thanks!
