### ISSUE TITLE
XML message is broken in emulator

### ISSUE THREAD

**Issue by PiereDome** [Microsoft/BotFramework-Emulator#100]
I am unable to test my cards in the emulator as the xml is not parsed correctly. I get the following in the emulator, but it works in MSTeams.
![emulator xml issue](https://cloud.githubusercontent.com/assets/1903016/22789808/722cfac0-eea1-11e6-9a67-90cabbfb55f3.PNG)

and here is the code for that
`let ticketList = '<ul>';`
`tickets.forEach(function (ticket) {`
`    ticketList += '<li><b>' + ticket.id + '</b> - <b>' + ticket.company.name + ':</b> <small>' + ticket.summary + ' </small></li>'`
`});`
`ticketList += '</ul>';`
`var msg = new builder.Message(session)`
`    .textFormat(builder.TextFormat.xml)`
`    .text(ticketList);`
`session.send(msg);`

**Comment by eanders-MS** [comment]
@PiereDome The XML text format is a Skype-only format. While some of the other channels are also able to interpret XML formatting (MSTeams and Telegram, for example), many others cannot. 

https://docs.botframework.com/en-us/csharp/builder/sdkreference/activities.html#textformat

Have you tried using Markdown? It also supports unordered lists. 

Apologies for the inconvenience.

**Comment by PiereDome** [comment]
I have. I was just trying to build more than just lists, but that makes sense. Thanks for the quick reply
