### ISSUE TITLE
Clicking on name under Endpoint open new view rather than selecting existing view

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/BotFramework-Emulator#1004]
## Version
4.0.0-preview.40025

## Describe the bug
To the left of the UI is a Bot Explorer pane. In here is a section for Endpoints. Clicking on an endpoint opens a new view every time rather than selecting the corresponding view if it is already open. The net effect is that a large number of views (seen as tabs in the right hand pane.) Expected behavior would be to select an already open view.

## To Reproduce
Refer to the description. (Add an endpoint or open a bot file. Click on the endpoint name.)

## Expected behavior
Refer to the description. (Select an already open view - equivalent of clicking the corresponding tab.)

**Comment by mewa1024** [comment]
Agree. Let's change the behavior to this:
1 - click on endpoint
2 - if endpoint is not already open, open it.
     if endpoint is already open, select it.
3 - if an endpoint is already open and the user wants to open a new conversation with the same endpoint, they would use the right-click menu.
