### ISSUE TITLE
Cannot emulate a specific user and/or conversation

### ISSUE THREAD

**Issue by Raseru** [Microsoft/BotFramework-Emulator#101]
At the Microsoft emulator download page, it says you can "Emulate a specific user and/or conversation"

This newer emulator seems to have lost this feature.

**Comment by eanders-MS** [comment]
Thank you for bringing this up. You are correct, the new emulator does not yet support these features. The ability to switch between users in a group conversation is coming soon. The ability to switch between conversations is also planned.

**Comment by navzam** [comment]
Any update on this for the new emulator? In the previous version, I got around this by modifying `server.json` manually, but even that doesn't seem to work in the new version.

**Comment by tonyanziano** [comment]
Hi @navzam ,

We do have a work item tracking this #522 , but it is currently in our backlog and has not yet been assigned to a milestone, although that may change.

**Comment by vishwacsena** [comment]
dupe of #197
