### ISSUE TITLE
Azure login is not working

### ISSUE THREAD

**Issue by JeevaJose** [Microsoft/BotFramework-Emulator#1016]
Emulator version : 4.0.41423

Request Id: XXXXXXXXXX-41bf-a07d-XXXXX
Correlation Id: XXXXXXXXd4d0-xx-x-xxxxxxxxxxxx
Timestamp: 2018-10-23T16:18:02Z
Message: AADSTS50020: User account 'xxxxx' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application xxxx6b7f-xx-axxe-xxin that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
Advanced diagnostics: Disable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by justinwilaby** [comment]
Thank you for the submission. This is a known issue with AAD for accounts that are not part of the Microsoft tenant and we're working on a resolution.

**Comment by rcarmo** [comment]
Any idea on resolution time?

**Comment by justinwilaby** [comment]
Fixed by #1113
