### ISSUE TITLE
Change 'invisible' scrollbars to ones that appear on hover

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-Emulator#1019]
Currently the emulator intentionally has invisible scrollbars, which can create a sizing issue where the container of a scrolling section appears to have unexplained white-space on the right, where the invisible scrollbar is sitting.

For discussion: What if we instead implemented a more elegant solution where the scrollbar is invisible until a mouseover or scroll occurs over that part of the app? VS Code currently does this where any scrollbar is invisible until scrolling or mouse-over occurs, which then causes the scrollbar to appear (it is a lighter grey bar in the dark theme). 

The scrollbar also elegantly 'fades out' when mouse-over ends, over approximately 2 seconds.

VS Code example of non-hovered panel: 
![image](https://user-images.githubusercontent.com/14900841/47393429-48f18a00-d6d4-11e8-8fb8-4e791c4803ba.png)

VS Code example of the same panel on scroll/hover: 
![image](https://user-images.githubusercontent.com/14900841/47393444-53ac1f00-d6d4-11e8-9502-2d115f7f41b3.png)

[enhancement]

Tagging @mewa1024 as this is primarily a design enhancement. :)

**Comment by corinagum** [comment]
@mewa1024 I believe we are aiming for a temporary fix where scrollbars are **visible** when a panel or section have overflow. Can I use the specs for all three themes on these slides? https://microsoft-fuse-design.invisionapp.com/d/#/console/14907902/310024730/preview (The one linked, and the two previous slides for the other themes) 

Just temporarily I turned all the scrollbars magenta to show where there would be scrollbars:
![image](https://user-images.githubusercontent.com/14900841/47531761-5e48ee80-d863-11e8-986c-34b40f382375.png)

Unfortunately there would be some visual regressions that I'll need to address. (Inspector has two scrollbars for some reason). There are also horizontal scrollbars on the left - would you prefer for horizontal bars to be hidden?

is it okay if *all* scrollbars are now visible (which looks a little funky), or is it better to only apply styling to some scrollbars? If only some, could you let me know which ones? 

Other places that would have a visible scrollbar are: the certificates modal, the adding services modal, the welcome page. 

Thanks Melanie!

**Comment by mewa1024** [comment]
@corinagum Can we turn off the horizontal scrolling in the sidebar? The content is supposed to truncate, like this screenshot from VS Code:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/39317542/47539473-77629700-d885-11e8-9db8-55d67e5b0688.png">

sorry that wasn't included in the specs.

**Comment by mewa1024** [comment]
@corinagum oh but it's fine to show the other scrollbars (the ones that aren't in the sidebar).

**Comment by sgellock** [comment]
closing won't fix.  if customers raise the issue we can reconsider
