### ISSUE TITLE
Centos 7: About box no dismiss button

### ISSUE THREAD

**Issue by daveta** [Microsoft/BotFramework-Emulator#1029]
## Version
What version of the Emulator are you using.  4.0.0-preview-bugbash

## Describe the bug
Help->About gives a dialog, but there's no button to dismiss. (Escape dismisses)
<img width="867" alt="about-no-dismiss" src="https://user-images.githubusercontent.com/6182197/47523711-83cafd80-d84d-11e8-8bb6-6645eed82d31.PNG">

## To Reproduce
On Centos7, Help->About 

[bug]

**Comment by tonyanziano** [comment]
This is specific to the distro of Linux:

On Ubuntu:

![image](https://user-images.githubusercontent.com/3452012/47531692-3194d700-d863-11e8-91a5-460692da417f.png)

**Comment by tonyanziano** [comment]
Addressed in #1042. Can change text if necessary
