### ISSUE TITLE
Always got error from Bot emulator

### ISSUE THREAD

**Issue by andy51002000** [Microsoft/BotFramework-Emulator#103]
I built up a Hello World!Bot on my IIS server. 
But I always got error "Error: The bot's MSA appId or passsword is incorrect from bot emulator. " even if appId and passsword are right.

**Comment by eanders-MS** [comment]
Hi @andy51002000 Please make sure you're using an appId and password generated from the Microsoft Application Portal: https://apps.dev.microsoft.com/. It doesn't work with arbitrary values.

Take a look at this auth toubleshooting guide: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by andy51002000** [comment]
1.The ID & Password are both generated from MS. And bot's ID\Password  are same as Emulator's. 

2. I followed the troubleshooting guide and tested **"Step 1: Connect without a password on localhost".**
- Blanked out ID and Password in my Web.config
- Tested the Bot Emulator with empty ID and Password. 
- My bot url endpoint is correct and end with/api/messages
However, I still experienced  "Error: The bot's MSA appId or passsword is incorrect from bot emulator. "
![emulator](https://cloud.githubusercontent.com/assets/18550249/23086962/6fbaa0ce-f5ab-11e6-8257-41ac57da4295.png)
![web_config](https://cloud.githubusercontent.com/assets/18550249/23086969/77a913a6-f5ab-11e6-9be9-965313ca69f7.png)
![mybotweb](https://cloud.githubusercontent.com/assets/18550249/23086970/7bbb26a0-f5ab-11e6-902f-8cd385e90e72.png)

**Comment by andy51002000** [comment]
Hi @eanders-MS could you give some advise

**Comment by eanders-MS** [comment]
It seems your bot is still running with credentials specified. I wonder, do you have build-specific web.config translations? They would appear underneath web.config, and look like web.debug.config, web.release.config, etc. If so, do they contain MSA credentials.

**Comment by NOTPOWERUSER** [comment]
I don't have any build-specific web.config translations.
It's a pretty simple Hello World! Bot.
- I downloaded Bot template. 
- Compiled template with visual studio 2015.
- And then published to my windows server 2012.
- Launched emulator and saw error log  "Error: The bot's MSA appId or password is incorrect from bot emulator. "

And we found if published to windows 7, the emulator is work.

We prefer to use windows server 2012 as Bot service's host, if possible.
Please give me some advice.

**Comment by andy51002000** [comment]
I don't have any build-specific web.config translations.
It's a pretty simple Hello World! Bot.

I downloaded Bot template.
Compiled template with visual studio 2015.
And then published to my windows server 2012.
Launched emulator and saw error log "Error: The bot's MSA appId or password is incorrect from bot emulator. "
And we found if published to windows 7, the emulator is work.

We prefer to use windows server 2012 as Bot service's host, if possible.
Please give me some advice.

**Comment by danmarshall** [comment]
Hi @andy51002000 - can you try removing the app settings altogether instead of blanking them out? Just a thought...

**Comment by andy51002000** [comment]
Hi @danmarshall - I tried but it still doesn't work.

**Comment by eanders-MS** [comment]
Hi @andy51002000, Some users have been able to solve this kind of issue by updating their Bot Application Project template. See this issue: https://github.com/Microsoft/BotFramework-Emulator/issues/165

**Comment by eanders-MS** [comment]
Closing out this issue. @andy51002000, if you're still having a problem, drop a note here and we'll reopen the issue.

**Comment by ramicodes** [comment]
issue still persists.
