### ISSUE TITLE
Error occurs when I try to sign in with Azure

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotFramework-Emulator#1034]
## Version
4.0.42244

## Describe the bug
I tried signing in with Azure and encountered this error:

```
An error occurred
Microsoft IT
Microsoft Federation Gateway

You need to use appropriate certs from certificate dialog when prompted during authentication. Close your application and try again using virtual or physical smard card certificate. For troubleshooting or support, please contact Global Helpdesk(https://microsoft.sharepoint.com/sites/remote/SitePages/helpdeskPhone.aspx)

About Certificates


Ok - Physical smart card certificate. 
Ok - Virtual smart card certificate.
Do not choose this certificate.
Error details
Activity ID: a48c73a6-d7d6-4053-847f-936cd35e1590
Relying party: Microsoft Federation Gateway
Error time: Thu, 25 Oct 2018 20:04:38 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) BotFrameworkEmulator(V4PREVIEW)/4.0.42244 Chrome/61.0.3163.100 Electron/2.0.9 Safari/537.36
```

## To Reproduce
1. Open Bot Framework Emulator V4
2. Click on File > Sign in with Azure
3. Click on Sign in with Azure in the dialog box
4. Enter a microsoft.com email address and press Next
5. See error

## Screenshots
[![Screenshot][1]][1]

  [1]: https://i.stack.imgur.com/1yv3e.jpg

[bug]

**Comment by justinwilaby** [comment]
@v-kydela - Please try this again to see if the problem is fixed. Recent changes in AAD should have resolved this and a number of other AAD related issues.

**Comment by v-kydela** [comment]
It works like a charm! Shall we close this issue?
