### ISSUE TITLE
Emulator - Welcome screen is no longer centered

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1035]
## Version
4.0.0-preview-bugbash

## Describe the bug
"Welcome tab" is looks no longer vertically centered.

## Expected behavior
Should look more like this: 
[Screen on Invision](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15205961/316621301/preview)

## Screenshots
Looks too high up in the tab:
![screen shot 2018-10-25 at 12 18 50 pm](https://user-images.githubusercontent.com/39317542/47530699-3015df80-d860-11e8-87c7-ee8cb43727f4.png)

## Additional context

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1054
