### ISSUE TITLE
Emulator - Help drop down has "Search box" appearing off the left

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1036]
## Version
4.0.0-preview-bugbash

## Describe the bug
When you open the Help menu, sometimes the Search item appears way off to the left of the screen, covering over the taskbar. This a few times, but not consistently.

## Expected behavior
It should appear below the Help menu.

## Screenshots
This is what it did:
<img width="1680" alt="screen shot 2018-10-25 at 12 19 15 pm" src="https://user-images.githubusercontent.com/39317542/47530973-0315fc80-d861-11e8-8a9e-286fa207947e.png">

Then jumped into place later:
<img width="1680" alt="screen shot 2018-10-25 at 12 19 28 pm" src="https://user-images.githubusercontent.com/39317542/47530981-0ad5a100-d861-11e8-8f7c-d75cab5ae409.png">

It happened a few times.

[bug]

**Comment by sgellock** [comment]
this appears to only happen on first launch
