### ISSUE TITLE
Get rid of Gulp & Simplify v4 packaging process

### ISSUE THREAD

**Issue by tonyanziano** [Microsoft/BotFramework-Emulator#1037]
We don't need to use gulp anymore, and we can move to pure npm / node scripts. We should also try to simplify the packaging config for all platforms like in v3.

**Comment by compulim** [comment]
Do it! 💪

I think it's hard, but also think about using Webpack as little as possible. It is because Electron doesn't quite need bundling as web browser do, there are no network traffic. And it could make the app launch faster (less things to parse/interpret at boot time).

**Comment by tonyanziano** [comment]
- [x] Windows
- [x] Linux
- [ ] Mac

**Comment by tonyanziano** [comment]
Pushing Mac work to 4.3

**Comment by tonyanziano** [comment]
Addressed in #1200
