### ISSUE TITLE
Emulator - Azure sign in does not let me sign in under a new tenant

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1040]
## Version
4.0.0-preview

## Describe the bug
I signed in the Emulator with my Microsoft org id, signed out, then closed the Emulator. When I reopen the Emulator again and sign in as a different, non-Microsoft id, I get an error.

## To Reproduce
1. Sign in to Emulator with a Microsoft id.
2. Sign out.
3. Close Emulator.
4. Open Emulator and sign in with a different Azure account. See the error messages below.

## Screenshots
<img width="365" alt="image" src="https://user-images.githubusercontent.com/39317542/47538709-a119bf00-d881-11e8-8564-4ebd8188d248.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/39317542/47538715-af67db00-d881-11e8-8622-ccce9395bffe.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/39317542/47538720-b5f65280-d881-11e8-8e6d-2e48ef4be9c5.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/39317542/47538725-bc84ca00-d881-11e8-8981-bb712aa64803.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/39317542/47538746-d0c8c700-d881-11e8-9897-2f59122ec23f.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/39317542/47538847-3cab2f80-d882-11e8-8c6e-5fb9c999eb2e.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/39317542/47538771-e1793d00-d881-11e8-94a2-038a9c9be7f7.png">

[bug]

**Comment by brazierdavid** [comment]
The original report is a bit misleading, I don't think it is to do with signing out and the signing in with a different id.  I think the problem is that the emulator is somehow hard coded to authenticate microsoft.com ids against the Microsoft tenant/AD only, and doesn't work with personal ids.  When I try to log in with an outlook.com id (which is associated with Azure) I get the same error:
> Microsoft
> Sign in
> Sorry, but we’re having trouble signing you in.
> 
> AADSTS50020: User account 'xxx.yyy@outlook.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application '4f28e5eb-6b7f-49e6-ac0e-f992b622da57' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
> ©2018 Microsoft Terms of use Privacy & cookies 
> Request Id: ed68caaa-b337-45e2-ba32-efee14985f00
> Correlation Id: 29db409d-27be-4bed-93ce-afb9f798a131
> Timestamp: 2018-11-15T16:06:38Z

**Comment by brazierdavid** [comment]
Having looked at the code, I think the cause may be this application id in azureAuthWorkflowService.ts, line 40:
`const clientId = '4f28e5eb-6b7f-49e6-ac0e-f992b622da57';`
I presume that is registered on Microsoft's own AD and thus not available to users on a different AD (or personal LIve IDs etc).

**Comment by brazierdavid** [comment]
I registered a "Bot Emulator" app on my own AD, gave it the right redirect URI and Windows Azure Service Management API permission and changed the clientId in azureAuthWorkflowService.ts to the new app ID, and I could then log in.  So perhaps that clientId needs to be configurable in settings?

**Comment by rcarmo** [comment]
I'm getting this too - I can't actually use the emulator to log in to either my corp Azure subscription or my MSDN subscription because of it, which renders the services pane completely useless. 

Any idea on why this is this way and when it will get fixed?

**Comment by justinwilaby** [comment]
This should be resolved now. If you are still seeing an error, please reopen this issue or feel free to create a new one.
