### ISSUE TITLE
Emulator - can't Quit Emulator when signed in

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1043]
## Version
4.0.0-preview for Mac
(Did not test on Windows)

## Describe the bug
When I have signed in to Azure, quitting the Emulator (with cmd-Q, File > Quit, and using the OS taskbar) opens a modal that says "You have signed out of your account" but it does not quit the Emulator. Had to force quit.

**This seems to happen only when I'm automatically signed in--i.e., the sign in modal flow doesn't appear. Not sure why I'm sometimes signed in automatically because I haven't checked either the "Keep me signed in" checkbox at the end of the org sign in flow or Emulator's "Keep me signed into the Bot Framework Emulator" checkbox in the Emulator's "Success!" modal.**

## To Reproduce
1. Open the Emulator.
2. On Welcome tab, click on "Sign in with Azure." 
3. "Success!" modal appears. In the screenshots below, the sign in flow did not appear. It must have remember my sign in from earlier sessions.
4. File > Quit.
5. Modal appears that says "You have signed out of your account" .
6. Welcome screen shows that I am signed out (text has changed back to "Sign in with Azure."
7. Nothing else happens.
8. Go to taskbar, ctrl-click for context menu, select "Quit".
9. Modal appears that says "You have signed out of your account" .
10. Nothing else happens.
11. Try Cmd-Q.
12. Modal appears that says "You have signed out of your account" .
13. Nothing else happens.

## Expected behavior
The Emulator should quit (and log you out behind the scenes if you have not selected to stay logged.)

## Screenshots

Here's screens from the steps 1-10 above: 

<img width="1680" alt="screen shot 2018-10-26 at 9 30 52 am" src="https://user-images.githubusercontent.com/39317542/47580310-74a68700-d903-11e8-9635-30aed33425dd.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 30 57 am" src="https://user-images.githubusercontent.com/39317542/47580313-796b3b00-d903-11e8-97bf-5343cfca3ba1.png">

**Not sure why, but I'm signed in automatically here:**

<img width="1680" alt="screen shot 2018-10-26 at 9 31 06 am" src="https://user-images.githubusercontent.com/39317542/47580322-7ec88580-d903-11e8-890b-db8c6934ac11.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 32 38 am" src="https://user-images.githubusercontent.com/39317542/47580347-8be57480-d903-11e8-89b1-b32e638e6538.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 32 41 am" src="https://user-images.githubusercontent.com/39317542/47580355-90119200-d903-11e8-8fb9-72de7adf41c6.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 33 25 am" src="https://user-images.githubusercontent.com/39317542/47580384-9d2e8100-d903-11e8-8996-24f4c523590f.png">

<img width="1680" alt="screen shot 2018-10-26 at 9 33 27 am" src="https://user-images.githubusercontent.com/39317542/47580401-a7507f80-d903-11e8-96e3-937151bf6678.png">

And steps 11-13 (trying cmd-Q after waiting several minutes):
<img width="1680" alt="screen shot 2018-10-26 at 9 40 42 am" src="https://user-images.githubusercontent.com/39317542/47580425-b6cfc880-d903-11e8-833a-8878e76769f0.png">

[bug]

**Comment by justinwilaby** [comment]
@mewa1024 - are you closing the "You've signed out" window manually? If so, this will cause a problem since the emulator relies on events from that window to verify the sign out has completed. Closing this window manually will prevent those events from being received.
