### ISSUE TITLE
"Choose a different location" links are enabled even when a bot file is not open

### ISSUE THREAD

**Issue by cbtham** [Microsoft/BotFramework-Emulator#1048]
## Version
4.1.0

## Describe the bug
Clicking "choose a different location" does not open windows path picker

## To Reproduce
1. Click resource icon
2. Click on "chat files"
3. Click on "choose a different location"

## Expected behavior
Open a file path picker to select directory

## Screenshots
![image](https://user-images.githubusercontent.com/5702935/47644278-aa1fce80-dba8-11e8-8d88-a9bf1addf197.png)

[bug]

**Comment by justinwilaby** [comment]
The "Choose a different location" links should present a modal with current path info and an option to "browse" for a new location. Are you not seeing the modal with path info or are you not able to browse after the modal is presented?

![image](https://user-images.githubusercontent.com/2652885/47658915-153db680-db51-11e8-8f0e-5bb81a7404ac.png)

**Comment by justinwilaby** [comment]
@cbtham - A bot file must be open in order to change the resource locations since these locations are associated with a bot file. 

This defect should be "Choose a different location" links are enabled even when a bot file is not open
