### ISSUE TITLE
Unable to authenticate bot framework credentials in Emulator

### ISSUE THREAD

**Issue by jasonchuah4** [Microsoft/BotFramework-Emulator#1055]
Hi,

I have Microsoft AppId and Password assigned in web.config. When I started my bot project locally, and try to connect through Emulator, it would spawn this error message: `request to https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token failed, reason: write EPROTO 0:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:c:\projects\electron-39ng6\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:802:`

I've tried troubleshooting by referring to this page [https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0) and apparently I found out I need to use proxy address to access the authentication page. Does emulator have any parameters for me to add my company proxy address?

**Comment by vishwacsena** [comment]
We'll track support for proxy addresses via #1057
