### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Fed29** [Microsoft/BotFramework-Emulator#1057]
## Version

**OS**: Windows 10 version 1607

**Bot Framework Emulator**: v4.1.0

**Node**: v10.9.0

**node-fetch**: node-fetch@2.2.0

## Describe the bug
I work behind a company proxy and when I start a new conversation the BotFramework Emulator is not able to connect to the **login.microsoftonline.com API**, in order to obtain the access_token, as explained in [your documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#issue-an-http-request-to-the-microsoft-login-service).

Here is the error: 

**request to https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token failed, reason: connect ETIMEDOUT 104.45.0.24:443**

This is because the BotFramework Emulator ignore both the system proxy and the HTTP_PROXY env variable.

## To Reproduce
1. Being behind a proxy (you can use Fiddler on Windows which create a local proxy at http://localhost:8888 )
2. Setup the system proxy and ENV variables:
    HTTP_PROXY=http://localhost:8888
    HTTPS_PROXY=http://localhost:8888
    NO_PROXY=localhost,127.0.0.1
3. Open Bot Framework Emulator and connect to a bot inserting Url, AppID and AppPassword
4. Wait and you won't see the API call through the proxy (This means if you have internet access only passing through the proxy, the emulator cannot reach the URL and will receive the timeout error)

## Expected behavior
The expected behavior is that the Emulator use one of the following solution:
* **system's proxy configuration** (proxy, proxy ignore list, etc) 
* **env variables proxy's configuration** (HTTP_PROXY, HTTPS_PROXY, NO_PROXY) 
* **custom proxy's configuration** you can edit in the settings' pane

## Screenshots
![botframeworkemulator-error](https://user-images.githubusercontent.com/8274153/47725608-2376fa00-dc59-11e8-9cb0-019af5573973.jpg)

## Additional context

In previous versions this behaviour was not present.

I see in your code (https://github.com/Microsoft/BotFramework-Emulator/blob/master/packages/emulator/core/src/facility/botEndpoint.ts#L117) you are using **node-fetch** and this module support **http.agent** but by default it's null (https://github.com/bitinn/node-fetch#options).

### Reproduce error in node-fetch
Code to reproduce the behaviour outside of the Emulator context:

```
let tokenEndpoint = 'https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token'
let fetch = require("node-fetch")

let appId = "<your App ID>"
let appPwd = "<your App Password>"
let body = {
    "grant_type": 'client_credentials',
    "client_id": appId,
    "client_secret": appPwd,
    "scope": appId + '/.default'
}

fetch(tokenEndpoint, {
    method: 'POST',
    body: new url.URLSearchParams(body),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  })
  .then(res => res.json())
  .then(json => console.log(json))
  .catch(err => console.error(err));
```

Code to fix the behaviour outside of the Emulator context:

```
let tokenEndpoint = 'https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token'
let fetch= require("node-fetch")

let appId = "<your App ID>"
let appPwd = "<your App Password>"
let body = {
    "grant_type": 'client_credentials',
    "client_id": appId,
    "client_secret": appPwd,
    "scope": appId + '/.default'
}

let HttpsProxyAgent = require('https-proxy-agent');
var proxy = process.env.http_proxy
var agent = new HttpsProxyAgent(proxy);

fetch(tokenEndpoint, {
    method: 'POST',
    body: new url.URLSearchParams(body),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    agent: agent
  })
  .then(res => res.json())
  .then(json => console.log(json))
  .catch(err => console.error(err));
```

Related issues: 

* https://github.com/Microsoft/BotFramework-Emulator/issues/1055
* Discussion about ENV HTTP_PROXY support in node-fetch: https://github.com/bitinn/node-fetch/issues/195

[bug]

**Comment by justinwilaby** [comment]
@Fed29 - We are accepting contributions from the community! Please feel free to take a crack at this fix. I'm happy to help with this if you need it.

**Comment by compulim** [comment]
Also need to verify if ngrok works with HTTP/S proxy. If it don't, we need to give a warning in case the user set `HTTP_PROXY` env.

**Comment by justinwilaby** [comment]
This is the implementation I have planned:

**packages/app/maiin/src/main.ts**
```js
const fetch = require('node-fetch');
global.fetch = function (...args) {
    // No Proxy
    if (!process.env.HTTPS_PROXY) {
        return fetch(...args);
    }
    const [urlOrRequest, requestInit = {}, ...rest] = args;
    // URL is first param attach the proxy
    // to the RequestInit
    const HttpsProxyAgent = require('https-proxy-agent');
    const agent = new HttpsProxyAgent(process.env.HTTPS_PROXY);
    if (typeof urlOrRequest === 'string') {
        requestInit.agent = agent;
    } else {
        urlOrRequest.agent = agent;
    }
    return fetch(urlOrRequest, requestInit, ...rest);
};
```

Fetch is now available on the global object for node. This does not require passing around a custom fetch object nor does it require a ponyfill as a dependency in `core`.

**Comment by compulim** [comment]
I am not a fan of polluting the global namespace. But it will just do the trick for the first bullet point and not clamping down on "cross platform" support on Emulator Core. 👍

**Comment by compulim** [comment]
@justinwilaby did you check if `https-proxy-agent` will retrieve proxy settings from WININET? Proxy settings on Windows is not exposed via `HTTP_PROXY_AGENT` env.

**Comment by marcinwal** [comment]
I downloaded recent version and still have same problems while being behind company proxy, while it is fine for v3 still cannot connect on local host using emulator v4; I have two variables http_proxy and https_proxy defined in my environment; once  those are deleted emulator works fine but I do not have access to the external world..

**Comment by SvartAlfe** [comment]
I just tried the last version (4.4.1) this morning behind a proxy, and bypassing ngrok for local usage.
I can send a message from the emulator to the bot, but the bot cannot send this message back to the emulator.
Finally I ended up by using the version 4.09 alpha, which is working as expected and without special configuration.
