### ISSUE TITLE
unable to send attachments (Zip file or Image files) in bot framework emulators

### ISSUE THREAD

**Issue by virithareddy** [Microsoft/BotFramework-Emulator#106]
Hi all,

Please let me know, what is the C# code for how to attach  Images or Zip Files With Reply Message In Bot Framework and how user can download attached file from reply messages.

Thanks in advance.

**Comment by eanders-MS** [comment]
Hi @virithareddy, Have you had a chance to look over the documentation yet?
https://docs.botframework.com/en-us/core-concepts/attachments/
https://docs.botframework.com/en-us/csharp/builder/sdkreference/attachments.html
