### ISSUE TITLE
Add Telemetry Infrastructure to Emulator

### ISSUE THREAD

**Issue by tonyanziano** [Microsoft/BotFramework-Emulator#1083]
Add telemetry infrastructure to the emulator so that we can see what features of the emulator are being used and how often.

- [ ] language that explains what we're collecting and why
- [ ] opt-out instructions

**Comment by justinwilaby** [comment]
Will this be an opt-in feature?

**Comment by tonyanziano** [comment]
According to @vishwacsena 's spec it will be opt-in by default, and explicit opt-out. We are following the same strategy as az cli.

**Comment by vishwacsena** [comment]
Pushing out to 4.3. @sgellock; @yochay; @Kaiqb FYI.

We need to close on dev design and @tonyanziano will continue to flush that out with the AZ team through 4.2 for implementation in 4.3
