### ISSUE TITLE
[QnA Maker instrumentation] Include emulator scenario x version identifier in User-Agent header on all calls to QnA Maker APIs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#1087]
Is your feature request related to a problem? Please describe.
Today, we do not have any view into QnA Maker traffic that are driven by botbuilder. QnA Maker service instruments all calls to the service and can report on User-Agent to identify the specific client.

Describe the solution you'd like
On all calls to QnA Maker service (from the inspector including login, train, publish as well as reassign intent), include User-Agent header with the following value -
botbuilder/emulator/inspector/major.minor.patch.build
botbuilder/emulator/list-qnamaker-apps/major.minor.patch.build

[enhancement]

**Comment by tonyanziano** [comment]
Related to #1086

**Comment by tonyanziano** [comment]
Addressed in #1092 

===

There is no easy way for us to distinguish between calls made from the inspector, and calls made from the services flow without going into each call and adding on a custom user agent string, which would be tedious and fragile as the emulator grows. For now we will just add a custom user agent string of `botbuilder/emulator/version` to all outgoing requests.
