### ISSUE TITLE
Move Emulator Wiki pages to docs.microsoft.com

### ISSUE THREAD

**Issue by ovishesh** [microsoft/BotFramework-Emulator#1090]
**Is your feature request related to a problem? Please describe.**
Inconsistent docs experience for developers. There is already a doc on docs.microsoft.com that talks about [debugging with the Emulator](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0), but there is this new doc @JonathanFingold told me about that [lives on the Wiki pages](https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started). This new doc on Wiki pages is great but not easily discoverable.

**Describe the solution you'd like**
Keeping it consistent with the rest of the docs for Bot Service/Bot Framework, move all the emulator docs over to docs.microsoft.com with either a section for Emulator under "Debug" section or something similar. 

**Additional context**
See the discussion thread from this issue on [bot-docs](https://github.com/MicrosoftDocs/bot-docs/issues/531). Copying over the suggestions from that issue to here:

**Some suggestions on updating the content**

**Get up and running:**
- update the doc on the [instructions link ](https://github.com/Microsoft/BotFramework-Emulator/blob/master/README.md#download) with a better language such as "Download the Emulator for your platform from the GitHub releases page"

**Connecting to bot using a .bot file**
Bullet point 2, sub bullet 1 -> Make a _note_ about AAD/Corp credentials not supported at the moment (unless that is fixed already)

Lastly, foot notes should link people off to "Azure Bot Services" (which already exists) and also a link to deploying the bot (context being that they've tested their bot locally as explained in this doc)

**Comment by cwhitten** [comment]
@Kaiqb is this making it in 4.4?

**Comment by cwhitten** [comment]
ping @Kaiqb

**Comment by ivorb** [comment]
This will make it for 4.4

**Comment by ivorb** [comment]
Applicable content that was in the wiki is now in the emulator article within docs. Please close this issue.
