### ISSUE TITLE
Accessibility - Tabs: tabs are no longer close-able via keyboard input [Regression]

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-Emulator#1097]
## Version
latest master

## Describe the bug
When using keyboard focus to navigate through the app, pressing Enter when the 'close' button of a tab is in focus does not close the tab.

## To Reproduce
1. Open Emulator
2. Navigate to a tab (blue outline) via keyboard
3. Press tab to focus on the close button of the tab
4. Hit enter.
5. Note that tab did not close.

## Expected behavior
Tabs should close using keyboard input when the close button is in focus.

## Screenshots

![image](https://user-images.githubusercontent.com/14900841/48589590-09901500-e8f1-11e8-95df-933e3023713d.png)
Screenshot: example of keyboard focus being on a close button. Pressing enter at this point will not close the tab.

[bug]

**Comment by tonyanziano** [comment]
I can't repro this. My tabs close fine with enter. @justinwilaby maybe try to repro this as well?

**Comment by corinagum** [comment]
I'll try it again!

**Comment by corinagum** [comment]
can't repro anymore! closing.
