### ISSUE TITLE
Accessibility - Narrator on Tabs is confusing when reading two buttons at once

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-Emulator#1098]
## Version
latest master

## Describe the bug
When navigating through the app via NVDA (screen reader), the narrator says "Welcome close" when focusing on the Welcome tab. 

## To Reproduce
1. Open Emulator with NVDA running
2. Press tab until the Welcome tab is in focus (blue outline)
3. Notice that Narrator says "Welcome close"
4. Press tab again
5. Notice that Narrator doesn't say "Close" when the close button is in focus

## Expected behavior
Instead of saying "Welcome close", the narrator should say the tab name, "Welcome" when it is in focus, and "Close" when tab is pressed and the close button is in focus.

[bug]

**Comment by corinagum** [comment]
Comments from accessibility: 

o	[Jen] Maybe a P1/AccSelfYellow?  Sounds like a problem with a label or an aria attribute.
o	[Jason] This is a valid bug.  The problem here is that they’ve made the list item actionable and embedded a second actionable item within it. This is what shows up in the inspect.exe. The two need to be separated. The second tab to the close button reads nothing. 
How found:             Mouse move (2280,74)
hwnd=0x00000000000D0E5C 32bit class="Chrome_RenderWidgetHostHWND" style=0x56300000 ex=0x20
Name:                                        "🗋 Welcome Close "
ControlType:                             UIA_ButtonControlTypeId (0xC350)
LocalizedControlType:             "button"
BoundingRectangle:                  {l:2251 t:53 r:2368 b:85}
IsEnabled:                                 true
IsOffscreen:                              false
IsKeyboardFocusable:              true
HasKeyboardFocus:                 false
AccessKey:                               ""

**Comment by tonyanziano** [comment]
Addressed in #1131
