### ISSUE TITLE
[Question] CLI/ Programmatic use 

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotFramework-Emulator#110]
Hi - can you point me towards examples/tests that show how I can use the emulator programmatically? I want to be able to run functional tests against localhost without needing to set up directline and ngrok; the emulator seems to be the answer to that so long as I can manipulate it without a GUI.

Thanks!

**Comment by eanders-MS** [comment]
Hi @rposbo, the emulator does not support "headless" operation. I wish I had a better answer for you!
