### ISSUE TITLE
Need up to date channel inspector or channel capabilities matrix

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotFramework-Emulator#1102]
**Is your feature request related to a problem? Please describe.**
It's often difficult to decide what media to use in which channel. Buttons, cards, adaptive cards and carousels all have different levels of support/rendering depending on the channel. Right now, the only way to determine if/how media renders in a channel is to deploy a bot to that channel and see what happens. 

**Describe the solution you'd like**
I've heard discussion of a "channel inspector" that will show how different media renders in each channel. I could also imagine a channel capabilities matrix that at least gives a binary signal for the media supported on different channels. I've seen [this link](https://docs.botframework.com/en-us/channel-inspector/channels/Skype/) linked from old docs, but am not sure if it's up to date or currently referenced in any GA docs. 

**Describe alternatives you've considered**
The only alternate is to deploy a bot to a channel and see if it works, which adds friction to the dev process

[enhancement]

**Comment by justinwilaby** [comment]
This is on the radar for future releases.

**Comment by vishwacsena** [comment]
Tracked via #599
