### ISSUE TITLE
Emulator - update doc for connecting to Azure storage

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1111]
Update ["Write directly to storage" doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#using-blob-storage) to tell users where to find these fields (needed for msbot connect and the Emulator's manual connection modals).

Azure Storage (blob storage):
- friendly name (defaults to serviceName)
- Azure Tenant id (either GUID or xxx.onmicrosoft.com)
- Azure Subscription Id
- Azure resource group name
- Azure service name
- Blob storage connection string
- Blob container name

Azure Cosmos DB:
- friendly name (defaults to serviceName)
- Azure Tenant id (either GUID or xxx.onmicrosoft.com)
- Azure Subscription Id
- Azure resource group name
- Azure service name
- CosmosDB connection string
- CosmosDB database name
- CosmosDB collection name

Related to issue #934

**Comment by Kaiqb** [comment]
@mewa1024 - closing this issue because we will be using appsettings/env file.
