### ISSUE TITLE
Emulator - update doc for connecting to App Insights

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Emulator#1112]
Update ["Application Insights keys" doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-app-insights-keys?view=azure-bot-service-4.0) to tell users where to find these fields (needed for msbot connect and the Emulator's manual connection modals).

- friendly name (defaults to serviceName)
- Azure Tenant id (either GUID or xxx.onmicrosoft.com)
- Azure Subscription Id
- Azure resource group name
- Azure service name
- App Insights InstrumentationKey
- (OPTIONAL) App Insights Application Id

Related to issue #935

**Comment by Kaiqb** [comment]
Updated.
