### ISSUE TITLE
Emulator - Inspector pane should have a default message (never be blank)

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1127]
## Describe the bug
In user studies, participants did not understand that clicking on a log message would provide information about that activity in the Inspector pane. Design should supply a default message in the log pane to explain to users how to use it.

**Comment by mewa1024** [comment]
@cwhitten can we promote this to a P1 for 4.3?

**Comment by cwhitten** [comment]
Yes I think this makes sense to add for 4.3. Do you have any guidance on the messaging or additional UX consideration?

**Comment by mewa1024** [comment]
@cwhitten How about 

"Click on a log item in the panel below to inspect activity. 
[new line] You can also inspect the JSON responses from your LUIS and QnA Maker services by selecting a "trace" activity. Learn more."

"Learn more" will link to https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0 (I can set up an aka.ms link.) 

Yay/nay?

**Comment by mewa1024** [comment]
@cwhitten assigning back to you for triage.
