### ISSUE TITLE
ActivityTypes.ConversationUpdate

### ISSUE THREAD

**Issue by harshendra181** [Microsoft/BotFramework-Emulator#113]
ActivityTypes.ConversationUpdate   called 2 times so welcome message is comming twice

**Comment by eanders-MS** [comment]
When a bot joins a conversation via emulator, the emulator will send your bot two `ConversationUpdate` messages: one for the bot joining the conversation, the other for the user(s) present in the conversation. This change was made in preparation for group conversation support, where users can come and go during the lifetime of the conversation.

To filter your bot from the ConversationUpdate.MembersAdded list (C#):
```javascript
case ActivityTypes.ConversationUpdate:
    IConversationUpdateActivity update = activity;
    var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
    if (update.MembersAdded != null && update.MembersAdded.Any())
    {
        foreach (var newMember in update.MembersAdded)
        {
            if (newMember.Id != activity.Recipient.Id)
            {
                var reply = activity.CreateReply();
                reply.Text = $"Welcome {newMember.Name}!";
                await client.Conversations.ReplyToActivityAsync(reply);
            }
        }
    }
    break;
```
