### ISSUE TITLE
Download link opens Windows Store and fails to download

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotFramework-Emulator#1130]
_From @paulio on August 8, 2018 15:19_

Create an embedded text document launches the Windows Store rather than download the file
``` 
var contentType = "text/plain";
var attachment = new Attachment
{
    Name = "Transcript.txt",
    ContentUrl = $"data:{contentType};base64,{Convert.ToBase64String(bytes)}",
    ContentType = contentType
};
```

_Copied from original issue: Microsoft/BotFramework-Emulator#752_

**Comment by tonyanziano** [comment]
I was able to repro this on `master`:

![image](https://user-images.githubusercontent.com/3452012/52451887-b4316180-2af5-11e9-8126-7d4691781b28.png)

**Comment by tonyanziano** [comment]
Got a workaround for this working:

![image](https://user-images.githubusercontent.com/3452012/52672449-bec37080-2ed2-11e9-9c03-5153ef09e3a1.png)


The only issue is that the title of the download window is set to whatever the href is, which is the data url, so visually it doesn't look amazing.
