### ISSUE TITLE
Update Emulator to Web Chat v3 latest

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-Emulator#1132]
## Describe the bug
https://github.com/Microsoft/BotFramework-WebChat/pull/1385 has been merged into Web Chat, 
Update Emulator per Tony's notes on https://github.com/Microsoft/botbuilder-tools/issues/702

## To Reproduce
See https://github.com/Microsoft/botbuilder-tools/issues/702

## Expected behavior
Be able to show transcripts

## Additional context
Fix has been merged into Web Chat, so workaround needs to be removed in Emulator (& Web Chat package updated)

[bug]

**Comment by vishwacsena** [comment]
We need to verify these two paths work - 
1. Create a chat file, open it in emulator, verify that chat files render correctly as transcript in emulator
2. Use the latest chatdown tool (from botbuilder-tools/master) and generate a transcript file. Verify that the transcript file will render in emulator.

**Comment by vishwacsena** [comment]
verify if #1091 is fixed via the latest webchat v3.

**Comment by corinagum** [comment]
Sorry @vishwacsena, I got my bugs confused. https://github.com/Microsoft/botbuilder-tools/issues/702  should be fixed in the Web Chat bump, not 1091. @tonyanziano FYI
