### ISSUE TITLE
No voice input

### ISSUE THREAD

**Issue by GaebsterSoft** [Microsoft/BotFramework-Emulator#1135]
Hi verybody,

I use Bot Framework emulator V4. I generated a Bot on Azure (also V4) and donwloaded the source code for VS 2017. It I test my Bot in Azure in the built-in online test, I am able to interact with my bot over voice and test.

It start my downloaded Bot via Bot Framework Emulator V4.1 I am only able to interact with my bot over text. Why is there no mic-button?  I've heard the should be one.

Thanks for help

**Comment by compulim** [comment]
The speech feature in Emulator is currently in private preview. So the microphone will only show up for bots that are in flight.

On the other hand, speech feature in Web Chat is production and you will need to specify a speech token for it.

**Comment by compulim** [comment]
Bigger thinking: should we allow the user to put in their own speech subscription key in UI of the Emulator?

**Comment by GaebsterSoft** [comment]
Sorry, I don't understand. I want to use the Emulator for a presentation of my Skill in school. I don't want to publish it or assign it to a channel. How can I use Voice input inside the Emulator? Thank you

**Comment by corinagum** [comment]
Hi @GaebsterSoft sorry for the late reply! 
Right now speech is not supported on Emulator, but is available in v4 of Web Chat. We hope to have an Emulator update with Web Chat v4 very soon. Progress for updating Emulator to v4 can be tracked [here](https://github.com/Microsoft/BotFramework-Emulator/issues/1206). 

If you are interested in doing a presentation with Speech Services on a bot, and you don't mind using Web Chat, you can check out [this sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/06.c.cognitive-services-speech-services-js) on how to get set up. The downside to this workaround is that you would need a webpage hosting Web Chat, but our samples can also help you get set up. Please feel free to ping us on the [Web Chat repo](http://github.com/Microsoft/BotFramework-WebChat) if you have questions.

**Comment by leolorenzoluis** [comment]
> So the microphone will only show up for bots that are in flight.

@compulim What do you mean with bots that are in flight? With the latest pre release version, the microphone does not show up at all anymore.
