### ISSUE TITLE
request to https://127.0.0.1:44311/api/messages failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by himanshu143nith** [Microsoft/BotFramework-Emulator#1137]
Bot Framework Emulator v4.1.0
Bot Info: Bot Framework V4 BotBuilder .NET Core (SimpleBot)
Enabled SSL in Web Server Settings.
dotnet --version 2.1.500

**Comment by himanshu143nith** [comment]
Hi @jwiley84! Thanx for the reply. No, that is posted by someone else. However, the issue appears to be similar.

**Comment by jwiley84** [comment]
Can you post a screenshot of your emulator when this occurs, please?

**Comment by YashashGaurav** [comment]
I was facing the same issue. Thought it to be something related to the HTTPS request-response from the emulator and did the following that actually worked(well for the time being):

In VS2017, changed the project property(Debug) to not use SSL, and made sure I created a new .bot config for the HTTP endpoint created by IISExpress. Used that with the emulator, and it worked. Will think about HTTPS on the new emulator release. Hopefully it'll work.

**Comment by simra** [comment]
The underlying bug here is likely that the emulator can't connect to IIS Express on localhost using a self-signed SSL cert.  This is a regression from V3.  Cert validation is valuable but we need to be able to disable it for localhost connections.

**Comment by rvinothrajendran** [comment]
Use the App URL instead of SSL Url , find URL in VS -> Debug property window

**Comment by justinwilaby** [comment]
We are not likely to fix this since it may introduce security vulnerabilities and non-ssl alternatives exist. If you must run your bot locally using SSL, please consider using a free CA like https://letsencrypt.org/

**Comment by simra** [comment]
Sorry to comment on a closed issue but I wonder if you can describe the security risk.  Every major browser allows for localhost https connections using self-signed certificates.
