### ISSUE TITLE
More descriptive error messages than 'couldn't send' 

### ISSUE THREAD

**Issue by SarahSexton** [Microsoft/BotFramework-Emulator#1163]
When I use the Emulator, instead of the error message simply saying "couldn't send," it should be a lot more descriptive. Describe in more detail, such as, "Failed to establish a TCP IP connection. Did you remember to start your emulator?"

**Comment by SarahSexton** [comment]
I am referring to the former: the message under the failed message's chat bubble. "Couldn't send." Sorry for the ambiguity.

**Comment by tonyanziano** [comment]
No worries, I will move this over to the WebChat repository then because that UI is embedded in the WebChat control and out of the control of the Emulator.

**Comment by tonyanziano** [comment]
@compulim Tagging because this would need to be a Webchat change.

**Comment by justinwilaby** [comment]
Wouldn't the message in the log panel provide sufficient information about the error? The message under the chat bubble is not meant to be comprehensive and probably should not be due to the limited  screen real estate.

**Comment by cwhitten** [comment]
Hello!

This is going to be addressed in the Offline UI set of stories in the WebChat project [here](https://github.com/Microsoft/BotFramework-WebChat/issues/135)
