### ISSUE TITLE
Bot Emulator does not show error message when it fails to load .bot file

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotFramework-Emulator#1166]
## Version
4.2.0

## Describe the bug
If .bot file is not valid, emulator does nothing. No warnings/errors.

## To Reproduce
If the bot file has a missing comma or other errors, the emulator should show a message indicating that it couldn't load the file because the file was invalid. Instead, it just doesn't open the file.

## Expected behavior
Show an error message to the users so that they don't try to open the same file again and again.
[bug]

**Comment by justinwilaby** [comment]
The error messages for such occurrences are in the notifications pane. Look for a red notification count on the lower left of the emulator:
![image](https://user-images.githubusercontent.com/2652885/49902331-817e2c00-fe18-11e8-8f1a-4eb34d380608.png)

Clicking on the icon will open the notification pane and display the error:
![image](https://user-images.githubusercontent.com/2652885/49902369-98bd1980-fe18-11e8-819f-09c53e71b925.png)
