### ISSUE TITLE
"Migration complete!" popup strong html tags

### ISSUE THREAD

**Issue by artemious7** [Microsoft/BotFramework-Emulator#1167]
## Version
v4.2.0

## Describe the bug
I have just upgraded from Emulator v3 to v4.2.0 and "Migration complete!" window pops up. It says: 

    ... saved them as <strong>.bot files</strong>...

The "strong" tag isn't handled properly and gets displayed instead of applying <strong>strong</strong> formatting.

## To Reproduce
1. Migrate from v3 to v4 (I didn't check if this happens after clean install)
2. Open Emulator
3. See the "Migration complete!" pops up

## Expected behavior
Proper formatting of the &lt;strong&gt; html tag

## Screenshots
![image](https://user-images.githubusercontent.com/16724889/49938231-f2d5e180-fee1-11e8-9472-3a8f316cfe01.png)

## Additional context
none

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1173
