### ISSUE TITLE
Emulator fails to connect to QnA Maker services

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotFramework-Emulator#1168]
## Version
4.2.0

## Describe the bug
When I attempt to add an existing QnA Maker service via the emulator, it claims, "You have not signed up for a QnA Maker account under ${this.props.authenticatedUser}." Clicking the **Go to QnA Maker** button on the message does apparently nothing.

## To Reproduce
1. Create a QnA Maker KB.
1. Start a bot locally.
1. Open the bot in the Emulator.
1. Click the plus-sign next to services, and select **Add QnA Maker**.
   - Note that I logged into Azure earlier to add LUIS services, so that step is missing here.
1. Get a pop-up Message titled **Create a QnA Maker knowledge base** that claims I don't have an authenticated account (see screenshot below).
1. Click **Go to QnA Maker**.
1. Marvel as the message box goes away, but nothing else happens.

## Expected behavior
1. I was able to create a KB. I should be able to access it from the Emulator using the same account.
1. The  **Go to QnA Maker** button should do _something_.

## Screenshots
Here is the message box from the Emulator:

![qna-emulatorerror](https://user-images.githubusercontent.com/35047199/49958099-a6c57580-febe-11e8-8669-6d543eb4e878.png)

Note that there is a strange hiccup on the QnA Maker portal every time I open the site:

![qna-siteerror](https://user-images.githubusercontent.com/35047199/49958169-d8d6d780-febe-11e8-912d-7c8dc89a0a17.png)

[bug]

**Comment by justinwilaby** [comment]
Fixed
