### ISSUE TITLE
New Microsoft Bot with VS 2015 error 405 and 401 using simulator on localhost

### ISSUE THREAD

**Issue by fernandospaiva** [Microsoft/BotFramework-Emulator#117]
Hello, I'm using the latest Bot Application.zip template for VS 2015 to create a new empty Bot project. When I try to simulate on Microsoft Bot Framework Emulator v3.5.25, I'm getting this errors:

with http://localhost:3979
 - [23:40:09] -> POST 405 [conversationUpdate] 

with http://localhost:3979/api/messages
 - [23:40:41] -> POST 401 [conversationUpdate] 
 - [23:40:41] Error: The bot's MSA appId or passsword is incorrect. 
 - [23:40:41] Click here to edit your bot's MSA info. 

My appSettings is:

  <appSettings>
    
    <add key="BotId" value="YourBotId" />
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
  </appSettings>

Thanks

**Comment by eanders-MS** [comment]
This error indicates the your emulator's bot connection was configured with appId and password, but they were somehow invalid. In this case, I'd recommend running with no credentials (cleared from bot config and emulator) to ensure the simple case is working. Once that connection is established, try adding the appId and password back in.
