### ISSUE TITLE
When several "Live Chat" tabs are opened, attachment is uploaded to a wrong "Live Chat"

### ISSUE THREAD

**Issue by arieschwartzman** [Microsoft/BotFramework-Emulator#1195]
## Version
4.2.1

## Describe the bug
When using the Attachment Prompt and you have several "Live Chat" tabs are opened, attachment is uploaded to a wrong "Live Chat". Leaving only one "Live Chat" tabs works fine.

## Additional context

[bug]

**Comment by cwhitten** [comment]
Pending reproduction

**Comment by tonyanziano** [comment]
Was able to reproduce the issue. The attachment is sent to the first livechat opened.

**Comment by tonyanziano** [comment]
This was fixed with #1364
