### ISSUE TITLE
Include packaging scripts in repository

### ISSUE THREAD

**Issue by gareththackeray** [Microsoft/BotFramework-Emulator#120]
I've forked this repo and am making some small changes.  It would be really helpful for me to be able to package my changes into an Electron repo.  Could you include these scripts in this repository?

**Comment by eanders-MS** [comment]
Sure, this should be possible. We separated out the auto-updater from the main repo so that forked builds wouldn't try to auto-update to the mainline build, and the packaging scripts got swept up in that division.

**Comment by eanders-MS** [comment]
Package scripts are now in package.json. Build a redistributable using `npm run dist`.
