### ISSUE TITLE
Markdown not supported within a Card attachment

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotFramework-Emulator#122]
**OS**: Windows
**OS Version**: 10.15042.3
**Emulator Version**: 3.5.25
**SDK**: C# v3.5.5

The following response from a bot:
```
"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "[GeekTrainer](https://github.com/GeekTrainer)",
        "subtitle": "[Click to view](https://github.com/GeekTrainer)",
        "text": "[Click to view](https://github.com/GeekTrainer)",
        "images": [
          {
            "url": "https://avatars2.githubusercontent.com/u/6109729?v=3"
          }
        ]
      }
    }
```
results in the markdown-written `text`, `subtitle`, and `title` fields rendered as plain text in the emulator:
![like this](https://content.screencast.com/users/bc3tech/folders/Snagit/media/74485c44-45de-42a2-a61a-4ec1b3415e1f/03.15.2017-13.59.png)

The same is also true of HeroCard attachments:
```
"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "[GeekTrainer](https://github.com/GeekTrainer)",
        "subtitle": "[Click to view](https://github.com/GeekTrainer)",
        "text": "[Click to view](https://github.com/GeekTrainer)",
        "images": [
          {
            "url": "https://avatars2.githubusercontent.com/u/6109729?v=3"
          }
        ]
      }
    }
```
![like this](https://content.screencast.com/users/bc3tech/folders/Snagit/media/97d5c258-e674-410a-a522-c75b39513ed9/03.15.2017-14.00.png)

**Comment by eanders-MS** [comment]
Hi @brandonh-msft This sounds like an issue of the WebChat control itself. Could you open an issue for it there? (https://github.com/Microsoft/BotFramework-WebChat)
