### ISSUE TITLE
Emulator - Inspector pane should clear after Restart conversation.

### ISSUE THREAD

**Issue by dmvtech** [Microsoft/BotFramework-Emulator#1223]
**Describe the solution you'd like**
If one has previously selected an error in log pane that then shows in the Inspector pane, the error is kept after clicking the Restart conversation button. Expected that Inspector pane should clear/reset when conversation is reset. Optionally a setting to allow to clear or not on Restart conversation.

[enhancement]

**Comment by justinwilaby** [comment]
I would expect the inspector and log panes to normalize when a conversation is restarted. Tagging this as a bug and a possible regression.
