### ISSUE TITLE
[dev only] when webpack recompiles, extensions stop working

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Emulator#1229]
This only happens in the development environment, but is a poor developer experience.

There are some other improvements that can be made as well:
  - [x] Resume UI state after webpack recompiles
  - [ ] Be able to make changes to emulator core without rebuilding & restarting 
  - [ ] maybe more...

**Comment by tonyanziano** [comment]
Addressed by #1577
