### ISSUE TITLE
[Telemetry Compliance] First-time splash page / modal for Telemetry. Docs page as well.

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Emulator#1236]
We need a first-time splash page or modal telling the user about how our telemetry works and what we are collecting, as well as how to opt out of the data collection.

We also need a docs page that we can link to; the settings page will have the same link. Currently the link points to [https://aka.ms/bot-framework-emulator-data-collection]().

Here is what the app settings UI looks like:

![image](https://user-images.githubusercontent.com/3452012/51269343-1d9ad600-1977-11e9-8822-6c14fb5670cf.png)

**Comment by Kaiqb** [comment]
@tonyanziano - we don't need a docs.microsoft.com page. Per my discussion with Chris and Melanie, this can be a Help option that provides information on what is collected.

**Comment by tonyanziano** [comment]
@Kaiqb Ok I will get the updated design from Chris and / or Melanie.

**Comment by mewa1024** [comment]
@Kaiqb Were you thinking the "Learn more" link could instead be a sentence or two explaining what we're collecting and how? If so, can you provide that copy?

**Comment by tonyanziano** [comment]
Implementation is ready to go. Just waiting on official language from CELA.

**Comment by tonyanziano** [comment]
CELA gave an update that didn't provide concrete requirements for the modal. Melanie is responding, and hopefully we will get an update by tomorrow which will allow us to decide whether it's feasible for 4.3, or gets punted to 4.4.

**Comment by tonyanziano** [comment]
We should punt this to 4.4. It looks like CELA is going to require a more formal review process in which we fill out and submit a form declaring what we are collecting.

**Comment by tonyanziano** [comment]
Pushing to 4.5 to align with Telemetry & Security compliance work
