### ISSUE TITLE
Connect to a bot without a .bot file - revisions

### ISSUE THREAD

**Issue by cwhitten** [Microsoft/BotFramework-Emulator#1237]
In the Services pane, replace the `Open Bot` button with copy that says:

The Services caret is default _expanded_ and the content inside is the following:

>NO SERVICES AVAILABLE
>
>To connect the Emulator to services, [open a .bot file](www.example.com) or [create a new bot configuration](www.example.com).
>
>[Learn more about using services.](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0#build)

on click of `open a .bot file` - the system file browser opens with .bot files available for selection, and opens the .bot file when the user clicks the enabled `Choose file`

on click of `create a new bot` - the New bot modal opens with the url linked with the current active live chat tab populated in the `Endpoint URL` in the bot configuration form.

**Comment by justinwilaby** [comment]
Reopening after discovering use cases that may break this implementation.
