### ISSUE TITLE
Minimum requirements?

### ISSUE THREAD

**Issue by jusso-dev** [Microsoft/BotFramework-Emulator#124]
Hi,

Could someone please advise what the minimal requirements are for Bot Emulator? what i mean by this more specifically is, the minimal .NET version you can use to run the .EXE? i have tried using .NET 4.0 but it fails to execute with the attached error.
![image](https://cloud.githubusercontent.com/assets/16183422/23982228/33e51e2a-0a60-11e7-9a6c-52cf96afe9b8.png)

**Comment by eanders-MS** [comment]
Hi @jusso-dev I wonder if your version of Windows is 32 bit. We only support 64 bit Windows currently. It is on our roadmap to make a 32 bit build, but don't yet have a timeline for this.

**Comment by jusso-dev** [comment]
Hi, 

No the version is definitely 64 bit. I've tried windows 7, 10 and server 2012

**Comment by eanders-MS** [comment]
The Emulator uses [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) as its Windows installer, which is built in C# and requires at least .NET 4.5. Is it an option for you to update to .NET 4.5? Alternatively, you can clone this repo and build from source. .NET is only required by the installer.

**Comment by jusso-dev** [comment]
I imagine my work will one day (probably talking a year at least) upgrade beyond windows 7 and .NET 4

But that's good advice might just clone it and build it for .NET 4, thanks heaps for the advice

**Comment by eanders-MS** [comment]
Here are instructions to build and run locally: https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#build-and-run-from-source.

One point of detail: When building and running locally, there is no dependency on .NET. The installer needs .NET, but the app itself does not use it.

**Comment by jusso-dev** [comment]
Sorry just to clarify, it looks like the bot builder is written in typescript, how exactly would i build and compile this in visual studio? Or am I'm missing something ?

**Comment by eanders-MS** [comment]
We use [Visual Studio Code](https://code.visualstudio.com/) to develop the emulator.
