### ISSUE TITLE
User-Agent Header not added to LUIS/QnA Extensions

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotFramework-Emulator#1242]
## Version
4.2.1

## Describe the bug
No adding of the emulator info to the LUIS/QnA extensions

#1092 doesn't affect the extensions, just requests from the app.  

Original issue on LUIS telemetry: #1086 

[bug]

**Comment by justinwilaby** [comment]
LUIS and QnA extensions bot use the APIs defined in their respective botbuilder-tools dependencies. Custom emulator headers will require the removal of these dependencies and the reimplementation of the apis with custom headers.

**Comment by stevengum** [comment]
Turns out that Electron automatically tacks on `BotFrameworkEmulator/${version}` to all outgoing requests, so while #1092 doesn't touch the extensions, we still gather telemetry on the extensions. Closing this issue and filing issue #1248 to track the work per discussion with @tonyanziano.
