### ISSUE TITLE
Allow to specify SSL certificates

### ISSUE THREAD

**Issue by martinoss** [microsoft/BotFramework-Emulator#1246]
**Is your feature request related to a problem? Please describe.**
In our company, SSL traffic is being intercepted, also for tentant restriction reasons (https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions). The company's root certificate is installed in the clients Windows Trusted Root Certification Authorities.
I believe because for cross platform reasons, many newer Microsoft tools have it's own handling of trusting certificate chains. Now, in the Bot Framework Emulator I get this error:
`16:24:24]request to https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token failed, reason: self signed certificate in certificate chain`

**Describe the solution you'd like**
**Like in Microsoft Azure Storage Explorer**, it should be possible to import certificates to be trusted.

**Describe alternatives you've considered**
Rely on Windows certificate store or document a way to specify additional trusted certificates.

**Additional context**
![image](https://user-images.githubusercontent.com/2587942/51484654-677f2400-1d9c-11e9-9d35-844ca44d31fb.png)

**Comment by martinoss** [comment]
Current workaround for me is disabling TLS verification for node:

![image](https://user-images.githubusercontent.com/2587942/51524572-b5446c80-1e2e-11e9-813c-73bf3b9862b7.png)

**Comment by cwhitten** [comment]
Thank you @martinoss for the workaround. Closing this issue as we do not have plans to bring this functionality into the Emulator.
