### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by kbremner** [Microsoft/BotFramework-Emulator#125]
There's no tests currently for any of the code, is this planned?

**Comment by eanders-MS** [comment]
This is a problem right now. We're currently in the process of adding unit tests to the [WebChat project](https://github.com/Microsoft/BotFramework-WebChat). Emulator tests coming soon after.

**Comment by mgbennet** [comment]
We now have a testing framework for the emulator! Currently we're a little sparse on coverage, but we'll get more tests soon.
