### ISSUE TITLE
Emulator doesn't load .transcript files from explorer, or url links

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1257]
## Version
4.2.146766

## Describe the bug
If you have a transcript file and try to load it from the explorer or from a URL link or from the shell it does not load the transcript.

## To Reproduce
1. Go to folder with .transcript file
2. double click on it
3. Emulator loads with blank screen

Alternate paths that are broken as well.
**from cmd prompt**
```
start foo.transcript
```

**from url**
```
file://c:/scratch/foo.otranscript
```

## Expected behavior
To show transcript

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1269
