### ISSUE TITLE
Emulator not properly closing ngrok processes

### ISSUE THREAD

**Issue by MrLuje** [Microsoft/BotFramework-Emulator#1258]
## Version
4.2.1 on Windows10 1809

## Describe the bug
When I close the main window, ngrok processes become orphans and are lying around until I close them manually

I tend to keep my emulator opened for several hours, sometimes days without closing it.
I also reconnect ngrok tunnels when asked from the notification pane.

## To Reproduce
1. Open emulator
2. Enable ngrok
3. Leave it opened a few hours
4. Close the emulator
5. ngrok processes are still running

## Expected behavior
ngrok processes opened by emulator should close upon closing the main window

## Screenshots

![image](https://user-images.githubusercontent.com/632075/51851350-03bca400-2324-11e9-9523-42e852cc2667.png)

You can see from process explorer that ngrok process are not attached to emulator anymore.
![image](https://user-images.githubusercontent.com/632075/51851657-a2490500-2324-11e9-8a9c-a52e8894af47.png)

**Comment by cwhitten** [comment]
@justinwilaby will investigate if https://github.com/Microsoft/BotFramework-Emulator/pull/1291 fixes this.
