### ISSUE TITLE
Windows installer launches directly into emulator

### ISSUE THREAD

**Issue by dkisselev** [microsoft/BotFramework-Emulator#1259]
## Version
4.2.1

## Describe the bug
When installing the emulator on Windows, the installer shows the progress bar, then disappears and immediately launches the emulator.

This behavior is not typical for windows installers and disorienting as the new emulator window appears above anything else the user is working on.

Most installers show a final page with a "Finish" button and a checkbox (checked by default) to confirm whether the user wants to run the software right away.

## To Reproduce
1. Download and run BotFramework-Emulator-4.2.1-windows-setup.exe
2. Proceed through the first few prompts until the installer progress bar starts working
3. Change windows to any other open app (optional)
4. Observe that the installer closes itself without any warning and the emulator appears above all other work (stealing context).

## Expected behavior
When install progress is finished, the installer should stay in the background, show a final confirmation page that offers the option to open the emulator, and flash a taskbar notification to alert the user that it's finished.

[bug]

**Comment by tonyanziano** [comment]
We can try this out and see how it feels. It _should_ be as easy as flipping the `oneClick` property in the build config to `true`.

**Comment by dkisselev** [comment]
Just to be clear, 

I'm not trying to suggest whether or not showing the wizard is necessary (or if a silent/one-click install option would be better),

But if you want the installer to show a wizard, then the wizard should show a final confirmation page before it launches a new program that steals context.

**Comment by DesignPolice** [comment]
@tonyanziano sounds like fun... I will be back in the morning we can chat about this.

**Comment by tonyanziano** [comment]
@DesignPolice Sure, I can give you the expected dimensions of the graphics and show you what it's supposed to look like.

However, we should first test the auto update experience without a silent launcher to see what the behavior is like.

**Comment by DesignPolice** [comment]
digging through my # tags - @tonyanziano are we still tracking visuals for this? thanks m

**Comment by tonyanziano** [comment]
@DesignPolice this is on the backlog for now. If I get some cycles, I'll try out the auto update experience without a silent installer, and then we can go from there.

**Comment by DesignPolice** [comment]
@tonyanziano Happy New Year.. Chris tagged me on this, does that mean it is off backlog. hehe - I have some bandwidth

**Comment by tonyanziano** [comment]
@DesignPolice Happy New Year to you! I have yet to take a look at this because I still need to button up what I was working on before I left for the holidays. I'll get back to you.

**Comment by DesignPolice** [comment]
ok cool, I will be in the office tomorrow... if that helps
