### ISSUE TITLE
some screenshots are missing

### ISSUE THREAD

**Issue by fallanic** [Microsoft/BotFramework-Emulator#126]
Hi,

thanks for the good docs. 
Some screenshots are missing, making it a bit harder to go through them

https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started#connect-to-a-bot-hosted-remotely
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)

**Comment by eanders-MS** [comment]
Thank you for taking the time to report this. We're revamping our docs at the moment. This will be fixed in the new pages.
