### ISSUE TITLE
Add folder location for transcript files, the input field is not editable

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#1260]
## Version
4.2.146766

## Describe the bug
I can't type or paste into the folder path when editing transcript locations.

## To Reproduce
1. Go to files
2. Click on "Choose Location"
3. try to type or paste into the edit fields
**you can't edit them**

## Expected behavior
input boxes should support input.

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/51859515-2a5ee880-22ec-11e9-957a-f3d7ec6ee913.png)

[bug]

**Comment by cwhitten** [comment]
@mewa1024 we want to not make it look like this input field in tom's screenshot is editable. can you provide guidance on how we could adjust the UI to avoid this expectation? we could expand the browse click surface to include the input, avoiding the cursor behavior, or we could style it something other than an input box altogether?
