### ISSUE TITLE
Opening attached transcript results in empty native dialog

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1263]
## Version
4.2.146766

## Describe the bug
When opening the attached transcript file it displays empty popup dialog

## To Reproduce
1. Open attached transcript file .

## Expected behavior
To not have a dialog, and if there is a dialog, for it to have text.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/51860165-ca694180-22ed-11e9-8cdc-af9f881d612e.png)

[bug]

[BasicComponentDialogTest.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2804531/BasicComponentDialogTest.zip)

**Comment by tonyanziano** [comment]
Got a workaround for this working:

![image](https://user-images.githubusercontent.com/3452012/52672390-950a4980-2ed2-11e9-9c8c-f5c6de0b5a3b.png)


The only issue is that the title of the download window is set to whatever the href is, which is the data url, so visually it doesn't look amazing.

**Comment by tonyanziano** [comment]
Suggestions for fixing the window title welcome.

Basically the workaround is after intercepting the click inside of `hyperlinkHandler.ts`, if it is a data url, I programatically create an `<a>` element with the href set to the data url and the `download` attribute and issue a click on it.

I've tried messing with `target`, `id`, and `name` attributes to change the name of the download window,
