### ISSUE TITLE
Open bot from file is confusing. Default to enter endpoint or provide both options.

### ISSUE THREAD

**Issue by msolhab** [Microsoft/BotFramework-Emulator#1265]
Starting a new bot conversation using a bot file is confusing. Allow the user to enter the endpoint directly by default, or provide both options (using a bot file or entering an endpoint) from the Bot Emulator homepage.

**Comment by cwhitten** [comment]
hello @msolhab ! We have recently reintroduced this behavior and will be available soon. Stay tuned. 

For reference:

https://github.com/Microsoft/BotFramework-Emulator/issues/1209
https://github.com/Microsoft/BotFramework-Emulator/issues/1237

**Comment by msolhab** [comment]
Thanks for your response. A couple of observations on the current emulator interface:
1) Only way to start is using a .bot file. Cannot add an endpoint unless some .bot is opened first.
2) If you add more than one endpoint running simultaneously, testing in the emulator works but the original .bot file gets modified with the new endpoints info, which corrupts the original environment setting. This causes subsequent bot runs to fail due to mismatched environment names.

**Comment by cwhitten** [comment]
Hello @msolhab. Are you seeing this behavior when running the Emulator locally from source? We haven't yet published a version with the renewed ability to connect to a bot via a url, but you can use it today if you build from source and start up the services yourself. We plan to release a version of the app with these changes towards the end of February.
