### ISSUE TITLE
Debugging multiple bots 

### ISSUE THREAD

**Issue by lonche** [Microsoft/BotFramework-Emulator#127]
I want to use one instance for multiple bots. How to debug / set up this ? I didn't find any docs about ...
Edit : one more thing ... i see somewhere that video cards are available for node.js sdk. 
How to post video using c# sdk ?

**Comment by eanders-MS** [comment]
The emulator remembers previous bot endpoints. You can switch between them, though a new conversation will be started each time. Can you tell me more about what you're trying to do in regard to multiple bots?

In C#, to send a video, you can choose to add it to the outgoing message as a generic Attachment or as a VideoCard attachment. Check out this sample bot: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-RichCards

**Comment by lonche** [comment]
> The emulator remembers previous bot endpoints. You can switch between them, though a new conversation will be started each time. Can you tell me more about what you're trying to do in regard to multiple bots?


Some example ? What should update / set when conversation starts ?

**Comment by eanders-MS** [comment]
The example would simply be selecting one endpoint in the emluator's address bar dropdown (or typing in a new one), and then when you're ready to switch to another bot, click in the address bar, clear its contents to see the dropdown again, and select a different endpoint. Each time you change endpoints, you're switching to another bot.

When the conversation starts you'll receive an activity type of `ActivityTypes.ConversationUpdate`. This issue shows how to handle this activity type: https://github.com/Microsoft/BotFramework-Emulator/issues/113
