### ISSUE TITLE
Leftover Install of Preview 2 Version Breaks Launching a Bot File from Explorer

### ISSUE THREAD

**Issue by codefoster** [microsoft/BotFramework-Emulator#1270]
Likely a very low priority issue or non-issue considering few will install Preview 2 and then a newer version, but I wanted to get this here for the record. 

## Version
4 Preview 2 and 4.2.1

## Describe the bug
Needed to uninstall preview 2 version of emulator before 4.2.1 would work.4.2.1 was install with Emulator 4 Preview 2 already installed. Launching the .bot file prompted for a file association and I wasn't able (with limited effort) to find the Emulator executable. Uninstalling both versions and reinstalling 4.2.1 resolved the issue. Likely a non-issue considering it involves a preview version of Emulator.

## To Reproduce
1. Install 4 Preview 2
1. Install 4.2.1
1. Launch a .bot file

## Expected behavior
Bot to open in Emulator 4.2.1

## Additional context

[bug]

**Comment by tonyanziano** [comment]
Good to know. Thanks for reporting!

**Comment by tonyanziano** [comment]
Haven't had any future reports of this. It seems like the workaround is to uninstall all versions of the Emulator and reinstall with the current version. You can also try deleting the app's installation folder.
