### ISSUE TITLE
Adding a service via Bot Emulator should be more easy to discover

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/BotFramework-Emulator#1274]
In order to edit encrypted .bot configuration file Bot Emulator is a great place to modify .bot configuration file. This is a good alternative to msbot cli tool.

However this should be more easy to discover on Emulator. Maybe a UI tutorial at first run would be great.

![image](https://user-images.githubusercontent.com/118657/51944070-2508b780-242c-11e9-83c8-e263e91dd6f9.png)

**Comment by tonyanziano** [comment]
Assigning to @mewa1024 for design consideration.

**Comment by cwhitten** [comment]
hello @ikivanc - we hope our efforts to remove direct interaction with .bot files in our targeted `4.4` release will alleviate the pain you're experiencing. closing for now
