### ISSUE TITLE
Provide a Save command for the bot file configuration (don't save without asking)

### ISSUE THREAD

**Issue by pkirch** [Microsoft/BotFramework-Emulator#1277]
### Use this [query](https://github.com/Microsoft/botframework-emulator/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
My bot file settings were gone when I changed them in the Bot Framework Emulator.

**Describe the solution you'd like**
I changed the endpoint settings in the Bot Framework Emulator to test the same bot at another endpoint. I did not know that it would save it directly to my bot file and overwrite my previous settings.

**Describe alternatives you've considered**
When I change the settings in the Bot Framework Emulator I would like to have a save command to save my settings to the bot file. As long I have not explicitly saved my settings in the Bot Framework Emulator I do not want my bot file changed.

**Additional context**
I mean the settings page when I right-click the an endpoint (e.g. development or production) and click on "Edit configuration".

[enhancement]

**Comment by tonyanziano** [comment]
Hi @pkirch ,

This is intended behavior. When you select "Edit Configuration" for an endpoint, and change the configuration, it will save the updated version.

If you want to test a new endpoint configuration without modifying an existing one, then you want to hit the "+" button to add a new configuration. This will still modify your bot file by adding a new endpoint, but it will leave your old ones intact.

![image](https://user-images.githubusercontent.com/3452012/52065738-ff62d780-252b-11e9-9646-32a5e689bfa6.png)

![image](https://user-images.githubusercontent.com/3452012/52065755-08ec3f80-252c-11e9-9a30-3fbb39779920.png)

**Comment by tonyanziano** [comment]
Some further clarification: The emulator exposes a lot of the bot file configuration through the bot explorer pane via the Endpoint and Services collapsible regions. Anything you see in those fields is a direct representation of your bot file in real time. This means that any modifications you make to these fields will be reflected in your bot file on disk immediately.

There is no explicit save functionality because of this. You can always add a service / endpoint to test, and remove it if you no longer want it.

**Comment by pkirch** [comment]
I understand your intended behavior. IMO that's different to other applications I use like Visual Studio where you have to explicitly save settings even when they are made in a settings dialog. 

Maybe I can suggest that you rename the "Submit" button from the settings dialog into a "Save" button.

**Comment by navzam** [comment]
This is closely related to #1172. Even if it's by design for the emulator to edit your .bot files, that isn't clear. It's very easy to accidentally delete your endpoints/services.

**Comment by tonyanziano** [comment]
Adding @mewa1024 for design consideration.

**Comment by mewa1024** [comment]
Changing the button from "Submit" to "Save" makes sense to me.

**Comment by tonyanziano** [comment]
The text have been changed to 'Save' in #1296
