### ISSUE TITLE
.bot file completely rearranged simply by changing port number

### ISSUE THREAD

**Issue by jamestruitt** [Microsoft/BotFramework-Emulator#1278]
I checked out the repo containing the .bot file for a bot my team was working on. Cy simply changing the port number, the entire file was rearranged making a diff of changes nearly incomprehensible.

**Comment by stevkan** [comment]
Hi @jamestruitt, can you elaborate on what you mean by 'the entire file was rearranged'? Can you post a screenshot of the .bot file (blocking out any keys/secrets)?

**Comment by stevkan** [comment]
Closing due to lack of response. Please reopen if the problem persists and you need help.
