### ISSUE TITLE
Emulator - New bot config "Azure for Government" check box does nothing

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1281]
## Version
4.2.148187 Mac and Windows both

## Describe the bug
The checkbox has no explanation and is not checkable.

## To Reproduce
1. Open "New bot configuration modal" (File > New Bot Configuration or the link from the Welcome screen)
2. Try to select "Azure for US government"
3. Nothing happens.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/39317542/52139249-7370ae80-2604-11e9-8960-047e1a2ae1f7.png">

## Expected behavior
There should be some explanation of what this setting is and a link to learn more.
Use this link: https://aka.ms/bot-framework-emulator-azuregov

The checkbox should be checkable and uncheckable.

[bug]

**Comment by tonyanziano** [comment]
- [ ] Wire up checked state
- [ ] Add learn more link to docs

**Comment by mewa1024** [comment]
@cwhitten @tonyanziano I actually don't know what this checkbox is supposed to do or where it came from. Who would know? Jim?

**Comment by tonyanziano** [comment]
@mewa1024 and I spoke about the checkbox, and are reaching out to Jim for further information about bots in Azure gov so that we can maybe rework how we surface the option in the UI.

**Comment by sgellock** [comment]
@mewa1024 @tonyanziano JeffDers will know.  he added this

**Comment by mewa1024** [comment]
@tonyanziano added the Learn more link to the original description, but repeating it here: https://aka.ms/bot-framework-emulator-azuregov 

Any chance we can add this to the "Add configuration" modal as well? Looks like the checkbox there works, but the Learn More link would be useful. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39317542/52659255-c0c90780-2eb1-11e9-82c8-f406c5f127dc.png">

(unassigning myself.)
