### ISSUE TITLE
Emulator - UI actions can clear embedded WebChat messages from view

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#1285]
## Version
4.2.148187 Windows and Mac

## Describe the bug
Presentation mode clear previous messages from view.

## To Reproduce
1. Open bot.
2. Start typing in messages.
3. Click on "presentation mode" button (icon looks like a desktop screen)
4. Presentation mode appears without the messages that were already entered.

## Expected behavior
Presentation mode should show the same messages as non-presentation mode.

## Screenshots
![image](https://user-images.githubusercontent.com/39317542/52140944-0ca1c400-2609-11e9-93fb-5f01844e2796.png)

<img width="436" alt="image" src="https://user-images.githubusercontent.com/39317542/52140969-2511de80-2609-11e9-8519-9c5e8043978a.png">

[bug]

**Comment by tonyanziano** [comment]
This is fixed in @justinwilaby 's branch for #1394
