### ISSUE TITLE
endpointKey is populated with the subscriptionId value in .bot file using Azure login

### ISSUE THREAD

**Issue by stevkan** [Microsoft/BotFramework-Emulator#1286]
## Version
4.2.1

## Describe the bug
When adding QnA as a service via Azure login the endpointKey is populated with the subscriptionId value. Subsequently, the actual endpointKey key:value is not being stored in the .bot file.

## To Reproduce
1. Open your .bot file in Emulator
2. Select 'Add QnA Maker' under Services and login via Azure
3. Select a knowledge base and add it
4. Observe added JSON in .bot file

## Expected behavior
Both the endpointKey and subscriptionId keys should have the appropriate values

```js
{
  "type": "qna",
  "endpointKey": "subscriptionId",
  "hostname": "hostname",
  "id": "id",
  "kbId": "kbId",
  "name": "name"
}
```

[bug]

**Comment by a-b-r-o-w-n** [comment]
@stevkan I have not been able to reproduce this issue following the steps provided. The value I see for `endpointKey` corresponds to a key in my cognitive services azure resource.

**Comment by a-b-r-o-w-n** [comment]
@stevkan I see it now. I was unaware of the endpoint key on the QnA side. Let me dig into this a little more.
