### ISSUE TITLE
Error messages in webchat, emulator are unhelpful 

### ISSUE THREAD

**Issue by jackiebecker** [microsoft/BotFramework-Emulator#1288]
When using the emulator and webchat, sometimes my bot throws errors (resulting in HTTP 500 responses). However all I see in the chat is "failed to send - retry" which doesn't help me to debug what the problem might be--I have to go into Visual Studio & enable breaking on all 'Common Language Runtime Exceptions' to get to where the error is actually being thrown & see the message, which is not something everyone would know to do + is inconvenient. Having the bot output the actual content of error messages somehow would be immensely useful in the dev/test cycle.

**Comment by cwhitten** [comment]
@jackiebecker , we've recently introduced the Bot Inspector feature to give you more information as to what is going on in your bot runtime. 

https://github.com/microsoft/BotFramework-Emulator/blob/master/content/CHANNELS.md

We've also introduced more details error messaging when connecting to bots. For example: bad/missing authentication parameters.

I will close this issue for now. However, the BF Emulator will always be adding new features to help bot developers build and debug their bots.
