### ISSUE TITLE
QnA "Manage service" option brings you to the QnAMaker.ai homepage rather than the knowledge base

### ISSUE THREAD

**Issue by stevkan** [Microsoft/BotFramework-Emulator#1289]
## Version
4.2.1

## Describe the bug
On an added QnA service, if you right click and choose "Manage service" the link brings you to the QnAMaker.ai homepage rather than the knowledge base despite the link including the kbId. The current link directs the user to:
```
https://www.qnamaker.ai/?kbid=549...d761
```
but should point to
```
https://www.qnamaker.ai/Edit/KnowledgeBase?kbId=549...d761
```

## To Reproduce
1. Right click on an added QnA service and choose "Manage service"
2. Link opened in browser bring you to "https://www.qnamaker.ai/?kbid=549...d761"

## Expected behavior
Link opened in browser should bring you to "https://www.qnamaker.ai/Edit/KnowledgeBase?kbId=549...d761"

## Screenshots
![image](https://user-images.githubusercontent.com/18403946/52148399-6791e600-261e-11e9-83b9-c7fdaa988579.png)

[bug]

**Comment by a-b-r-o-w-n** [comment]
@stevkan thanks for the bug report. This seems to be a change in the QnA service which is redirecting `https://www.qnamaker.ai/Edit/KnowledgeBase?kbId=549...d761` to `https://www.qnamaker.ai/?kbid=549...d761`. We will work with their team to understand why and report back.
