### ISSUE TITLE
How to open multiple emulator in Windows?

### ISSUE THREAD

**Issue by ooclleeke** [Microsoft/BotFramework-Emulator#129]
I would like to open multiple emulator to test my Bot.  Is there any way to open multiple emulator?

**Comment by eanders-MS** [comment]
This is not possible right now. The reason for the limitation is our integration with ngrok. ngrok's free-tier service allows only one instance at a time running on the host machine. There are certainly cases where this feels too limiting. I think I could be convinced to change it :)

In the meantime, if you want this functionality, it's pretty simple to build and run from source. That way you can disable the check locally (and even submit a pull request?). The line of code containing the instance check is [here](https://github.com/Microsoft/BotFramework-Emulator/blob/master/src/server/main.ts#L145).

Instructions to build and run from source: https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#build-and-run-from-source

**Comment by ooclleeke** [comment]
I test my bot at localhost. So no need to use ngrok. Thanks.

**Comment by eanders-MS** [comment]
Fixed with build 3.4.26

**Comment by Tushti02** [comment]
[14:15:13] Checking for new version...
 [14:15:14] Failed to start ngrok: undefined
 [14:15:14] ngrok may already be running in a different process. ngrok's free tier allows only one instance at a time per host.

Hi,
 I am facing this issue while using Bot framework channel Emulator and ngrok tunneling software.
 I gave the proper path in App settings of emulator for ngrok.exe and had also launched emulator as administrator. But end up in above error.
 If anyone can help in this.

Thanks !

**Comment by eanders-MS** [comment]
Hi @Tushti02, as I mentioned in the other issue you raised #315, I believe there is a way of calling the ngrok API that would allow all instances of the emulator to share the same ngrok process. I've created a new issue for tracking this as a bug/feature request: #316. I don't have a timeline for when this work will start, or complete, but wanted to mention that it looks like there is a solution.
