### ISSUE TITLE
No auto scroll for new messages

### ISSUE THREAD

**Issue by lyzs90** [Microsoft/BotFramework-Emulator#13]
hey i love the new emulator. however, when i send or receive messages, the display does not scroll down to the latest one. not sure if this is the intended behavior?

**Comment by eanders-MS** [comment]
It is supposed to scroll. Can you provide the json of a message that isn't scrolling? There is one known scenario where it might not scroll:when there are images in a markdown-formatted message.

**Comment by lyzs90** [comment]
my bot will send out 3 consecutive messages:
- a text message
- a carousel
- another text message (wrapped in a setTimeout)

i tried every possible combination and autoscrolling only breaks when there are at least two messages and the one with setTimeout is one of them. there are images in my carousel but it doesnt seem to be an issue.

the code i'm running is:
```
intents.matches('someIntent', [
    (session, args) => {

        var task = builder.EntityRecognizer.findEntity(args.entities, 'someEntity');
        session.send(`Searching for... ${task.entity}`);

        // Code to dynamically build carousel based on task.entity
        session.send(carousel);

        setTimeout ( () => session.send("Some message"), 5000);
            session.beginDialog('/someDialog');
    }
]);
```

**Comment by eanders-MS** [comment]
@lyzs90 What version of the emulator are you running? I am not able to repro in 3.5.20.

Note that the intended behavior is that it will only autoscroll when you are scrolled down to the very bottom. If you've scrolled up to view previous messages, it will not autoscroll when new messages arrive.

**Comment by lyzs90** [comment]
@eanders-MS i'm on 3.5.20. uploaded a short clip [here](http://recordit.co/k7b1GhnycO) for reference

**Comment by eanders-MS** [comment]
@lyzs90 Are you willing to create a simple repro bot? If not, perhaps allow me access to your bot for debugging?

**Comment by lyzs90** [comment]
Sure, here is a minimal example:
[TestCase.zip](https://github.com/Microsoft/BotFramework-Emulator/files/603551/TestCase.zip)

**Comment by eanders-MS** [comment]
@lyzs90 I'm unable to reproduce the issue with your test case (but thank you for providing one). Here's a clip of my session with your test case bot: http://recordit.co/UJVnavhrrW. Are you using the bot a different way than I did?

**Comment by lyzs90** [comment]
@eanders-MS nope not that i can think of. strange, for me everything is fine up till the first carousel. then i have to scroll to see the last two messages. i tried reinstalling the emulator but to no avail

**Comment by eanders-MS** [comment]
Hi @lyzs90, Quick update to this thread: I'm able to reproduce this auto-scroll issue under different conditions. The problem resides in the web chat control used by the emulator ([BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat)). I will leave this issue open until we're properly tracking the issue there.

**Comment by eanders-MS** [comment]
Tracking the issue here: https://github.com/Microsoft/BotFramework-WebChat/issues/190
