### ISSUE TITLE
Attaching non-us luis resource in bot emulator is not possible

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Emulator#1310]
This [issue](https://github.com/MicrosoftDocs/bot-docs/issues/835) was reported by a customer in the docs repo. Here are the details from the customer:

**To Reproduce**
1. create a luis model on eu.luis.ai or au.luis.ai
2. try to add new luis service in bot framework emulator
3. you will only see models from www.luis.ai

Expected behavior
There should be possibility to select different luis portals

**Comment by cwhitten** [comment]
this is addressed in the latest version of the emulator
