### ISSUE TITLE
Discussion: Should we automatically set Locale in settings?

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-Emulator#1317]
Currently, a fresh install of the app does not have an automatically set Locale in settings:
![image](https://user-images.githubusercontent.com/14900841/52822771-8d2fde00-3067-11e9-8ac3-0b43d4625e6a.png)
I came across this when running Mock Bot and testing locale. In the screencap below, the first response from the bot is when Locale wasn't set, and the second is after I set en-US. 

![image](https://user-images.githubusercontent.com/14900841/52822732-6b365b80-3067-11e9-9bc5-bfd23a3c1db5.png)

In Web Chat, we currently set the default as 'en-US'. Is this something we would want to do with Emulator?
![image](https://user-images.githubusercontent.com/14900841/52822943-13e4bb00-3068-11e9-9265-cc5856d89d81.png)
(`Composer.js` in Web Chat)

**Comment by tonyanziano** [comment]
Hmm, we actually used to have this as the default because it was the default value in V3. I can't remember if we changed that behavior for a specific reason though.

**Comment by justinwilaby** [comment]
I believe this is only used by webchat and webchat defaults to `en-us` So a null field in the UI actually triggers a default value in webchat to en-us.

**Comment by corinagum** [comment]
Wouldn't the bot be able to respond with  `en-US` in the first query above if that were the case?

**Comment by tonyanziano** [comment]
This was fixed with #1329
