### ISSUE TITLE
Not ableto connect with any BotBuilder-Samples(Node.js Samples) using Bot botframework-emulator

### ISSUE THREAD

**Issue by ravik12KPIT** [Microsoft/BotFramework-Emulator#132]

**Comment by eanders-MS** [comment]
Is your bot running locally or remotely?
Are you supplying MSA appId and password, or running without credentials?
What are you supplying for the bot endpoint?
What port is your bot listening on?

**Comment by ravik12KPIT** [comment]
Hi Eric,

My Bot is running locally(I am using BotBuilder-Samples from https://github.com/Microsoft/BotBuilder-Samples).
I am running it without credentials.
My end point is http://localhost:3978/api/messages
Port is : 3978

Below error I got every time
[cid:image001.png@01D2A22B.70EFE8B0]


On more thing I would like to highlight here is, I am able to hit http://localhost:3978/api/messages from Advance Rest client but getting error “ERROR: ChatConnector: receive - no security token sent.“ so the concern is Node.js bot sample is listening on applied port properly but Bot emulator is not able to connect on that.


Regards,
Ravi Khatri

**Comment by eanders-MS** [comment]
Your screenshot of the error didn't come through via email. Can you repost it?

**Comment by ravik12KPIT** [comment]
Please find attached error screenshot.

Regards,
Ravi Khatri

**Comment by eanders-MS** [comment]
Still didn't make it. I think you'll have to copy/paste it directly into github. I guess github has problems receiving images over email.

**Comment by eanders-MS** [comment]
The message `ERROR: ChatConnector: receive - no security token sent` is expected when the bot is running without credentials and accepts a connection from something that doesn't appear to be the emulator, so it isn't unusual that you saw it when using Advance Rest client.

Can you describe the error you are getting in the emulator?

**Comment by ravik12KPIT** [comment]
![error_screenshot](https://cloud.githubusercontent.com/assets/26485078/24178273/25dfd6e0-0ece-11e7-8596-3d0c336b66cc.PNG)

**Comment by eanders-MS** [comment]
Everything looks correct, I'm stumped. Maybe an invisible character in the appId or password field? You might try deleting your endpoint and re-adding it.

**Comment by ravik12KPIT** [comment]
Yes Eric,
I tried all these but no luck.

**Comment by eanders-MS** [comment]
I think the next step would be to run [fiddler](https://www.telerik.com/download/fiddler) as a local proxy to capture more detail about the error and facts leading up to it.

**Comment by ravik12KPIT** [comment]
Okay, Sorry but I am not aware about fiddler.
Could you please help me on that.

**Comment by sapson** [comment]
I have the exact same issue, unable to use the bot framework emulator to connect to my local running bot.
When fiddler is running, I can see some details :
 `WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
Error: Request to 'http://localhost:52672/v3/botstate/emulator/users/default-user' failed: [404] Not Found
    at Request._callback (c:\usr\botpoc\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:452:46)
    at Request.init.self.callback (c:\usr\botpoc\messages\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (c:\usr\botpoc\messages\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (c:\usr\botpoc\messages\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)`

**Comment by eanders-MS** [comment]
@ravik12KPIT fiddler (downloadable from the link I provided earlier) is network inspection software. It lets you view all the network traffic sent and received from your computer. It can offer more detailed information about which network request is failing.

**Comment by eanders-MS** [comment]
@sapson The emulator will return 404 from the state API if there's no active bot connection. Was the emulator connected to your bot?

**Comment by sapson** [comment]
@eanders-MS No the emulator is unable to connect to the bot, same symptoms as user @ravik12KPIT has reported. I can test the bot from the console, or after deployment to azure. But the emulator is unable to connect the bot running on localhost. Only when fiddler is active I get some more info (as shared).

**Comment by ravik12KPIT** [comment]
After running fiddler the Bot Emulator is able to connect to my node.js code but when I say Hi then I am getting below error.
error ocurred [Error: Request to 'http://localhost:53524/v3/conversations/kl4kd1jennea659mc/activities/ic80ehll62hg1fhac' fail
ed: [403] Access Denied]

and below are the screenshots
[cid:image003.jpg@01D2A986.E97EF890]


[cid:image004.jpg@01D2A986.E97EF890]

**Comment by eanders-MS** [comment]
@ravik12KPIT With your bot and emulator running locally, could you send me:
- the first few lines of your emulator log, I'd like to see the host & port your emulator is listening on.
- the JSON content of a message sent from the emulator to your bot (copy/paste) from the emulator's detail view. I'd like to see what the serviceUrl is set to.
- the JSON of a reply sent from the bot to the emulator (available from fiddler).

Thank you!

**Comment by ravik12KPIT** [comment]
@eanders-MS<https://github.com/eanders-MS> Please go through below required data.
From: Ravi Khatri
Sent: Thursday, April 6, 2017 12:54 PM
To: 'Microsoft/BotFramework-Emulator' <reply@reply.github.com>; Microsoft/BotFramework-Emulator <BotFramework-Emulator@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/BotFramework-Emulator] Not ableto connect with any BotBuilder-Samples(Node.js Samples) using Bot botframework-emulator (#132)

**Comment by eanders-MS** [comment]
@ravik12KPIT Are you running firewall or security software that is preventing the post back to the emulator? You may need to create a rule to allow emulator traffic.

**Comment by eanders-MS** [comment]
Hi @ravik12KPIT, While we still don't have root cause for this issue, a workaround reported by another user is to change your endpoint protocol from `http` to `https`. YMMV. If it works, please let us know here.
```https://localhost:3978/api/messages```

**Comment by ravik12KPIT** [comment]
Okay I will check it and let you know.

Sent from my Windows Phone
________________________________

**Comment by ravik12KPIT** [comment]
Still not working just changed http://localhost:3978/api/messages to https://localhost:3978/api/messages.
From: Ravi Khatri
Sent: Wednesday, May 31, 2017 7:52 AM
To: Microsoft/BotFramework-Emulator <reply@reply.github.com>; Microsoft/BotFramework-Emulator <BotFramework-Emulator@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/BotFramework-Emulator] Not ableto connect with any BotBuilder-Samples(Node.js Samples) using Bot botframework-emulator (#132)

Okay I will check it and let you know.

Sent from my Windows Phone
________________________________

**Comment by pjsummersjr** [comment]
I'm having the same issue and it appears that the Bot Emulator is configuring ngrok for some random local port - every time I restart the emulator it says "Emulator listening  http://[::]:some-random-port". Once I enter in an actual endpoint, the emulator works for that endpoint but the ngrok association isn't updated. If you go to the ngrok traffic inspector page on localhost:4040 you can see the port it is listening on and it isn't the port in my emulator configuration. Seems to me, ngrok shouldn't be initialized until someone configures the endpoint URL.

**Comment by soso-maitha** [comment]
i have same issue :(

**Comment by AskYous** [comment]
I have the same issue when I was following this tutorial:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-3.0

**Comment by cwhitten** [comment]
It looks like various connection issues in the last two years have rolled into this one that may have been unrelated to each other. We're going to close this for now. Please open a new issue if you're on the latest version of the Bot Framework Emulator and experiencing connection issues while following a sample from BotBuilder-Samples.
