### ISSUE TITLE
Improve debugging behavior

### ISSUE THREAD

**Issue by martinoss** [microsoft/BotFramework-Emulator#1320]
**Is your feature request related to a problem? Please describe.**
When debugging with Bot Framework Emulator and Visual Studio, the delay it generates on active breakpoints results in multiple retries that makes it hard to trace a single request. Same breakpoint hits multiple times.

**Describe the solution you'd like**
Maybe there already exists a trick I'm not aware of, but I wish to be able to isolate the debugging of a request more isolated.
I imagine to have a setting on the Emulator that waits "forever" without running into a timeout. 

**Describe alternatives you've considered**
...or maybe something can be done in the SDK to debounce/block requests.

**Additional context**

[enhancement]

**Comment by justinwilaby** [comment]
This is a good suggestion. I've run into this as well.
tagging @compulim  - is this possible with DirectLine?

**Comment by cwhitten** [comment]
Hi @martinoss. Check out the new Bot Inspector feature: 

https://github.com/microsoft/BotFramework-Emulator/blob/master/content/CHANNELS.md

I will close this issue for now. However, the BF Emulator will always be adding new features to help bot developers build and debug their bots.
