### ISSUE TITLE
Latest version of Emulator does not clear the conversation history when "Restart conversation" is clicked

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotFramework-Emulator#1323]
## Version
4.2.142494

## Describe the bug
Emulator does not clear the conversation history when "Restart conversation" is clicked

## To Reproduce
1. Enter text into the conversation panel
2. Click on 'Restart conversation'
3. Observe that the conversation history is still present

## Screenshot

![image](https://user-images.githubusercontent.com/41968495/53185818-a3ccbc80-35b4-11e9-9893-ba927b399bc0.png)

## Expected behavior
The conversation history should disappear

[bug]

**Comment by cwhitten** [comment]
This is addressed in #1325, thank you for the ticket @v-kydela!
