### ISSUE TITLE
Missing Payment Handling Parity Between v3 & v4 Emulator

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Emulator#1324]
## Describe the bug
Using https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/sample-payments the V3 Emulator properly displays "Checkout with Microsoft Emulator" window.  The V4 Emulator displays a "Look for an app in the Store" window.

## To Reproduce
1. Use https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/sample-payments  sample
2. Click the Buy button in the V4 Emulator

## Screenshots
V4 Emulator:
![image](https://user-images.githubusercontent.com/11055362/53198597-9a9e1880-35d1-11e9-91da-384031b54444.png)

V3 Emulator:
![image](https://user-images.githubusercontent.com/11055362/53198609-a12c9000-35d1-11e9-9399-3006c904a1bf.png)

[bug]

**Comment by tonyanziano** [comment]
What version of the v4 emulator were you using when you encountered this bug? There was a similar issue with adaptive cards containing links to data URLs that was fixed recently, and I'm wondering if this is related. (#1130)

**Comment by EricDahlvang** [comment]
I'm using 4.2.1

![image](https://user-images.githubusercontent.com/11055362/53201403-cc66ad80-35d8-11e9-815f-7bd6e172185b.png)

**Comment by tonyanziano** [comment]
I was just able to repro this with the latest nightly (4.2.149424). I've also looked through the codebase and this UI doesn't even exist in v4. We would have to add it back. Going to tag as backlog for now.

**Comment by EricDahlvang** [comment]
Closing this, since Payments have been deprecated.
