### ISSUE TITLE
Release 4.2.1 for mac .dmg Couldn't send

### ISSUE THREAD

**Issue by Duncanmoo** [Microsoft/BotFramework-Emulator#1331]
## Version
4.2.1 (Mac .dmg)

## Describe the bug
When using the Bot Emulator I repeatedly get "Couldn't send" when posting a message. Nothing in the log screen.

## Solution
Download the .zip version of the release, it works.

[bug]

**Comment by tonyanziano** [comment]
@a-b-r-o-w-n / @justinwilaby Can you try to repro this on the nightlies?

**Comment by a-b-r-o-w-n** [comment]
@tonyanziano I was not able to repro on the nightly with a locally running bot nor a remote bot.

**Comment by justinwilaby** [comment]
I'm not able to repro this either unless I specify an endpoint that doesn't exist. 

@Duncanmoo - I'm closing this for now as it seems 3 of us could not repro. If you have exact repro steps and are using the v4.3+ Emulator, feel free to re-open this.
