### ISSUE TITLE
Reading transcripts directly from Azure Blob Storage

### ISSUE THREAD

**Issue by krajniak** [microsoft/BotFramework-Emulator#1332]
### Use this [query](https://github.com/Microsoft/botframework-emulator/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
There is no easy way to see transcripts of real conversation that happened on real channels 

**Describe the solution you'd like**
There should be a possibility to load transcripts from azure blob storage container that is used by
AzureBlobTranscriptStore to store all the conversation activities.
Transcripts are saved as separate blob files in one container, each containing one activity. Emulator only accepts json files that are arrays of activities. There is no easy way to convert list of blob with singe activity into a json with a list of all activities.

Best solution for this problem would be to give access to these transcripts using credentials from .bot file.

**Describe alternatives you've considered**
If it is to hard, maybe some solution that allows converting list of blobs into .transaction file

**Additional context**

[enhancement]

**Comment by cwhitten** [comment]
Hello @krajniak - we have deprecated using .bot files and will not be adding new functionality that utilizes it. 

I like your idea of a blob to .transcript converter, but I don't see it being part of the Emulator. The Bot Framework CLI would be a tool to consider such functionality. Please open a feature request there for continued discussion: https://github.com/microsoft/botframework-cli
