### ISSUE TITLE
Emulator Mangles quotes

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/BotFramework-Emulator#134]
The emulator transforms the quote types on its output.   From a debugging / testing point of view this complicates things as the output is not what one expects and turn valid JSON into non-valid JSON

It changes this:
"text"

To this:
“text”

Additionally, the latter types of quotes are not valid when using in JSON.

**Comment by eanders-MS** [comment]
Can you provide more detailed repro steps? I'm not able to repro from your description. When I copy a json blob from the emulator into a text editor like notepad++, I see plain quotes:

This:
![image](https://cloud.githubusercontent.com/assets/12176807/24118815/55f97d94-0d6c-11e7-9d34-0a7ba2a2e5ff.png)

Pastes to this:
```
{
  "type": "conversationUpdate",
  "membersAdded": [
    {
      "id": "12345",
      "name": "User 1"
    }
  ],
  "id": "iikla18mb45dmf5f",
  "channelId": "emulator",
  "timestamp": "2017-03-20T19:53:00.
  ```

**Comment by LarsLiden** [comment]
Here is what I get.   See first quote before "action"

{“action":{“5f7608e9-60a1-48dd-99f7-a759c5d9b60f":{“NegativeEntities":[],"RequiredEntities":[“2ad4d675-ac3c-48d9-b700-f09a33f9d498","0438a7df-9d3f-47e4-b89d-23bf54a62e96"],"action_type":"text","content":"$color
is a nice color,
$name."},"883106bd-2b59-4bba-8424-a64ee694ee9b":{“NegativeEntities":[“2ad4d675-ac3c-48d9-b700-f09a33f9d498"],"RequiredEntities":[“0438a7df-9d3f-47e4-b89d-23bf54a62e96"],"action_type":"text","content":"What
is your favorite color,
$name?"},"8868ae64-a188-43cc-bf6d-ba8b358532ce":{“NegativeEntities":[“0438a7df-9d3f-47e4-b89d-23bf54a62e96"],"RequiredEntities":[],"action_type":"text","content":"What
is your
name?"}},"blis-app-version":"1.0","entity":{“0438a7df-9d3f-47e4-b89d-23bf54a62e96":{“EntityType":"LUIS","LUISPreName":null,"name":"name"},"2ad4d675-ac3c-48d9-b700-f09a33f9d498":{“EntityType":"LUIS","LUISPreName":null,"name":"color"}},"traindialog":{“b1668d0f-432c-405d-a96e-3c5d1b8fbff7":{“turns":[{“input":{“context":{},"entities":[],"masked-actions":[],"text":"Hi","text-alts":[],"text-entities":[]},"output":"8868ae64-a188-43cc-bf6d-ba8b358532ce"},{“input":{“context":{},"entities":[“0438a7df-9d3f-47e4-b89d-23bf54a62e96"],"masked-actions":[],"text":"Lars","text-alts":[],"text-entities":[{“EndToken":3,"EntityType":"0438a7df-9d3f-47e4-b89d-23bf54a62e96","StartToken":0}]},"output":"883106bd-2b59-4bba-8424-a64ee694ee9b"},{“input":{“context":{},"entities":[“0438a7df-9d3f-47e4-b89d-23bf54a62e96","2ad4d675-ac3c-48d9-b700-f09a33f9d498"],"masked-actions":[],"text":"Blue","text-alts":[],"text-entities":[{“EndToken":3,"EntityType":"2ad4d675-ac3c-48d9-b700-f09a33f9d498","

**Comment by LarsLiden** [comment]
Clarification.  It's not copying the text the right pane.  This occurs for the Bot's output.

**Comment by eanders-MS** [comment]
I still don't know how to repro this.

**Comment by LarsLiden** [comment]
Have your bot output some JSON.  If you swing by my office I can demo.  Thx

On Mar 20, 2017 3:46 PM, "Eric Anderson" <notifications@github.com> wrote:

I still don't know how to repro this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotFramework-Emulator/issues/134#issuecomment-287921808>,
or mute the thread

**Comment by eanders-MS** [comment]
Thanks for the clarification. Am able to repro now. This is the WebChat control's rendering of the text, the emulator isn't involved. @danmarshall for tracking, but you might want to file an issue there.

**Comment by eanders-MS** [comment]
As a workaround, you could preformat the message. Example:
```javascript
reply.text('```\n{"this": "that"}\n```');
```

**Comment by eanders-MS** [comment]
I think what you're seeing is correct behavior. Unless you're preformatting the text, the chat control doesn't know you're trying to show code.

**Comment by billba** [comment]
Surrounding text with a single backtick does result in code formatting in GitHub e.g. `{code}` so I would tend to think that since Marked supports "GitHub flavored markdown" it would work.

Next question: why would it quote quotes inside curly brackets?

**Comment by LarsLiden** [comment]
So the other chat canvases (i.e. Skype, Facebook, etc.) to not have this
issue.  They display the text in the chat canvas exactly as it is sent to
to bot.  It's only in the WebChat/Emulator that it substitutes the quote
type (to one that causes JSON parse failures).

**Comment by LarsLiden** [comment]
(Seems that requiring preformatting on one canvas but not others causes confusion)

**Comment by eanders-MS** [comment]
@LarsLiden This will require a change to the WebChat control. Can you file an issue there?
