### ISSUE TITLE
post response code 404 (not found) bot emulator

### ISSUE THREAD

**Issue by aishjain** [Microsoft/BotFramework-Emulator#1342]
## Version
v4
## Describe the bug
Getting an error-404

**Comment by cwhitten** [comment]
Hi @aishjain. Can you please add some additional detail to the issue you are having?

**Comment by aishjain** [comment]
Hey @cwhitten  thank you for the response and basically i was trying to run a helloworld bot with the bot emulator when this error came up. I was referring this site
 https://coursetro.com/posts/code/45/Microsoft-Bot-Framework-Tutorial:-Hello-World-Bot!

**Comment by cwhitten** [comment]
That webpage isn't supported or maintained by Microsoft. Following a similar Hello World example [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp) is what we recommend and it up to date with our tools.

**Comment by aishjain** [comment]
@cwhitten I am not so good with c# so i am using node js but i cant seem to get the bot application option while creating a project in node js , what's the way around it?And I am very new to this so sorry for the basic doubts and thank you for the help.

**Comment by justinwilaby** [comment]
Closing this as it seem to have been answered.
