### ISSUE TITLE
Allow the Emulator user to specify a User ID to be used for conversations

### ISSUE THREAD

**Issue by cwhitten** [Microsoft/BotFramework-Emulator#1344]
see https://github.com/Microsoft/BotFramework-Emulator/issues/197 & https://github.com/Microsoft/BotFramework-Emulator/issues/1254

**Comment by cwhitten** [comment]
What we want to do here is allow a user id override provided in the Settings page that will be used for conversations. @darrenj does this align with your needs?

**Comment by darrenj** [comment]
Yes, exactly that. Once set within settings all activities would be stamped with this on the 'from.id' property. 

We should also make sure the work item to look at the new conversation behaviour is evaluated at the same time as starting a conversation with a new (different userid) will be more confusing than it is today!

**Comment by mewa1024** [comment]
@cwhitten On the Settings, page, would it make sense to combine the "Auth" and "Sign-in" settings? These sections:
![image](https://user-images.githubusercontent.com/39317542/55817931-619b0400-5aaa-11e9-8007-9ac9129c94c3.png)

Are these all related to the end user? If so, can we use one section called "User settings" with the three checkboxes:

"[  ]  Use version 1.0 authentication tokens"
"[  ]  Use a sign-in verification code for OAuth cards"
"[  ]  Use a customized user ID:" (_followed by a text field on a new line)_

**Comment by Aliandi** [comment]
@cwhitten to finish this issue there're two things left:
	• Fix the multiple chats opening problem we are having
	• Adapt the settings UI to let the user input the GUID
For the second one we would need the input of the UX team. Should we go with what @mewa1024 proposed?

**Comment by cwhitten** [comment]
No issues here grouping these options into a single group. Let's go with @mewa1024 's recommendation. Thanks!

**Comment by Aliandi** [comment]
Great!! Working on it!

**Comment by cwhitten** [comment]
@denscollo @Aliandi this is ready to be re-opened against `master`.  There has been a refactor to some of the code-paths involved so some changes will be necessary.
