### ISSUE TITLE
Changing ngrok path via browse doesn't enable save button

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotFramework-Emulator#1345]
## Version
Emulator version: 4.3.0 (could not repro on 4.2.1)
OS: Windows 10

## Describe the bug
In the emulator settings, if you change the "Path to ngrok" by clicking the "Browse" button and choosing a file, the "Save" button remains disabled. Manually typing in the "Path to ngrok" text box does enable the button though.

## To Reproduce
1. Go to the emulator settings
2. Click "Browse" next to "Path to ngrok"
3. Choose a file (different than what it was)
4. Notice that the "Save" button is still grayed out and cannot be clicked

[bug]

**Comment by justinwilaby** [comment]
I am able to repro. Thank you for raising this.
