### ISSUE TITLE
Can't select text in the conversation

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotFramework-Emulator#1346]
## Version
Emulator version: 4.3.0 (could not repro on 4.2.1)
OS: Windows 10

## Describe the bug
In the conversation window, you can't click and drag in a message to select text. This is true for both cards and the plain message text. This makes it really difficult to copy text from a conversation!

## To Reproduce
1. Start a conversation with a bot
2. Say something to the bot and get a reply back
3. Try to select your message text or the bot's response text

## Additional context
A workaround is to click on the message and select the text from the inspector, but that's pretty painful.

[bug]

**Comment by cwhitten** [comment]
@navzam How about using the Inspector payload to copy what you need?

**Comment by navzam** [comment]
@cwhitten As I noted, that's pretty painful

**Comment by cwhitten** [comment]
Shoot, didn't see that. Thanks for the feedback. @navzam When someone copies a large area from the chat window with multiple messages, what do you expect to get written to the clipboard?

**Comment by justinwilaby** [comment]
Can this can be transferred to WebChat? The WebChat control is should be defining what can and cannot be selected.

**Comment by cwhitten** [comment]
@justinwilaby I actually think what is causing this is the Emulator specific overlay for selectable messages that is not allowing the text to be selected.

**Comment by navzam** [comment]
@cwhitten Hmm good question... I don't think I have exact expectations for what gets copied if you select multiple messages. Based on experience with other apps, I would expect all selected text to get copied along with an unpredictable jumble of spaces/tabs/newlines :) For me the most important thing is to be able to select text within a single message and copy that.

**Comment by justinwilaby** [comment]
We should consider copying JSON representing a transcript fragment for the selected messages or a right-click menu with options on formatting for the copied messages.

for example: select messages, right click, choose from 1. copy text, 2. copy transcript, 3...
