### ISSUE TITLE
Emulator reporting 

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#1347]
## Version
4.2.150548

## Describe the bug
Emulator is not rendering trace activities correctly, instead it reports "No renderer for this activity" as shown below. Also clicking trace entries on the right hand side log panel renders a LUIS inspector strangely.

![image](https://user-images.githubusercontent.com/33519520/53870696-a38be280-3ff2-11e9-97e6-a5f7f0b23284.png)

## To Reproduce
- Use Emualtor against a Bot that sends trace activities (let me know and I can give you a bot file internally)

## Expected behavior
- No renderer error
- Trace activities render in log view

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/53870647-8eaf4f00-3ff2-11e9-84e0-1fe38edaa848.png)

## Additional context

[bug]

**Comment by justinwilaby** [comment]
This looks like a webchat issue since it should be ignoring activities of type `trace`. Also, are you able to paste the activity json here and provide a screen capture of the strange behavior with the Luis inspector?

**Comment by stevengum** [comment]
Crosslinking to issue #1328 and PR #1334

**Comment by justinwilaby** [comment]
Closing this as fixed via #1349

**Comment by KatieProchilo** [comment]
When should this fix go public? Is it available in a preview version now?

**Comment by tonyanziano** [comment]
@KatieProchilo this fix will be available in v4.3.2 which is building right now. I'll update this thread when it finishes.

**Comment by tonyanziano** [comment]
@KatieProchilo version 4.3.2 is now available here: [v4.3.2](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.3.2)
