### ISSUE TITLE
Problem with the V4.3  Unable to connect

### ISSUE THREAD

**Issue by Mo-GH** [Microsoft/BotFramework-Emulator#1355]
unable to connect !

![image](https://user-images.githubusercontent.com/34102804/53924215-8bac7100-407b-11e9-9838-621b573298e6.png)

**Comment by Mo-GH** [comment]
its was the Proxy Settings

**Comment by vansh187** [comment]
> its was the Proxy Settings

i am getting the same error but not able to resolve it .can u tell me the solution.
