### ISSUE TITLE
Cannot fetch LUIS apps

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/BotFramework-Emulator#1356]
## Version
4.3.0

## Describe the bug
When trying to add a LUIS app to a bot file in Bot Emulator it cannot find 

## To Reproduce
0. Set up some LUIS apps in West Europe (https://eu.luis.ai)
1. Click '+' next to 'Services'
2. Select LUIS
3. Log in to Azure if asked
4. Emulator tries to fetch LUIS apps
5. Emulator shows partially filled dialog saying it could not find anything

## Expected behavior
LUIS apps linked to my account are found

## Screenshots
![image](https://user-images.githubusercontent.com/3463496/53955049-3488b980-40d8-11e9-870b-f2c6240c745c.png)

[bug]

**Comment by justinwilaby** [comment]
I am able to repro this. The root cause is that the luis authoring keys are not shared across regions. The Emulator will have to match the region with the authoring key for that region in order to pull data.

**Comment by hansmbakker** [comment]
Great :+1:

**Comment by hansmbakker** [comment]
Thank you for the quiclass resolution

**Comment by hansmbakker** [comment]
Is this available in a prerelease?
