### ISSUE TITLE
Nightly build keeps trying to "update" to 4.3

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotFramework-Emulator#1357]
## Version
Emulator version: 4.2.150548 (latest nightly build)
OS version: Windows 10

## Describe the bug
I'm using the latest nightly build, which was released after version 4.3. Every time I open the emulator, it finds an "update" to version 4.3 and tries to apply it when I close the emulator.

Not sure if it's related but it seems strange that the nightly version number is still 4.2.x

## To Reproduce
1. Install nightly build v4.2.150548
2. Open the emulator
3. Wait a few minutes, then check the "Help" menu to see "Restart to Update..."
4. Close the emulator to see the Windows "allow app to make changes to your device" prompt.

## Expected behavior
I expect the nightly build to not downgrade me to the latest stable version.

[bug]

**Comment by cwhitten** [comment]
hi @navzam we're working on this right now - the nightly build process has experienced an issue with npm not allowing it to correctly version the nightly. We've removed the nightly in question and will push a 4.3.x nightly as soon as it is addressed.

**Comment by navzam** [comment]
Great, thanks!

**Comment by tonyanziano** [comment]
The build number is a separate issue.

I believe what's happening in your case is that in your application settings, you do not have the "Use pre-release versions" box ticked, but you do have the "Automatically download and install updates" box ticked. When you don't have the pre-release versions box ticked, then the auto updater will look at this repo for updates, the latest being 4.3.0. However, if you use pre-releases, it will check for the newest update from our [Nightlies repo](https://github.com/Microsoft/botframework-emulator-nightlies/releases).

So if you want to suppress the message, either disable Automatically checking for updates via the settings page, or make sure you tick the box for pre-release versions.

![image](https://user-images.githubusercontent.com/3452012/53982015-ace77e80-40c8-11e9-8623-ee6c431d2605.png)

**Comment by navzam** [comment]
@tonyanziano  Ah I didn't know about that setting, thanks for pointing it out. I checked "Use pre-release versions" and now it's behaving as expected. It'd be great to point out that setting in the "Nightly Builds" section of this repo's README or the nightly build repo.

With those two boxes checked, will I get automatic updates for each nightly build?

**Comment by tonyanziano** [comment]
@navzam Glad to hear it. Good suggestion, I think that's a great idea. I'll work on adding some documentation for that.

Yes you will get automatic updates for each nightly build. I'm actually about to upload a new, correctly-numbered nightly (v4.3.0x) to the nightlies repo very shortly, and you should be able to pick that one up.

:)

**Comment by tonyanziano** [comment]
Going to close this issue now. The newest nightly is out as well! [Link](https://github.com/Microsoft/botframework-emulator-nightlies/releases/tag/4.3.050674)
