### ISSUE TITLE
WebChat tries to render all activity types

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/BotFramework-Emulator#1358]
## Version
4.3.0

## Describe the bug
The latest Emulator version and a few past versions have been trying to render `endOfConversation` activities and failing with a sort of error message

## To Reproduce
The BotBuilder V3 Node SDK seems to generate `endOfConversation` activities when the bot encounters an error, though you can probably reproduce this in any SDK by sending your own activity

## Expected behavior
The Emulator should not try to render anything but message activities in its conversation panel

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/53984113-80823100-40cd-11e9-9241-69660088c12d.png)

## Additional context
This is the same as https://github.com/Microsoft/BotFramework-Emulator/issues/1328 but with `endOfConversation` activities instead of `trace` activities.

[bug]

**Comment by pepperakos** [comment]
I can also confirm this same behavior... I have 4.3.0 of the bot emulator and had started an Enterprise Bot using the instructions from MS just yesterday.

**Comment by cwhitten** [comment]
To address this in the near term, the Emulator will ignore `trace` and `endOfConversation` Activity types.

**Comment by compulim** [comment]
Sample for activity middleware, https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/10.b.customization-password-input.

**Comment by corinagum** [comment]
@justinwilaby started a Teams conversation where hiding the trace may not be an ideal solution. Reopening this issue for discussion and visibility.

**Comment by cwhitten** [comment]
For visibility: The plan to address is that in Emulator mode, we don't render `trace` activity types, in sidecar mode we will, with implemented renderers for the `trace`, and specifically the debug `trace` type. What we won't do is render an activity whose type we do not have a renderer for all-up, of which the LUIS trace type, or endOfConversation is an example.

**Comment by cwhitten** [comment]
this is till addressed in https://github.com/Microsoft/BotFramework-Emulator/pull/1363
