### ISSUE TITLE
Image Upload Image contentUrl issue on Bot Framework Emulator 4.3.0

### ISSUE THREAD

**Issue by ikivanc** [microsoft/BotFramework-Emulator#1362]
## Version
4.3.0

## Describe the bug
Hi Team, 

I'm trying to upload an image on new updated Emulator 4.3.0.

It seems like there are some changes however those are not reflected on documentation, I couldn't find them. Also [botbuilder sample](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/15.handling-attachments ) is not up-to-date too 

attachment.ContentUrl format has been changed,

Before the update I was able to access uploaded images in local TEMP directory and I was able to see the image on emulator now It changed to a new format "[object Promise]/v3/attachments/e960b300-41b7-11e9-992f-9fa6f8384922/views/original" 

it uses a localhost IP for new Emulator with ngrok, I'm able to access the image after change like below  
https://myngrokip.ngrok.io/v3/attachments/8fe5b190-41b2-11e9-992f-9fa6f8384993/views/original,

![image](https://user-images.githubusercontent.com/118657/54041135-0094bd80-41d8-11e9-95e3-bc4353019e91.png)

I changed manually in my code to access the image using "turnContext.Activity.ServiceUrl". It seems like it's a bug on Emulator and SDK. What is the best practice to access in my code and see my image in emulator as well?

Thanks.

**Comment by tonyanziano** [comment]
I believe the `[object Promise]` prefix of the `contentUrl` is due to the [new way in which the ngrokService retrieves the emulator URL](https://github.com/Microsoft/BotFramework-Emulator/blob/master/packages/app/main/src/ngrokService.ts#L66).

I wonder if this is causing the issue.

**Comment by a-b-r-o-w-n** [comment]
This looks due to a change in an interface for `getServiceUrl` in commit efdf84d. We need to `await` [here](https://github.com/Microsoft/BotFramework-Emulator/blob/master/packages/emulator/core/src/directLine/middleware/upload.ts#L98)

**Comment by EricDahlvang** [comment]
@tonyanziano  I'm able to repeat this issue in 4.4.1.  Navigating to the url results in:

{"error":{"code":"ServiceError","message":"The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined"}}

![image](https://user-images.githubusercontent.com/11055362/59544097-2f4fbd80-8ec4-11e9-9215-9c3c3bc703a5.png)

**Comment by tonyanziano** [comment]
It appears that the previous PR fixed images being uploaded via the Web Chat sendbox, however, the upload from the bot is still broken.

This is addressed in #1661
