### ISSUE TITLE
[Telemetry Compliance] In settings, data collection "learn more" link is broken

### ISSUE THREAD

**Issue by navzam** [microsoft/BotFramework-Emulator#1377]
## Version
Emulator version: 4.3.2

## Describe the bug
In the settings page, under "Data Collection", the "Learn more" link is broken. It looks like it tries to go to https://aka.ms/bot-framework-emulator-data-collection.

![learn_more](https://user-images.githubusercontent.com/126523/54392864-e3dc0800-4665-11e9-8be3-c07814d5373e.PNG)

[bug]

**Comment by tonyanziano** [comment]
Hey @navzam ,

This is a known issue. It was supposed to link to information about the data collection policy, but that hasn't been finalized yet. Data collection is going to be disabled in 4.3.3 which should be released later today.

**Comment by tonyanziano** [comment]
The link has been changed to direct to this repo for now.

**Comment by tonyanziano** [comment]
Needs to be updated along with #1236

**Comment by tonyanziano** [comment]
This was fixed in #1236. Link now says "Privacy statement" and links to the [official Microsoft privacy statement](https://aka.ms/privacy).
