### ISSUE TITLE
How do i maintain the chat after refreshing the chat page

### ISSUE THREAD

**Issue by pratyushdhanuka** [Microsoft/BotFramework-Emulator#138]
I was able to successfully create a chat bot in .Net
but the thing is every time I refresh the page, the entire chat is reset.

Is there some way I can maintain the session itself and not allow its contents to become empty.

**Comment by danmarshall** [comment]
See related issues here:
https://github.com/Microsoft/BotFramework-WebChat/issues/353
https://github.com/Microsoft/BotFramework-DirectLineJS/issues/9

**Comment by eanders-MS** [comment]
Closing as this is a question about the WebChat control rather than the emulator.

**Comment by billba** [comment]
Also related:
https://github.com/Microsoft/BotFramework-WebChat/issues/365
