### ISSUE TITLE
Data Collection 'Learn more' link doesn't point to privacy/data collection information

### ISSUE THREAD

**Issue by scheyal** [Microsoft/BotFramework-Emulator#1381]
## Version
4.3.2

## Describe the bug
Data collection link 'Learn More' must point to data collection usage policy & additional info on what's collected.

## To Reproduce
1. start the emulator
2. go to settings.
3. click on learn more

## Expected behavior
Give a clear and concise description of what you &  how telemetry is collected.

## Additional context

[bug]

**Comment by justinwilaby** [comment]
Duplicates #1377
