### ISSUE TITLE
POST connect ECONNREFUSED 192.168.1.4:3978

### ISSUE THREAD

**Issue by mccstan** [Microsoft/BotFramework-Emulator#139]
When testing the Framework locally, i'm gztting this  error. Can anyone help ?

**Comment by eanders-MS** [comment]
It looks like the emulator is expecting your bot to be running on host 192.168.1.4, listening on port 3978. Is this the case? What is your bot endpoint? Does it look like this? `http://192.168.1.4:3978/api/messages`

**Comment by eanders-MS** [comment]
Closing due to no response. @mccstan If you're still having problems please open a new issue. Cheers.
