### ISSUE TITLE
Formatting on LUIS inspector is wonky

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1390]
## Version
4.3.3

## Describe the bug
The formatting of the tabs on the luis inspector is bad

## To Reproduce
Generate luis trace and view the inspector 

## Expected behavior
*  More space between the tab links. 
* make it look like actual tabs instead of links.
* put borders on sections (it is not clear there are 2 panes in the luis inspector pane

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/55014318-fe887800-4fa7-11e9-8c5b-64e5967af599.png)

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1399
