### ISSUE TITLE
[LUIS] (intermediate value).map is not a function in trace log

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1392]
## Version
4.3.3

## Describe the bug
When you don't have a LUIS service configured you get a strange error in the trace log.

## To Reproduce
Generate a conversation with LUIS trace but without having LUIS configured as a service.

## Expected behavior
I don't think this is something that should be shown to the user?  Or the message should have more information.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/55014921-19a7b780-4fa9-11e9-8c36-08cbd0f5e958.png)

## Additional context

[bug]

**Comment by tonyanziano** [comment]
Addressed in #1399
