### ISSUE TITLE
Implement "Sidecar" debugging mode

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/BotFramework-Emulator#1394]
As a bot developer, I want to be able to enter a debugging mode in the Emulator that allows me to connect to a BotDebugger enabled bot so I can focus on interactions between my bot and the user when interacting with an external channel like Skype or Teams.

## Acceptance Criteria
1. An actionable 'view' menu item with the text: "Enter Sidecar Debug Mode" should exist. 
2. When selected, the user enters into sidecar debug mode which closes an existing Botfile (if present) after confirming with the user first. 
3. When sidecar debugging is enabled, The Webchat control enters into a "readonly" state by removing the message input and the services pane is hidden since no botfile is needed for this mode.
4. The webchat control is provided a custom message renderer that displays trace activities in a meaningful way to the user which includes the original message activity as well as any important trace data.
5. The state is remembered by the Emulator and is applied on subsequent startups.
6. The menu item is updated to use [Enter,Exit]Sidecar Debug Mode depending on the state.

## Definition of Done

1. An actionable menu item exists that toggles the debug mode.
2. If a botfile is open and the user enters sidecar debug mode, a confirmation is presented that  all open conversations will be closed
3. The webchat control enters and exits readonly mode and the services pane hides and shows successfully when the menu item is toggled.
4. Trace activities are rendered with a custom renderer in the webchat control when in sidecar debug mode.
5. The user can connect their locally running bot to the emulator while interacting with is using any channel. 
6. **NOTE** Diffing 2 bot state objects as described in #1395 will remain it's own task

**Comment by justinwilaby** [comment]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/2652885/55248879-f890d200-5207-11e9-9da9-6de74aea39ef.png">

**Comment by sgellock** [comment]
Running through this morning's daily build and we're looking good.
