### ISSUE TITLE
Implement Diffing Between Bot State Objects

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/BotFramework-Emulator#1395]
As a user, when in Sidecar Debugging mode as described in #1394, I want to be able to diff two bot state objects sent to the Emulator on each turn in the conversation.

## Acceptance Criteria
1. The user can select 2 bot state objects and view the diff in accordance to the designs

## Definition of Done
1. The user can view the diff between 2 bot state objects when in sidecard debug mode.

**Comment by mewa1024** [comment]
Updated comps on Invision: https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/17203017

**Comment by cwhitten** [comment]
Addressed in https://github.com/Microsoft/BotFramework-Emulator/pull/1400
