### ISSUE TITLE
Easily switch between configurations

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotFramework-Emulator#14]
To switch between configurations (e.g. local and Azure hosted), currently I have to close down the instance and reload.

Would be good to be able to have multiple instances running (e.g. by right clicking on the Windows taskbar) or be able to easily switch once I have connected to a configuration

**Comment by eanders-MS** [comment]
I think I may not completely understand what you're trying to do. Can you give me more detail about why you need to quit and restart the instance? The address bar remembers unique bot endpoints and their MSA info. Is it not adequate to switch between bots this way?

On a related note, we're changing the design of the emulator in the near future in a way that might alleviate some of the issues you're having:
- We're going to implement a new way of managing your bot endpoints: moving away from the address bar notion and more toward a traditional list. This will let you store multiple localhost bots, which is not possible now.
- We're going to remember conversations. When you switch to another bot, it will return to the conversation you were having with it previously, with full history. We'll also have list of prior conversations you can reload.

**Comment by eanders-MS** [comment]
@brendanarnold We're going to add support for multiple running instances of the emulator. This will be available in the next release (scheduled for this coming Thursday 12/8)
