### ISSUE TITLE
I have a problem with starting my bot from emulator - BotFrameworkAdapter.processActivity(): 401 ERROR - NotBeforeError: jwt not active

### ISSUE THREAD

**Issue by montacerdk** [microsoft/BotFramework-Emulator#1406]
I am developing a bot with Microsoft Bot Framework for Node.js.

I changed the LUIS App in the .bot file wit ha new one and then I generated a new botFileSecret, I tested my bot locally with the Bot Framework Emulator and everything just worked fine.

Then, I got this error: 

```

**Comment by tonyanziano** [comment]
Hi @montacerdk,

I'm a little confused by your issue; it's hard to diagnose without more information. You say that your bot was working locally within the Emulator just fine, but then you got the error in the title?

When exactly do you get that error? Is it when immediately starting a conversation with your bot, is it when sending a message after starting the conversation, or is it when only sending a message that contacts the LUIS service?

**Comment by montacerdk** [comment]
I just changed the LUIS App in the .bot file with these steps:
 - Decrypt the .bot file with the MSBot tools command.
 - Change the Subscrption Key and AppId
 - Encrypt the .bot file again
 - Update the .env file with the new .botFileSecret
 - Enter the new .botFileSecret to the emulator

I tested the new LUIS app after starting the bot, and everything is alright. suddenly, I got that Error above when I tried to test the bot with Emulator. it indicated a trouble with authentication (microsoftAppId and microsoftAppPassword).

I followed the instructions in this [Troubleshooting Bot Framework authentication](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-authentication-problems?view=azure-bot-service-4.0#PW).

As a first step, If I delete the microsoftAppId and microsoftAppPassword from the .bot file and make their values **null** in the **index.js** file, the error disappears and I can test the bot from Emulator without any issue.
```
const adapter = new BotFrameworkAdapter({
  appId: null,
  appPassword: null
});
```

Then, in the second step, I sent this this request in order to check the validity of the appId and appPassword:

```
curl -X POST \
  https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=client_credentials&client_id=<APP_ID>&client_secret=<APP_PWD>&scope=https://api.botframework.com/.default'
```

Then, I found out the the appId and appPassword are valid because I received the access token. 

Response:

```
{
    "token_type": "Bearer",
    "expires_in": 3600,
    "ext_expires_in": 3600,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGGAKI..."
}
```

However, I was blocked in the third steps because the same error persists.

For now, the bot starts fine when I run it from VSCode, as shown in this picture.

![image](https://user-images.githubusercontent.com/26897940/55432146-718a8380-5592-11e9-9d0b-ccc18466729d.png)

Then, If I start the emulator and it tries to connect the bot I get the same error …

![image](https://user-images.githubusercontent.com/26897940/55433698-270b0600-5596-11e9-9464-43c09bae0756.png)

I hope that this explantion would be helpful to understand the issue.

Thanks,

**Comment by cwhitten** [comment]
@montacerdk are you still having this issue? It seems like something is wrong in the way you have your runtime configured. It's unclear if this is an issue with the BF Emulator.

**Comment by montacerdk** [comment]
@cwhitten, this issue was resolved by generating a new bot file secret.
Thank you.
