### ISSUE TITLE
[Telemetry Compliance] Make auto update opt-in

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Emulator#1408]
Change auto update so that it is opt-in by default, and add UI that allows the user to opt-in when an update is detected.

**Comment by mewa1024** [comment]
Let's follow these steps:

1. User selects **Help** > **Check for updates...**
2. First-time experience, a modal appears with this content (using our usual modal styles):

    **Update available**
    Bot Framework <xxx> is available. How would you like to install the update? You will need to restart 
    the Emulator after installing.
 
    (    ) Download and manually install this update.
    ( * ) Install this update and restart the Emulator.
    (    ) Automatically download and install all updates.
 
     **Cancel** [ secondary button ] **Update**  [ primary button ]

By default, the middle radio button is selected ("Install this updated and restart the Emulator"). If the user selects the first button and clicks "Update", Emulator will start the download and use the usual modals for progress, examples below copied these screenshots from the v3 migration flow (should be more or less the same): 
![image](https://user-images.githubusercontent.com/39317542/57722802-20af8580-763c-11e9-9f90-9952911334cf.png)
etc.

If the user selects the third button, Emulator will start downloading and installation (with usual modals for progress):
![image](https://user-images.githubusercontent.com/39317542/57722844-3a50cd00-763c-11e9-9972-50e0deb1d847.png)
![image](https://user-images.githubusercontent.com/39317542/57722869-45a3f880-763c-11e9-9f0f-2cbae32c0ee3.png)
etc.

The next time they select **Help** > **Check for updates...**, Emulator will skip the "Update available" modal and start downloading and installing. To turn off auto-installing updates, the user will need to go to the Settings tab.

**Comment by tonyanziano** [comment]
@mewa1024 Sounds good. The only thing is that we can't really use a modal & progress bar for the "Install" step because that is controlled by the native operating system installer, but the rest should be doable.

I'm currently using the VSCode radio button style for the modal:

![image](https://user-images.githubusercontent.com/3452012/57723386-5f920b00-763d-11e9-8b38-67e454193769.png)

**Comment by mewa1024** [comment]
@tonyanziano cool. Is there a radio button for light theme? I suspect the white dot on gray background won't meet accessibility.

**Comment by tonyanziano** [comment]
@mewa1024 doesn't look like it:

![image](https://user-images.githubusercontent.com/3452012/57724985-df6da480-7640-11e9-8e61-e52da619ccd8.png)

**Comment by mewa1024** [comment]
@tonyanziano I chatted with the VS Code designer offline, and VS Code doesn't actually use a radio button anywhere, so they didn't run into the need for a spec on a light background.

So let's use a black border--it's a little closer to MS Fabric's radio: https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup

**Comment by tonyanziano** [comment]
@mewa1024 so like this?

![image](https://user-images.githubusercontent.com/3452012/57734949-fbc90b80-7657-11e9-80d4-1268e64fd131.png)

Or would you prefer the original blue fill with a black border?

**Comment by mewa1024** [comment]
@tonyanziano Sorry--original blue for the selected but black border for unselected.

**Comment by tonyanziano** [comment]
@mewa1024 roger.
