### ISSUE TITLE
Emulator sends 2 conversation updates in parallel

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1409]
## Version
4.3.3 

## Describe the bug
Emulator sends 2 ConverationUpdate events in parallel.  This is not correct.  It should send them sequentially (waiting for the response from the bot before sending another one.

## To Reproduce
1. create conversation
2. your bot receives 2 conversation updates overlapping requests.

## Expected behavior
It should send them sequentially...since it is the indicator of the start of a conversation it is important to wait for the response from the request before proceeding.

[bug]

**Comment by cwhitten** [comment]
@tomlm i can't reproduce your issue. nevertheless I've gone ahead and awaited the called to conversationUpdate in https://github.com/Microsoft/BotFramework-Emulator/pull/1414. If you still see the issue in the nightly please re-open.
