### ISSUE TITLE
Emulator LOG window is not showing ConversationUpdate messages in the log

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1410]
## Version
4.3.3

## Describe the bug
When a conversation is started 2 converstionUpdate messages are sent to the bot, but they do NOT show up in the LOG window.  They used to.

## To Reproduce
1. Start Conversation
2. Look in log window, there are no ConversationUpdate messages.

## Expected behavior
The ConversationUpdate messages should be in the log so they can be inspected.  They also should be in the log for .transcript files

[bug]

**Comment by cwhitten** [comment]
addressed in https://github.com/Microsoft/BotFramework-Emulator/pull/1414
