### ISSUE TITLE
When using nodemon

### ISSUE THREAD

**Issue by luisdiogo2071317** [Microsoft/BotFramework-Emulator#1412]
## Version
Using version 4.3.3

## Describe the bug
When I use nodemon for some reason I get an error where it points at the "name" in the bot file. If I remove any other, will say every time the same. Even with `node` and `npm start` it doesn't work

## To Reproduce
1. nodemon
2. it works for some moment correctly
3. error

## Expected behavior
In another test project it works very well

## Screenshots
 ```
"name": "TourismBotExpedita",
          ^
```
![erronodemon](https://user-images.githubusercontent.com/35113622/55725848-660de100-5a06-11e9-8e2d-079cce936aea.jpg)

[bug]

**Comment by cwhitten** [comment]
hi @luisdiogo2071317 are you using `nodemon` to run the Bot Framework Emulator locally, or are you using `nodemon` to start a bot and manage its process(es)?

**Comment by luisdiogo2071317** [comment]
Hi, I am using it to start the bot, normally, without ngrok. It never happened before. I think is because I am using 101 extensions in vs code and one of them may be conflicting and doing something that shouldn't

**Comment by luisdiogo2071317** [comment]
I found the error for any reason I was importing .bot itself and not the bot.js, at least found it kinda quickly
