### ISSUE TITLE
Emulator will not connect to bot

### ISSUE THREAD

**Issue by Dewain27** [Microsoft/BotFramework-Emulator#1413]
## Version
4.3.3-52662
## Describe the bug
Trying to connect to a production bot and Emulator will not connect.  I have tested this from numerous machines and it works on all but one.  It seems that this machine was updated from 4.1 to latest drop.

## To Reproduce
1. Open .bot file
2. Click on production
3. Emulator will not connect

## Expected behavior
Expected Bot to connect to emulator, but will not connect

## Screenshots
![image](https://user-images.githubusercontent.com/18688053/55726078-9a68a980-59d4-11e9-8402-9393f35e53ca.png)
![image](https://user-images.githubusercontent.com/18688053/55726192-d69c0a00-59d4-11e9-8397-a6885ea74d91.png)
![image](https://user-images.githubusercontent.com/18688053/55726243-ef0c2480-59d4-11e9-97a9-09d48ba23aa7.png)

## Additional context
Updated ngrok to latest stable build and still will not connect to bot.

[bug]

**Comment by Dewain27** [comment]
I am noticing that it looks like one of the updates didn't clear the 4.1.0 version

![image](https://user-images.githubusercontent.com/18688053/55727328-65aa2180-59d7-11e9-8f5e-d8a0195a84d7.png)

**Comment by tonyanziano** [comment]
Was resolved with a reboot.
