### ISSUE TITLE
Mac installer copy: "Bot Frameworks Emulator"

### ISSUE THREAD

**Issue by cwhitten** [Microsoft/BotFramework-Emulator#1416]
is this intended? it seems like it should read Bot Framework Emulator

<img width="568" alt="Screen Shot 2019-04-09 at 9 25 26 PM" src="https://user-images.githubusercontent.com/1156704/55851575-174b6e80-5b0e-11e9-8cf8-1f7b490e5193.png">

**Comment by tonyanziano** [comment]
That definitely seems wrong. @mewa1024 can you confirm that this is right / wrong? If not, maybe @DesignPolice can correct it for us. The original .tiff file is in the source.

**Comment by DesignPolice** [comment]
Well that looks like a typo, designers... smh
