### ISSUE TITLE
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized

### ISSUE THREAD

**Issue by jefferydai** [microsoft/BotFramework-Emulator#1417]
## Version
The version of the Emulator is 4.3.3

## Describe the bug
This is the first time I download the source code of my bot and use the emulator to connect it.
When I downloaded source I have pressed "Yes" when asking whether including app settings in the zip file.
I just input the my bot URL and press "connect", and then I can see following error in my bot console:
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized(node:17164) UnhandledPromiseRejectionWarning: Error: Error: Unauthorized Access. Request is not authorized
    at BotFrameworkAdapter.processActivity (E:\KGQA\Azure-MS\djtbot-src\node_modules\botbuilder\lib\botFrameworkAdapter.js:469:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)(node:17164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized
(node:17164) UnhandledPromiseRejectionWarning: Error: Error: Unauthorized Access. Request is not authorized
    at BotFrameworkAdapter.processActivity (E:\KGQA\Azure-MS\djtbot-src\node_modules\botbuilder\lib\botFrameworkAdapter.js:469:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

 

## To Reproduce
1. start my local bot (based on node.js):
    npm start
2.  start the emulator and do following actions:
a. press "File"-> "Open Bot"
b. Enter a Bot URL of http://localhost:3978/api/messages
c. press "Connect"
d go to the window where I started my local bot and I can see the above error message.
e if I type a message in the emulator, I can not see the response from the bot. 

The following is the setting of the emulator:
![image](https://user-images.githubusercontent.com/44393697/55853712-e3fff280-5b94-11e9-9cf0-ce07a17399a4.png)

## Expected behavior
The local bot should not show error message when emulator connects to it.

## Screenshots
Below is the console of my local bot
![image](https://user-images.githubusercontent.com/44393697/55854411-2b877e00-5b97-11e9-8d36-4cd8d7028c46.png)

## Additional context
(C:\ProgramData\Anaconda3) C:\Users\Administrator>node --version
v10.15.3

Thanks a lot!

**Comment by jefferydai** [comment]
The README.MD of the bot says only input bot URL :
![image](https://user-images.githubusercontent.com/44393697/55855854-30e6c780-5b9b-11e9-8fe2-9e5daa8a434b.png)

I am not sure if this is right.
I tried input bot URL, app ID and app password, then after I press "Connect", the bot did not show any error message. BUT when I type my message in the emulator, I still can not see the response.
![image](https://user-images.githubusercontent.com/44393697/55856294-71931080-5b9c-11e9-92c1-d027bde941a5.png)

![image](https://user-images.githubusercontent.com/44393697/55856337-94252980-5b9c-11e9-9340-9e712b5a2501.png)

**Comment by jefferydai** [comment]
Additionally, I tested my bot in "Test in Web Chat", the bot works well. I can see the response from the bot.
![image](https://user-images.githubusercontent.com/44393697/55856596-54127680-5b9d-11e9-9319-2f5c7ba9c2c2.png)

**Comment by cwhitten** [comment]
Hello @jefferydai - by chance could you have put the incorrect appId/password in the connection form?

**Comment by jefferydai** [comment]
Hello Chris,

Thank you very much!

Just when I am replying to you, I notice "If you don't have a bot configuration, create a new bot configuration" in the welcome section of emulator.

[cid:_Foxmail.1@83a3f3fb-7215-a3b2-2f9c-38b9ed9877f3]

Then I create the bot file for my local bot. After I press "Save and connect", this time emulator works well, I can see the response.
And I double checked following two types of connecting to by local bot:
1. Input the URL, appID/password
2. Select bot which is defined by bot file from "My bots" form in the Welcome section

I find type 1 always fail and type 2 always OK. So I guess if this is a bug.

Thanks a lot.

________________________________
dai_juntang@pactera.com

**Comment by tonyanziano** [comment]
@jefferydai .

There has been significant work done to the flow for opening a bot via URL over the past 2 months. Please download the latest version of the Emulator [over on the nightly repo releases page](https://github.com/Microsoft/botframework-emulator-nightlies/releases) and if the issue persists, let us know.
