### ISSUE TITLE
Error 500 using bot emulator v3.5.25 on localhost

### ISSUE THREAD

**Issue by robinmak** [Microsoft/BotFramework-Emulator#145]
Hi, I've downloaded bot emulator v3.5.25 and connect the emulator to http://localhost:3979/api/messages to test the bot.
When testing the bot using the emulator on localhost (in Visual Studio F5 mode), I keep getting error 500 with the following details:

"message": "An error has occurred.",
  "exceptionMessage": "Could not find any recognizable digits.",
  "exceptionType": "System.FormatException"

Anyone else having the same issue?

![image](https://cloud.githubusercontent.com/assets/14850931/24360774/dcd3137e-133a-11e7-9c92-3a7f8849abbd.png)

![image](https://cloud.githubusercontent.com/assets/14850931/24360819/fce2dcbc-133a-11e7-9fe3-bf36808cffc1.png)

**Comment by eanders-MS** [comment]
This is a callstack from your bot. It appears to be failing to parse a GUID. You should be able to catch it in your code. Perhaps set a breakpoint here:
![image](https://cloud.githubusercontent.com/assets/12176807/24365921/61b9c142-12cc-11e7-82a2-dbe50d556fd9.png)
