### ISSUE TITLE
XML in received messages

### ISSUE THREAD

**Issue by gala132** [Microsoft/BotFramework-Emulator#146]
Hi all!
I was working with the Framework but when I sent my bot to a Group Conversation I stumbled upon a few issues.
The problem is that within the skype conversation, I get xml in the `session.message.text` variable, which is working fine if we have one-to-one conversations.
This happens after mentioning the bot like described in the other issue.
Here is the output of the `session.message` variable.
```
{ text: '<at id="28:xxxx-16b6-4540-a6aa-56923ed0fb58">XBOT</at> asd',
  type: 'message',
  timestamp: '2017-03-27T22:14:49.735Z',
  entities: 
   [ { mentioned: [Object],
       text: '<at id="28:xxxx-16b6-4540-a6aa-56923ed0fb58">XBOT</at>',
       type: 'mention' },
     { locale: 'en-US', platform: 'Web', type: 'clientInfo' } ],
  attachments: [],
  address: 
   { id: '95559454',
     channelId: 'skype',
     user: 
      { id: '29:xxx-XJWQwWw24XpE-IF6pLZWzvl9kLV6sM5iOMJE',
        name: 'XY' },
     conversation: 
      { isGroup: true,
        id: '19:840da69e20484f5f8fadbcf1c8c8a33b@thread.skype' },
     bot: { id: '28:xxxx-16b6-4540-a6aa-56923ed0fb58', name: 'XBOT' },
     serviceUrl: 'https://smba.trafficmanager.net/apis/',
     useAuth: true },
  source: 'skype',
  agent: 'botbuilder',
  user: 
   { id: '29:xxxx-XJWQwWw24XpE-IF6XLZWzvl9kLV6sM5iOMJE',
     name: 'XY' } }
```
For the client side (myself) I am using a skype for linux beta version.
SDK: Node
The botbuilder package version: botbuilder@3.7.0
If any additional details needed I can provide them. (Scrubbed some id's from the dump, so those are not valid.)
Related to #104
Although, it could be related to the Botframework itself, but since it is causing issues here too (like described in the 104 issue), it is fine to have it here also.

**Comment by eanders-MS** [comment]
This sounds like a bug in Skype. You will get better results reporting this over at https://github.com/Microsoft/BotBuilder/issues. This page is only for issues relating to the BotFramework Emulator.

**Comment by gala132** [comment]
That's what I thought, thanks for the response.
