### ISSUE TITLE
[Telemetry Compliance] Security: Ensure any secrets are stored in compliant crypto stores (or not cached)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Emulator#1464]
## Ensure compliant handling of secrets
Ensure any secrets handled by the emulator are stored in compliant crypto stores or not cached at all for security compliance.

### Relevance
* encryption/decryption of .bot files
* encryption/decryption of app-id/password

**Comment by scheyal** [comment]
@tonyanziano - Can you assess dev cost of caching secrets in compliant stores for each platform?

**Comment by justinwilaby** [comment]
@scheyal - The Emulator passes absolutely all encryption work for bot files to [this library](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botframework-config/src), in particular [this line](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-config/src/encrypt.ts#L26)

**Comment by tonyanziano** [comment]
@justinwilaby For context, there has been an ongoing email thread about Emulator security & compliance which includes an impending security review.

While it is true that we hand all encryption / decryption off to `botframework-config`, we still keep a copy of the bot secret on the user's disk, which is what @scheyal is referring to. We need to work out a system for storing these (and future sensitive information -- msa app id / pw once the .bot file is no longer used) in a compliant fashion.

**Comment by scheyal** [comment]
Yes, what Tony said 😊

More generally, any handled secrets in BF must be stored in approved crypto stores (or not be cached at all).

**Comment by justinwilaby** [comment]
Ah, Got it. I was mistakenly under the impression this was a crypto related audit. This makes sense to me now. Let me know if there is something I can help with!

**Comment by tomlm** [comment]
Why do we need to do this?  We did a security review for this and got sign off on this approach.

**Comment by scheyal** [comment]
We need to refer to that sign off and see if we can transfer the approval for this issue to this review. 

We are required to run a security & privacy review on the emulator before we can release it.
