### ISSUE TITLE
Emulator is storing path property .bot file

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1468]
## Version
4.3.3 on ubuntu 

## Describe the bug
When I create a bot file and save it it has the path to the file in it.  This is incorrect because when this file is checked in and enlisted on a nother machine the path will be wrong.

## To Reproduce
1. new bot
2. save file
3. open bot file
You will see
```javascript
{
    "name": "test",
    "description": "",
    "services": [
        {
            "type": "endpoint",
            "appId": "",
            "appPassword": "",
            "endpoint": "http://locahost:3978/api/messages",
            "id": "365ae7b0-6978-11e9-b469-05e7bdef4b86",
            "name": "http://locahost:3978/api/messages"
        }
    ],
    "padlock": "",
    "version": "2.0",
    "overrides": null,
    "path": "/home/tom/src/github/botbuilder-samples/experimental/adaptive-dialog/declarative/10.EchoBot/test.bot"
}
```

## Expected behavior
the root path prpoperty should not bein the file

## Workaround
- Remove the `path` field from the botfile before checking it in.

**Comment by justinwilaby** [comment]
Removing this could be far-reaching. I'm seeing 46 occurrences in code where bot.path is being referenced. The path field appears to have been added intentionally for backwards compatibility. This may be a "wontfix" scenario due to the risk.

**Comment by tonyanziano** [comment]
Currently the path is used as a GUID for .bot files as there is no other way for the Emulator to distinguish between them. I'm leaning towards "wont fix" until we move away from bot files. It's deeply ingrained into the infrastructure at the moment.
