### ISSUE TITLE
LUIS No Models modal issues

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1471]
Have no LUIS models on your account and see the following:

<img width="421" alt="Screen Shot 2019-04-29 at 1 09 24 PM" src="https://user-images.githubusercontent.com/1156704/56923724-1e67fb80-6a80-11e9-9c11-6d00f9063fc7.png">

It should not say {label}, and instead have the value interpolated into the string.

Clicking on "Connect to a LUIS model manually" - nothing happens. Clicking on the link should do something

Clicking on "Learn more about LUIS models" - nothing happens. Clicking on the link should something.

Clicking on "Go to LUIS" - the modal closes. Clicking on the link should actually go to LUIS.

**Comment by ivanov-dan** [comment]
@cwhitten  Do we know the URLs for "Learn more about LUIS models" and "Connect to a LUIS model manually" links?

**Comment by cwhitten** [comment]
"Connect to a LUIS model manually" should open a new modal with service configuration form. This exists today in a couple other places. I believe all that is needed here is to add an `onClick` prop:

`onClick={this.props.launchConnectedServiceEditor}`

"Learn more about LUIS models" should probably link out to the documentation for LUIS. Let's have it point here: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/what-is-luis?
