### ISSUE TITLE
Go to LUIS link does nothing

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#1488]
## Version
4.3.57327

## Describe the bug
I tried to add LUIS, and after succesfully logging in I get this message.  Clicking on the GOTO LUIS does nothing.

![image](https://user-images.githubusercontent.com/17789481/57049290-367c7e00-6c2c-11e9-82dc-737c9697b92c.png)

## Expected behavior
* I expect to be able to add luis
* I expect the link to work

[bug]

**Comment by tomlm** [comment]
Addition notes:
* Connecto a LUIS Model mannually does nothing
* Learn more about LUIS models does nothing

**Comment by cwhitten** [comment]
This will be addressed in https://github.com/Microsoft/BotFramework-Emulator/pull/1484/files
