### ISSUE TITLE
Adding Azure storage resources takes forever because it is enumerating all resources

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1489]
## Version
4.3.3.57327

## Describe the bug
It takes almost 3 minutes to enumerate my storage accounts

## To Reproduce
1. add azure storage
2. wait wait wait wait go get a cup of coffee, fork a project, build it, make PR come back and wait

## Expected behavior
To quickly get access to my storage account

[bug]

**Comment by tonyanziano** [comment]
Covered in  #1490
