### ISSUE TITLE
Azure Storage Explorer has poor layout

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1491]
## Version
4.3.57327

## Describe the bug
- Layout doesn't have consistent spacing
- Scroll bar is missing

## To Reproduce
1. Add Azure Storage
2. Look at dialog

## Expected behavior
- Spacing should be consistent.  
- There should be a visible scrollbar that I can use
- Do we really want Zebra style for our list?

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/57049651-db4b8b00-6c2d-11e9-8d30-281043db1998.png)

[bug]

**Comment by tonyanziano** [comment]
Merged into #1490
