### ISSUE TITLE
Azure Storage Picker has poor layout for long names

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#1492]
## Version
4.3.3.57327

## Describe the bug
Picker doesn't crop text

## To Reproduce
1. Go to azure storage picker
2. Scroll until you find a resource which has long name

## Expected behavior
It should crop, or scroll or ellipsis or something.  

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/57049727-2d8cac00-6c2e-11e9-8d0b-e71cc413835a.png)

[bug]

**Comment by tonyanziano** [comment]
Merged into #1490
