### ISSUE TITLE
Azure Storage Accounts show container name only - should show storage + container name

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#1493]
## Version
4.3.3.57327

## Describe the bug
I added all of the azure storage accounts.  The list of names don't match my storage account names at all. 

## To Reproduce
1. Add Azure Storage
2. The name which is added doesn't match the portal at all

![image](https://user-images.githubusercontent.com/17789481/57050770-0b495d00-6c33-11e9-9f82-5130df3a1458.png)

## Expected behavior
Name of the entry to help me to know what I'm clicking on.

[bug]

**Comment by cwhitten** [comment]
Still need to find a consistent repo
