### ISSUE TITLE
Deep links for Add Azure Storage/Cosmos DB process are broken

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#1495]
Related to #1494 

## Version
4.3.3.57327

## Describe the bug
All azure storage deep links fail to load because the url which is generated is wrong (see #1494 )

## To Reproduce
1. Add azure storage
2. Double click on the Azure Storage link

It fails to load (probably because the resourceGroup = **resourceGroups** and so it builds a bad url.

## Expected behavior
The whole POINT of adding the resource is to let you navigate to them.

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/57050944-d2f64e80-6c33-11e9-9acd-9e633a27f3bc.png)

[bug]

**Comment by justinwilaby** [comment]
Linking has changed for the Azure portal. These links all worked when first implemented then Azure decided to change them. The new links require the domain name e.g. microsoft.onmicrosoft.com whereas before they used the TenantId. 

The problem with fixing this is that there does not appear to be an api that retrieves the domain name for a particular tenant/user combo.

**Comment by stevengum** [comment]
Justin and I synced in person, right now there are a couple of things going on.

- #1559 fixed the problem where the resource group was being stored incorrectly (issue #1494)
  - The a
- the resource _type_ used when constructing a deep link for Storage account is incorrect, it should be `'Microsoft.Storage/storageAccounts'`
  - The id for a Storage Account saved via the emulator has all the correct information for connecting to a resource in the portal barring the tenantId.
  - _Note:_ The id also contains additional information which takes a user to a different view than the simple overview for a resource when accessing via the Azure portal.

**e.g.:**
`/subscriptions/<SUBSCRIPTION-GUID>/resourceGroups/<RESOURCE-GROUP-NAME>/providers/Microsoft.Storage/storageAccounts/<RESOURCE-NAME>/blobServices/default/containers/<DEFAULT-CONTAINER-NAME>` 
**vs**
`/subscriptions/<SUBSCRIPTION-GUID>/resourceGroups/<RESOURCE-GROUP-NAME>/providers/Microsoft.Storage/storageAccounts/<RESOURCE-NAME>/overview`
