### ISSUE TITLE
Sending images seems to fail

### ISSUE THREAD

**Issue by rposbo** [Microsoft/BotFramework-Emulator#15]
Selecting an image attachment in the emulator - with or without entering a text message also - just hangs on "sending"; it never seems to hit the bot endpoint.

**Comment by rposbo** [comment]
![image](https://cloud.githubusercontent.com/assets/316233/20532006/67100830-b0d0-11e6-8c74-982f02be55a7.png)

It stays as "sending" and doesn't hit any breakpoints in the bot's `api/messages` `POST` endpoint

**Comment by craigjensen** [comment]
This appears to be an issue with the emulator and we'll look into a fix.  Thanks for the report.

**Comment by eanders-MS** [comment]
This appears to be a problem in the webchat control itself. I've logged an issue here https://github.com/Microsoft/BotFramework-WebChat/issues/172, and will update the emulator to the latest webchat when a fix is ready.

**Comment by eanders-MS** [comment]
Fixed with https://github.com/Microsoft/BotFramework-Emulator/commit/f2656c47769931f24be07d713b87f0859f5e2be1, and will be available in the next release, which should go out sometime within the next business week.
