### ISSUE TITLE
Suggestion - Emulator V3.5.25

### ISSUE THREAD

**Issue by teochenglim** [Microsoft/BotFramework-Emulator#150]
I wish to port my "The Resistance", Multiplayer game from telegram to Microsoft Bot framework. But then the new Emulator make it impossible to debug/build.

My game will require message send fore and back to user "chat room" and "private message", because some secret will be send to user as intel, like who is spy, and your secret selection.

Wiki:
https://en.wikipedia.org/wiki/The_Resistance_(game)

Telegram api make it easy because chat room id is less than 0, and private room id is more than 0. But Bot Framework doesn't have the concept of "room msg" and "private msg"

Also with the new Emulator, I can use other user to test "room". Let's say user1 input A, User 2 input B.

How to improve?

1. Create the "room" concept
2. Allow User A input.. and also able to switch to User B input (Maybe the bottom left hand corner)

**Comment by eanders-MS** [comment]
Hi @teochenglim, thank you for the great feedback. These are good suggestions. #2 is a planned feature (ability to switch user in group conversation). Once that is implemented, supporting #1 will be straight forward.

We don't yet have a timeline for delivering these features, but I'll make sure they're on our roadmap.

**Comment by teochenglim** [comment]
Cool! Can't wait to see it is happening.

**Comment by teochenglim** [comment]
Thanks mate!
