### ISSUE TITLE
When in inspector mode, pressing enter in open bot window does not open bot

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Emulator#1504]
## Version
4.4

## Describe the bug
On a mac, when in inspector mode, entering a url and hitting enter just closes the window.

It should connect to the bot and open the inspector.

## To Reproduce
1. enable inspector mode
2. open bot url
3. type a url, press enter instead of clicking the button

**Comment by cwhitten** [comment]
This issue exists in Opening a bot in Emulator mode as well.

**Comment by tonyanziano** [comment]
This is fixed now due to #1551  & #1554
