### ISSUE TITLE
Add a Background Image for When There Are No Tabs Open

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Emulator#1508]
**Describe the solution you'd like**
I think it would be great if we had a background graphic similar to what VSCode has when there are no tabs open:

![image](https://user-images.githubusercontent.com/3452012/57105526-d9da9b00-6cdf-11e9-95d8-1a21b1732b6c.png)

Currently, the Emulator's background is just a blank screen which isn't very nice to look at:

![image](https://user-images.githubusercontent.com/3452012/57105554-e9f27a80-6cdf-11e9-8c44-73fc3947b2f5.png)

**Describe alternatives you've considered**
For starters, I was thinking we could plop an SVG of the logo on that background _until_ and _if_ we decide to go with something else.

**EDIT**:

Quick mockup I did (I think it would look better with text underneath):

![image](https://user-images.githubusercontent.com/3452012/57106635-c846c280-6ce2-11e9-88b2-e7a8dc7d5bc6.png)

@DesignPolice / @mewa1024 any thoughts?

**Comment by mewa1024** [comment]
Can we make the logo even fainter? Like the same color as the sidenav background?

What about these shortcuts for the text:

Open a bot                               Ctrl + O
New bot configuration            Ctrl + N

What other keyboard shortcuts do we have? If there is one for the Welcome tab, it would be useful to show it here as well.

**Comment by DesignPolice** [comment]
That sounds like an easy fix. Tony If I give you the SVG can you control the transparency percentage? or I can sample and make it a solid color that is a couple of clicks darker than the background? dark theme or high contrast would need a different file with that solution. Happy to help.

**Comment by cwhitten** [comment]
Thanks @DesignPolice we'd appreciate it

**Comment by tonyanziano** [comment]
@DesignPolice yeah we can control the SVG opacity on our end.

**Comment by mewa1024** [comment]
@DesignPolice I unassigned me and assigned this to you. Let me know if that's okay.

**Comment by DesignPolice** [comment]
I actually was thinking about this when I woke up.. haha.

I will send him the file today
m

________________________________

**Comment by DesignPolice** [comment]
okay, @tonyanziano sending you an SVG if this file works and we make it a light percentage - so it doesn't compete with the other elements on the page on the light maybe 5-10%.

**Comment by tonyanziano** [comment]
@DesignPolice Thanks, I'll try it out and I can post the results here

**Comment by cwhitten** [comment]
@tonyanziano will coordinate/handoff with @denscollo
