### ISSUE TITLE
Resizing the window slows down / freezes the UI

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/BotFramework-Emulator#151]
If you have history of conversations in the emulator and you resize the window, the emulator freezes up for a while as it's being redrawn.  This happen even when the Log has been cleared so it's a separate issue

(Currently one needs to resize window to get the carousel arrows to draw - a know bug in webchat)

**Comment by vishwacsena** [comment]
@mewa1024 ; @tonyanziano  - let's make sure we dont have this issue in V4 as part of responsiveness pass.

**Comment by cwhitten** [comment]
Not reproducible on current BotFramework-Emulator v 4.2.1, closing.
