### ISSUE TITLE
[mac] Protocol launch does not start new conversation

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Emulator#1512]
## Version
4.3.3-57771

## Describe the bug
Opening a `bfemulator://` link on mac opens the emulator but fails to start a conversation.

## To Reproduce
`open bfemulator://livechat.open?botUrl=http%3A%2F%2Flocalhost%3A3979%2Fapi%2Fmessages`

## Expected behavior
Should open emulator and start a conversation.

## Screenshots
<a href="https://cl.ly/f3410d" target="_blank"><img src="https://d1jfzjx68gj8xs.cloudfront.net/items/0P361u2D0G1N280m3w1J/Screen%20Recording%202019-05-03%20at%2009.18%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by justinwilaby** [comment]
The root cause appears to be a change in how protocol urls are handled when we moved to Electron 4. I'm able to repro this and am working on a fix.
