### ISSUE TITLE
Sidecar window slider gets stuck in 'slide' mode

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-Emulator#1513]
## Version
4.3.3-57771

## Describe the bug
Adjusting the middle vertical slider can make Emulator stuck in the slide mode, and the mouse can't escape from unintentionally adjusting the slider.

## To Reproduce
1. Open sidecar mode
2. Drag the middle vertical slider and let go
3. Move the mouse around the screen, expecting only the cursor to move, but see the window adjust sizes
4. Note that clicking away from window or pressing escape doesn't release slide mode.

## Expected behavior
Slider should be released after user lets go of the slider.

## Screenshots

![ezgif-1-2a4dd83841af](https://user-images.githubusercontent.com/14900841/57155212-b8d18300-6d8f-11e9-8e63-85181dd3de18.gif)

[bug]

**Comment by tonyanziano** [comment]
This is due to the upgrade to Electron 4 which uses a different version of Chromium in which the architecture of webviews (which house the inspectors) has changed. Now the webviews eat all mouse events and they do not make it back to the slider component.
