### ISSUE TITLE
Restart conversation with same UserId causes "unable to connect"

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Emulator#1533]
## Version
4.4.0

## Describe the bug
When conversing with a Bot, if you click Restart Conversation with same UserId it restarts the conversation and then reports Unable to connect. From here on the emulator is unable to connect/send/receive mesages to a Bot and requires a restart.

## To Reproduce
1. Talk to a Bot
2. Restart conversation with same userid
3. Observe unable to connect error

## Expected behavior
It works :-)

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/57314069-c21b6200-70a5-11e9-88dc-9c76560b20bd.png)

## Additional context

[bug]

**Comment by darrenj** [comment]
@cwhitten FYI, you might want to take a look ahead of the next triage

**Comment by cwhitten** [comment]
Looking at this now @darrenj

**Comment by cwhitten** [comment]
I'm seeing this behavior with .bot file connections only.

**Comment by darrenj** [comment]
Thanks! Will this trigger a new stable release today/tomorrow? 4.4.2 I guess?

**Comment by cwhitten** [comment]
@darrenj I want to address https://github.com/microsoft/BotFramework-Emulator/issues/1537 before we publish a new stable release. No ETA on this, but we're actively working it.
