### ISSUE TITLE
The userID should not be reset by default

### ISSUE THREAD

**Issue by snapfisher** [microsoft/BotFramework-Emulator#1539]
The default action on "restart conversation", or actually stopping and restarting the emulator, should be to use the same user ID. New IDs should be generated only if requested (through the drop down). This will make the emulator more consistent, both in general and in respect to previous versions.

**Comment by paulio** [comment]
This probably explains why User Data does not appear to be persistent even when using a Persistent state store?  This makes testing REALLY difficult.

**Comment by tonyanziano** [comment]
@snapfishert & @paulio we've reworked the userId logic and added a new feature (#1456, #1590) where you can now define a custom userId in the app settings page.

![image](https://user-images.githubusercontent.com/3452012/58724505-9e3ff900-8391-11e9-8ba9-9c80c1fca309.png)


After defining this value, conversations you start will be initialized with this value, **even after restarting the emulator**. The only way the value changes is if you hit the "Restart with new conversation id" button (which is also the default of the button).

Internally, we have discussed flipping the default of the restart button, but have decided to keep "restart with new id" as the default.
