### ISSUE TITLE
v3.5.26 broken on Ubuntu

### ISSUE THREAD

**Issue by tkalfigo** [Microsoft/BotFramework-Emulator#154]
Downloaded latest v3.5.26 and I get an empty window. No errors on the console. 

Went back to v3.5.25 which works fine.

**Comment by eanders-MS** [comment]
Thanks for reporting this. Investigating now.

**Comment by eanders-MS** [comment]
This issue turns out to be in the BotFramework-WebChat control (incorrect casing on an import path). I will follow up on that repo's issues page.

**Comment by eanders-MS** [comment]
Issue: https://github.com/Microsoft/BotFramework-WebChat/issues/415
Fix: https://github.com/Microsoft/BotFramework-WebChat/pull/416

**Comment by eanders-MS** [comment]
Fixed in 3.5.27
