### ISSUE TITLE
Provide a way to clear cookies/state

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Emulator#1561]
# Clear Emulator State

Related to #1467. The `cookies` created as part of Authentication flows involving Azure Active Directory cause headaches for users leveraging authentication in their Bots. The caching/remember-me behaviour is "odd" in normal browsers and this appears to be the root cause of the auth issues we've run into.

Deleting the cookie files reference in #1467 works really well, we should consider a "Clear State" or similar menu item in the Emulator to perform this without users digging around in the file system.

**Comment by justinwilaby** [comment]
Agreed. It may be useful to clear these cookies on all failed login attempts as well. This would remedy the case where the user selects the wrong certificate by mistake.

**Comment by justinwilaby** [comment]
related to #1480

**Comment by cwhitten** [comment]
this is addressed in https://github.com/microsoft/BotFramework-Emulator/pull/1596

**Comment by darrenj** [comment]
🕺
