### ISSUE TITLE
[Bot Inspector] - Reconnection

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1563]
### Reconnection 

A conversation tab in bot inspector mode in the Emulator should have the ability to reconnect to the bot at will. This will allow the user to have a faster feedback loop using the emulator as they change their bot runtime and want to restart the conversation. Currently they would have to initiate a new conversation via the Open Bot modal and providing AppId and AppPassword credentials. 

*High-level code changes*: 

 - When a user first connects to a bot in Bot Inspector mode, the Emulator saves a url:appid:apppassword tuple in memory. This data is not persisted. Closing the Emulator or closing the conversation tab should clear out this sensitive data, and reconnection would be via the Open Bot modal mechanism. 

- Introduce a reconnect button similar to the restart conversation button when a conversation tab is in debug mode that will establish a new secure connection with the url:appid:apppassword tuple to the bot and issue the `/INSPECT open` command. The user would still need to copy the received `/INSPECT attach` command containing a new UUID into the channel conversation.

**Comment by stevengum** [comment]
Related: #1506

**Comment by cwhitten** [comment]
Addressed in https://github.com/microsoft/BotFramework-Emulator/pull/1634
