### ISSUE TITLE
[Bot Inspector] Paged State-Diffing

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1565]
### Paged State-Diffing 

Currently to move into state diff mode one has to open a context menu (right-click) and select an option from that menu to render the diff. This was a temporary solution until we had the cycles to build state-diff paging into the Bot State Inspector panel, where you can both move into state diff mode on a given Bot State, and page forward/backward to future/previous bot state diffs via buttons. 

*High-level code changes* 

- Introduce new buttons in or near the bot state extension to move into and out of state diff mode and page through state diff modes when currently in state diff mode. 
- Extension manifest change to support Icons
- Adjustment of the Bot State context menu in the chat control to no longer provide the menu item. 
- Provide the extension with all current Activities so it can maintain its own state.

**Comment by cwhitten** [comment]
@mewa1024 can you attach the related design assets to this ticket?

**Comment by mewa1024** [comment]
These are the designs are a little stale, but my original thought was that the commands for inspect mode (called "Debugging mode" in the comps) should have a menu from the app's menu bar like this:
![image](https://user-images.githubusercontent.com/39317542/57904367-4cdb2a00-7827-11e9-88b9-86ca70485382.png)

Paging would also be avaible in the inspector pane as icons in the upper right. The "<" means go to previous state, ">" means go to next state, and the map marker icon means resume from here. ">" and the map marker would be disabled if you were on the latest state:
![image](https://user-images.githubusercontent.com/39317542/57904488-c5da8180-7827-11e9-96bc-077cc2b049c3.png)
![image](https://user-images.githubusercontent.com/39317542/57904531-f3bfc600-7827-11e9-833a-3de9be3d1727.png)
