### ISSUE TITLE
[Bot Inspector] Collapsible JSON

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1566]
### Collapsible JSON viewer 

Going into the Beta of the feature, we anticipated that emitted bot states could be at times hard to read given deeply nested JSON objects. Prototypes created to soften this issue were around new data visualizations (trees, graphs) but internal feedback was suggestive that more thought was needed if it was the right thing to do. Users are all suggesting the same thing: Collapsible JSON. Rather than creating an entirely new visualization we can augment our existing JSON view to be collapsible, and potentially provide this view across all JSON payloads. 

*High-level code changes*

- Refactor a significant portion of the existing JSON viewer to be collapsible by integrating with or heavily borrowing from a library like [react-json-view](https://github.com/mac-s-g/react-json-view).

- Understand existing WebView caching strategies to avoid performance overhead, include benchmarks against existing load times
- Consolidate debug extension & all up json view [P1]
- Consider using React Hooks & a css-in-js library like [emotion](https://emotion.sh/docs/introduction)
- Theming

**Comment by mewa1024** [comment]
This seems good to me. Long-term, would it be possible for to install JSON viewers as extensions, similar or same as to the JSON extensions for VS Code?

**Comment by justinwilaby** [comment]
<img width="539" alt="Screen Shot 2019-06-04 at 12 03 40 PM" src="https://user-images.githubusercontent.com/2652885/58906498-deb8b300-86c0-11e9-819a-919c8838b746.png">
Light
<img width="539" alt="Screen Shot 2019-06-04 at 12 03 28 PM" src="https://user-images.githubusercontent.com/2652885/58906499-deb8b300-86c0-11e9-93e6-edd015178a15.png">
Dark
<img width="538" alt="Screen Shot 2019-06-04 at 12 03 12 PM" src="https://user-images.githubusercontent.com/2652885/58906500-df514980-86c0-11e9-9683-b191770bcaa1.png">
High Contrast
