### ISSUE TITLE
When a second livechat is started there are no conversation update activities

### ISSUE THREAD

**Issue by Aliandi** [microsoft/BotFramework-Emulator#1569]
## Version
Emulator 4.4

## Describe the bug
When a livechat is started, closed, and then reopened from the endpoint sidebar, it starts the same chat instead of creating a new livechat.

## To Reproduce
1. Open a bot
2. Open the settings page
3. Close the bot
4. Open the bot from the endpoint menu

![noConvUpdate](https://user-images.githubusercontent.com/22912283/57653512-5d31a180-75a8-11e9-93ee-335e98f6e73f.gif)

## Expected behavior
It should restart the conversation.

## Possible solution
We've found that if we remove this `if`, the emulator works as expected and it does not affect the behavior of any existing functionality. This is because when opening the bot from the endpoint menu, `shouldStartNewConversation` is always `false`.

```
componentWillMount() {
    window.addEventListener('keydown', this.keyboardEventListener);
    if (this.shouldStartNewConversation()) {
      this.startNewConversation();
    }
  }
```
Is there a reason for that `if` to be there? Could we delete it? If so, we will be uploading a PR with that solution.

**Comment by justinwilaby** [comment]
@Aliandi - Please check opening a transcript from a file if you change this code. I believe this is necessary for that path.

**Comment by cwhitten** [comment]
@Aliandi would you mind picking up this work? Like Justin mentions, let's make sure the behavior around conversation window opened with a transcript file is preserved.

**Comment by cwhitten** [comment]
it looks as though this was introduced with https://github.com/microsoft/BotFramework-Emulator/pull/1558.

**Comment by Aliandi** [comment]
@cwhitten yes, we are working on this, we'll be creating a PR soon!

**Comment by tonyanziano** [comment]
The issue has been resolved indirectly.
