### ISSUE TITLE
Error when sending image files to the emulator

### ISSUE THREAD

**Issue by weewey** [Microsoft/BotFramework-Emulator#157]
I'm getting an error when sending image files to the emulator.

![image](https://cloud.githubusercontent.com/assets/12046617/24853555/1340a740-1e0e-11e7-870b-5acbde8267cd.png)

**Comment by eanders-MS** [comment]
We've pulled Emulator build 3.5.26 due to this and a few other issues. We will be releasing a recovery build later today. For the moment, downgrading to 3.5.25 is the suggested mitigation. Sincere apologies!

**Comment by saibimajdi** [comment]
I have the same issue today, just after updating the emulator! BTW, the issue occured also with the embeded web chat control.
Error message :
`Uncaught TypeError: this.props.sendFiles is not a function C:\Users\saibi\AppData\Local\botframework\app-3.5.26\resources\app\node_modules\botframework-webchat\built\Shell.js 26 20 {} `

**Comment by eanders-MS** [comment]
Apologies! We're working to make a fixed build available. In the meantime downgrading to 3.5.25 will restore this functionality.

**Comment by eanders-MS** [comment]
Fixed in 3.5.27

**Comment by ejadib** [comment]
I'm facing a similar issue, when trying to upload a WAV: [err-client] Uncaught TypeError: this.props.sendFiles is not a function C:\Users\ezequ\AppData\Local\botframework\app-3.5.28\resources\app\node_modules\botframework-webchat-speech\built\Shell.js 27 20 {}

**Comment by eanders-MS** [comment]
3.5.29 is now available with a fix for the file upload issue: https://github.com/Microsoft/BotFramework-Emulator/releases
