### ISSUE TITLE
[Telemetry Compliance] Dependency scan 

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1578]

**Comment by tonyanziano** [comment]
Currently sitting at 39 alerts:

![image](https://user-images.githubusercontent.com/3452012/57799456-fc1ee080-7703-11e9-9f87-e6f537355598.png)

Tasks for completion:

- [ ] run `npm audit` and update any vulnerable dependencies to resolve alerts
