### ISSUE TITLE
[Telemetry Compliance] Attack surface analyzer

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1579]

**Comment by tonyanziano** [comment]
Status: Have not run the analyzer yet.

Tasks for completion:

- [ ] Run analyzer on baseline machine for each platform **_before_** installing the emulator
- [ ] Run analyzer on baseline machine for each platform **_after_** installing the emulator
- [ ] Use report from analyzer to drive down attack surface on potentially vulnerable services
