### ISSUE TITLE
Crash starting emulator

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/BotFramework-Emulator#158]
![image](https://cloud.githubusercontent.com/assets/6528486/24871285/f68896a2-1dcd-11e7-88c9-688496483b13.png)

**Comment by LarsLiden** [comment]
I had to uninstall and re-install the emulator to fix this issue

**Comment by eanders-MS** [comment]
Thanks for the report.

**Comment by eanders-MS** [comment]
Closing this issue now due to lack of actionable info and lack of repro.
