### ISSUE TITLE
[Telemetry Compliance] Use appropriate linters

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1581]

**Comment by tonyanziano** [comment]
Status: Waiting on an email from security determining if there is a compliant set of ESLint rules we can follow.

Tasks for completion:

- [ ] Get confirmation of ESLint rules
- [ ] If there is a set of ESLint rules, apply them to the project

**Comment by tonyanziano** [comment]
Addressed in corresponding VSO work item.
