### ISSUE TITLE
Emulator should not open the sidebar by default

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Emulator#1585]
## Describe the bug
The Emulator should open with the sidebar closed:
![image](https://user-images.githubusercontent.com/39317542/58056554-61b10980-7b16-11e9-8d5c-a1e47b32694c.png)

**Comment by justinwilaby** [comment]
@mewa1024 - The emulator remembers the mode from the previous session. I believe this won't be an issue once we build #1564

**Comment by justinwilaby** [comment]
resolved by #1564
