### ISSUE TITLE
Unable to see Qna Maker trace

### ISSUE THREAD

**Issue by snapfisher** [microsoft/BotFramework-Emulator#1586]
In the emulator, version 4.4.1, if I click on the QnA Maker trace, in the log, the inspector just shows "Unable to find a QnA Maker service with Knowledge base ID {Guid}.  Please add a QnA Maker Service to your bot", but the QnA Maker service is there and the bot connects to it.  This is some kind of issue in the emulator.  Note that I am using the new template without a .bot file

**Comment by tonyanziano** [comment]
Hi @snapfisher ,

Currently, the LUIS & QnA inspectors (spawned when clicking a LUIS or QnA trace) still require a .bot file with a corresponding service entry in order to work. They cannot be used with a bot that's connected solely via endpoint.
