### ISSUE TITLE
LUIS Trace reporting unauthorized

### ISSUE THREAD

**Issue by snapfisher** [microsoft/BotFramework-Emulator#1587]
Using the emulator version 4.4.1, if I click on a LUIS trace, I get a new log message that says "[LUIS] Unauthorized: Your bot is not configured to interact with LUIS App: {Guid}.  Please connect your bot to LUIS using the services pane", except that my bot is using LUIS just fine and in fact, when I click on the trace link, I am seeing the trace in the inspector.  So there is some issue with the emulator.  I am using the new bot templates without a .bot file.

**Comment by tonyanziano** [comment]
Hi @snapfisher ,

Currently, the LUIS & QnA inspectors (spawned when clicking a LUIS or QnA trace) still require a .bot file with a corresponding service entry in order to work. They cannot be used with a bot that's connected solely via endpoint.
