### ISSUE TITLE
Conversation UI fails to load at first launch

### ISSUE THREAD

**Issue by smacdo** [microsoft/BotFramework-Emulator#1588]
## Version
4.4.1

## Describe the bug
I installed the Bot Framework Emulator (Windows Setup) on two different machines. On both machines I was not able to bring up the conversational view to talk to my bot. The initial screen shows up where it asks for an endpoint url. When I type in my bot's endpoint url and click 'connect' nothing happens. If I create a .bot file and then try to load it, the application's screen is blank.

After I close the emulator and open it again the problem goes away and everything works as expected. This has happened on two different work machines so I don't think it's anything with my box.

## To Reproduce
1. Install emulator
2. Run emulator
3. Add bot endpoint and click connect
4. Nothing happens

## Expected behavior
The bot conversation view shows up

## Additional context

[bug]

**Comment by justinwilaby** [comment]
@smacdo - Did these machines previously have the Emulator installed on them?

**Comment by smacdo** [comment]
No they did not.

**Comment by justinwilaby** [comment]
I am able to repro this as described. It appears the Emulator is attempting to read the `server.json` when first launched but this file is written for the first time on exit. A fix is forthcoming.

**Comment by justinwilaby** [comment]
This was fixed by #1577
