### ISSUE TITLE
ngrok sometimes does not spawn with new Emulator installs

### ISSUE THREAD

**Issue by justinwilaby** [microsoft/BotFramework-Emulator#1597]
ngrok fails to spawn with new Emulator installs sometimes. 

repro steps:

1. On a machine without a previous Emulator install (or after deleting the @bfemulator directory, open a bot with a remote endpoint
2. attempt to connect to the endpoint and let it fail with the "Configure ngrok" message
3. Configure ngrok in the settings 
4. attempt to connect to the remote bot again

expected behavior:
ngrok will spawn and the connection will be successful.

observed behavior:
ngrok does not spawn and the "Configure ngrok" message is still seen

workaround:
Close and reopen the Emulator

**Comment by lobigm** [comment]
Thanks its works

**workaround:
Close and reopen the Emulator**
