### ISSUE TITLE
The application "botframework-emulator.app" can't be opened. OS X

### ISSUE THREAD

**Issue by almirbi** [Microsoft/BotFramework-Emulator#16]
When trying to open the OS X app, I get the following message:

![screen shot 2016-11-22 at 19 42 33](https://cloud.githubusercontent.com/assets/6254473/20537043/dd7895e4-b0eb-11e6-88d7-53fdac644e9f.png)

**Comment by eanders-MS** [comment]
Can you describe how you acquire and launch the app? The way I've successfully done this (on OSX) is to download it, copy the resulting zip to the Applications folder, search for the app in Spotlight, and launch from there.

**Comment by almirbi** [comment]
I did the same

**Comment by almirbi** [comment]
![screen shot 2016-11-23 at 10 11 53](https://cloud.githubusercontent.com/assets/6254473/20556005/483586a2-b165-11e6-8bd5-bb658da12e11.png)

**Comment by almirbi** [comment]
I will try to upgrade to latests OS X

**Comment by almirbi** [comment]
I was using [Keka](http://www.kekaosx.com/en/) to unzip the archive. Seems that that was the problem. Just us the default Archive app and then it works.

**Comment by eanders-MS** [comment]
Our install process on OS X does need improvement.
