### ISSUE TITLE
4.4.2 does not work with Gov-hosted bots

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotFramework-Emulator#1606]
Currently connecting to an Azure Gov bot does not work on the 4.4.2 version of the emulator.

- Connect via endpoint
  - The connect via endpoint dialog does not include the "Azure for US Government Learn more." checkbox that is available when adding a new endpoint to the bot file.
  - Webchat correctly renders, but all messages are Unauthorized
  - Emulator emits the standard "incorrect MSA AppID and MSA AppPassword message"
- Connect via bot file
  - The "Azure for US Government Learn more." was checked.
  - Webchat does not finish rendering.
  - No data on if any activities are sent to the bot

Above data was from testing with @hristp 
The bot hosted in Azure Gov was working with the Test in WebChat in the portal.

### Completion criteria:
- [x] **Connecting to bot in Azure Gov via endpoint should work**
   - ~[ ] Need extendable UI for different sovereign regions~ _Not needed until we add more National Clouds_
- [x] **Connecting to bot in Azure Gov via .bot file should work**
   - ~[ ] Need extendable UI for different sovereign regions~ _Not needed until we add more National Clouds_
- [x] **Inspector mode also works with bot in Azure Gov**
- [ ] **OAuth with a Gov bot should work**
- [x] **Add protocol support (`"livechat"` and `"inspector"`) (new arg for public, `.us`)**

**Comment by stevengum** [comment]
I'm going to try a repro today or early next week, I think this might technically be a P0 but I will leave that to you @cwhitten

**Comment by stevengum** [comment]
I have a repro, but am currently working on #1567

**Comment by cwhitten** [comment]
Confirmed regression against v4.2. I've re-labeled as a P0 for the July release train.

**Comment by hristp** [comment]
Consider using the string "AzureUSGovernment" for Fairfax, to be consistent with naming throughout Azure CLI.

**Comment by stevengum** [comment]
On further investigation, passing a `channelService` value in to `getBotEndpoint` when it pushes a new Endpoint onto the EndpointSet will permit communication with a Gov-hosted bot.

It looks like we may need to add a new header for channel service (e.g. `x-emulator-channelservice`) to pass it in. This leads to the question of what do we want this value to look like, either a simple value like `"public"` or `"usgov"` or the actual value used `""` or `"https://botframework.azure.us"`

`packages\emulator\core\src\conversations\middleware\getBotEndpoint.ts`

```ts
import * as Restify from 'restify';

import { BotEmulator } from '../../botEmulator';
/** NEW **/
import { usGovernmentAuthentication } from '../../authEndpoints';

export default function getBotEndpoint(botEmulator: BotEmulator) {
  return (req: Restify.Request, res: Restify.Response, next: Restify.Next): any => {
    const request = req as any;
    const { endpoints } = botEmulator.facilities;
    /**
     * IF query params exist, the call is creating a
     * conversation independent from a bot file.
     */
    if (req.headers && 'x-emulator-botendpoint' in req.headers) {
      const {
        'x-emulator-botendpoint': botUrl,
        'x-emulator-appid': msaAppId = '',
        'x-emulator-apppassword': msaPassword = '',
      } = req.headers as { [prop: string]: string };

      let endpoint = endpoints.get(botUrl);
      if (!endpoint) {
        const params = req.body as any;
        endpoint = endpoints.push(null, {
          botId: params.bot.id,
          botUrl,
          msaAppId,
          msaPassword,
          /** NEW **/
          channelService: usGovernmentAuthentication.channelService
        });
      } else {
        // update the endpoint in memory with the new
        // appId and password if they exist in the params
        if (msaAppId) {
          endpoint.msaAppId = msaAppId;
        }
        if (msaPassword) {
          endpoint.msaPassword = msaPassword;
        }
      }
      request.botEndpoint = endpoint;
    } else {
      request.botEndpoint = endpoints.getByAppId(request.jwt.appid);
    }

    return next();
  };
}
```

**Comment by stevengum** [comment]
The work being done is currently on the [`stgum/gov`](https://github.com/microsoft/BotFramework-Emulator/tree/stgum/gov) branch ([first commit](https://github.com/microsoft/BotFramework-Emulator/commit/317411e9406f822647fac8f8aa75a49f2af8abd7)).

### Completed:
- Refactor to pass ChannelService in
- Protocol support for the Channel Service via `cloud`
  - example: `&cloud=azureusgovernment`

### WIP:
- Tests
- Add UI to connect to bot via Endpoint
- Additional cleanup
