### ISSUE TITLE
Cannot connect to new bot without credentials after previously connecting to one with

### ISSUE THREAD

**Issue by chivandikwa** [microsoft/BotFramework-Emulator#1622]
## Version
4.4.2

## Describe the bug
If I connect to a bot that has credentials then try and open a new chat with another bot that does not have credentials even though I leave the options blank it still cannot connect and I get 401 error. The only way around this is to close the application and start again.

## To Reproduce
1. Start up a bot that has an app ID and app password
2. Connect to bot using emulator
3. Start up a bot that does not have an app ID and app password
4. Connect to bot using emulator. Not how there are now 401 error
5. Restart emulator
6. Conect again to bot using emulator. Works as expected now.

## Expected behavior
I expect to be able to create chats between multiple bots easily.

## Screenshots

[bug]

**Comment by justinwilaby** [comment]
@denscollo - I tested this with multiple bots and scenarios was not able to repro. If you are able to repro this and the steps you took differ from those provided by @chivandikwa, please feel free to update this ticket.

**Comment by denscollo** [comment]
@justinwilaby after reviewing different scenarios, we were able to reproduce the issue by following the next steps:

1. Start up a bot with credentials in port [localhost:3978].
2. Connect it using emulator.
3. Stop the execution of the bot.
4. Start up a bot without credentials in the same port [localhost:3978].
5. Connect again using emulator.

It seems that the second bot is receiving the credentials of the first bot. We'll check it and see if we can find a way to solve it!
