### ISSUE TITLE
URL connection to local bot requires appId and app

### ISSUE THREAD

**Issue by diberry** [microsoft/BotFramework-Emulator#1632]
## Version
What version of the Emulator are you using.

4.4.2

## Describe the bug
Expect to be able to connect to a locally running bot with a locally running emulator via URL without appId or appPassword.

## To Reproduce
1. Download ABS basic bot (C#, v4)
2. Run, wait for brower to open with bot web site.
3. Open emulator, connect via http://localhost:3978/api/messages with no other settings. 
4. Enter "hello" as user text and submit.
5. Log says
[11:39:25]Emulator listening on http://localhost:51203
[11:39:26]ngrok listening on https://cfacaa58.ngrok.io
[11:39:26]ngrok traffic inspector:http://127.0.0.1:4040
[11:39:26]Will bypass ngrok for local addresses
[11:39:27]
[11:39:27]POST401directline.conversationUpdate
[11:39:27]
[11:39:27]POST401directline.conversationUpdate
[11:39:27]POST200directline.startConversation
[11:39:31]-> messagehello
[11:39:31]Cannot post activity. Unauthorized.
[11:39:31]POST401directline.postActivity

6. New connection, same url with appId and appPassword, the bot responds as expected.

## Expected behavior
Expect to get working bot response

## Additional context
When does a local bot need appId and appPassword for a URL connection

[bug]

**Comment by tonyanziano** [comment]
Hi @diberry ,

Did you mean for this to be a feature request? This is working by design.

If your local bot is initialized with code that expects an appId & password, such as a C# sample with both values filled out in `appsettings.json`, then your bot will return a 401 if those credentials are not passed in, regardless of whether it is local or not.

This is a requirement inside of the bot code, and not something that the Emulator can control.

**Comment by diberry** [comment]
@tonyanziano How do I know when my bot needs the appId and password. I don't think it is something I selected - perhaps it is a default setting someplace?

**Comment by tonyanziano** [comment]
@diberry If you are using one of the **C# samples**, the AppId & Password will be located inside of `appsettings.json` within the root of the project.

You can find examples of that [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/02.echo-bot/appsettings.json) and [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.core-bot/appsettings.json).

If you are using a **JavaScript** sample, then the values will be pulled from the environment variables `MicrosoftAppId` & `MicrosoftAppPassword` as seen in [this file.](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/02.echo-bot/index.js#L30)

**Comment by diberry** [comment]
@tonyanziano I created an azure bot service bot (basic c#). I didn't select the check boxes for appId and appPassword when I created the bot, although I did see that they were there. Who on the ABS side, can I ask about this internally?

**Comment by diberry** [comment]
#please-close
