### ISSUE TITLE
The conversation mock up takes very long time (30 seconds) to show up after loading the transcript

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Emulator#1637]
## Version
4.4.2

## Describe the bug
The conversation mock up takes long time to show up after loading the transcript(any size), roughly 30 seconds.

## To Reproduce
1. Load any test transcript, and initially the mock up won't show up
2. Wait about 30 seconds, you will see the mock up shows up.

## Expected behavior
Conversation Mock View shows up instantly with the LOG view..

## Additional context
I saw there was a recent fix from ISSUE #1256 to address the load failure, could it be related?

**Comment by tonyanziano** [comment]
Hi @dawwa ,

The fix for #1256 shouldn't have caused any performance issues, but it is possible. I'll try to repro this issue and figure out what's going on.

**Comment by tonyanziano** [comment]
Going to close this issue in favor of tracking the issue at #1623

**Comment by tonyanziano** [comment]
Check if this is fixed by #2034
