### ISSUE TITLE
Taking longer than usual to connect.

### ISSUE THREAD

**Issue by aragornwu1308** [microsoft/BotFramework-Emulator#1639]

**Comment by aragornwu1308** [comment]
can not connect to the bot and always show 'Taking longer than usual to connect.
'

**Comment by zsiebers** [comment]
@aragornwu1308 did you figure out what the issue was?

**Comment by aragornwu1308** [comment]
yeah, something wrong when generating the .bot file

**Comment by cooperka** [comment]
For what it's worth, I got this "Taking longer than usual to connect" warning when I tried connecting to my bot that had a Twilio integration set up. I had to remove the adapter for the emulator to be able to connect. Beginner mistake!

```diff
 const controller = new Botkit({
   webhook_uri: '/api/messages',
-  adapter, // Remove this line
 });
```

**Comment by 4ININ** [comment]
If you try to test your bot with Bot Framework Emulator, try to connect like a http://localhost:<your port>/api/messages without https!!!
