### ISSUE TITLE
Microphone button not visible when opening bot via URL

### ISSUE THREAD

**Issue by stevkan** [microsoft/BotFramework-Emulator#1640]
## Version
4.4.2

## Describe the bug
The microphone does not display when accessing a bot via the Open Bot command (with credentials) found on the Welcome page. However, the microphone does display if the bot is accessed via a .bot file (with credentials).

## To Reproduce
1. Click Open Bot on Welcome page
2. Type in endpoint and associated Id / Password for the bot
3. Click Connect
4. Notice no microphone appears, only the send button in its place

Steps to reproduce correct behavior via .bot file:
1. Create or open a .bot file
2. Verify Id / Password for the bot have been applied and saved
3. Click Save & Connect
4. Microphone is visible in place of the send button

## Expected behavior
The microphone should display when accessing a bot via the Open Bot command on the Welcome page.

## Screenshots
Using Open Bot:
![image](https://user-images.githubusercontent.com/18403946/59628488-999b7480-90f5-11e9-854a-9959bb8e6518.png)

Using .bot file:
![image](https://user-images.githubusercontent.com/18403946/59628529-b2a42580-90f5-11e9-8836-3aa6f10d5719.png)

[bug]

**Comment by justinwilaby** [comment]
I am able to repro this issue and I have a fix forthcoming. The root cause is the botfile is not used when opening a bot via url so no endpoint is found and thus, no speech token is retrieved.
