### ISSUE TITLE
All of a sudden, Emulator stopped showing message input box and Restart button

### ISSUE THREAD

**Issue by siva3378** [microsoft/BotFramework-Emulator#1645]
## Version
4.4.2 (4.4.2.61547)

## Describe the bug
I was using 4.4.1, but in the background, it got updated to 4.4.2 and few things stopped working:

1. There is no "Message input box" in the bottom
2. There is no "Restart" button
3. When I try to open a new bot which is running locally, bot framework is triggering "onMessage" event instead of "onMembersAdded" with the text "/INSPECT open"

## To Reproduce
Steps to reproduce the behaviour:
1. Start running the bot (anyone from javascript node bot samples
2. Open Emulator
3. Open Bot which is running locally

## Expected behaviour
1. Restart button, Message input box should be visible

## Screenshots
![image](https://user-images.githubusercontent.com/9330864/59772664-7e269a00-92ac-11e9-8fc0-dc95c0d3d892.png)

## Additional context
OS: Mac Mojave

[bug]

**Comment by tonyanziano** [comment]
@siva3378  I believe you might be in "Inspector Mode" when you do not mean to be.

You can get out of this mode by going to the application menu bar clicking on "View," and unchecking "Bot Inspector Mode."

![image](https://user-images.githubusercontent.com/3452012/59790647-46f0c280-9285-11e9-9556-6b92e38499da.png)


This is a feature that has been overhauled pretty drastically in recent versions. If you want to try the latest and greatest, try out the latest [nightly build.](https://github.com/microsoft/botframework-emulator-nightlies/releases)

**Comment by siva3378** [comment]
I'm feeling very stupid now. Sorry for this invalid bug.

**Comment by tonyanziano** [comment]
No worries! This feature isn't very well-documented yet, so I can see how this could happen.
