### ISSUE TITLE
Focus Send Box after Restarting Conversation

### ISSUE THREAD

**Issue by MJ422** [microsoft/BotFramework-Emulator#1646]
It would be very helpful, and a huge plus for developer convenience, if we could quickly start drafting a message instead of having to click 'Restart conversation' then scroll down & click in to the 'Type a message' field to begin a new message after restarting. 

Alternatively, we could allow 'tab' command to quickly jump into 'Type your message' box.

Cheers!

**Comment by justinwilaby** [comment]
@MJ422 - 

So focusing the input after restarting a conversation would be desired?

**Comment by MJ422** [comment]
yes, that would be very helpful! It just can be a bit tedious clicking restart, then clicking the input-message field, then starting to type. Thanks for the reply!!

**Comment by justinwilaby** [comment]
I agree with you on this. I too restart conversations many dozens of times a day...

I'll bring this up with the team and see if we can add it to the next release.

**Comment by justinwilaby** [comment]
reference [this diff](https://github.com/microsoft/BotFramework-WebChat/pull/2087/files#diff-8ccddae778bd3eb72d4f4496ee7fb191) for webchat implementation

**Comment by MJ422** [comment]
Does this apply to the Bot Framework Emulator as well? Just a little confused about where to implement that change in the code linked in your last comment @justinwilaby. I'm pretty new to all this 🤷‍♂ 😊

**Comment by justinwilaby** [comment]
@MJ422  - Ignore my last comment. It was more of a note to identify where this was implemented in webchat. I'm not sure yet if this is how we'd implement it in the Emulator.

**Comment by cwhitten** [comment]
@MJ422 we're going to close this as "working as designed". Accessibility requirements don't allow us to short circuit expected focus behavior when interacting with actionable buttons.
