### ISSUE TITLE
Bot emulator fails to connect due to proxy environment variables

### ISSUE THREAD

**Issue by ebmtz** [microsoft/BotFramework-Emulator#1647]
Hello. I was having issues connecting the bot emulator to my virtual assistant template. I was always getting a `Taking longer than usual to connect` message, but nothing seemed to be wrong with my setup. I develop behind a corporate proxy, and it turns out that the emulator was taking my  `HTTP_PROXY` and `HTTPS_PROXY` environment variables and trying to go through the proxy and connect to localhost. The proxy simply kept blocking the connection and I wasn't able to move forward until I deleted the variables from my system.

This feels like it shouldn't happen. Especially since I'm developing locally and the emulator seemed insistent onto using the proxy anyways. Which is even weirder is that our network is set up to bypass the proxy for local connections, so I'm really not sure how this even happened.

**Comment by justinwilaby** [comment]
Thank you for posting this. I believe our documentation may be missing the specifics on these settings. In this case, using the `NO_PROXY` env variable should fix it. 

For example: `NO_PROXY=localhost` will disable the proxy for urls including the string `localhost`.

If this is still an issue or if you are having trouble, feel free to contact us again.

**Comment by ebmtz** [comment]
Woow that worked. I wish I'd known about this way earlier. Thanks! I'll close the issue then.

**Comment by vijaysaimutyala** [comment]
@ebmtz How do I set this variable. I tried the below and it did not seem to work. I set the internet options to "Automatically detect settings" like below

![image](https://user-images.githubusercontent.com/7084628/84531083-a3a08500-ad01-11ea-9448-e4bde4380a57.png)

and before running my bot, I did the below which did not work. Am I right here ?

`set NO_PROXY=localhost`

**Comment by ebmtz** [comment]
I never had to mess with my LAN settings. I had simply defined the values for `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`. After defining those, things were working okay. Sorry if this doesn't help much, but that's all I did.

**Comment by vijaysaimutyala** [comment]
Thanks @ebmtz I'll try it out.
