### ISSUE TITLE
Bot Emulator Connectivity issue

### ISSUE THREAD

**Issue by jacobchikku** [Microsoft/BotFramework-Emulator#165]
I am trying to connect just a Hello world bot application and its getting the error POST connect ECONNREFUSED 127.0.0.1:3978, on the emulator, i have tried with valid MSA id and secret and also blank ones. but still receiving the same.

**Comment by jacobchikku** [comment]
Resolved this issue by downloading and unzipping and copying the Visual Studio Bot Application template from https://docs.botframework.com/en-us/downloads/

**Comment by eanders-MS** [comment]
I'm glad you found a solution!
