### ISSUE TITLE
Where is the emulator installed? 

### ISSUE THREAD

**Issue by targetnull** [Microsoft/BotFramework-Emulator#166]
I'm using the latest release version 3.5.27, the emulator works fine in the first run, but I can't find anything like a shortcur on my desktop or in the start menu. So I have to click the installer every time I want to run the emulator, and that is slow. Where is the emulator installed on my Windows 10, can I use a shortcut? Thanks.

**Comment by eanders-MS** [comment]
Hi @targetnull This is a regression in the latest build. We're prepping a recovery build and will have a patch out soon.

**Comment by mohamedmansour** [comment]
Happened to me too, but it is located in:

`C:\Users\Mohamed\AppData\Local\botframework\app-3.5.27`

I right clicked on `botframework-emulator.exe` and add it to start menu, for now.

**Comment by LlewellynJones** [comment]
I tried that and when I ran the emulator I got:

write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-x64\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

**Comment by LlewellynJones** [comment]
I've been giving this thing a good college but it no work... Pointing to c:\jenkins... huh?

**Comment by eanders-MS** [comment]
@LlewellynJones Pay no mind to that file path. It's just debugging information encoded into the Electron binary at the time it was built.

Your error message suggests you are able to launch the emulator, but are getting this error when trying to send your bot a message. Is this what you're experiencing?

**Comment by LlewellynJones** [comment]
Okay, I see what I was doing, connecting to https://... not http://... and
my app didn't have ssl enabled. I'm okay with running it from the appdata
folder for now.


Cheers,
James
my own book <http://myownbook.org>

**Comment by eanders-MS** [comment]
We released emulator version 3.5.28 today, with a fix for the "no shortcut" bug. Direct download link: https://github.com/Microsoft/BotFramework-Emulator/releases
