### ISSUE TITLE
Uploaded JSON file attachment garbled by emulator

### ISSUE THREAD

**Issue by weretygr** [microsoft/BotFramework-Emulator#1666]
## Version
4.4.2+

## Describe the bug
Uploading a JSON file with a file size of 79 bytes results in a downloaded file of length 8278.  The downloaded file contents cannot be converted back to the original contents.

## To Reproduce
1. Connect to a bot running v4 with the emulator
2. Click on the Upload button
3. Upload a well formed JSON file after determining the length of the file
4. Within the bot (OnTurnAsync method) , use the following code snippet to examine the length of the attachment and the contents

```
var activity = turnContext.Activity;
HttpClient httpClient = new HttpClient();
var responseMessage = await httpClient.GetAsync(attachment.ContentUrl);
var contentLengthBytes = responseMessage.Content.Headers.ContentLength;
var data = await responseMessage.Content.ReadAsStringAsync();
var bo = JObject.Parse(data);
JToken t = bo["data"];

var databytes = t.Children().Select(x => (byte)x).ToArray();
var stringJson = (Encoding.Default.GetString(
    databytes,
    0,
    databytes.Length));
var yourJson = JsonConvert.DeserializeObject<Object>(stringJson);
```

## Expected behavior
After executing the code snippet, the contents of the yourJson variable should be to contents of the original JSON file. The contentLengthBytes variable should not be multiples of the length of the original file.

[bug]

**Comment by tonyanziano** [comment]
I'm able to repro this, and looking into it.

**Comment by tonyanziano** [comment]
I've got a fix that looks promising on a local branch. Since we are in a code-freeze for the upcoming 4.5 release of the Emulator, you can look for this change in a nightly the week after 4.5 releases (sometime next week).

I'll update this thread accordingly.

**Comment by tonyanziano** [comment]
There's a PR up now. Once it gets merged, @weretygr you can download the first available nightly build (they build every night at 10PM PST) afterwards and the issue should be fixed.
