### ISSUE TITLE
Drop down list is collapse when I'm trying to select a value 

### ISSUE THREAD

**Issue by Shon-Elias** [microsoft/BotFramework-Emulator#1683]
## Version
What version of the Emulator are you using?
Version 4.5.1

## Describe the bug
I'm trying to select a value from the list but every time I open the list and hover the list it collapsed (**Input.ChoiceSet**)

## To Reproduce
1. using the emulator Version 4.5.1
2. try to select a value from Input.ChoiceSet
[bug]

**Comment by tonyanziano** [comment]
This is probably due to the same logic that caused #1680 .

We should be able to add a check for `<select>` tags like we did for `<input>`'s in #1681

**Comment by tonyanziano** [comment]
This issue has been fixed in the newest release, [4.5.2](https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.5.2) available now.
