### ISSUE TITLE
Add settings to more completely enable Direct Line similar behaviors

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Emulator#1689]
The Direct Line channel has a number of limitations not currently present in the Emulator: max message size, max file size, etc.  It would be useful for the Emulator to provide settings with default values similar to those of Direct Line.

[enhancement]

**Comment by tonyanziano** [comment]
Is there a compiled list of these limitations somewhere that we could use as a reference?

**Comment by EricDahlvang** [comment]
I'm not aware of a complete list of limitations per channel.  I just know this has come up multiple times: a customer develops a bot using the Emulator, then publishes the bot to a specific channel, only to find out that the channel has limitations they were unaware of (limitations that could have been highlighted during development, if the emulator also had those limitations).  Specifically, multiple customers have run into the file size limits of Direct Line, and have been confused why it works as expected with the Emulator.

@dandriscoll suggested via email exchange that this feature request might not be practical.  We should consult him too.

**Comment by daveta** [comment]
Closing per @EricDahlvang.
