### ISSUE TITLE
From.Id is changing on messages within a conversation

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Emulator#1695]
## Version
4.5.2-71403 (Mac)

## Describe the bug
When running the Emulator on the Mac the From.Id property on Activities being sent to the Bot are changing on every message. Also setting the UserId in the Emulator to specific ID is not respected and shows the same issue of a constantly changing UserId.

## To Reproduce
1. Send a message, inspect the `From.Id` in the inspector
2. Send another message and observe `From.Id` has changed

## Expected behavior
- Consistent `From.Id` for the session of the Emulator
` Providing an ID in Settings should be used.

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/61714511-e2a3a180-ad0f-11e9-8a6d-f90f984fcfff.png)

![image](https://user-images.githubusercontent.com/33519520/61714530-ecc5a000-ad0f-11e9-9fdb-c61071699bf3.png)

## Additional context
- Seems to fix 4.5 builds, I went back to the first 4.5 build and could repo
- Installing 4.4.2 doesn’t show this behaviour

[bug]

**Comment by tonyanziano** [comment]
Hi @darrenj ,

You actually are not expanding the `from` property in the JSON viewer. The `id` field you are looking at is the activity id at the root level, which _should_ be unique:

![image](https://user-images.githubusercontent.com/3452012/61731510-7dac7380-ad30-11e9-82b6-5d8304a3a3f8.png)

![image](https://user-images.githubusercontent.com/3452012/61731530-8b61f900-ad30-11e9-9d34-f1db06b46c6b.png)

**Comment by darrenj** [comment]
Thanks - confirmed, the ID is working as expected and it was the nesting that was confusing!
