### ISSUE TITLE
Publish packages to npm

### ISSUE THREAD

**Issue by mrgrain** [microsoft/BotFramework-Emulator#1707]
**Is your feature request related to a problem? Please describe.**
Using the botframework emulator cli and in automated or half-automated environments is currently not possible, unless the repository is cloned and the necessary npm/lerna commands are run. 

**Describe the solution you'd like**
Packages that are suitable for third-party consumption should be published to npmjs. Most notably `@bfemulator/emulator-cli` and `@bfemulator/emulator-core`.

**Describe alternatives you've considered**
Forking and publishing a version myself, but this would take away authority from the actual maintainers. Due to the monorepo,  depending on the git repo isn't possible either.

**Additional context**
The emulator-cli is a very useful tool to automate communication for the botframework. Especially when using testing tools like Botium. Having the packages published to npm will allow one to easily and consistently depend on it.

[enhancement]

**Comment by cwhitten** [comment]
Hi @mrgrain 

We don't have plans to publish these packages independently of the Emulator application. That said, the Bot Framework is working on a new umbrella cli tool. I'd like to connect you with @scheyal  to better understand your scenarios and see if it aligns with the roadmap being developed.

**Comment by mrgrain** [comment]
Thanks @cwhitten. Very keen to hear more about what @scheyal is doing.
