### ISSUE TITLE
how to install it on ubuntu?

### ISSUE THREAD

**Issue by fredia** [Microsoft/BotFramework-Emulator#171]
hello,I download the source code,and unzip it,but I don't know how to do next?

**Comment by eanders-MS** [comment]
Hi @fredia, If you'd like to build from source, follow the instructions in the `Build and Run from Source` section, here: https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute

If you'd rather install the binary distribution, download the .AppImage file for your architecture from the releases page: https://github.com/Microsoft/BotFramework-Emulator/releases

**Comment by sayak1711** [comment]
Can't find the "Test in Emulator" option in the AppImage in Ubuntu(PopOS)
