### ISSUE TITLE
[Usability][Screen reader-Welcome]In scan mode narrator focus encountered twice on welcome tab control and reading same info.

### ISSUE THREAD

**Issue by awalia13** [microsoft/BotFramework-Emulator#1718]
**Actual Result:**
In scan mode Narrator focus encountered twice on welcome tab control and reading same info which present in the welcome tab screen 

**Expected Result:**
In scan mode Narrator focus should not encountered twice on welcome tab control and should read the info once.
Example: In scan mode first should read as welcome tab after press the down arrow key should read as close button .

Note: Same issue repro with NVDA
This issue exits throughout the application for all text fields.
Note 1:Same issue repro below path
 Navigate to the Open bot ->Select the Open bot control->Open bot dialog
In scan mode narrator focus twice encountered on Microsoft app ID and Microsoft app password reading as same .
Please refer the attachment: Usability_Open bot dialog.zip
Same issue repro for below path also.
Welcome Bot Framework Emulator ->Create new bot configuration
In scan mode narrator focus twice encountered on Microsoft app ID and Microsoft app password reading as same .
Welcome Bot Framework Emulator->Open bot ->Open bot dialog ->Connect to the bot ->Live chat screen ->Edit ngrok setting
Please refer the attachment:Usability_Settings.zip
Screen reader focus twice encountered on the every text field and second time reading as blank.
Resources->Transcripts and chat files->choose a different location.
Screen reader focus twice encountered on the every text field and second time reading as blank.
Please refer the attachment:Usability_Choose.a.file.location.zip

**Repro Steps:**
Turn on the narrator 
1. Open the Bot Framework V4 Emulator.
2. Navigate to the Welcome tab screen using scan mode (Down arrow key)
3. Navigate to the welcome tab  
4. Observe the issue

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader focus encountered twice on same control and reading the same info so screen reader user will misguide information .

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator
[Usability_Welcome.zip](https://github.com/microsoft/BotFramework-Emulator/files/3491851/Usability_Welcome.zip)
[Usability_Open bot dialog.zip](https://github.com/microsoft/BotFramework-Emulator/files/3509353/Usability_Open.bot.dialog.zip)
[Usability_Settings.zip](https://github.com/microsoft/BotFramework-Emulator/files/3529985/Usability_Settings.zip)
[Usability_Choose a file location.zip](https://github.com/microsoft/BotFramework-Emulator/files/3534213/Usability_Choose.a.file.location.zip)

**Comment by Kumar2608** [comment]
Verified with Latest bot emulator version 4.5.2-7815 and NVDA 2019.2 issue got fixed now hence we are closing this bug
