### ISSUE TITLE
[MAS4.2.1][Screen reader-Welcome] In scan mode narrator is reading as “1 of 1 plan “ which is not meaning full info.

### ISSUE THREAD

**Issue by awalia13** [microsoft/BotFramework-Emulator#1719]
**Actual Result:**
In scan mode narrator is reading as “1 of 1 plan “which is not meaning full info which is present in the how to build a bot section 
Same issue repro for Build, Test, Publish, Connect, Evaluate.

**Expected Result:**
In scan mode narrator should read as “plan “.
For remaining elements also  Build, Test, Publish, Connect, Evaluate screen reader should read the proper info.

**Note:** Issue is not repro’ing with NVDA 

**Repro Steps:**
Turn on the narrator 
1. Open the Bot Framework V4 Emulator.
2. Navigate to the Welcome tab screen 
3. Navigate to the How to Build A bot section using down arrow key 
4. Observe the issue

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader is reading the unnecessary info then screen reader users will misguide the info. 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}](url)
[MAS4.2.1_Welcome.zip](https://github.com/microsoft/BotFramework-Emulator/files/3491907/MAS4.2.1_Welcome.zip)
![MAS4 2 1_Welcome](https://user-images.githubusercontent.com/46575396/62859732-98647d80-bd1b-11e9-8857-84e92fd15f23.png)

**Comment by Kumar2608** [comment]
Verified. Issue is working fine in NVDA. Hence Closing the issue
NVDA Version: 2019.1.1
