### ISSUE TITLE
Error 504 when connecting the emulator to my bot

### ISSUE THREAD

**Issue by Popo0463** [Microsoft/BotFramework-Emulator#173]
Hello,

I always receive a Error 504 : `[15:17:28] -> POST 504 [conversationUpdate]` when I try to connect emulator to my bot, even with a simple "hello world" bot. 
Version of emulator : 3.5.27
Version of node.js : v6.10.2

Can you help me ?
Thank you.

**Comment by eanders-MS** [comment]
Hi @Popo0463  Can you tell me a bit about your environment:

- Is your bot running on the same machine as the emulator, or hosted remotely?
- Are you running with MSA appId & password, or without credentials?
- What exactly are you seeing in:
  - The bot's console output.
  - The emulator's log view.

**Comment by Popo0463** [comment]
The bot is running on the same machine as the emulator, without credentials. Here is what I see :
![capture](https://cloud.githubusercontent.com/assets/22705014/25655434/1c0bd84c-2ff5-11e7-8676-e460dfb805fc.PNG)

**Comment by eanders-MS** [comment]
This might be happening due to your machine's proxy configuration. Can you try configuring your machine to bypass proxy for local addresses?

**Comment by Popo0463** [comment]
I configure my PC to bypass proxy for local addresses, but there is still an error 504. 
![capture](https://cloud.githubusercontent.com/assets/22705014/25900892/47cdb766-3595-11e7-8913-4e918a493d28.PNG)

**Comment by MarcoScabbiolo** [comment]
May be related to #187. When bypassing the proxy for local addresses do it both for `localhost` and `127.0.01`
