### ISSUE TITLE
[MAS4.2.8] [Programmatic and access -Welcome] An element of the given Control Type must support the Text pattern for Secret text field 

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1748]
**Actual Result:**
An element of the given Control Type doesn’t support the Text pattern for Secret text field present in the New bot configuration dialog.

**Expected Result:**
An element of the given Control Type must support the Text pattern for Secret text field
**How To Fix:** 1. Make sure the element has the appropriate Control Type property for its function.
2. If the current Control Type is correct, modify the element to support the Text pattern.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the Welcome pane 
4. Run the accessibility insights for windows tool 
5. Observe the issue

**User Impact:**
users who rely on AT will be affected if programmatically control type is not defined properly so the AT users will misguide the information 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Tools: Accessibility insights for Windows 

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={2f57ba18-487d-4adc-a077-377be980e7d5}](url)
![MAS4 2 8_New Bot configuration](https://user-images.githubusercontent.com/53518994/63323564-bb0e1c00-c343-11e9-9a9c-5885b210b538.png)

**Comment by tonyanziano** [comment]
Related to #1767

**Comment by Kumar2608** [comment]
As directed by customer, electron app wont support Accessibility Insights for Windows
hence we are closing this bug .
