### ISSUE TITLE
[MAS4.1.2] [Screen reader-Restart conversation menu] Screen reader is not reading the Name and state for Restart conversation menu

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1750]
**Actual Result:**
Screen reader is not reading the Name and state for Restart conversation menu

**Expected Result:**
Screen reader should read the Name and state for Restart conversation menu
Example: Screen reader should narrate as Restart conversation menu expanded\Collapsed 

**Note:** Issue is repro’ing with NVDA. Please refer attachment below

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the open bot and select it  
4. Dialog gest opened and connect the open bot  
5. Live chat screen gets opened 
6.Navigate to the Restart conversation menu 
7.Observe the issue.

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader is not reading the Name and state for menu control screen reader user will be affected.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator
 
**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}](url)
[MAS4.1.2_Restart Menu.zip](https://github.com/microsoft/BotFramework-Emulator/files/3519547/MAS4.1.2_Restart.Menu.zip)
![MAS4 1 2_Restart Menu](https://user-images.githubusercontent.com/53518994/63332863-f9143b80-c355-11e9-8b49-7135c4993894.png)
[MAS4.1.2_Restart menu_NVDA.zip](https://github.com/microsoft/BotFramework-Emulator/files/3545883/MAS4.1.2_Restart.menu_NVDA.zip)

**Comment by Kumar2608** [comment]
Verified in latest Bot emulator version -4.5.2-79718 .Issue partially fixed. hence we are reactivating this bug 
Now NVDA is reading as Restart conversation sub menu 2 of 3 but state is not announcing.

**Expected:** NVDA should read as "Restart conversation sub menu 2 of 3 expanded\Collapsed .

**Comment by corinagum** [comment]
@Kumar2608 or @awalia13, could you provide feedback on how best to resolve this issue? The code has `aria-expanded` applied to both states on this widget. As far as I know we don't have a way of forcing the screen reader to read that state out. Please see below for code showing aria-expanded true and false in both states.
![image](https://user-images.githubusercontent.com/14900841/65447697-035da580-ddec-11e9-908f-c2e75a18f5b1.png)
![image](https://user-images.githubusercontent.com/14900841/65447720-0a84b380-ddec-11e9-8aaf-075c3e34e203.png)

**Comment by awalia13** [comment]
Had a call with @corinagum. Please find below details.
Code seems good to me. NVDA support aria-haspopup attribute and take precedence over aria-expanded when both attributes are getting used. Because of aria-haspopup attribute NVDA is reading it as Submenu and when control goes to menuitems at that time it is providing full information of menu items along with position which is fine. Hence closing this bug.
