### ISSUE TITLE
[MAS4.1.2] [Screen Reader-Restart conversation menu] Screen reader is reading the wrong selection information for “Restart with new user ID and Restart with same user ID”

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1751]
**Actual Result:**
Screen reader is reading the wrong selection information for “Restart with new user ID and Restart with same user ID”
Screen reader is reading as Restart with new user ID 1 of 2 selected 

**Expected Result:**
 Screen reader should narrate as restart with new user ID menu item \Screen reader should narrate as restart with same user ID menu item.

**Note:** Issue is repro’ing with NVDA 
**Repro Steps:**
Turn on the Narrator 
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the open bot and select it  
4. Dialog gest opened and connect the open bot  
5. Live chat screen gets opened 
6.Navigate to the Restart conversation menu and select it 
7.Navigate to the “Restart with new user ID and Restart with same user ID” using down arrow key 
7.Observe the issue.

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader is reading the wrong selection information for menu items  screen reader user will be affected which menu got selected 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator 

**MAS Reference Link:**
[Sharepoint Link](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730})
[MAS4.1.2_Restart.zip](https://github.com/microsoft/BotFramework-Emulator/files/3519662/MAS4.1.2_Restart.zip)
![MAS4 1 2_Restart](https://user-images.githubusercontent.com/53518994/63333807-ab98ce00-c357-11e9-84ea-80f966ec24b5.png)

**Comment by tonyanziano** [comment]
I'm unclear on what accessibility pattern this control is supposed to follow.

If you look at this [ARIA example of an action menu button](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html) from W3, the narrator reads that menu exactly the same as it reads the Restart conversation menu in the Emulator.

Are there certain ARIA patterns that are not deemed as acceptable by MAS requirements? Or is there a list of approved ARIA patterns we can use?

**Comment by Kumar2608** [comment]
Verified. Issue is working fine in NVDA. Hence Closing the issue
NVDA Version: 2019.1.1
