### ISSUE TITLE
[MAS4.1.2] [Screen reader-Setting] Screen reader is not reading the state for checkboxes when the user selected the checkbox 

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1770]
**Actual Result:**
Screen reader is not reading the state for checkboxes when the user selected the checkbox 
“User settings, Application updated, data collection “ section under checkboxes 

**Expected Result:**
Screen reader should narrate the state for checkboxes when the user selected the checkbox
Example: Screen reader should narrate as Use version 1.0 authentication tokens check box checked when the user selected the check box 

**Note:** Issue is repro’ing with NVDA
**Note1:** This issue exits throughout the application for all checkboxes 

**Repro Steps:**
Turn on the narrator 
1.Open the Bot Framework V4 Emulator.
2.Navigate to Welcome tab screen and select it, screen gets opened  
3.Navigate to the open bot and select it  
4.Open bot dialog gets opened and connect to the open bot 
5.Live chat screen gets appears 
6.Navigate to the Edit ngrok settings and select it 
7.Emulator screen gets opened 
8.Navigate to the “1. User settings 2. Application updates 3. Data collection” section check boxes 
9.Observe the issue

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader is not reading the state for checkboxes screen reader user will be affected whether check boxes are in which state.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
Screen reader: Narrator

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}](url)
![MAS4 1 2_Setting](https://user-images.githubusercontent.com/53518994/63511689-7f1fb600-c4ff-11e9-8f1b-18265242d7b6.png)
[MAS4.1.2_Setting.zip](https://github.com/microsoft/BotFramework-Emulator/files/3529888/MAS4.1.2_Setting.zip)

**Comment by tonyanziano** [comment]
I can't reproduce this issue using NVDA (v2019.2). When focusing a checkbox like "Bypass ngrok for local addresses" the narrator reads "Bypass ngrok for local addresses checkbox checked"
