### ISSUE TITLE
[Usability-Settings] when we navigating to the scan mode “User ID “content is overlapping

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1772]
**Actual Result:**
when we navigating to the scan mode “User ID “content is overlapping, and error message is reading twice like “Enter a User ID User ID”

**Expected Result:**
when we navigating to the scan mode “User ID “content should not overlap and error message should read as “Enter a User ID ”

Note: Issue repro'ing  with NVDA 

**Repro Steps:**
Turn on the narrator 
1.Open the Bot Framework V4 Emulator.
2.Navigate to Welcome tab screen and select it, screen gets opened  
3.Navigate to the open bot and select it  
4.Open bot dialog gets opened and connect to the open bot 
5.Live chat screen gets appears 
6.Navigate to the Edit ngrok settings and select it 
7.Emulator screen gets opened 
8.Navigate to the “User ID” element using scan mode (Down arrow key)
9. Observe the issue

**User Impact:**
Users who rely on AT will be affected if the screen reader users while navigating to the UI content ,the content is overlapping and reading the info twice users will misguide the info.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Browser: Edge
Application: Bot Framework V4 Emulator
 Screen reader: Narrator 
[Usability_Setting.zip](https://github.com/microsoft/BotFramework-Emulator/files/3530094/Usability_Setting.zip)
 
[Usability_NVDA.zip](https://github.com/microsoft/BotFramework-Emulator/files/3545891/Usability_NVDA.zip)

**Comment by corinagum** [comment]
I am no longer able to reproduce this problem. I believe it may have been fixed with PR #1791

Accessibility team, please verify and let us know! Thank you

**Comment by Kumar2608** [comment]
Verified in latest bot emulator version 4.5.2-80829 with NVDA(2019.2) issue got fixed now hence we are closing this bug
