### ISSUE TITLE
"ARM" AppImage is wrong architecture

### ISSUE THREAD

**Issue by probonopd** [Microsoft/BotFramework-Emulator#178]
```
me@host:~$ wget https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.27/botframework-emulator-3.5.27-armv7l.AppImage

me@host:~$ filebotframework-emulator-3.5.27-armv7l.AppImage: ELF 64-bit LSB executable, x86-64, version 1, dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=c271a1d61198e53b90595d8bf0a7d50a57e0a53e, stripped
```

For this to work on ARM, the AppImage would need to be built for the ARM architecture.

**Comment by eanders-MS** [comment]
Thanks for reporting this.

**Comment by eanders-MS** [comment]
Hi @probonopd, we will be discontinuing support for the armv7 architecture on our releases page. Users on this architecture will be encouraged to build and run from source.
https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#build-and-run-from-source
