### ISSUE TITLE
Misleading error due wrong to LUIS auth failure message (related to bot removal?)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Emulator#1788]
See the following. The auth failure message is wrong. I am using luis in the composer (target bot) successfully, just nothing is specified in the emulator.

![image](https://user-images.githubusercontent.com/8867670/63891554-4ae24480-c99a-11e9-9387-10b41f19b3ff.png)

**Comment by cwhitten** [comment]
Note to fixer: If the conversation is generated via a .bot file continue to render this error in the message pane. If the conversation is generated via url connection, do not render this error in the message pane.
