### ISSUE TITLE
No x86_32 Build

### ISSUE THREAD

**Issue by Ordinary-Developer-JP** [Microsoft/BotFramework-Emulator#18]
I want to install BotFramework Emulator to 32bit Windows machine.
But, I can't found 32bit exe.

I build myself from code.
I want to distribute 32bit windows binary.

**Comment by eanders-MS** [comment]
This is a reasonable request.

**Comment by eanders-MS** [comment]
@Ordinary-Developer-JP, we researched this problem a bit and found the solution is not as simple as we'd hoped. We will track this as a feature request in our backlog, but for the time being our guidance for Windows x86 users is to build from source.
