### ISSUE TITLE
Bot Emulator 3.5.27 not able to connect to bot getting 301 response

### ISSUE THREAD

**Issue by kausthub** [Microsoft/BotFramework-Emulator#180]
So i followed the ChatConnector example for Node Js.
This is the log i see in bot emulator 
[20:34:29] -> POST 301 [conversationUpdate] 

Please help in solving this issue
This issue is on Windows 7

**Comment by eanders-MS** [comment]
Are you certain is was 301? I'm wondering if it could have been 401.
If 301:
- Was your bot running locally or remotely?

If 401:
- Was your bot configured with MSA appId and password, or running without credentials?

**Comment by kausthub** [comment]
It was 301 and it was running locally.
In fact from the emulator logs I got the payload which it tried to POST to
the bot.
I did the same using Postman and it worked.
Is there something which I am missing here ?

But when I used console connector to try out a hello world bot it worked.
So only the chat connector is causing issues.
Please help me to resolve this

Thank you

**Comment by eanders-MS** [comment]
Could you please copy/paste a few lines from your emulator log showing the error?

**Comment by kausthub** [comment]
This is all I see in red colour

POST 301 [conversation update]

Nothing else , I don't know why is it redirecting .

**Comment by eanders-MS** [comment]
A new version of the emulator is available that may be able to provide more information about the 301. Direct download link: https://github.com/Microsoft/BotFramework-Emulator/releases

**Comment by kausthub** [comment]
Nope still the same issue. Any idea on why this might be returning back 301?
I am on the latest 3.5.29
On windows 7

**Comment by Stevenic** [comment]
The 301 would have to be coming from something external as there's nothing in the Node SDK that does any sort of redirect.  Is it possible that you have a firewall or proxy of some sort running locally?  Out of curiosity can you see where it's redirecting you too???

**Comment by kausthub** [comment]
How can I see where it is redirecting me to ? I clicked on that log and it
shows me the body of the post which the emulator sent as the request but
where can I see the response ?
Thanks for the quick reply

**Comment by eanders-MS** [comment]
If the 301 is clickable in the emulator log, clicking it will show the content of the response in the detail view. If the 301 is not hyperlinked, then you'll need to inspect the network traffic using a network debugging tool like [fiddler](https://www.telerik.com/download/fiddler). If you use fiddler, be sure to set your machine's proxy settings to *not* bypass proxy for local addresses, otherwise you won't see localhost traffic in the fiddler capture.

**Comment by kausthub** [comment]
So on clicking the 301 response all I can see is a HTML like this
<HTML> \r\n  <head>
<title> redirection <\title>
<\head>
<body>
Redirect <\body>\r\n

But no redirect URL anywhere
What do I do now ?

Thanks

**Comment by eanders-MS** [comment]
Try using fiddler (as described above) to look at the `Location` header of the 301 response. This header contains the redirect URL.

**Comment by eanders-MS** [comment]
Going ahead and closing this now. If you'd like further assistance, reply here and we'll reopen it.
