### ISSUE TITLE
[MAS4.1.2] [Screen reader-File] Screen reader is not announcing the state for “Open recent and themes” menus 

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1804]
**Actual Result:**
Screen reader is not announcing the state for “Open recent and themes” menus present under file menu 
Screen reader is reading as open recent sub menu 

**Expected Result:**
Screen reader should narrate as open recent sub menu expanded \collapsed 

**Repro Steps:**
Turn on the NVDA 
1.Open the Bot Framework V4 Emulator.
2.Navigate to File menu and select it 
3.File menu gets opened 
4.Navigate to the “Open recent and Themes” menus 
5.Observe the issue

**Note:**
Same issue observed in Mac Os.

**User Impact:**
Users who rely on screen reader will be affected to navigate the control if screen reader is not reading the state for menu control screen reader user will be affected.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Application: Bot Framework V4 Emulator
Screen reader: NVDA 

OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}

**Attachment:**
[MAS4.1.2_File.zip](https://github.com/microsoft/BotFramework-Emulator/files/3562156/MAS4.1.2_File.zip)

[Screen reader is not announcing the state for Open recent and themes menus MAC.zip](https://github.com/microsoft/BotFramework-Emulator/files/3696847/Screen.reader.is.not.announcing.the.state.for.Open.recent.and.themes.menus.MAC.zip)

**Comment by tonyanziano** [comment]
This is another native feature that we have no control over. We would have to write a custom app menu to get around this.

**Comment by Kumar2608** [comment]
Issue got fixed hence we are closing this bug.
