### ISSUE TITLE
Installer does not install to computer

### ISSUE THREAD

**Issue by Spydernaz** [Microsoft/BotFramework-Emulator#181]
Installer on windows does not install the application. I have to run the installer every time

**Comment by eanders-MS** [comment]
Apologies, it's a bug in the latest version. We'll have a fix out next week.

**Comment by Spydernaz** [comment]
Thanks :)

**Comment by diegoenriquesantos** [comment]
Spydernaz, in 3.5.27 versión, I have installed in the following path: C:\Users\diego\AppData\Local\botframework\app-3.5.27\botframework-emulator.exe

The problem is that in this version not create the shortcut to botframework-emulator.exe.

Regards.

**Comment by eanders-MS** [comment]
Updated version is now available, with a fix for this issue. Direct download link: https://github.com/Microsoft/BotFramework-Emulator/releases

**Comment by Spydernaz** [comment]
thanks
