### ISSUE TITLE
[Usability] [Screen reader -Help] In browse mode screen reader is reading as blank and nvda focus got struck after “the bot framework emulator GitHub Project” link.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1810]
**Actual Result:**
In browse mode screen reader is reading as blank and nvda focus got struck after “the bot framework emulator GitHub Project” link.

**Expected Result:**
In browse mode screen reader should not read the blank and nvda focus shouldn’t  get struck after “the bot framework emulator GitHub Project” link.

**Repro Steps:**
Turn on the NVDA 
1.Open the Bot Framework V4 Emulator.
2.Navigate to the help menu and select it 
3.Navigate to the get started with  channels(bot inspector) and select it  
4.get started with the bot inspector screen gets appears 
5.Navigate to the “the bot framework emulator GitHub Project” using down arrow key(browse mode)
6.Observe the issue 

**User Impact:**
Users who rely on screen reader will be affected if screen reader is reading multiple times blank and focus is not moving to the next controls screen reader users will skip the feature. 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Application: Bot Framework V4 Emulator
Screen reader: NVDA
[Usability_Help.zip](https://github.com/microsoft/BotFramework-Emulator/files/3562293/Usability_Help.zip)

**Comment by tonyanziano** [comment]
@awalia13 @Kumar2608 

[According to another person from the accessibility team](https://github.com/microsoft/BotFramework-Emulator/issues/1793#issuecomment-529446089), this is the expected behavior in browse mode:

>and regarding the next query , If the user keeps pressing the down arrow, focus should stop at the last control.

Focus stops at the last control here, which is the GitHub link.

**Comment by awalia13** [comment]
@tonyanziano  -  Agree with you hence closing the bug. In modal dialog it should go to the first control after reaching last control but not on the pages.
