### ISSUE TITLE
Do font files in this repo license in MIT too?

### ISSUE THREAD

**Issue by maxloh** [microsoft/BotFramework-Emulator#1813]
I would like to use those font in my website.

**Comment by hcyang** [comment]
@maxloh, we have a developer looking into this issue.

**Comment by maxloh** [comment]
@hcyang Thanks.

**Comment by cwhitten** [comment]
Hello @maxloh. Thank you for your patience as I've done some digging on my end. The Segoe UI font files in this project are not intended to be used outside of the BF Emulator application. Segoe UI is not an open font. Microsoft's suggested location to purchase & download fonts from the Microsoft Corporation are [here](https://www.fonts.com/font/microsoft-corporation).
