### ISSUE TITLE
I can connect to my bot from the emulator and chat with it, but when I click on a received message, I don't see its JSON on the details tab.tab

### ISSUE THREAD

**Issue by RaghavaSurya** [Microsoft/BotFramework-Emulator#182]
done

**Comment by eanders-MS** [comment]
Hi @RaghavaSurya Can you please provide repro steps, or a little more context? Example:

> I can connect to my bot from the emulator and chat with it, but when I click on a received message, I don't see its JSON on the details tab.

Thank you.

**Comment by eanders-MS** [comment]
Could you please post a screenshot of this, and any other information you think useful, such as a copy of your emulator's log.

**Comment by eanders-MS** [comment]
Going ahead and closing this now. If you'd like further assistance, reply here and we'll reopen it.
