### ISSUE TITLE
 [MAS4.1.3] [Screen reader -Debug] When the user performs the action on “previous, Next, show diff” controls NVDA is not narrating the notification message information

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1820]
**Actual Result:**
When the user performs the action on “previous, Next, show diff” controls NVDA is not narrating the notification message information 

**Expected Result:**
Screen Reader should narrate the notification message information when the user performs the action on “previous, Next, Show diff” controls   
Example: when the user performs the action on “previous” control NVDA should narrate as Previous bot state button 

**Repro Steps:**
Turn on The NVDA 
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3. Bot screen upon connecting via azure/teams
4.Debug screen gets appeared on emulator 
5. Navigate to the “Previous and Next” arrow buttons and Show\hide diff controls
6. Observe the issue

**User Impact:**
Users who rely on screen readers will affect to navigate if Screen reader is not narrating the change notification message when we are perform the action on the controls  

**Test Environment:**
OS Build: Version 1903(OS Build 18362.239)
Application: Bot Framework V4 Emulator
Screen reader: NVDA 

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}
[MAS4.1.3_Debug.zip](https://github.com/microsoft/BotFramework-Emulator/files/3569437/MAS4.1.3_Debug.zip)

**Comment by tonyanziano** [comment]
This might be related to #1773 if we decide to create some sort of invisible screen-reader-only notification control.

**Comment by tonyanziano** [comment]
I'll take this one as I am also doing related #1773, and #1849
