### ISSUE TITLE
[MAS4.2.1] [Screen reader -Debug] In forward navigation NVDA is not reading the under JSON tab section controls information

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1834]
**Actual Result:**
In forward navigation NVDA is not reading the under JSON tab section controls information i.e. Root, Conversation, from, recipient…etc 

**Expected Result:**
In forward navigation  NVDA should read the under JSON tab section controls information i.e. Root, Conversation, From, recipient…etc

**Note:** Screen reader focus moving to the multiple times on Root control and reading the info which is not descriptive.
Please refer the attachment:MAS4.2.1_Debug.JSON.zip

**Repro Steps:**
Turn on the NVDA
1.	Open the Bot Framework V4 Emulator.
2.	Welcome tab screen gets opened
3.	Bot screen upon connecting via azure/teams
4.	Debug screen gets appeared on emulator
5.	Navigate to the JSON tab section under controls using tab key 
6.	Observe the issue

**User Impact:**
Users who rely on screen readers will affected if the screen reader is not reading the controls information then the screen reader users  will not able to get the controls info.

**Test Environment:**
OS Build: Version 1903(OS Build 18362.295)
Application: Bot Framework V4 Emulator
Screen reader: NVDA

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}
[MAS4.2.1_Debug.zip](https://github.com/microsoft/BotFramework-Emulator/files/3579135/MAS4.2.1_Debug.zip)
[MAS4.2.1_Debug JSON.zip](https://github.com/microsoft/BotFramework-Emulator/files/3579136/MAS4.2.1_Debug.JSON.zip)

**Comment by corinagum** [comment]
@corinagum @tonyanziano one of us should verify this as fixed, if not assign to Southworks.

**Comment by tonyanziano** [comment]
I just looked into this and it repros if the user doesn't interact with the frame first. However, once the webview frame containing the JSON inspector is focused and then clicked on using enter, the screen reader reads the information for the control.

**Comment by Kumar2608** [comment]
Issue got fixed hence we are closing this bug.
