### ISSUE TITLE
[MAS4.2.1] [Screen Reader-Services] In browse mode NVDA is reading the unnecessary information for “Key and value” elements

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1846]
**Actual Result:**
In browse mode NVDA is reading the unnecessary information for “Key and value” elements and reading the key and value info once at a time .

**Expected Result:**
In browse mode NVDA should not read the unnecessary information for “Key and value” elements and  NVDA focus should moves to the individual elements for key and value and should read the key and value info

**Repro Steps**:
Turn on the NVDA
1.Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the BOT explorer and select it 
4.Mavigate to the Services (+) and select it 
5.Dialog gets opened 
6. Navigate to the Add other resource and select it 
7.Navigate to the Key and value elements using browse mode (Down arrow key)
8.Observe the issue

**User Impact:**
Users who rely on screen readers will be affected if the screen reader is reading the inappropriate info for elements then the screen reader users will be misguide the info for elements 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.295)
Application: Bot Framework V4 Emulator
Screen reader: NVDA 

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}
[MAS4.2.1_Add other service.zip](https://github.com/microsoft/BotFramework-Emulator/files/3583666/MAS4.2.1_Add.other.service.zip)

**Comment by Kumar2608** [comment]
Verified in latest bot emulator version 4.5.2-81808 with NVDA(2019.2) issue still repro'ing hence we are reactivating this bug

**Comment by tonyanziano** [comment]
@Kumar2608 , @awalia13 ,

Would it be possible to include an updated video of the issue repro'ing please?

**Comment by tonyanziano** [comment]
Currently, the control reads:

"Key 0 edit, Add a key (optional), blank"
"Value 0 edit, Add a value (optional), blank"

"Key 1 edit, Add a key (optional), blank"
"Value 1 edit, Add a value (optional), blank"

... etc.

The behavior / logic of the control has changed since the initial open of the issue, so a new repro video would be much appreciated.

![image](https://user-images.githubusercontent.com/3452012/66443080-812bce80-e9f2-11e9-830e-2ec6cfb0737b.png)

**Comment by Kumar2608** [comment]
Verified in latest bot emulator version 4.5.2-82320 with NVDA(2019.2) Issue still repro'ing  hence we are reactivating this bug
Please refer the attachment:1846.zip
[1846.zip](https://github.com/microsoft/BotFramework-Emulator/files/3706539/1846.zip)
![1846](https://user-images.githubusercontent.com/53518994/66468535-f7d4d480-eaa3-11e9-8f61-78dd5a30161e.png)

**Comment by tonyanziano** [comment]
Thanks for the video @Kumar2608.

However, I'm still confused on what the ask is here to fix this issue.

Are both inputs supposed to be read at the same time? If so, what should the narrator say? Or is it a focus issue?

**Comment by tonyanziano** [comment]
Great, thanks for the clarification.

**Comment by Kumar2608** [comment]
Issue got fixed hence we are closing this bug.
