### ISSUE TITLE
[MAS4.1.2] [Screen Reader-Services] Screen reader is not reading the role for “Add Qna maker, Add dispatch” controls   

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1847]
**Actual Result:**
Screen reader is not reading the role for button controls.
Below are the controls 
1.Add Language understanding LUIS 2.Add Qna maker 3.Add Dispatch 4.Add Azure cosmos DB account 5.Add AZURE storage account 6.Add Azure application insights 7.Add other service 

**Expected Result:**
Screen reader should read the role for button controls 
Example: When the NVDA focus is on Add Qna maker should read as Add Qna maker button or Add Qna maker menu item 

**Repro Steps:**
Turn on the NVDA
1.Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the BOT explorer and select it 
4.Navigate to the Services (+) and select it 
5.Dialog gets opened 
6. Navigate to the controls using down arrow key 
7.Observe the issue

**User Impact:**
Users who rely on screen readers will be affected if the screen reader is not reading the role for controls then the screen reader users will not able to get the which type of control it is .

**Test Environment:**
OS Build: Version 1903(OS Build 18362.295)
Application: Bot Framework V4 Emulator
Screen reader: NVDA 

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}
[MAS4.1.2_Services.zip](https://github.com/microsoft/BotFramework-Emulator/files/3583743/MAS4.1.2_Services.zip)

**Comment by corinagum** [comment]
This is related to the context menu. Postponing for now.

**Comment by v-rampul** [comment]
#HCL-BotFrameworkEmulator; #Emulator-Win; #A11yMAS; #HCL; #MAS4.2.1; #A11ySev3
