### ISSUE TITLE
[MAS4.2.1] [Screen Reader-Services] When the user select the Services(+) control ,NVDA is reading the unnecessary information for Menu 

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1848]
**Actual Result:**
 When the user select the Services(+) control ,NVDA is reading the unnecessary information for Menu 
NVDA is reading as "Menu sub menu row 1 column 1" when the user select Service(+) control

Expected Result:
NVDA should read as "Services sub menu"  when the user select service(+) control 

Repro Steps:
Turn on the NVDA
1.Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened
3.Navigate to the BOT explorer and select it
4.Navigate to the Services (+) and select it
5.Dialog gets opened
6. Observe the issue

User Impact:
Users who rely on screen readers will be affected if the screen reader is reading the inappropriate info for control  then the screen reader users will be misguide the info for control 

**Test Environment:**
OS Build: Version 1903(OS Build 18362.295)
Application: Bot Framework V4 Emulator
Screen reader: NVDA

**MAS Reference Link:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}
[MAS4.2.1_Service.zip](https://github.com/microsoft/BotFramework-Emulator/files/3583778/MAS4.2.1_Service.zip)

**Comment by corinagum** [comment]
This is related to the context menu. Postponing for now.

**Comment by tonyanziano** [comment]
After testing, this is how context menus in Chrome are narrated. I tested out the context menu in Windows, and all it says when opened is "Context menu."

The narrator doesn't describe what the context menu is related to on native Windows OS. For example, if I right click on my Windows desktop, the narrator says "Context menu," it does not say "Desktop context menu."

This services context menu falls under the the same scenario, where the narrator is saying "Menu submenu," but not "Services menu submenu." I'm wondering if there is any flexibility on this standard.

**Comment by Kumar2608** [comment]
I agree your point but better to provide "Services sub menu " so that screen reader users  will helpa a lot.

**Comment by v-rampul** [comment]
#HCL-BotFrameworkEmulator; #Emulator-Win; #A11yMAS; #HCL; #MAS4.2.1
