### ISSUE TITLE
Hero card unable to render images in bot emulator version 4

### ISSUE THREAD

**Issue by Prskriti** [microsoft/BotFramework-Emulator#1850]

**Comment by tsuwandy** [comment]
@cwhitten, could you or someone in your team take a look?

**Comment by CoHealer** [comment]
@stevkan , can you please take a look

**Comment by tsuwandy** [comment]
@Prskriti , someone in our support team is looking into this.

**Comment by stevkan** [comment]
@Prskriti, can you tell me which SDK and version you are using? Also, can you post the code for your hero card?

**Comment by tsuwandy** [comment]
@Prskriti, could you post the code for hero card?  Thank you!

**Comment by stevkan** [comment]
Closing issue due to a lack of response. If this issue persists or you have new information to pass on regarding this issue, please feel free to reopen.
