### ISSUE TITLE
Getting security prompt to Open URL in latest version

### ISSUE THREAD

**Issue by BeMor81** [microsoft/BotFramework-Emulator#1851]
Getting security prompt to Open URL in latest version which is preventing the OAuth2 Github example from working. Select Confirm on the prompt and nothing further happens.

**Comment by mdrichardson** [comment]
@BeMor81 	

1. Can you provide the code that you use to display the OAuth Prompt?
2. Did you follow the [Authentication docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Cbot-oauth) to get your App Registration set up with OAuth? Pay special attention to [this section](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Cbot-oauth#create-and-register-an-azure-ad-application)

The Open URL prompt is normal and just ensures that the bot isn't trying to open anything malicious.

I just connected through GitHub OAuth using [the Bot Auth Sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication) and it worked just fine in Emulator. This is likely an issue with how you have Auth set up within your bot.

![image](https://user-images.githubusercontent.com/40401643/64553499-53b60d00-d2ee-11e9-976e-a2d60db81f1f.png)

**Comment by BeMor81** [comment]
> 
> 
> @BeMor81
> 
>     1. Can you provide the code that you use to display the OAuth Prompt?
> 
>     2. Did you follow the [Authentication docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Cbot-oauth) to get your App Registration set up with OAuth? Pay special attention to [this section](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Cbot-oauth#create-and-register-an-azure-ad-application)
> 
> 
> The Open URL prompt is normal and just ensures that the bot isn't trying to open anything malicious.
> 
> I just connected through GitHub OAuth using [the Bot Auth Sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication) and it worked just fine in Emulator. This is likely an issue with how you have Auth set up within your bot.
> 
> ![image](https://user-images.githubusercontent.com/40401643/64553499-53b60d00-d2ee-11e9-976e-a2d60db81f1f.png)

Thanks for the reply. The authentication settings within the bot are configure and a test returns a token. I'm using the Bot example from github. I am using Azure AD v1 authentication though. I've uploaded my project to Azure and tested via the Direct Line javascript https://github.com/microsoft/BotFramework-DirectLineJS and all works fine

**Comment by mdrichardson** [comment]
I apologize. By "...which is preventing the OAuth2 Github", I took it as using GitHub OAuth, not AADv1.

However, I was still able to get this working with AADv1:

![image](https://user-images.githubusercontent.com/40401643/64654315-bdf9ab00-d3dd-11e9-9309-34f249d9f041.png)

Here's a few things you can try:

* Restarting Emulator - it doesn't like it if you changed any Auth settings without completely restarting it
* In Emulator, go to File > Clear State
* Ensure you're using the [latest version of Emulator](https://github.com/microsoft/BotFramework-Emulator/releases)

Can you screenshot an image of it failing after you click Confirm? Does it present *any* errors or text in either Emulator or the console output?

**Comment by mdrichardson** [comment]
@BeMor81 	Are you still experiencing this issue? It needs to stay active to stay open.

**Comment by BeMor81** [comment]
Hi, Thanks for following this up. I've reverted back to a previous version for now. I'll try the update again at a later date. Please feel free to close. Thanks for your time and help with this.

**Comment by Edwardenis** [comment]
@BeMor81 I'm experiencing the same issue here with the latest version of the emulator.... could you provide the version that you used to make it work?

**Comment by Edwardenis** [comment]
I Downloaded the Bot Emulator version 4.4.0 and is working. In this version, it doesn't have the confirm alert... 

@mdrichardson can you test the OAuth example using AADv2? I really want to use the last version of the emulator but it seems like is not working with AADv2

**Comment by Edwardenis** [comment]
@BeMor81 could you provide the version of the emulator that you used? I'm using emulator version 4.5.2 with AADv2 and is not working either

**Comment by BeMor81** [comment]
@Edwardenis I'm using 4.3.0
