### ISSUE TITLE
v3.5.28 file upload broken

### ISSUE THREAD

**Issue by mattsimpson001** [Microsoft/BotFramework-Emulator#186]
Auto updated this morning and not great, unable to connect reporting issues with MSA account was fine on previous version. When I can connect unable to send images, no response from the client after selecting the file, no response from emulator nothing in the log window after submitting the file

**Comment by eanders-MS** [comment]
Hi @mattsimpson001, Thanks for taking the time to report this. We're working to get v3.8.29 out to fix the file upload issue. Can you describe your MSA connection issue in more detail?

**Comment by eanders-MS** [comment]
3.5.29 is now available with the file upload fix: https://github.com/Microsoft/BotFramework-Emulator/releases
