### ISSUE TITLE
v3.5.29 critical bug: won't connect to local bot

### ISSUE THREAD

**Issue by beatgates** [Microsoft/BotFramework-Emulator#187]
v3.5.27 was all good then auto updated to v3.5.28 then a few minutes later to v3.5.29
The v3.5.29 cannot connect to local bot. Clicking the connect, nothing happened, like dead. No error messages or logging at all.

**Comment by beatgates** [comment]
revert to v3.5.27 for the moment as that version was working without any problem.

**Comment by Jeffders** [comment]
Are you using ngrok? What URL are you using to connect to the bot? Are you using an MS App ID and password with the locally hosted bot? 

Presumably you are (1) opening the emulator, (2) entering the URL and credentials (if any), and (3) pressing connect, right?

I've not experienced the issue you are reporting, but let's try to figure out what's going on here.

**Comment by beatgates** [comment]
Not using ngrok. URL is http://localhost:3978/api/messages. Yes locally
hosted bot with *blank MS App ID and password* as this is allowed in v3.5.27

Yes 1 2 3, except in step 2, don't have to manually enter URL because it's
in the drop list.

On 10/05/2017 14:51, Jeff Derstadt wrote:

Are you using ngrok? What URL are you using to connect to the bot? Are you
using an MS App ID and password with the locally hosted bot?

Presumably you are (1) opening the emulator, (2) entering the URL and
credentials (if any), and (3) pressing connect, right?

I've not experienced the issue you are reporting, but let's try to figure
out what's going on here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotFramework-Emulator/issues/187#issuecomment-300373115>,
or mute the thread

**Comment by stenoid** [comment]
I've had a similar issue. I don't use ngrok and just connect with localhost (I do specify the app id and password, but this never seems to come through as expected so I also embed a separate id in the url to get round this issue). I'm seeing the requests coming through in node.js, but no responses appear in the emulator. I downgraded to v3.5.27 and it started working again.

**Comment by mtebbs** [comment]
Experiencing the same issue. All configuration is the same between the upgrade v3.5.27 to v3.5.29. Bots are built using v3.8.0/.1 of the botbuilder npm package.

**Comment by mtebbs** [comment]
FYI, it looks like the latest source has change,

May 10, 2017 at 2:08:46 PM PDT
`b71cd1a Upgrading typescipt version to 2.2.2 to support latest DirectLine package`

App running locally from built source at this commit doesn't have the issue.

**Comment by beatgates** [comment]
Found a work-around: firing up fiddler resuscitates the emulator...

**Comment by eanders-MS** [comment]
@beatgates That's in interesting piece of information, thanks. Is it still broken when fiddler isn't running?

**Comment by beatgates** [comment]
Yes, it's still broken if fiddler isn't running.

Guess those people who can use this version are not behind a corporate 
proxy/firewall or using a .Net bot? Still it doesn't make sense for the 
emulator not connecting to local hosted NodeJS bot...

**Comment by stenoid** [comment]
Yes, that matches my experience. The emulator auto-updated back to 3.5.29, but because I was working from home it started working again. Back in today (behind the proxy/firewall) and it stopped working.

**Comment by mtebbs** [comment]
See my comment above. FWIW the emulator works for me when built from the latest master source.

Could this be the reason?

May 10, 2017 at 2:08:46 PM PDT
`b71cd1a Upgrading typescipt version to 2.2.2 to support latest DirectLine package`

**Comment by MarcoScabbiolo** [comment]
Having the same issue behind a corporate proxy with 3.5.29, version 3.5.27 is working. Haven´t and wont try with Fiddler. Disabling the local machine firewall and antivirus protection doesn't change anything. Although my network is still behind a perimeter firewall, but that shouldn't be a problem unless the emulator is trying to connect to the internet.

**Comment by eanders-MS** [comment]
@MarcoScabbiolo would you be willing to build the emulator locally from source? If you can repro with a local build, then I can push code changes to you until we've solved the problem. The difficulty here is we don't have a local repro.

**Comment by MarcoScabbiolo** [comment]
@eanders-MS Totally understand that, next week I might have some time to do a local debug and in the best case scenario make the pull-request. I'll let you know.

**Comment by MarcoScabbiolo** [comment]
I'm not surprised to see the issue is a failure in the connection to the service, I've been able to catch the error in DirectLine, method DirectLine.prototype.startConversation, but it's a generic connection failure. Perhaps we should move this to [BotFramework-DirectLineJS](https://github.com/Microsoft/BotFramework-DirectLineJS)? I'm pretty sure the connection is failing because the application is not handling the proxy server properly, but it's a guess, I couldn't prove this yet.

**Comment by MarcoScabbiolo** [comment]
So here is what's going on:

[DirectLine](https://github.com/Microsoft/BotFramework-DirectLineJS) internally makes a call to `http://127.0.0.1:57142/v3/directline/conversations` which fails if, for example, you're behind a corporate proxy. No visual feedback is shown in the application when this error occurs. These are the error details:

```
{
   "message":"ajax error 503",
   "xhr":{

   },
   "request":{
      "async":true,
      "crossDomain":false,
      "withCredentials":false,
      "headers":{
         "Accept":"application/json",
         "Authorization":"Bearer eiik9jn9mijfmkem7c",
         "X-Requested-With":"XMLHttpRequest"
      },
      "method":"POST",
      "responseType":"json",
      "timeout":20000,
      "url":"http://127.0.0.1:57142/v3/directline/conversations"
   },
   "status":503
}
```

I've managed to solve the problem by bypassing the proxy for addresses to the IP 127.0.01. To reproduce 
 the error you could block requests to that IP.

**Comment by cwhitten** [comment]
Closing as stale.
