### ISSUE TITLE
Ability to open .chat and .transcript files without opening a bot first

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Emulator#1874]
### Use this [query](https://github.com/Microsoft/botframework-emulator/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
When trying to use .chat files to mock up conversation designs, I want to be able to view them in the emulator without opening a bot first. Today, I cannot open the Resources tab unless I have a bot open.

**Describe the solution you'd like**
I'd like to be able to open .chat files (and .transcript files) at any time in the emulator.

**Describe alternatives you've considered**
Creating an empty .bot file, then opening the .chat files.

**Additional context**

[enhancement]

**Comment by tonyanziano** [comment]
This could potentially be done via the application menu, and / or a protocol handler setup so double clicking a .chat file would open in the Emulator

**Comment by tonyanziano** [comment]
This will be possible in #2034

**Comment by tonyanziano** [comment]
Fixed in #2034
