### ISSUE TITLE
[BotBuilder] Connector can't get Conversation ID

### ISSUE THREAD

**Issue by mahmoudahmedarafa** [Microsoft/BotFramework-Emulator#188]
I am using the following code snippet from [Bot Framework Tutorial](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-connector#start-a-conversation) in my 'Post' method:

```
                var userAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
                var botAccount = new ChannelAccount(name: "Larry", id: "@UV357341");
                var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                var conversationId = await 
                          connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);

                IMessageActivity message_activity = Activity.CreateMessageActivity();
                message_activity.From = botAccount;
                message_activity.Recipient = userAccount;
                message_activity.Conversation = new ConversationAccount(id: conversationId.Id);
                message_activity.Text = reply;
                message_activity.Locale = "en-Us";
                await connector.Conversations.SendToConversationAsync((Activity)message_activity);
```

In line:

`var conversationId = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);`

the method is called and keeps running without returning an id. Any help with this issue?

**Comment by eanders-MS** [comment]
Hi @mahmoudahmedarafa Your question is specific to the BotBuilder SDK, and doesn't pertain to the emulator. Could you please post it over at https://github.com/Microsoft/BotBuilder?

**Comment by eanders-MS** [comment]
Well, let me back up and ask, do you see different results when talking to the Bot Framework vs. talking to the emulator?

**Comment by mahmoudahmedarafa** [comment]
@eanders-MS Question posted on https://github.com/Microsoft/BotBuilder.

What is the difference between talking to the Bot Framework vs. talking to the emulator, please?
I thought that they are the same thing; You talk to the emulator, the 'MessageController' class takes your message and sending it to the 'RootDialog' class (the bot), where the method 'MessageReceivedAsync' posts bot reply to the emulator UI.

**Comment by eanders-MS** [comment]
The emulator and the Bot Framework are different implementations of the same connector protocol. They should behave identically. If you were receiving conversationId from the Bot Framework, but not receiving it from the emulator, that would be an emulator bug.

**Comment by mahmoudahmedarafa** [comment]
How do I receive a me a conversationId from the emulator?

**Comment by eanders-MS** [comment]
Your bot code would be the same either way, but you would initialize your `connector` object to point to your locally running emulator, rather than the Bot Framework service endpoint.

**Comment by mahmoudahmedarafa** [comment]
So the '`https://docs.botframework.com/en-us/csharp/builder/sdkreference/d9/d69/class_microsoft_1_1_bot_1_1_connector_1_1_connector_client.html#a7a876011683cbb028e76b6f5b510d54f`' for the connector is the enpoint URL of the emulator?

If so, how do I make it absolute? I mean when I run my bot application on different machine it should work with no problems

**Comment by mahmoudahmedarafa** [comment]
```
public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (bot == null)
            {
                bot = new McDonaldsBot();
            }

            if (activity.Type == ActivityTypes.Message)
            {
                string message = activity.Text;
                string reply;

                McDonaldsLUIS McLUIS = await GetEntityFromLUIS(message);

                if (McLUIS.intents.Count() > 0)
                {
                    string top_scoring_intent = McLUIS.intents[0].intent;
                    string entity = McLUIS.entities[0].entity;

                    switch (top_scoring_intent)
                    {
                        case "OrderFood":
                            reply = entity + " costs ";
                            reply += (await GetOrderPrice(entity)).ToString() + '.';
                            break;
                        case "ChooseMainCategory":
                            reply = await GetMainCategoryOptions(entity);
                            break;
                        case "ChooseOtherMainCategory":
                            reply = await GetOtherMainCategoryOptions(entity);
                            break;
                        case "ExpressHunger":
                            reply = "Hi! We have Beef, Chicken, Fish sandwiches and more!";
                            break;
                        default:
                            reply = "Sorry, I am not getting you...";
                            break;
                    }
                }
                else
                {
                    reply = "Sorry, I am not getting you...";
                }

                activity = activity.CreateReply(reply);
            }
            else
            {
                HandleSystemMessage(activity);
            }

            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```

Here is my 'Post' method, if I'm sending the reply correctly from the bot, then why my emulator isn't posting bot's reply?

I am using BotFramework 3.5.27 emulator and Microsoft.Bot.Builder version 3.4.0.

I tried the BotFramework version 3.5.29 and Microsoft.Bot.Builder version 3.8.0 but I could't actually post my message. I verified that I already created a virtual directory for my project.

Also, I tried latest version of BotFramework version 3.5.29 and Microsoft.Bot.Builder version 3.4.0 and I couldn't post my message too.

**Comment by eanders-MS** [comment]
You're creating your reply activity, but never sending it. Have a look at the SimpleEchoBot sample from the C# BotBuilder SDK, in particular the MessagesController class: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleEchoBot/Controllers/MessagesController.cs

It is similar to yours, and sends a reply message.

**Comment by mahmoudahmedarafa** [comment]
I remember that I used this line in my app before issuing:
`await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());`

When the above line is executed, The emulator says: "Couldn't send, retry".

**Comment by mahmoudahmedarafa** [comment]
Finally I could get a reply from the bot, yet I get the following exception:
![emulator](https://cloud.githubusercontent.com/assets/22199398/26035246/c20910ca-38c9-11e7-9898-68f1fa0fdfc7.PNG)

**Comment by mahmoudahmedarafa** [comment]
Issue solved by updating VS 2017.
