### ISSUE TITLE
[MAS2.1.2][Keyboard Navigation- Welcome Tab screen] Focus gets trapped on first and last element of the page when user navigates through the page.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1881]
**Actual Result:**
After last interactive element of the pane i.e. "View analytics" the focus should land on the first interactive element but the focus gets trapped on "View analytics".
Same issue observed when we navigate with "Shift + Tab" in backward navigation, the keyboard focus gets trapped at the first interactive element i.e. "Bot Explorer".

**Expected Result:**
After last interactive element when user press "Tab", the focus should land on the first element and vice-versa.

**Note:**
Same issue observed throughout the application.

**Repro Steps:**

1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the Welcome tab and reach at "View analytics".
4. Try to navigate further through tab key and observe the issue.

**User Impact:**
When a component can receive keyboard focus, but the user are not able to move away from the component using the keyboard. 
Users will not be able to access other components on the page and would be trapped on it.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7bebdc3fe1-09a9-4aa2-a29b-e97764774e6c%7d](url)

**Attachment**
[MAS2.1.2.Keyboard.Navigation.zip](https://github.com/microsoft/BotFramework-Emulator/files/3658123/MAS2.1.2.Keyboard.Navigation.zip)

**Comment by awalia13** [comment]
@tonyanziano  - We found this issue in MAC only.

**Comment by ShikhaMishra11** [comment]
Fixed, Verified on MAC build 10.15 Beta(19A573a)
