### ISSUE TITLE
Set default locale on activities to OS locale

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Emulator#1884]
Filing this on behalf of @tomlm 

Emulator currently sets the default locale on outgoing activities to " ". 

This should instead default to the OS locale.

**Comment by vishwacsena** [comment]
@chrimc62

**Comment by tonyanziano** [comment]
I believe the plan is to send the locale set in the app settings page:

![image](https://user-images.githubusercontent.com/3452012/65789089-6cf1f280-e111-11e9-9add-0e8cf040fe3e.png)

As part of that work we can use Electron's [`app.getLocale()`](https://electronjs.org/docs/api/app#appgetlocale) API to set the Emulator's default locale to that value.

Closing as this will be addressed in #415
