### ISSUE TITLE
Cannot update emulator to latest version

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Emulator#1887]
## Version
4.5.2-79874

## Describe the bug
When the notification pops and I clicked "Restart", I got no response. 

## Expected behavior
Should start updating after clicking "Restart". 

## Screenshots
![image](https://user-images.githubusercontent.com/32497439/65798200-dda30a00-e125-11e9-889b-02784ad6d0d0.png)

[bug]

**Comment by tonyanziano** [comment]
Hi @zxyanliu ,

Thanks for reporting, but this is a known bug and is being tracked here: #1667
