### ISSUE TITLE
[Feature Request] Increase font size in Details and Log sections

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-Emulator#189]
As a user of Bot Framework Emulator, I'd like to be able to increase the font size of the text in the "Details" and "Log" areas.

**Comment by eanders-MS** [comment]
Hi @nwhitmont, Great idea. Thanks for posting. What about Ctrl/+, Ctrl/- to increase and decrease the app scaling, the way browsers work? Would this suffice for your needs? We've considered adding this to assist presenting with the emulator. The two concepts overlap enough I thought I'd mention it here.

**Comment by eanders-MS** [comment]
Support for zoom level added in 791d0d0bd41cd1ae202f027ac8d51bcc36be029a. Adds keyboard shortcuts to change zoom level:

- Ctrl+=: zoom in
- Ctrl+-: zoom out
- Ctrl+0: zoom to 100%

Menu items for zoom incoming shortly.

**Comment by eanders-MS** [comment]
Zoom support added in emulator v3.5.31
