### ISSUE TITLE
[MAS4.2.11][Screen Reader- Create new bot configuration] After "Save and connect", the focus goes on the hidden element and announced as "secret copied to the clipboard".

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1897]
**Actual Result:**
After "Save and Connect" button i.e. the last element of the dialog, the focus goes on the hidden element and announced "secret copied to the clipboard".

**Expected Result:**
The voiceover focus shouldn't lands on the hidden element or it shouldn't announced the status message again and again.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Create new bot configuration" button and activate it.
4. Open a "Create new bot configuration" dialog box gets opened.
5. Navigate to the "encrypt keys stored in your bot configuration." checkbox and check it.
6. Navigate to "copy" button and activate it.
7. Now, navigate through the pane and observe the issue after "Save and Connect" button.

**User Impact:**
If unnecessary information is announced after the control, then voiceover dependent users will get confused.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={eedc2941-f754-4739-b483-3f8180c5aaa5}](url)

**Attachment:**
[Focus goes on hidden element.zip](https://github.com/microsoft/BotFramework-Emulator/files/3685398/Focus.goes.on.hidden.element.zip)

**Comment by ShikhaMishra11** [comment]
Verified ,issue is fixed now so closing the bug.
