### ISSUE TITLE
[Usable] [Keyboard- Service] When we activate "+" button of "Service", the menu bar appears at the mouse pointer only.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1907]
**Actual Result:**
When we activates "+" button of the "Service", the menu bar appears where the mouse pointer is located.

**Expected Result:**
Ideally the "Menu" should opens below the "+" button.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Service" and click on "+" button.
4. Observe the issue.

**Note:**
Same issue observed in Linux also. Please refer the attachment: "menu bar appears at the mouse pointer_Linux"

**User Impact:**
Keyboard dependent user will gets confused if the menu bar appears only on the mouse pointer.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.5.2-linux

**Attachment:**
[menu bar appears at the mouse pointer only.zip](https://github.com/microsoft/BotFramework-Emulator/files/3690413/menu.bar.appears.at.the.mouse.pointer.only.zip)
[menu bar appears at the mouse pointer_Linux.zip](https://github.com/microsoft/BotFramework-Emulator/files/3797914/menu.bar.appears.at.the.mouse.pointer_Linux.zip)

**Comment by ShikhaMishra11** [comment]
Verified the issue and it is fixed in latest build.
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (version: 4.6.0-92058)

OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.6.0-92058-linux-x86_64
