### ISSUE TITLE
[Feature Request] Support for Up Arrow in message box

### ISSUE THREAD

**Issue by anth12** [Microsoft/BotFramework-Emulator#191]
Given this is an emulator intended for developers using the Bot Framework to test/debug their own Bots, it would be great to see support for a developers instinct when pressing the <kbd>Up</kbd> key to load the previously typed messages. Ideally the feature would allow cycling through messages but loading the last message only would still be useful.

Of course this would require implementation within the WebChat repo but as the intended purpose would be for the emulator, I wanted to gauge reaction here first.

Thanks for all the great work!

**Comment by danmarshall** [comment]
Related to https://github.com/Microsoft/BotFramework-WebChat/issues/58

**Comment by danmarshall** [comment]
I'm glad you brought this up, let's close the issue here and continue the discussion in the WebChat repo.
