### ISSUE TITLE
[MAS4.2.10] [Focus Order - Connect the bot] In JSON tab, the focus goes on the hidden controls.

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1910]
**Actual Result:**
After clicking on any chat button, the JSON Tab gets appeared on the right side of the screen. In this tab, after "JSON" the focus goes on 3 hidden button's. These hidden controls are "Left Arrow", "Right Arrow" and "Diff".
As well as with the voiceover, it informs "Dimmed Button" thrice in three tabs, it may misguide the user.

**Expected Result:**
After "JSON" the individual focus should lands on the next interactive element i.e. "Copy".

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Open Bot" button and activate it.
4. Open a Bot Dialog box gets opened.
5. Navigate to the "bot URL" edit box and enter URL- http://localhost:3978/api/messages
6. Navigate to "Connect" button and activate it.
7. "Live Chat" separate window appears.
8. Click on any chat button, observe "JSON" pane appears at right upper side of the screen.
9. Navigate to "JSON" pane.
9. Observe the issue.

**User Impact:**
The keyboard dependent users will be affected if the focus goes on the hidden element. As well as it confused the voiceover dependent user.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.5.2-linux

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={b24201d1-2276-4471-8183-e1e5353031ad}](url)

**Attachment:**
[In JSON tab, the focus goes on the hidden controls.zip](https://github.com/microsoft/BotFramework-Emulator/files/3690788/In.JSON.tab.the.focus.goes.on.the.hidden.controls.zip)

[In JSON tab, the focus goes on the hidden controls_Linux.zip](https://github.com/microsoft/BotFramework-Emulator/files/3819265/In.JSON.tab.the.focus.goes.on.the.hidden.controls_Linux.zip)

**Comment by awalia13** [comment]
@Kumar2608  - Please validate this bug.

**Comment by ShikhaMishra11** [comment]
**Comment:**
Issue fixed in new version of BOT Emulator. Hence we are closing the issue.

**Re-test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version: 4.6.0-89961)

OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator (Version: 4.6.0-88623)-linux
