### ISSUE TITLE
[MAS4.2.1][Screen reader-Live chat dialog] The voiceover announces the "JSON" table as "Blank Table".

### ISSUE THREAD

**Issue by Kumar2608** [microsoft/BotFramework-Emulator#1913]
**Actual Result:**
When the user navigates through contents available under the "JSON" frame, the voiceover announces the table as "Blank Table" which misguide the user.

**Expected Result:**
The voiceover should provide some information of the contents, so that the user will knew the presence of the contents.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the "Create new bot configuration" button and activate it.
4. "Create new bot configuration" dialog box gets opened.
5. Fill the required fields like bot name and endpoint URL example: http://localhost:3978/api/messages
6. Navigate to "Save and Connect" button and activate it.
7. Now, navigate through the pane and observe the issue after "Save and Connect" button.
8. "Live Chat" screen will appear.
9. Navigate to "[ConversationUpdate event detected]" button and activate it.
10. Observe the change in "JSON" tab and navigate to the tab.
11. After "Copy json" button press "Tab".
12. Observe the issue.

**User Impact:**
Users who rely on screen reader will be affected as they will not be able to knew the presence of content or controls in the table.

**Test Environment:**
OS: MacOs Version 10.15
Application: Bot Framework V4 Emulator (Version 4.5.2-80829)

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}](url)

**Attachment:**
[The voiceover announces the "JSON" table as "Blank Table".zip](https://github.com/microsoft/BotFramework-Emulator/files/3696077/The.voiceover.announces.the.JSON.table.as.Blank.Table.zip)

**Comment by ShikhaMishra11** [comment]
Verified and Fixed
