### ISSUE TITLE
Problem with Bot Framework Emulator

### ISSUE THREAD

**Issue by vincentbryan** [Microsoft/BotFramework-Emulator#192]
Hi all.
When I launch the emulator, it returns with " POST 400 [conversationUpdate] "
When I try to send some messages it returns with "POST 400 [message] Hello "
What's wrong with it?

PS:
 I run the code in VS2015, does it matter?
And I am able to open "localhost:3979 in Edge.
The url in the emulator is "http://127.0.0.1:3979/api/messages"

**Comment by eanders-MS** [comment]
Hi @vincentbryan, what version of the BotBuilder SDK are you using?

**Comment by eanders-MS** [comment]
Going ahead and closing this now. If you'd like further assistance, reply here and we'll reopen it.

**Comment by Vanshita** [comment]
Hey.
Same issue. 
Could you help me with it? 
I am using the latest version. Microsoft.Bot.Builder 3.8.1

**Comment by Temerario** [comment]
I have faced the same issue. I resolved it by using http://localhost:3979/api/messages instead of http://127.0.0.1:3979/api/messages
