### ISSUE TITLE
Copy/Paste into "New Bot Configuration" duplicates paste operation

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Emulator#1928]
## Version
4.5.2-82046 (Windows)

## Describe the bug
Pasting at URL into any of the New Bot File configuration text boxes within the emulator results in a duplicate URL being pasted in as shown below. Copy/pasting is a typical operation for this step given the complexity or URIs, secrets, etc.

## To Reproduce
1. Click New Bot File Configuration
2. Copy a URL (any) into Bot Name or Endpoint URL text box and observe it's pasted twice.

## Expected behavior
- Pasted once

## Screenshots

**Before**
![image](https://user-images.githubusercontent.com/33519520/66816967-e1f76180-ef32-11e9-887d-76f25195b1d1.png)

**After**
![image](https://user-images.githubusercontent.com/33519520/66817020-f4719b00-ef32-11e9-85ea-caa02df450b5.png)

## Additional context

[bug]

**Comment by tonyanziano** [comment]
@darrenj This was fixed in `v4.5.2-82320`. Please try updating your nightly to the latest version.
