### ISSUE TITLE
Bot emulator for 32 bit O.S windows 7 

### ISSUE THREAD

**Issue by ne00346536** [Microsoft/BotFramework-Emulator#193]
Hi ,

Emulator installation failing in  windows 7 with 32 bit system. Can you please let me know did the bot emulator supports 32 bit O.S. it  downloads automatically no option to select O.S wise with 32/64 bit.

Thanks.

**Comment by eanders-MS** [comment]
Hi @ne00346536, we don't support 32bit Windows OS at this time. A 32bit version is planned. Thanks for taking the time to post here.

**Comment by ne00346536** [comment]
@eanders-MS  Thanks for the details can you please let me know the release date.?


Thanks.

**Comment by Barakansanya** [comment]
@eanders-MS when will you support windows 7 with 32 bit system?

**Comment by tonyanziano** [comment]
@Barakansanya We currently have no plans of supporting 32 bit Windows.

**Comment by Barakansanya** [comment]
@tonyanziano thanks for your update, but surprisingly ENOUGH version 4.3.0 works on my 32 bit Windows OS

**Comment by tonyanziano** [comment]
@Barakansanya yes I believe Emulator v4 supported 32-bit Windows until either 4.4 or 4.5
