### ISSUE TITLE
App is not rendered (kind of offscreen window)

### ISSUE THREAD

**Issue by damassimo** [Microsoft/BotFramework-Emulator#195]
I installed the emulator (on windows 10) when connected to a second screen in extended mode. After the application setup the program was smoothly executed and rendered, but when I tried to use it in a single screen mode (let's call it laptop mode) the app was not appearing neither as a window nor as an icon in the taskbar. From the task manager it was identifiable as a background process.
On the gitter channel one of the suggestion was to connect a second screen and see what happen, unfortunately this is not a solution. In fact, I am able to run botframework-emulator only if connected to a second screen even if the app is rendered always on the main monitor (laptop). As soon as I detach the second monitor the app remains there but if I close it and open again it is not rendered anymore. This behaviour is very annoying. In addition, I noticed that if a close/start the emulator (extended screen mode) it is not always rendered even if present in the Task Mangaer's backgroud process list.

**Comment by eanders-MS** [comment]
Hi @damassimo, thank you for taking the time to file an issue here. There is a known bug in the way the emulator restores its screen position and window size when the number of monitors changes. What is different in your report is the absence of the taskbar icon. Does the emulator show up in the task switcher (Alt+Tab)? If so, as a work around you could focus it, and then Window+Arrow it to your current screen.

I will check the status of this bug. I'm sure we can get a fix in for the next release.

**Comment by damassimo** [comment]
@eanders-MS thank you very much for the suggestion! I tried the proposed procedure, but unfortunately the emulator do not appear into the task switcher (even if connected to a second screen).

**Comment by eanders-MS** [comment]
Restoration of window size and position has been improved in commit 791d0d0bd41cd1ae202f027ac8d51bcc36be029a. Will no longer restore to a non-visible position. I hope this solves the issue for you. The app not showing up for you in the task switcher may become a non-issue once you get this change, but this change doesn't directly address that one.

**Comment by ellwoods** [comment]
Sorry to be the bearer of bad news however I have just had this issue this morning, having installed the latest version late last week. What worked for me to get it back on the screen was using ALT-Tab then ALT-space and selecting Move, then using the arrows.

**Comment by eanders-MS** [comment]
We haven't made a new release yet, so this fix isn't yet generally available. Todo:
- [x] Fix this issue in code
- [ ] Release updated emulator
- [ ] Close this issue

**Comment by eanders-MS** [comment]
Fixed in emulator v3.5.31
