### ISSUE TITLE
[MAS2.4.3][Keyboard Navigation- Open Bot Dialog] After “Browse” button, the focus goes on hidden element.

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#1957]
**Actual Result:**
After "Browse" button the focus goes on the hidden element as well as the hidden element have functionality same as browse button.

**Expected Result:**
When user press Tab from "Browse" button, the focus should lands on "Microsoft App ID" edit field.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Navigate to the Welcome tab and reach at "Open Bot" button and activate it.
4. "Open a Bot" dialog gets appeared, navigate through the dialog.
5. Observe the issue.

**User Impact:**
User who rely on keyboard would be impacted as focus order is not in the ideal sequential order.

**Test Environment:**
OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.5.2-linux

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9%7D](url)

**Attachment:**
[After “Browse” button, the focus goes on hidden element.zip](https://github.com/microsoft/BotFramework-Emulator/files/3793874/After.Browse.button.the.focus.goes.on.hidden.element.zip)

**Comment by tonyanziano** [comment]
This has been fixed and is ready to be verified in the latest nightly version.

**Comment by ShikhaMishra11** [comment]
We have checked in the latest nightly, the issue is fixed now. So, we are closing the bug.

Test Environment:
OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.6.0.94518
