### ISSUE TITLE
error when emulating a sample LuisBot

### ISSUE THREAD

**Issue by gunnerwang** [Microsoft/BotFramework-Emulator#196]
<img width="182" alt="1" src="https://cloud.githubusercontent.com/assets/28732438/26117663/d0132ad0-3a99-11e7-948c-2b0a85344a6a.png">
<img width="557" alt="2" src="https://cloud.githubusercontent.com/assets/28732438/26117700/f23f9da0-3a99-11e7-820d-426e3bc2569b.png">
When I am emulating a sample LuisBot on the emulator, it always appears those red lines, preventing me from sending out messages. But when I am emulating the basic bot framework template, everything goes on smoothly. So have I missed some manipulations on Luis Dashboard, or something else goes wrong? Wait for a possible outcome!!!

**Comment by eanders-MS** [comment]
Hi @gunnerwang, it looks like your bot is returning HTTP 500 responses, likely due to your bot throwing an exception during the handling of the incoming message. The `500` in the log entry is clickable. Clicking on it should show additional information about the error, and may provide a hint about where your bot is crashing. If you are running your bot in a debugger locally, you should be able to break on the exception when it happens.

**Comment by gunnerwang** [comment]
<img width="420" alt="3" src="https://cloud.githubusercontent.com/assets/28732438/26139304/2aec3330-3b02-11e7-9fe5-d5d8d72986fc.png">
Thanks a lot for your help @eanders-MS But after I've checked my code and connection with LUIS app, there seems to be all right. Actually I'am a greenhand of this LUIS model and I cannot figure out how the error rises. Here attached are the error detail. If it's convenient for you, can you help interpret this error a bit more? Really appreciate it. [Bot framework run by VS and LUIS app run by the web]

**Comment by eanders-MS** [comment]
The `BotAuthentication` is a class attribute that verified MSA appId & password are valid. Are you running with appId & password specified? If so, I recommend clearing your credentials from your bot's config and from your emulator connection, and retrying. Once the connection is working with no credentials, add them back in.

**Comment by gunnerwang** [comment]
Thanks a lot for your guide！I've solved this problem already.
