### ISSUE TITLE
[MAS3.2.1][Keyboard Navigation -Open bot dialog] When the user close the dialog by "Esc key", the focus jumps on another content.

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#1961]
**Actual Result:**
When user presses the "Esc key" on dialog, focus is not moving on "Open bot" control. Focus moves somewhere else in bot explorer.

**Expected Result:**
On pressing  "Esc key" on dialog, focus should move to "Open bot" control instead of  some other control.

**Repro Steps:**
1.	Open the Bot Framework V4 Emulator.
2.	Navigate to the "Welcome tab" screen.
3.	Navigate to the "Open bot" button and activate it. 
4.	Open bot dialog gets opened.  
5.	Now, close the dialog by "Esc Key" and observe the issue.

**User Impact:**
User who depend  on the keyboard will face difficulty if the focus jumps on another content.

**Test Environment:**
OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.5.2-linux

**Impacted MAS Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7Ba4bbd37d-ee11-485e-b5c8-0539f0ac94b2%7D](url)

**Attachment:**
[the focus jumps on another content.zip](https://github.com/microsoft/BotFramework-Emulator/files/3797964/the.focus.jumps.on.another.content.zip)

**Comment by tonyanziano** [comment]
This has been fixed and is ready to be verified in the latest nightly version.

**Comment by ShikhaMishra11** [comment]
We have checked in the latest nightly, the issue is fixed now. So, we are closing the bug.

Test Environment:
OS: Ubuntu 18.04.3 LTS
Application: BotFramework-Emulator-4.6.0.94518
