### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unauthorized Access. Request is not authorized

### ISSUE THREAD

**Issue by Basavarajsk** [microsoft/BotFramework-Emulator#1968]
## Version
The version of the Emulator is 4.4.2

## Describe the bug
This is the first time I download the source code of my bot and use the emulator to connect it.
When I downloaded source I have pressed "Yes" when asking whether including app settings in the zip file.
I just input the my bot URL and press "connect", and then I can see following error in my bot console:
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
warning.js:18
(node:8776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:18
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized
botFrameworkAdapter.ts:614
(node:8776) UnhandledPromiseRejectionWarning: Error: Error: Unauthorized Access. Request is not authorized
warning.js:18
    at BotFrameworkAdapter.processActivity (c:\SVN_Repo\BotRepository\OCC\OCCPortalBot-Dev-src\node_modules\botbuilder\src\botFrameworkAdapter.ts:615:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

## To Reproduce

start my local bot (based on node.js):
npm start
start the emulator and do following actions:
a. press "File"-> "Open Bot"
b. Enter a Bot URL of http://localhost:3978/api/messages
c. press "Connect"
d go to the window where I started my local bot and I can see the above error message.
e if I type a message in the emulator, I can not see the response from the bot.

The following is the setting of the emulator:
![image](https://user-images.githubusercontent.com/24410864/68232696-aa587280-0023-11ea-8882-a9d62140dc6d.png)

## Expected behavior
The local bot should not show error message when emulator connects to it.

## Screenshots
![image](https://user-images.githubusercontent.com/24410864/68232806-e68bd300-0023-11ea-9b90-ef8ecb256b89.png)

## Additional context
Bot framework SDK version is 4.2 
$ node -v
v8.11.2
$ npm -v
5.6.0

[bug]

**Comment by tonyanziano** [comment]
Hi @Basavarajsk ,

Does your bot code include Microsoft App credentials? (MSA ID & MSA Password)

If so, you must enter those credentials into the "Open Bot" dialog in the Emulator when connecting to your bot.

**Comment by Basavarajsk** [comment]
Hi @tonyanziano ,

If i enter the valid MS app ID and MS app Password in emulator I am getting below error.

jpx/16*IOPG]]3p^Pi+vHpsC;@

**Comment by tonyanziano** [comment]
@Basavarajsk is your bot code properly consuming the MSA credentials, and are the correct environment variables set?

Your code might look something like this if you are using a sample:

```
const { BotFrameworkAdapter } = require('botbuilder');

const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,                  // Make sure these are set
    appPassword: process.env.MicrosoftAppPassword
});
```

**Comment by Basavarajsk** [comment]
Hi @tonyanziano ,
I have valid MSA credentials and those are set properly as environment variable.

.env file has below parameters
```
MicrosoftAppId=XXXXXXXXXXXXX
MicrosoftAppPassword=XXXXXXX
```

index file has below adapter code
```
const { BotFrameworkAdapter } = require('botbuilder');
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});
```
Same bot on Azure Portal with webchat is working fine.
![image](https://user-images.githubusercontent.com/24410864/68447303-79379800-0205-11ea-8f9b-e2fa2aa0240c.png)

**Comment by Basavarajsk** [comment]
Hi,

The local bot is working when emulator connects to it.
![image](https://user-images.githubusercontent.com/24410864/68521581-8e292f80-02c8-11ea-9a69-10cd32bf791e.png)

Fix: Removed the below parameters from the .env file in local.
MicrosoftAppId=XXXXXXXXXXXXX
MicrosoftAppPassword=XXXXXXX
