### ISSUE TITLE
Multi user configuration and support, set user name/id 

### ISSUE THREAD

**Issue by wictorwilen** [microsoft/BotFramework-Emulator#197]
I miss being able to set user name/id in the new BotFx emulator -why was this feature cut?

**Comment by eanders-MS** [comment]
The new emulator has a different user interface design from its predecessor. Because of this, some of the features do not map 1:1. This is one of those instances. Configurable user name/id is a feature that will be coming in as part of a new management UI for conversations and users in conversations.

**Comment by wictorwilen** [comment]
Thanks!
I'll use ye ole one until it's complete.

**Comment by garypretty** [comment]
@eanders-MS any update on when this feature will be available?

**Comment by tonyanziano** [comment]
@garypretty this is being tracked by #522 . It is currently in our backlog of items and has not yet been assigned to a milestone, although, that may change.

**Comment by ryanvolum** [comment]
Any update on this issue? This is a particularly useful feature to test bot-to-human handoff scenarios.

**Comment by darrenj** [comment]
Controlling the UserId is a critical need for testing authentication and human handoff scenarios. At this time the Emulator *is not able to be used* for more complex Bot testing and has led to time-consuming workarounds which takes developers out of our tooling workflow.

[Linked Accounts](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-linkedaccounts.md) based scenarios are a key blocked for our Virtual Assistant customers. In this scenario, a Bot can be linked to other services (e.g. O365, Google) ahead of a voice-led conversation removing the need for a user to be prompted for authentication which in voice first scenarios doesn't work.

This approach works by having a user log-in through a mobile app/website and perform the account linking. The "object identifier" is used as the user identifier which is then also passed on the from.id activity property meaning the two can be matched and tokens retrieved.

I'd suggest we implement two things:

1.  [P0] The emulator generates a random UserId and needs to provide a way (Settings pane ideally) for the User to provide their own UserId (typically a GUID) which is then set on the from.id property.
2. [P1] When/If the user clicks "signin" within the emulator we retrieve the '"http://schemas.microsoft.com/identity/claims/objectidentifier' claim and set this to the UserId automatically (could prompt for confirmation). This would avoid the need for the user to "find" their UserId when they are using a microsoft account.

**Comment by cwhitten** [comment]
@darrenj 👍I like this suggestion. We'll cut a ticket to address the P0

**Comment by alevinetx** [comment]
Is this correct in that this is still an open issue, with no way to emulate multiple users within the same conversation?

**Comment by tonyanziano** [comment]
Hello @alevinetx ,

Yes, this is still currently unsupported in the Emulator.

**Comment by cwhitten** [comment]
Hello. We'll close this issue as we have no plans to support multi-user on our 6-12 month roadmap.
