### ISSUE TITLE
Local IIS hosting of Bot with HTTPS

### ISSUE THREAD

**Issue by omarmciver** [microsoft/BotFramework-Emulator#1972]
I created the EchoBot template in a .net core 3 MVC web app and I am hosting it locally with IIS. 

In addition to the default name binding on the web application, I added another binding ("myapp") with a locally generated SSL (using the New-SelfSignedCertificate powershell command). I then also registered the certificate with my local trusted root CA. Finally, I added a few additional MVC pages so I could easily confirm the site was running ok.

When I connect the BotFramework Emulator via the default host binding (i.e. http://localhost/api/messages) it connects and all works well.

When I connect the BBotFramework Emulator via the named host binding (i.e. https://myapp/api/messages) it fails and I get a "stalled" response.

I've checked the pages I added and the SSL certificate is fully trusted and working without error.

In the Emulator Settings I've tried populating the localhost override with "myapp". Still the same result.

Any idea what I'm missing here?

**Comment by compulim** [comment]
@omarmciver thanks for the issue. We currently do not support .NET Core 3 in 4.6. We are evaluating the support in an upcoming release.

**Comment by omarmciver** [comment]
Ah I see. That's a shame. Could you point me in any other direction to get started on the client side of the bot without using the emulator?
