### ISSUE TITLE
I am getting Couldn't send message but after few seconds i am getting the result also

### ISSUE THREAD

**Issue by veerendra242** [microsoft/BotFramework-Emulator#1977]
## Version
What version of the Emulator are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by compulim** [comment]
@veerendra242 please describe your bug by filling out the form.

**Comment by anusharavindrar** [comment]
@veerendra242 Can you please explain in detail as to what you are trying to do and what error are you encountering?

**Comment by veerendra242** [comment]
Hi Anusharavindrar,

I am try to pass input , at that time i am getting couldn't send msg but after few seconds i am getting the exact answer

**Comment by anusharavindrar** [comment]
@veerendra242 can you fill the above form with the emulator version and the steps to reproduce the behavior along with the screenshots?

**Comment by anusharavindrar** [comment]
@veerendra242 are you still having issues?

**Comment by anusharavindrar** [comment]
Closing the issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have the need to get this resolved.
