### ISSUE TITLE
Multiple conversations missing

### ISSUE THREAD

**Issue by wictorwilen** [Microsoft/BotFramework-Emulator#198]
Previously one could have multiple conversations in the same emulator - why was this feature cut in the new version?

**Comment by eanders-MS** [comment]
Could you please clarify what you mean by multiple conversations? The ability to return to a previous conversation is a planned feature, but has not been implemented yet.

**Comment by wictorwilen** [comment]
Exactly, just as I could start a new conversation in previous version and then go back to the previous one. Glad it's on the roadmap!

**Comment by vishwacsena** [comment]
Multiple conversations (live chats) are natively supported in the V4 emulator.
