### ISSUE TITLE
Sending messages in a list format e.g. "1. hi" always auto numbers from 1

### ISSUE THREAD

**Issue by JedLJRobertson** [microsoft/BotFramework-Emulator#1987]
## Version
4.6.0

## Describe the bug
When the emulator receives messages starting with a list like "[0-9]. some message" it interprets it as a list, and changes the number to 1. This is problematic if you're sending a list in multiple messages, or simply sending another message starting with "[0-9]*." 

## To Reproduce
1. Chat to a bot in the emulator
2. Have the bot send a message like

> 6. A list item

3. Observe the message formatted as

> 1. A list item

## Expected behavior
The bot framework emulator should not renumber lists sent from the bot.

## Screenshots
![image](https://user-images.githubusercontent.com/42597642/68726710-3c193e80-0627-11ea-9eaa-fde2a188a7b7.png)

## Additional context
Behaviour in MS Teams and Webchat was as expected.

[bug]

**Comment by tonyanziano** [comment]
Hi @JedLJRobertson ,

This is a limitation of Markdown which Web Chat uses (by default) to render activities. It sees any number as the start of a list, and so, will enumerate the list items starting at 1.

You can disable markdown for specific activities in Web Chat by setting the activity's `textFormat` property to `'plain'`.

In JS this would like this:

```
await context.sendActivity({ text: `${steps}. Step without markdown`, textFormat: 'plain' });
```

Here is an example of me testing a bot in Web Chat, where one out of two messages is setting the `textFormat` property to `'plain'`, and one is not:

![image](https://user-images.githubusercontent.com/3452012/68795385-b1741780-0605-11ea-90be-5e2e466f7387.png)

and the source code for the above example:

```
let steps = 1;
class EchoBot {
  onTurn() {
    return async (context) => {
      await context.sendActivity(`${steps}. Step with markdown`);
      await context.sendActivity({ text: `${steps}. Step without markdown`, textFormat: 'plain' });
      steps++;
  }
}
```
