### ISSUE TITLE
Emulator not working on corporate PC starting with version 4.4.0

### ISSUE THREAD

**Issue by martinoss** [microsoft/BotFramework-Emulator#2011]
## Version
4.6.0

## Describe the bug
On our corporate machines (behind proxy), my team is locked on using version 4.3.3.
Using this version, we are able to connect to our local bot without an issue. With newer versions, messages from the bot are not displayed in the emulator albeit the log is displaying activity. Additionally we see the warning "Taking longer than usual to connect".

## To Reproduce (on corporate machine)
1. Start with an echo bot
2. Connect using the emulator > 4.3.3
3. "Taking longer than usual to connect.", no messages

## Expected behavior
I expect the emulator to work in our environment also with 4.4.0 and higher versions.

## Screenshots
v.4.6.0
![image](https://user-images.githubusercontent.com/2587942/69652986-c7a4bd80-1072-11ea-89c1-720bd6917982.png)

v.4.3.3
![image](https://user-images.githubusercontent.com/2587942/69653357-5dd8e380-1073-11ea-97fd-9fa2cceb79ed.png)

## Additional context
I know it's hard to reproduce from outside our company, but I would be happy to get some ideas from one of the experts who know what change from 4.3.3 to 4.4.0 could cause such a behavior. Did something change with authentication or are there any requests from outside involved that could be blocked by the firewall? Or did something change with port opening or something like that?
See also #1568.

[bug]

**Comment by cwhitten** [comment]
Hi @martinoss - we're going to investigate this and report back as to what is happening. This is definitely a bug and we will address it in our first release of the upcoming calendar year 2020.

**Comment by martinoss** [comment]
Hi @cwhitten, thank you for the good news!

**Comment by cwhitten** [comment]
@martinoss can you see if the issues remains on the latest release of the Emulator? https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.7.0

**Comment by martinoss** [comment]
@cwhitten I just tested it with v4.7.0 and it's now working 🎉 Thank you for the excellent service 👍
