### ISSUE TITLE
I cant install bot framework emulator (32-bit)

### ISSUE THREAD

**Issue by GerardoReyes14** [Microsoft/BotFramework-Emulator#202]
I try to install it but it tells me that the version is not compatible with the laptop, apparently it is because my laptop is 32 bits

**Comment by eanders-MS** [comment]
We do not provide a 32-bit emulator build for Windows at the moment. This issue has been reported here frequently though. It's clearly a blocking a number of users, and a gap in our support. We will add 32-bit support in a future release.

**Comment by divapgr** [comment]
what is the alternate solution for installation of emulator on Windows 7 32bit systems

**Comment by Jeffders** [comment]
Right now there isn't an alternative as there is not a 32 bit build of the emulator available. You could try downloading the source and running the emulator yourself from code.

**Comment by ravichandranjv** [comment]
A simpler solution to the32-bit problem could be to use a VM on Azure and use a 64 bit OS image although I am trying to run the emulator with the code but it is really tough. The gulpfile does not even have a default task and Electron installation is tougher! :)

**Comment by tonyanziano** [comment]
32-bit is available for Linux and Windows now in [version 4.1.0](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.1.0), but for Mac we support only 64-bit.
