### ISSUE TITLE
Emulator Not Displaying Bot Replies in Chat Window

### ISSUE THREAD

**Issue by mhtraylor** [Microsoft/BotFramework-Emulator#203]
Emulator Version: 3.5.29 x86-64 Linux AppImage
Using BotConnector REST API
![screenshot_20170521_130710](https://cloud.githubusercontent.com/assets/4132471/26286265/8823e828-3e26-11e7-94fb-544f1db7d7c4.png)

POST from Emulator:
`{
  "type": "message",
  "text": "hello",
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "textFormat": "plain",
  "timestamp": "2017-05-21T17:42:57.367Z",
  "channelData": {
    "clientActivityId": "1495388572328.06277521107227613.0"
  },
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsTts": true,
      "supportsListening": true
    }
  ],
  "id": "k1l6kng12dkmcdn99"
}
`
POST from Bot:
`{
  "type": "message",
  "id": null,
  "timestamp": "2017-05-21T17:42:57.371Z",
  "serviceUrl": "http://127.0.0.1:42871",
  "channelId": "emulator",
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "conversation": {
    "isGroup": null,
    "id": "hb2cmmk5in24g3h73",
    "name": null
  },
  "recipient": {
    "id": "cdgbn1c9dn096a5ml",
    "name": "Bot"
  },
  "textFormat": "plain",
  "attachmentLayout": null,
  "membersAdded": null,
  "membersRemoved": null,
  "topicName": null,
  "historyDisclosed": null,
  "locale": "en-US",
  "text": "You say: hello",
  "summary": null,
  "attachments": null,
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsTts": true,
      "supportsListening": true
    }
  ],
  "channelData": {
    "clientActivityId": "1495388572328.06277521107227613.0"
  },
  "action": null,
  "replyToId": "",
  "localTimestamp": "2017-05-21T12:42:57-05:00"
}
`

**Comment by eanders-MS** [comment]
In your bot's reply message, the `from` and `recipient` fields appear to be reversed: The message indicates it's from the user to the bot.

**Comment by mhtraylor** [comment]
Well I definitely missed that :) I was reusing the activity object from the initial message, so the from-to was certainly incorrect. Thanks for your time!
