### ISSUE TITLE
Connecting to bot opens Azure Gov webpage

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotFramework-Emulator#2031]
## Screenshots

![snippet-recording](https://user-images.githubusercontent.com/40401643/71683095-6abdb680-2d46-11ea-8fbc-d43d232bf96c.gif)

## Version

4.7.0

## Describe the bug

Connecting to bot opens Azure Gov webpage if you press enter/return instead of clicking Connect

## Steps to reproduce

1. Click Open Bot
2. Enter endpoint
3. Press enter or return instead of clicking connect
4. Watch the azure gov page open

This could be repro'd by a few others on the support team, as well.

[Bug]

**Comment by tonyanziano** [comment]
I've noticed this myself as well, and I believe it is caused by the link somehow getting focus when pressing enter.

Thanks for reporting this.
