### ISSUE TITLE
Improve sendTyping() emulation

### ISSUE THREAD

**Issue by tomwilshere** [Microsoft/BotFramework-Emulator#204]
Currently the emulator displays the following on receipt of a sendTyping() message:

![image](https://cloud.githubusercontent.com/assets/1241839/26353062/54ccbc3e-3fb6-11e7-96fb-8d81b848e0a3.png)

It would be great for the emulator to replicate the behaviour seen in most messenger platforms of a subscript "BOTNAME is typing..." or similar UX.

**Comment by eanders-MS** [comment]
Hi @tomwilshere, you might be running an older version of the emulator. The typing indicator did look like that at one time. The current release is 3.5.29, and its typing indicator displays as animated dots:
![image](https://cloud.githubusercontent.com/assets/12176807/26365984/2bea7792-3f9e-11e7-8c77-fa293bb889ae.png)

Emulator download page: https://github.com/Microsoft/BotFramework-Emulator/releases

Further suggestions about the typing indicator should be made at the WebChat repo (emulator uses the WebChat control for its chat interface): https://github.com/Microsoft/BotFramework-WebChat
