### ISSUE TITLE
Unable to update bot on 32bit Windows 10

### ISSUE THREAD

**Issue by cbtham** [microsoft/BotFramework-Emulator#2047]
## Version
4.4.2 > 4.7.0 
*Specifically on Surface Pro X which supports 32bit

## Describe the bug
No such file or directory when emulator performs installation of newer update over 4.4.2

## To Reproduce
1. Install 4.4.2 on Surface Pro X or 32 bit windows 10
2. Post installation, check update & attempt to update
3. This error popped up-
![image](https://user-images.githubusercontent.com/5702935/72436702-07b72f80-37dc-11ea-82af-ec3d65e189d3.png)

## Expected behavior
Installation to proceed as expected. Prior to Surface Pro X launch in October, I have successfully installed bot emulator v4. Based on the changelog, I believe it was already 4.5 or 4.6. For some reason, it doesnt work on recent releases.

## Additional context

[bug]

**Comment by cbtham** [comment]
If I were to install 4.7.0 directly, this error shows:-

![image](https://user-images.githubusercontent.com/5702935/72436974-a774bd80-37dc-11ea-9e40-736461c6038b.png)

**Comment by mdrichardson** [comment]
@cbtham I've come across something similar before. Can you attempt the following steps:

1. Uninstall any current version of Emulator using "Add or Remove Programs"
2. In File Explorer, go to `%AppData%` and delete the `@bfemulator` folder.
3. Download and install [v4.7.0](https://github.com/microsoft/BotFramework-Emulator/releases/download/v4.7.0/BotFramework-Emulator-4.7.0-windows-setup.exe) of the Emulator

Let me know if you receive any errors and what step they occur in.

**Comment by tonyanziano** [comment]
@cbtham This is most likely due to the fact that -- several releases ago -- we stopped releasing a 32-bit Windows installer in favor of only a 64-bit installer.

I'd recommend doing a clean re-installation like @mdrichardson suggested.

**Comment by mdrichardson** [comment]
@tonyanziano I wasn't aware of that and could see this coming up again. Do you happen to know when the releases were 64-bit-only? Is it currently both?

**Comment by tonyanziano** [comment]
@mdrichardson Let me see if I can find exactly when this happened.

**Comment by tonyanziano** [comment]
@mdrichardson I can't seem to track it down because it only required a change in our build system instead of a source code change, but I think it was some time around v4.3 or v4.4. (v4.4 is when we stopped releasing 32-bit linux artifacts).

I haven't tried installing the Emulator on a 32-bit machine, but judging from our build process it should be a 64-bit installer.

There's also an option to build an installer that works for both architectures that we could try if this ends up being a common problem.

**Comment by mdrichardson** [comment]
@tonyanziano Are 32-bit customers just SOL with anything beyond v4.3-ish, then?

**Comment by tonyanziano** [comment]
@mdrichardson Assuming the new installer doesn't work on 32-bit machines, yes. However, I haven't tried and can't confirm.

**Comment by mdrichardson** [comment]
@cbtham If you're unable to get it installed and don't want to use an older version (< v4.3), your other option would be running [Web Chat](https://github.com/Microsoft/BotFramework-WebChat) locally.

**Comment by cbtham** [comment]
> @cbtham I've come across something similar before. Can you attempt the following steps:
> 
> 1. Uninstall any current version of Emulator using "Add or Remove Programs"
> 2. In File Explorer, go to `%AppData%` and delete the `@bfemulator` folder.
> 3. Download and install [v4.7.0](https://github.com/microsoft/BotFramework-Emulator/releases/download/v4.7.0/BotFramework-Emulator-4.7.0-windows-setup.exe) of the Emulator
> 
> Let me know if you receive any errors and what step they occur in.

![image](https://user-images.githubusercontent.com/5702935/72519248-f2044180-3891-11ea-8665-f6d5e1cda9c6.png)

I followed your step to clean install it. This happened after the installer extracted and installed everything. I'm not sure this is related to just the surface pro X or generally 32bit windows

**Comment by mdrichardson** [comment]
@cbtham If you're unable to get it installed and don't want to use an older version (< v4.3), your other option would be running [Web Chat](https://github.com/Microsoft/BotFramework-WebChat) locally.

I'm going to close this issue as unfortunately, those are the only solutions at this point.
