### ISSUE TITLE
[Usable- Bot App]: ' NVDA is announcing disable on required edit field.

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#2049]
**Actual Result:**
When focus reach to mandatory edit filed, NVDA reports invalid even the edit field is blank which is confusing for screen reader 

**Expected Result:**
'Invalid' announcement for required/mandatory field should not be announced by NVDA.

**Repro Steps:**
1.Turn on NVDA
2. Switch on the Bot framework emulator
3. Activate 'Create new bot-configuration' button and select it.
4. Navigate to edit field
5. Observe NVDA announcement.

**User Impact:**
Users who rely on Screen Readers will be affected by announcement if NVDA reports invalid for blank mandatory field.

**Test Environment:**
Platform: Win32
Application: Bot Framework V4 Emulator (Version 4.7.1)
OS Build: Version 2004 (OS Build 19541.1000)
Tool: NVDA

**Guideline Reference**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BF98F4235-B6BD-47D3-8DA4-F28B9B6FBFA8%7D&file=Guideline%20101%20%E2%80%93%20Recommended%20Assistive%20Technology%20Tools%20for%20MAS%20Testing%20of%20Microsoft%20Digital%20Properties.docx&action=default&mobileredirect=true&cid=441f476a-2092-4dde-8403-70dcb430a62e

Attachment:
[Invalid announcement-DT issue.zip](https://github.com/microsoft/BotFramework-Emulator/files/4069741/Invalid.announcement-DT.issue.zip)

**Comment by ayush070502** [comment]
A11ySev4
