### ISSUE TITLE
[Object Information- Open Bot dialog]: Suggestion list available announcement is not provided on edit field. 

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#2050]
Actual Result
No information is given by VO regarding to the suggestions available for "enter URL edit box".

Expected Result
When focus moves on the "enter URL edit box", Vo should inform that suggestions are available for the same.

Repro Steps
1.Turn on Voice Over
2. Launch Bot Framework evaluator V4
3.Navigate to the Open bot 
4.Select the Open bot control button
5. Navigate to 'Bot URL' edit box and observe the announcement for suggestion.

Actual User Impact
When user is navigating through tab key, then he/she might miss the suggestion information which has appeared below the "enter URL edit box.

Test Environment
Platform: Mac 10.15.3 Beta (19D49f)
App: Bot Framework Emulator V4
App version: Version 4.7.0-99577 (4.7.0-99577.99577)
Tool: Voice Over

MAS Reference
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}
 
[Auto Suggestion-DTissue.zip](https://github.com/microsoft/BotFramework-Emulator/files/4070393/Auto.Suggestion-DTissue.zip)

**Comment by v-rampul** [comment]
#HCL-BotFrameworkEmulator; #Emulator-MAC; #A11yMAS; #HCL; #MAS4.2.1; #A11ySev2
