### ISSUE TITLE
[Screen Reader- New Bot Config]: Voice over is giving incorrect information when navigate using tab key on edit field of 'New bot configuration dialogue'.

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#2051]
Actual Result
When user navigate to 'Bot endpoint url' using tab key voice over is giving incorrect information such as 'Text unselected' which does not make sense.

Expected Result
For better user experience, incorrect information should not be announced.

Repro Steps
1.Turn on Voice Over
2.Launch Bot framework app.
3. Navigate to 'New Bot configuration button' and activate it.
4. Navigate to Bot URL name edit field followed by endpoint url edit field 
5. Observe the voice over announcement.

Test Environment
Platform: Mac 10.15.3 Beta (19D49f)
App: Bot Framework Emulator V4
App version: Version 4.7.0-99577 (4.7.0-99577.99577)
Tool: Voice Over

Actual User Impact
The focus moves on the "enter bot name" edit box twice after entering the name. First time it says "selected", second time it says "not selected".

MAS Reference
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858}

Attachment
[Incorrect information-DT issue.zip](https://github.com/microsoft/BotFramework-Emulator/files/4070524/Incorrect.information-DT.issue.zip)

**Comment by v-rampul** [comment]
#HCL-BotFrameworkEmulator; #Emulator-MAC; #A11yMAS; #HCL; #MAS4.2.1; #A11ySev4
