### ISSUE TITLE
[Usable] Hidden dialogue is appearing after saving the "save tanscript"

### ISSUE THREAD

**Issue by ShikhaMishra11** [microsoft/BotFramework-Emulator#2054]
Actual Result:
Hidden dialogue is appearing after saving the "save transcript" 

Expected Result:
Unnecessary dialogue should not be appear, which can be confusing to the screen reader dependent user.

Test Environment
Platform: Mac 10.15.3 Beta (19D49f)
App: Bot Framework Emulator V4
App version: Version 4.7.0-99577 (4.7.0-99577.99577)
Tool: Voice Over

Repro Steps:
1.Open the Bot Framework V4 Emulator.
2. Welcome tab screen gets opened.
3. Create a new bot Using shortcut key using Ctr+N
4. Navigate on save transcript button and activate this button.
5. Navigate with tab key on screen and observe the issue.

User Impact:
Voice over dependent user will face the difficulty if unnecessary hidden dialogue will be appear on system.

Attachment
[Hidden dialogue- DT issues.zip](https://github.com/microsoft/BotFramework-Emulator/files/4070828/Hidden.dialogue-.DT.issues.zip)

**Comment by v-rampul** [comment]
#HCL-BotFrameworkEmulator; #Emulator-MAC; #A11yMAS; #HCL; #MAS4.2.1; #A11ySev4;
