### ISSUE TITLE
Bot Inspector Mode missing

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Emulator#2056]
## Version
4.7.0

## Describe the bug
The Bot Inspector Mode is described in my emulator under Help, but I have no option under View to enable the Bot Inspector Mode:

![image](https://user-images.githubusercontent.com/29750798/72614913-be79f380-3933-11ea-9661-b79a35104362.png)

How can I enable that mode as I want to debug Teams using the emulator...

[bug]

**Comment by mdrichardson** [comment]
@stephanbisser 

There's a couple of things you could/might be talking about, so I'll cover both.

### JSON Inspector

The [JSON Inspector](https://github.com/microsoft/BotFramework-Emulator/wiki/Inspectors) is a panel within Emulator that allows you to view Activity JSON as well as LUIS and QnA Maker data.

You don't need to enable it. You just need to click on what you want to inspect after connecting with the bot:

![image](https://user-images.githubusercontent.com/40401643/72633255-edc93a00-390c-11ea-85fd-3e22b2ec1fd3.png)

### Inspection Middleware / Sidecar Debugging / Debug Mode

I think this may be what you're actually looking for. It allows you to inspect bot state as well as all activity flow. [Follow the docs to add it to your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-inspection-middleware?view=azure-bot-service-4.0&tabs=csharp).

If you want to test it quickly:

1. Download Sample 47 ([C#](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/47.inspection) / [Node](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/47.inspection))
2. Start the bot
3. Open Emulator
4. When opening the bot, ensure you click "Open in debug mode"

![image](https://user-images.githubusercontent.com/40401643/72633472-6203dd80-390d-11ea-959e-1f87eaf7b5a9.png)

5. Open another Emulator window or tab, and open the bot again, but not in debug mode
6. Copy/paste the inspect command from the first tab/window into the new one
7. Talk to the bot in the newer tab/window

![image](https://user-images.githubusercontent.com/40401643/72633574-9e373e00-390d-11ea-9a94-2d2b2298d26a.png)

![image](https://user-images.githubusercontent.com/40401643/72633598-a8593c80-390d-11ea-81ee-b46b93ae6b29.png)

**Comment by stephanbisser** [comment]
@mdrichardson the second option is what I might be looking for. But I actually want to use the emulator to inspect the bot which is served through Teams and I see this in my emulator under help:

![image](https://user-images.githubusercontent.com/29750798/72636105-a5d30300-395e-11ea-9e4e-bf53315dacfe.png)

is the 2nd option you described the same as this?

**Comment by mdrichardson** [comment]
@stephanbisser Yep, that's the second option!

**Comment by stephanbisser** [comment]
Great thanks for the information, issue can be closed!
