### ISSUE TITLE
Transcript rendering very slow

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Emulator#2062]
## Version
4.7.0

## Describe the bug
When opening a Transcript file (like the attached) it takes around 60 seconds to render the cards. No loading feedback is given so it can be natural to assume it's not working and reset the emulator / raise an issue.

## To Reproduce
1. Open attached transcript

## Expected behavior
Optimise transcript loading or provide a "loading" message to the user

[skills-calendar.zip](https://github.com/microsoft/BotFramework-Emulator/files/4116928/skills-calendar.zip)
[bug]

**Comment by tonyanziano** [comment]
I believe this is the same bug as #1623 & #1637.

**Comment by tonyanziano** [comment]
See if this is fixed with #2034

**Comment by tonyanziano** [comment]
Please try this with the newest nightly. It looks to me like it has been fixed.

Reopen if the issue persists.
