### ISSUE TITLE
Missing support for adaptive card 

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/BotFramework-Emulator#207]
I cannot visualize my adaptive cards in the emulator which makes impossible to test my bot . is it something planned?

**Comment by danmarshall** [comment]
Which version of the Emulator are you using? By any chance - did you build your own Emulator from source?

**Comment by TechWatching** [comment]
Excuse me, I had the old version of the emulator installed on my computer as well as the new one and I used the old one. Closing the issue.
