### ISSUE TITLE
Add ability to create and send a custom event to the bot

### ISSUE THREAD

**Issue by mdesalvo** [microsoft/BotFramework-Emulator#2080]
**Is your feature request related to a problem? Please describe.**
We have channels (e.g.: a voice channel) which start the conversation with the bot through a custom activity of type event. Actually we cannot simulate a custom event with the emulator, because it only offers the capability to send predefined system events (e.g.: conversationUpdate, typing, ping).

**Describe the solution you'd like**
We would like to define a custom event through the "Conversation" menu, which could offer a "Send Custom Activity" option: this may open a window in which we could cut&paste the raw json of the desired activity, or it may offer us a form to compile mandatory fields of a custom event activity (e.g: name, value). It would also be great that this could be persisted, so that the menu would always remember that custom activity event and allow us to send it whenever we need. 

[enhancement]

**Comment by tonyanziano** [comment]
Hi @mdesalvo ,

This work item is already being tracked by #1700 .

It was scheduled for this upcoming release (around March) but was bumped into the next release.

Thanks for the feedback!
