### ISSUE TITLE
Dependency on a 3rd Party tool which Requires signup!! Bot EMulator -> Ngrok

### ISSUE THREAD

**Issue by archmangler** [microsoft/BotFramework-Emulator#2085]
Please explain why we need ngrok to make the debug consol for bot framework work?

Without this third party tool, and without signup to it, the Azure bot local debug console and tools are useless because we get this error:

```
[22:33:43]Error: The bot is remote, but the service URL is localhost. Without tunneling software you will not receive replies.
```

Is there a way around this?

**Comment by mdrichardson** [comment]
From [the Wiki](https://github.com/microsoft/BotFramework-Emulator/wiki/Tunneling-%28ngrok%29):

> Computers running behind firewalls and home routers are not able to accept ad-hoc incoming requests from the outside world. Tunneling software provides a way around this by creating a bridge from outside the firewall to your local machine. ngrok, developed by inconshreveable, is an example of such tunneling software.

So, your bot/DirectLine doesn't know where to send messages without tunneling software like ngrok. You can use any tunneling software, but ngrok is the most widely-used. Although you need to create an account to download it, you can sign up for the free version and everything will work just fine.

Alternatively, you could use [Azure Service Bus Relay](https://blog.botframework.com/2019/04/16/debugging-your-locally-hosted-v4-bot-using-azure-relays/), but the setup is more involved and you'd need to pay for the Azure services.

**Comment by mdrichardson** [comment]
@archmangler I'm going to close this as I believe your issue has been fully addressed. Feel free to re-open if you disagree.
