### ISSUE TITLE
Set Conversation Data via StateClient  - unauthorized for user

### ISSUE THREAD

**Issue by arthurtina724** [Microsoft/BotFramework-Emulator#209]
Emulator version: v3.5.29
BotBuilder version: 3.5.9
I created an instance of Microsoft.Bot.Connector.StateClient by passing the appId/password and the base uri as service url of the emulator (ie. http://127.0.0.1:52855)

`  public void SetConversationData(string conversationUid, ConversationChannel channelId, object[] data) {
      var account = new MicrosoftAppCredentials { MicrosoftAppId = _botCreds.BotAppId, MicrosoftAppPassword = _botCreds.BotPassword };
      var stateClient = new StateClient(new Uri(_botStateUrl), account);
      string channel = channelId.ToString();
      stateClient.BotState.SetConversationData(channel, conversationUid, new BotData(eTag: "*", data: data));
    }`

The channelId is "emulator" and data is just an object[]. 
The state client throws an exception stating: 
{"Authorization for Microsoft App ID [MYAPPID] failed with status code Unauthorized and reason phrase 'Unauthorized'"}

This was working in a previous version of the emulator. My goal is to proactively start a conversation with the emulator and set conversation data.

**Comment by eanders-MS** [comment]
Hey @msft-shahins, could you please verify this code snippet is creating and initializing a `StateClient` correctly?

**Comment by arthurtina724** [comment]
@eanders-MS This was a data issue with the the botid and emulator user id. I was not utilizing the correct conversation member Id's when creating the conversation. It's a bit odd that it the connector client allowed me to start the conversation and to fail auth when setting the conversation data. Either way I was able to get passed this issue. Thanks, I will close the issue.
