### ISSUE TITLE
How to remove open confirm url in adaptive openurl action

### ISSUE THREAD

**Issue by Rajendrakumarnune** [microsoft/BotFramework-Emulator#2099]
I don't want to show confirmation message after clicking Open url action button like below

![image](https://user-images.githubusercontent.com/8529163/76514951-c14e1c00-647e-11ea-8bbc-af8a41416f2e.png)

**Comment by tonyanziano** [comment]
Hi @Rajendrakumarnune ,

This only happens in the Emulator due to security concerns. This is by design and you will not see this when chatting with your bot unless you implement the confirmation message on the client yourself.
