### ISSUE TITLE
Version 4.8 issues error "[onTurnError]: Error: missing activity.from.id"

### ISSUE THREAD

**Issue by hinojosachapel** [microsoft/BotFramework-Emulator#2106]
## Version
4.8.

## Describe the bug
I was happily using version 4.7. Everything was fine. Then the "Update available" notification appeared and I proceeded with it. After that, I was unable to use the emulator. A consistent error was thrown from my bot: "[onTurnError]: Error: missing activity.from.id". After some time wasted figuring out what was happening, I uninstalled version 4.8 and reinstalled 4.7. And everything was right again. Now I continue to use 4.7 till this issue get fixed.

## To Reproduce
1. Just open a bot in the emulator version 4.8
2. See error "[onTurnError]: Error: missing activity.from.id".

## Expected behavior
To work as expected, just like in version 4.7.
[bug]

**Comment by tonyanziano** [comment]
Hi @hinojosachapel ,

Thanks for reporting this issue. I'm sorry to hear that you're having trouble with the latest release.

Is there a certain scenario with your bot that causes this error to appear? Or are you just trying to send a message to your bot when you open it?

Is this happening at the stage of the conversation when it is first opened and the conversation update activity is sent, or is this later in the conversation when you try to send a message to the bot?

**Comment by tonyanziano** [comment]
I have found the bug and am working on a fix.

**Comment by tonyanziano** [comment]
@hinojosachapel I have made a PR that will fix the bug, and we aim to release a new patch (v4.8.1) of the Emulator later today or tomorrow that will include this fix.

**Comment by tonyanziano** [comment]
@hinojosachapel please update to the latest nightly version -- **4.8.0-113681** -- and try talking to a bot to verify that the issue has been fixed.

Please re-open the issue if not.

**Comment by hinojosachapel** [comment]
@tonyanziano Thanks a lot. I can confirm that the issue has been fixed. Good work! Regards.
