### ISSUE TITLE
Prevent update

### ISSUE THREAD

**Issue by MarcoScabbiolo** [Microsoft/BotFramework-Emulator#211]
Given some issues like #187, and others that may arise in the future, could we have a way to stop the emulator from updating in case a newer version doesn't work in some environments? Something like `--no-update` would be more than enough.

Having to re-install the application every time I have to run it again is **seriously painfull**. Wouldn't like to have to sniff the network and block the update address.

**Comment by eanders-MS** [comment]
This is a good suggestion, thank you. Also apologies for the problems you're experiencing right now. Until we add this flag, another option at your disposal is to build & run from source. Locally built emulators do not check for updates. [Build and Run from Source](https://github.com/Microsoft/BotFramework-Emulator/blob/master/CONTRIBUTING.md#build-and-run-from-source).

**Comment by MarcoScabbiolo** [comment]
I´ve been looking for a way to implement this but I couldn´t find where `Electron.autoUpdater.setFeedURL` or `Electron.autoUpdater.checkForUpdates` are being called. Is this excluded from the master branch for some reason?

**Comment by eanders-MS** [comment]
We build releases out of an internal branch that adds a few lines of code to run the app updater.

**Comment by eanders-MS** [comment]
Hi @MarcoScabbiolo, a few updates relating to this issue:
- We've added a `--noupdate` command line argument to skip the update check on startup. This will be available in the next release.
- We're also working to move away from the private release branch. In the near future, all code will be in this repo.

**Comment by eanders-MS** [comment]
It's actually --no-update, and is now available in emulator v3.5.31.
