### ISSUE TITLE
Add possibility to see bot output (cards, etc) as it is will be in real chat (Teams, Skype)

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/BotFramework-Emulator#2116]
Hello

Upon development of Bot I'm using Bot Emulator a lot! It's very useful tool to create business logic bug free apps.

But markdown and card formatting that is bright and shining in a Bot Emulator is quite different from what I see in Teams and Skype. May i ask you to incorporate viewing chat messages in Bot Emulator as it will be in real Teams, Skype with combobox or something. 

So I won't need to publish app for testing.

**Comment by tonyanziano** [comment]
Hi @SiarheiKuchukBelitsoft ,

Thanks for the feature request, but we have no current plans of emulating all the different channels as it would be an enormous effort both in implementation and maintenance.

Many of the channels support and add new features that aren't supported in other channels, and so we would have to implement all these different features in the Emulator. Additionally, we would have to constantly maintain parity with the channels as they updated these features indefinitely.

This is not feasible with the current team size and resources available to us.
