### ISSUE TITLE
Default Locale setting to en-US in settings page

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#2122]
This will help guard against some missing language default/fallback mechanisms in the Adaptive runtime

**Comment by tonyanziano** [comment]
Hmmm, odd. This [should already default to `en-US`](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/shared/src/types/serverSettingsTypes.ts#L127).

**Comment by cwhitten** [comment]
Odd, you may be right @tonyanziano. I reinstalled and the code you link matches the behavior I saw on a clean install. @vishwacsena is it possible you changed this value?
