### ISSUE TITLE
Can't sign in to Azure

### ISSUE THREAD

**Issue by statickx666** [microsoft/BotFramework-Emulator#2128]
When trying to sign in to Azure, the login window just appears, says Page not found, automatically closes and then the error message of Something went wrong appears.

![image](https://user-images.githubusercontent.com/31363842/78933238-9ef3f200-7a6e-11ea-96cc-07b675ce1e26.png)

**Comment by dmvtech** [comment]
Can you try selecting 'clear state' from the `File` menu and then trying again please?

**Comment by statickx666** [comment]
I did the clear state, at first it loaded the sign in screen correctly, once i finished entering my credentials y crashed and sent me to the Something went wrong screen.

**Comment by tonyanziano** [comment]
Can you try using a network traffic sniffer, [like Fiddler](https://www.telerik.com/download/fiddler), to capture network traffic while trying to sign in? Then we might be able to see at what point in the auth flow something is failing.

**Comment by statickx666** [comment]
Hi, sorry for the late response. I tried ussing fiddler as you asked, when i tried to sign in, it tunneled to aadcdn.msftauth.net:443, then after setting user/pass, it redirected to autologon.microsoftazuread-sso.com/443, and instantly sent the error message again.

 
![image](https://user-images.githubusercontent.com/31363842/79764108-885d5e80-82ea-11ea-9d5d-f6159f1e16e1.png)

**Comment by tonyanziano** [comment]
@statickx666 in your fiddler trace did you see a request that returned the 404 you are seeing in the sign-in dialog?

**Comment by statickx666** [comment]
No, just 443, then the crash, actually the window with the 404 no longer appears, it lasted for less than a second before, but now it goes straight to the error window. 
The crash always happens after the Stay signed in option. I will try with a different account.

**Comment by cleemullins** [comment]
@statickx666 Were you able to resolve this?

**Comment by statickx666** [comment]
Hi, no I couldn't, i think it has something to be with my account status. I'm marked as a contributor, but cannot see some services in Azure. I asked others to download the application and try to sign in, and they didn't have the errors i had. 
So i'll keep checking from that side. Thx.

**Comment by gabog** [comment]
Ok, thanks, we'll close the issue for now, feel free to reopen it if you still need assistance.
