### ISSUE TITLE
Update to v3.1 authentication framework

### ISSUE THREAD

**Issue by boardofchris** [Microsoft/BotFramework-Emulator#213]
The emulator uses v3.0 authentication framework which is to be discontinued July 2017. See https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-authentication#security-protocol-changes

See BotFramework-Emulator/src/server/settings.ts line 152

**Comment by eanders-MS** [comment]
The emulator supports both v3.0 and v3.1 auth. See commit dfcc82d1ec373aac8b814615461272dc7956bc8.

**Comment by boardofchris** [comment]
Thanks for the link. I don't see the v3.1 update in  BotFramework-Emulator/src/server/conversationManager.ts. Is this where Emulator to Bot authentication is performed?

Stepping through code in the bot framework, the authentication path taken in v3.0.

**Comment by eanders-MS** [comment]
That's correct. The emulator sends messages to the bot using v3.0 authentication, but supports receiving old or new (v3.0 or v3.1). This is for compatibility with bots on older SDKs while we phase out v3.0 auth.

Are you seeing a problem?

**Comment by boardofchris** [comment]
I see it would be difficult to support bots using the older authentication approach. I understand the need to  implement v3.0 for the time being. 

There is a problem with v3.1 emulator authentication with the chatconnector in the node botbuilder implementation. Botbuilder works with the emulator now only because it is using v3.0. It is not an emulator problem  per se.

**Comment by eanders-MS** [comment]
Ok, I'll go ahead and close this out if you don't mind.

I see you logged a similar issue over at the BotBuilder repo. Is this the bug you're referring to? https://github.com/Microsoft/BotBuilder/issues/2878

**Comment by boardofchris** [comment]
Yes, that is the issue I found.
