### ISSUE TITLE
Getting 401 error after deployment and swapping to production version

### ISSUE THREAD

**Issue by marvoh** [microsoft/BotFramework-Emulator#2131]
Hi,

I don't understand whether is is a token renewal issue or something else.

All channels return 401 issue after swapping deployment slots.

Any pointers would be appreciated

**Comment by anusharavindrar** [comment]
@marvoh can you please elaborate on the steps(if possible with screenshots) so that I can repro on my end? Was the bot working as expected before swapping to production version?

**Comment by anusharavindrar** [comment]
@marvoh are you still working on this? Do you still need help?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to re-open if issue persists.
