### ISSUE TITLE
Google Sign In Wont Work With Bot Browser

### ISSUE THREAD

**Issue by Jay-study-nildana** [microsoft/BotFramework-Emulator#2134]
## Version
What version of the Emulator are you using.

4.8.1

## Describe the bug
Give a clear and concise description of what the bug is.

I am working with Google O Auth. its all setup fine on the azure bot web settings. that works fine. 

Now, I try to sign in, it loads the bot browser. but, Google gives an error (after taking the login email address) asking me to use some other browser. 

## To Reproduce
1. run any bot authentication sample and try to use login with Google configured as a connection in bot settings.

## Expected behavior
ideally it should just allow me to complete the auth flow. 

## Screenshots

![botframeworkbrowsererror](https://user-images.githubusercontent.com/14297315/80515085-0979bd00-899f-11ea-9afb-cc815f03dffb.png)

## Additional context

[bug]

**Comment by Jay-study-nildana** [comment]
Quick Update 

I configured GitHub and that seems to work just fine. So, we are good with that. Its something to do with Google and the way it treats browsers.

**Comment by tonyanziano** [comment]
Hi @Jay-study-nildana ,

Thanks for reporting and testing out the GitHub auth provider as well.

I did a little bit of research just now and it sounds like it might have something to do with one or both of the following:

 - the User Agent string that Electron attaches to all outgoing requests
 - the version of Chrome we are running (69)

![image](https://user-images.githubusercontent.com/3452012/80519388-c4bd3a00-893c-11ea-9b8a-3b54669a8ef2.png)

A lot of the issues I saw reporting this same auth error dialog seem to have been opened up in the last 3 months or so, so maybe it is a recently added restriction to Google auth.

**Comment by Jay-study-nildana** [comment]
I agree with your assessment that this is some google thing. If this will take a while to fix, it is cool, because, I have discussed with my customers and they are okay with no google support as of now. 

Further, yes, the auth system works fine with other providers (as proved with my GitHub working system). So, worst case scenario, our client is okay with simply building our own generic oauth provider, to which we can plug google in. 

So, ultimately, if you want to close this bug away, I am okay with it or perhaps merge with this with other (past and future) similar bug reports.

**Comment by tonyanziano** [comment]
We'll keep it open for tracking.
