### ISSUE TITLE
Adaptive Card Action.Submit does not fire 

### ISSUE THREAD

**Issue by wellbread** [microsoft/BotFramework-Emulator#2136]
## Version
4.8.1

## Describe the bug
If an Adaptive Card (ver. 1.0, 1.1, 1.2) has any input elements, an ActionSet element, Action.Submit action with "data" property, the Action.Submit action does not fire in the emulator. Interesting thing: when there are no any inputs element in an Adaptive Card, everything is working as expected even with "data" property of Action.Submit.
For example, this json will fire in the emulator:

```json
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
      {
        "type": "TextBlock",
        "text": "New TextBlock"
      },
      {
        "type": "Input.Text",
        "id": "id_input",
        "placeholder": "Placeholder text"
      },
      {
        "type": "ActionSet",
        "actions": [
          {
            "type": "Action.Submit",
            "id": "Action.Submit",
            "title": "Submit"
          }
        ]
      }
    ]
  }
```

But the same with an action property "data" will not:

```json
{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "New TextBlock"
    },
    {
      "type": "Input.Text",
      "id": "id_input",
      "placeholder": "Placeholder text"
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "id": "Action.Submit",
          "data": "Submit",
          "title": "Submit"
        }
      ]
    }
  ]
}
```

And this will also fire:

```json
{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "New TextBlock"
    },    
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "id": "Action.Submit",
          "data": "Submit",
          "title": "Submit"
        }
      ]
    }
  ]
}
```

## Expected behavior
Adaptive Card with inputs elements and Action.Submit action with "data" property should fire in the Bot Framework Emulator.

[bug]

**Comment by v-kydela** [comment]
Hello @wellbread 

This is working as expected/designed. As you've discovered on your own, a string submit action can only work when the card has no inputs. This is because the card tries to combine the inputs with the action data by adding properties to it, and you cannot add properties to a string. This is all explained in my blog post: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/

You can try object submit actions instead:

```json
        {
          "type": "Action.Submit",
          "id": "Action.Submit",
          "data": {},
          "title": "Submit"
        }
```
