### ISSUE TITLE
Not rendering reply when using bfemulator://livechat?botUrl=http://localhost:3978/api/messages

### ISSUE THREAD

**Issue by hailiu2586** [microsoft/BotFramework-Emulator#2137]
## Version
4.8.1

## Describe the bug
Reply from bot not rendered in the chat window when emulator launched through bfemulator://livechat... protocol

## To Reproduce
1. have a bot running locally on http://localhost:3978/api/messages
2. launch the emulator through bfemulator://livechat?botUrl=http://localhost:3978/api/message
3 once the emulator opens, type in the live chat
4 the trace window on the right shows that the bot replied

## Expected behavior
expect the bot reply to show up in the chat window on the left. But the reply is not shown.

## Screenshots
![image](https://user-images.githubusercontent.com/7472301/80999331-53c4c900-8df9-11ea-89eb-a72c045ba861.png)

## Additional context
If I restart the conversation in emulator then the bug goes away.

[bug]

**Comment by cwhitten** [comment]
this should be addressed in https://github.com/microsoft/BotFramework-Emulator/pull/2146 and in 4.9.0
