### ISSUE TITLE
Opening emulator via deep link causes chat to hang.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Emulator#2144]
## Version
4.8.1

## Describe the bug
Pressing the "Test In Emulator" button in the 0.0.3 preview version of composer will successfully launch the emulator but the chat session will hang. If you manually launch the emulator everything works fine. This issue seems to reproduce fairly reliably on Windows but looks like it may be ok on Mac's.

[bug]

**Comment by tonyanziano** [comment]
Fixed in #2146, and this will be available in 4.9.0
