### ISSUE TITLE
QnAMaker Trace not working

### ISSUE THREAD

**Issue by GitDruid** [microsoft/BotFramework-Emulator#2162]
In Bot Framework Emulator (4.9.0) I have LUIS trace working but QnA trace don't.
Is the following sentence from @tonyanziano still valid?

"Currently, the LUIS & QnA inspectors (spawned when clicking a LUIS or QnA trace) still require a .bot file with a corresponding service entry in order to work. They cannot be used with a bot that's connected solely via endpoint."

If so, is it possible to have a sample .bot file to do the trick?
Better if this could be fixed, and so no .bot file needed.

_Originally posted by @tonyanziano in https://github.com/microsoft/BotFramework-Emulator/issues/1586#issuecomment-494185211_

**Comment by tonyanziano** [comment]
Hi @GitDruid ,

Yes, the behavior is still the same. The QnA inspector still needs a .bot file to function properly.

Your .bot file would need to have an entry in the `services` property that looks similar to this:

```
{
    "name": "qna-testing-bot",
    "description": "",
    "services": [
        {
            "type": "qna",
            "endpointKey": "<key>",
            "hostname": "<hostname>",
            "id": "4",
            "kbId": "<kbid>",
            "name": "qna",
            "subscriptionKey": "<key>"
        }
    ],
    "padlock": "",
    "version": "2.0",
    "path": "C:\\Users\\tonya\\Desktop\\qna-luis-testing.bot",
    "overrides": null
}

This can be added through the Emulator UI by creating a new OR opening an existing .bot file, and then adding a new QnA Maker service:

![image](https://user-images.githubusercontent.com/3452012/87699651-0397aa80-c74a-11ea-9c37-88533dbdf881.png)

![image](https://user-images.githubusercontent.com/3452012/87699707-1ad69800-c74a-11ea-8ae1-90831275eb05.png)


I hope this helps.

```

**Comment by GitDruid** [comment]
Thank you very much @tonyanziano . It works (the inspector looks al little stretched to be honest, but it works).

Alessandro.

**Comment by johnzan0743** [comment]
Thank you for the help, I can successfully connect to my qna service now. But for some reason, I can only inspect the confidence score by testing it online, not locally on the emulator.

**Comment by tonyanziano** [comment]
Hi @johnzan0743,

When you are talking to your bot locally using the Emulator, and leveraging QnA, do you see any entries in the Log Panel of the Emulator that are labeled "QnA Trace?"

**Comment by johnzan0743** [comment]
> Hi @johnzan0743,
> 
> When you are talking to your bot locally using the Emulator, and leveraging QnA, do you see any entries in the Log Panel of the Emulator that are labeled "QnA Trace?"

Interesting things happened, now I can see the confidence score, (I guess I need to restart to make it happen), but only when the confidence score is higher than the threshold. If it were below the threshold, nothing can be traced but only suggesting me to manually add the question and answer, good enough though.
