### ISSUE TITLE
Emulator 4.9 version infinite software update

### ISSUE THREAD

**Issue by himpatel** [microsoft/BotFramework-Emulator#2167]
Every time I open the application, it is always stuck in a infinite update loop even after updating the emulator several times.

![image](https://user-images.githubusercontent.com/15386655/88051520-6045fb80-cb76-11ea-80e4-bf6ae57bcf2a.png)

**Comment by anusharavindrar** [comment]
@himpatel, can you try to uninstall and reinstall the latest version and see if you still encounter the same issue?

**Comment by anusharavindrar** [comment]
@himpatel, did you get a chance to reinstall the latest version and test?

**Comment by himpatel** [comment]
@anusharavindrar Hey, reinstalling the application solved the issue. Thank you so much! 

On a side note I also had Emulator 4.7 also installed. I uninstalled both and reinstalled 4.9.
