### ISSUE TITLE
"request to http://localhost:8000/api/messages failed, reason: connect ECONNREFUSED 127.0.0.1:8000"

### ISSUE THREAD

**Issue by neethumoltp** [microsoft/BotFramework-Emulator#2172]
Hi,

Im running a python echo bot using docker container and getting error ""request to http://localhost:8000/api/messages failed, reason: connect ECONNREFUSED 127.0.0.1:8000""

#docker run daqbot
======== Running on http://127.0.0.1:8000 ========
(Press CTRL+C to quit)

Content of requirements.txt 
botbuilder-core>=4.7.0
aiohttp

Docker file:

FROM python:3
ADD app.py /
COPY requirements.txt /tmp/
RUN pip install  -r /tmp/requirements.txt
COPY . /tmp/
CMD [ "python", "./app.py" ]

**Comment by jwiley84** [comment]
Hi @neethumoltp 

Were there any issues deploying your bot?
What method did you use to deploy?

**Comment by neethumoltp** [comment]
I’m running it on my local machine with docker container.

**Comment by jwiley84** [comment]
Thank you. I'm tracking a couple of docker issues I believe to be related, and should have an answer for you shortly

**Comment by jwiley84** [comment]
@neethumoltp what OS are you using?

**Comment by neethumoltp** [comment]
MAC OS.

**Comment by jwiley84** [comment]
@neethumoltp your docker file doesn't seem to be exposing any ports. Can you add `EXPOSE 8000`  to the end, and then run your bot using `docker run -p 8000:8000 daqbot`

**Comment by peterinnesmsft** [comment]
@neethumoltp just checking in to see if there is any update from your side?

**Comment by mdrichardson** [comment]
Closing on behalf of @jwiley84
