### ISSUE TITLE
error when trying to connect to the emulator: value: ""Error: getaddrinfo ENOTFOUND westeurope.api.cognitive.microsoft.com""

### ISSUE THREAD

**Issue by irinapskov** [microsoft/BotFramework-Emulator#2176]
I run my bot locally. from the VS Code:
npm run start

I got:
restify listening to http://[::]:3980
Get the Emulator: https://aka.ms/botframework-emulator
To talk to your bot, open your '.bot' file in the Emulator
ApplicationInsights:CorrelationIdManager [
  Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com'
  }
]
turnContext.activity.from.name  User
root
turnContext.activity.from.name  User
continue
ApplicationInsights:Sender [
  'Ingestion endpoint could not be reached 5 consecutive times. There may be resulting telemetry loss. Most recent error:',
  Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com'
  }
]
ApplicationInsights:Sender [
  'Ingestion endpoint could not be reached 10 consecutive times. There may be resulting telemetry loss. Most recent error:',
  Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com'
  }
]

Then I opened the Bot Emulator and send a "hallo" message to the bot. I got:
500: value: ""Error: getaddrinfo ENOTFOUND westeurope.api.cognitive.microsoft.com""

Bot config looks the following:
    "name": "PLRS Bot",
    "description": "",
    "services": [
        {
            "type": "endpoint",
            "appId": "xxx",
            "appPassword": "xxx",
            "endpoint": "http://localhost:3980/api/messages",
            "id": "d703f7d0-dd38-11ea-a105-0b5bf03d00f0",
            "name": "My Bot"
        }
    ],
    "padlock": "",
    "version": "2.0",
    "path": "mypath\\My Bot.bot",
    "overrides": null

**Comment by peterinnesmsft** [comment]
@irinapskov, thank you for opening this issue. The issue you are describing appears to be unrelated to the emulator, and more likely a network issue on your end, as evidenced in errors attempting to resolve endpoint 'dc.services.visualstudio.com', which is outside of our domain of support.

If you have any product behavior, how-to, or general understanding questions, please use StackOverflow: https://stackoverflow.com/search?q=bot+framework
