### ISSUE TITLE
on Turn trace error due to status code 400 in http request

### ISSUE THREAD

**Issue by spd3344** [microsoft/BotFramework-Emulator#2187]
bot is working fine upto 30 messages per conservation, after 30 messages bot is throwing Turn trace error.
I have observed in terminal that due to "put method HTTP/1.1" 400 None " response bot is throwing error, By changing what setting I can increase the messages per conservation limit
I am using cosmos db

**Comment by dmvtech** [comment]
Hi @spd3344 

- What setting are you changing? 
- Are you using any specific sample to reproduce this with? 
- Are you using cosmosdb in the cloud or with local Azure storage emulator?
- Does it reproduce with memory state instead of cosmos?

**Comment by spd3344** [comment]
I didn't change any setting, I am using cosmosdb with local storage emulator.
I have observed that some etag in bot source code(cosmosstoragedb.py) is getting triggered For some concurrency control.
It is getting triggered after 30 messages, how to fix this?

**Comment by dmvtech** [comment]
Hi @spd3344 I'm not sure on to fix. I will try and reproduce it first. Do I need a/your specific bot to reproduce, or will any work? (as long as using cosmosdb and 30 messages). For example, will this reproduce with a simple Python Echo bot?

**Comment by tsuwandy** [comment]
@dmvtech, any update on this?

**Comment by dmvtech** [comment]
I tested with a C# bot and didn't have the issue. I will test with Python. @spd3344 can you answer my questions above? Do you have a reproduction sample?

**Comment by dmvtech** [comment]
@spd3344 I need more info. I assume it's not just 30 messages, but 30 messages that save state to cosmosDB. I'm kind of shooting at the dark here; if you can provide a reproduction and share it in a github repository (sanitized of PII), that would be _great_. Or if you can give me the exact steps to reproduce this. Thanks.

**Comment by dmvtech** [comment]
hi @spd3344 Just checking in. Are you able to share a sanitized reproduction and steps with me?

**Comment by dmvtech** [comment]
Hi @spd3344 I'm closing this one as I haven't heard from you in some time and we still need further information to proceed. Please reopen or let us know if you are still having issues and need assistance.
