### ISSUE TITLE
Rendering error occurs when text contains pair of curly braces

### ISSUE THREAD

**Issue by Danieladu** [microsoft/BotFramework-Emulator#2192]
## Describe the bug
When the text of Activity contains `{}`, Emulator would render into an  empty text. 
For example, the text is "{abc}",
![image](https://user-images.githubusercontent.com/7289268/93839432-82b3dc80-fcbf-11ea-8015-cedd093f1be9.png)

the emulator result is:
![image](https://user-images.githubusercontent.com/7289268/93839405-729bfd00-fcbf-11ea-9bf1-5b21ec6a568e.png)

[bug]

**Comment by corinagum** [comment]
Duplicate of #4154
