### ISSUE TITLE
Ngrok not getting detected

### ISSUE THREAD

**Issue by deeepss** [microsoft/BotFramework-Emulator#2197]
ngrok.io is whitelisted in my network but still Microsoft Bot Emulator is not able to start the ngrok. Where can I find the logs atleast ?
![ngrok](https://user-images.githubusercontent.com/2598330/97392870-2e65d300-18e3-11eb-9401-bcd14e3c0b38.png)

**Comment by dmvtech** [comment]
Hi @deeepss Can you share what your Emulator settings looks like (sanitized of personal/sensitive information). Also, what version of Emulator are you running?

**Comment by dmvtech** [comment]
Also, can you confirm the version of ngrok (`ngrok.exe -v`) and if it is running currently (`ps -name ngrok` in PowerShell)?

**Comment by deeepss** [comment]
I am using ngrok version 2.3.35

**Comment by dmvtech** [comment]
Have you configured the path to ngrok and selected `Run ngrok when the Emulator starts up` ? You must also restart Emulator after selecting this option.

![image](https://user-images.githubusercontent.com/43397658/97645326-dc6b9d00-1a09-11eb-9ba9-da09370689fc.png)

**Comment by deeepss** [comment]
![Capture](https://user-images.githubusercontent.com/2598330/97871566-fd3b3780-1d14-11eb-8874-1013c78f45e4.PNG)

Its the same here as well.

**Comment by dmvtech** [comment]
Interesting. Are you able to get to _either_ of the following urls (when emulator is running and you have a bot opened):

```
http://127.0.0.1:4040
http://127.0.0.1:4041
```

**Comment by dmvtech** [comment]
And just to confirm; you have **closed and restarted** Emulator after saving the settings?

**Comment by deeepss** [comment]
> And just to confirm; you have **closed and restarted** Emulator after saving the settings?

Yes. I have even restarted my VM just to be on safer side

**Comment by deeepss** [comment]
> Interesting. Are you able to get to _either_ of the following urls (when emulator is running and you have a bot opened):
> 
> ```
> http://127.0.0.1:4040
> http://127.0.0.1:4041
> ```

Hello, yeah this works. Only when the bot is opened the ngrok is actually getting active. When I reopen the emulator without the Bot being launched, I run into the same issue. So, my conclusion is, unless the bot is in running/debugging mode, ngrok may not be active.
Please correct me, if I am wrong.

**Comment by dmvtech** [comment]
Yeah, looks like you actually have to have a bot open in Emulator for it to work. The bot endpoint doesn't actually have to be running/available, but in Emulator you do need to have one opened.

Since this seems resolved, I will close this. Please let us know if you have any other issues.
