### ISSUE TITLE
Bot Framework Emulator doesn't show activities timestamp and typing message

### ISSUE THREAD

**Issue by AkumaTen** [microsoft/BotFramework-Emulator#2198]
Hi!
I'm testing the [ActivityTypes.Typing](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=javascript#send-a-typing-indicator) in a simple Echo Bot and I notice that Bot Framework Emulator doesn't show activities timestamp and "typing" message.
![image](https://user-images.githubusercontent.com/38658826/98004064-c5ed8900-1def-11eb-9bae-c2e5e631edec.png)

- generator-botbuilder@4.10.3
- Node.js and TypeScript

I found no documentation regarding this issue and I'm quite new to Bot and Bot Framework.
Thanks!

**Comment by anusharavindrar** [comment]
@AkumaTen, for the typing message, we currently do not support it and are not actively working on to fix. For the timestamp issue, I am able to repro it on my end and have filed for the bug #2199, where you can track the progress.
