### ISSUE TITLE
Bot Framework Emulator does not show activities timestamp

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotFramework-Emulator#2199]
## Version
4.10.0

## Describe the bug
The current version 4.10.0 of the Emulator does not show timestamps for the activities.

## Screenshots
![image](https://user-images.githubusercontent.com/48731427/98035645-b2312b00-1dcd-11eb-9a12-970b1d6a1511.png)

## Additional context

[bug]

**Comment by tonyanziano** [comment]
@anusharavindrar Please try to repro this bug with version 4.11.0. It will be released by EOD today.

![image](https://user-images.githubusercontent.com/3452012/98583680-9b7d4f00-2279-11eb-95b7-eae28ccad5cf.png)

**Comment by anusharavindrar** [comment]
@tonyanziano, version 4.11.0 of the Emulator shows the activities timestamp correctly. Closing the issue as resolved.
