### ISSUE TITLE
DeserializationError: Cannot deserialize content-type: text/html

### ISSUE THREAD

**Issue by frankbass3** [microsoft/BotFramework-Emulator#2203]
I did download the samples and i try to run the Multi-Turn-Prompt the python version. 
The project start fine and create me the url: http://localhost:3978    
I open it in the bot framework Emulator http://localhost:3978/api/messages  
And it crash: 

[on_turn_error]: Cannot deserialize content-type: text/html
Traceback (most recent call last):
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\venv\lib\site-packages\botbuilder\core\bot_adapter.py", line 128, in run_pipeline
    context, callback
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\venv\lib\site-packages\botbuilder\core\middleware_set.py", line 69, in receive_activity_with_status
    return await self.receive_activity_internal(context, callback)
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\venv\lib\site-packages\botbuilder\core\middleware_set.py", line 79, in receive_activity_internal
    return await callback(context)
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\bots\dialog_bot.py", line 40, in on_turn
    await super().on_turn(turn_context)
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\venv\lib\site-packages\botbuilder\core\activity_handler.py", line 68, in on_turn
    await self.on_message_activity(turn_context)
  File "C:\Users\Francesco.tangari\Documents\Projects\Bots\botbuilder-samples\samples\python\05.multi-turn-prompt\bots\dialog_bot.py", line 50, in on_message_activity
    self.conversation_state.create_property("DialogState"),

....

   raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html

it crash when it do that:

return await step_context.prompt(
            ChoicePrompt.__name__,
            PromptOptions(
                prompt=MessageFactory.text("Please enter your mode of transport."),
                choices=[Choice("Car"), Choice("Bus"), Choice("Bicycle")],
            ),
        )

There is no way to send the "JSON" version to the bot emulator?
because i have problems creating the webchat version. So i need to use the local emulator 
So.. there is a way to continue the conversation? maybe rendering the JSON instead of the HTML? 
I don't need the beauty of the html i need just to make testing.

**Comment by v-kydela** [comment]
Thank you for the report, @frankbass3. I can see that your error message mentions HTML and your comments seem to confirm that you are expecting HTML to be used in some way. What HTML are you talking about? Also, please provide the following:

1. A link to the sample you're talking about
1. Screenshots of the problem
1. Repro steps

**Comment by frankbass3** [comment]
Yes 

- The sample is the mulit-turn-prompt   link:https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/05.multi-turn-prompt
- Screenshoot attached
- steps was simple just open the project run the app.py, go in emulator put the url.

![image](https://user-images.githubusercontent.com/375789/98651541-b19f1400-233a-11eb-855d-8f919caf3206.png)

**Comment by mrivera-ms** [comment]
@v-kydela, could you please look at the reply? Thank you.

**Comment by v-kydela** [comment]
@mrivera-ms - Don't worry, this is on my list

**Comment by v-kydela** [comment]
@frankbass3 - I'm sorry but I cannot reproduce the problem. When I debug Python sample 5 in Visual Studio Code without any app ID or password or virtual environment, the sample works in Emulator without issue:

![image](https://user-images.githubusercontent.com/41968495/99123257-afe08500-25b4-11eb-9e93-38bf9bf9dd44.png)

We will need to figure out what makes your situation different from mine. I will need some more information about your repro steps, which may not be as simple as you think.

1. What version of Emulator are you using?
1. What version of the sample are you using? (You can provide the commit that your local Git repo is at)
1. Have you provided any credentials in the config file?
1. Have you activated a virtual environment?
1. Have you installed the requirements from requirements.txt?
1. Do you encounter the problem when you run the sample in Visual Studio Code or only in PyCharm?
1. Do you encounter the error immediately after connecting to the localhost in Emulator or do you have to send a message from Emulator to the bot first?
1. What HTML are you talking about? (I asked this before and given that there's a mystery to be solved I still need an answer)

**Comment by frankbass3** [comment]
Magically today appear an update pop-up on the Emulator and i could update it to the version v4 and now it works. 
Thank you.

**Comment by sachinanto** [comment]
We are also facing similar issue, can some one help

**Comment by cjusko** [comment]
I'm seeing this issue as well all of a sudden. Had a bot working consistently on the emulator for a few months. After upgrading my machine to Windows 11, reinstalling the Emulator, I'm seeing this issue.

Working in a Hatch venv:

- "python==3.11.0"
- "botbuilder-integration-aiohttp>=4.14.0"
- Emulator on latest release version 4.15.1

Even after recreating a really simple test bot I get this error here:
```
async def on_members_added_activity(
        self,
        members_added: ChannelAccount,
        turn_context: TurnContext
    ):
        await turn_context.send_activity("Hello world!")  # Error thrown here
```

Any advice?
