### ISSUE TITLE
Silent installation

### ISSUE THREAD

**Issue by daleym64** [microsoft/BotFramework-Emulator#2217]
Working for a large company we need to deploy Bot Framework Emulator to a lot of computers.
It's super frustrating that there is no silent or unattended switches or any switches for the installer

**Comment by stevkan** [comment]
@daleym64, Emulator is built using [Electron](https://www.electronjs.org/). As such, silent installation, and other installation features, are managed by Electron and not, specifically, as part of the application being built.

The discussion in this issue, [silent install parameter for windows installer](https://github.com/electron/electron-packager/issues/549#issuecomment-270459819), suggests a possible solution for you to consider.
