### ISSUE TITLE
latest build doesn't show json 

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Emulator#2232]
## Version
What version of the Emulator are you using.
![image](https://user-images.githubusercontent.com/17789481/107723422-edc57600-6c95-11eb-9648-deda7ad9b7ba.png)

## Describe the bug
I updated to latest preview and it stopped display json.  I rebooted, still not display json.  I installed 4.11.0 and it started working again.

## To Reproduce
Install 4.11 212215 

## Expected behavior
To be able to see json

[bug]

**Comment by tonyanziano** [comment]
I can repro this in dev. Looking into a fix.

**Comment by tonyanziano** [comment]
There was a breaking change in Electron that flew under the radar when I bumped up the version. `<webview>` tags are now disabled by default, and need to be explicitly enabled in the code. All the inspectors are hosted within these `<webview>` tags.

I have a PR up that re-enables them: #2233
