### ISSUE TITLE
Can't it work without ngrok even if it's locally?

### ISSUE THREAD

**Issue by tetsuya-zama** [Microsoft/BotFramework-Emulator#224]
Hello. I need help.

I'm trying bot framework and the emulator in my company. I cannot download ngrok due to my company's security policy.

So, I'm trying to use the emulator without ngrok setting. The bot is running locally at http://localhost:3978/api/messages.

But when I try to connect the emulator to my local bot, only "couldn't send" message is shown and I didn't get any other logs.(see the attachment below.)

<img width="960" alt="screen" src="https://user-images.githubusercontent.com/1510341/27015774-0808e19c-4f52-11e7-8765-6b105384eb13.PNG">

I'm sure that my local bot is running because I get "MethodNotAllowedError" when I access to http://localhost:3978/api/messages by my browser.

Can't the emulator work without ngrok even if it's locally?
Or should I concern any other problem?

Regards.

**Comment by eanders-MS** [comment]
ngrok is not required when running the bot and emulator locally; you should not need to install it. What is interesting about your screenshot is there's no log entry of the emulator sending the message to the bot. I think your message never made it out of the webchat control. The webchat control embedded in the emulator communicates with the "server side" of the emulator over a localhost socket, and I suspect that connection is failing.

Try this experiment: With the emulator running, take note of the port it is listening on. In your screenshot above, it is 63470, but it changes each time. Once you know the emulator's port, open a web browser and navigate to `http://localhost:$(port)` where `$(port)` is the emulator's port.

If you can successfully connect to the emulator, you'll see an error message like this:
`{"code":"ResourceNotFound","message":"/ does not exist"}`

If you cannot connect this way, you'll see something else.

**Comment by tetsuya-zama** [comment]
Thank you for your reply.

I accessed http://localhost:${my emulator's port} by browser and I got the same response you wrote.

But when I tried to watch HTTP messages by Fiddler4, I finally found the problem.
My problem was loopback limitation of windows 10.
When I tried to send message to my bot via emulator with running Fiddler4, Fiddler suggested me to exempt loopback limitation of SID of the emulator. 

After I clicked "OK" and reboot the emulator, it is working fine.

Thank you.

**Comment by tetsuya-zama** [comment]
Sorry, I had misunderstood a little bit.

> When I tried to send message to my bot via emulator with running Fiddler4, Fiddler suggested me to exempt loopback limitation of SID of the emulator.

It was not SID of the emulator but SID of Fiddler4.
So, only if Fiddler is running, the emulator works fine. Do you have any idea for making it work fine without Fiddler?

**Comment by eanders-MS** [comment]
When Fiddler starts up, it changes your proxy settings. I don't have a complete picture of what's happening, but my hunch is it could be related to your proxy settings. The emulator refers to the local machine by **127.0.0.1** rather than **localhost**. I wonder if that's part of the problem. It turns out that localhost doesn't resolve to 127.0.0.1 for everyone (this will be fixed in the next release). As a quick test, could you try running the following command (from a command prompt) with and without Fiddler running:
`ping -4 localhost`
I'm wondering if it returns **127.0.0.1** in both cases, or if the non-Fiddler case returns something else.

**Comment by tetsuya-zama** [comment]
Thank you for your reply.

I did ping to localhost with and without Fiddler and I got 127.0.0.1 in both cases.

I don't think it's proxy or name resolution problem. According to [here](https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback), Windows restricts apps to reach localhost(127.0.0.1) by default. For UWP apps, "checknetisolation.exe" will help me. But I can not find how to exempt the limitation for electron apps.

When Fiddler is running, Fiddler exempts the limitation by itself and enables the emulator to reach 127.0.0.1 via Fiddler as proxy.

**Comment by eanders-MS** [comment]
The loopback restriction only applies when trying to connect to Metro/Immersive/UWP apps, and the emulator is not one of those. What do your proxy settings look like with and without fiddler running?

**Comment by tetsuya-zama** [comment]
I'm so sorry for my misunderstanding.

I haven't checked my default proxy setting because it is set by WPAD automatically. But I've found that it tries to access to our proxy if I try to connect 127.0.0.1. If localhost, it loops back correctly. So, it might be  problem around our proxy setting as you wrote.  

>It turns out that localhost doesn't resolve to 127.0.0.1 for everyone (this will be fixed in the next release)

I think this enhancement will resolve my problem.

Thank you so much.

**Comment by eanders-MS** [comment]
I'm glad you found a solution. Closing this issue now.

**Comment by sivabalan11** [comment]
I m having this issue currently. I m running the bot emulator locally but the emulator is looking for ngrok to be activated, how do I stop it from happening ? 
![image](https://user-images.githubusercontent.com/21130830/78722295-c91ea600-78ee-11ea-80fe-76213c528b0f.png)
