### ISSUE TITLE
Throttling issue when testing Composer root and skill bots locally with the Emulator

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Emulator#2246]
## Version

version: 4.12.0

## Describe the bug

I get a HTTP 500 status error due to ngrok tunneling limits after a short amount of time.

## To Reproduce
1. Create root and skill bots in Composer.
1. Start the bots from Composer.
1. Test the root bot in the Emulator (only instance of it or ngrok running)
1. Interact with the root and the skill.
1. Error: In 6-10 interactions within a short time, hit the throttling limit.

## Expected behavior

Be able to meaningfully test interactions with the root and skill bots, i.e. more that 6-10 exchanges in the Emulator.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/111355318-7b550680-8644-11eb-8157-ac394787b2bd.png)

![image](https://user-images.githubusercontent.com/35047199/111355210-637d8280-8644-11eb-9bde-819f1e91fc31.png)

## Additional context

I pinged the Composer team about this. Their response was:

> Can you log an issue in the Emulator repo? This looks like its an ngrok configuration issue and the emulator team will be the best to help diagnose this.

Composer version info:

Version:  1.4.0-rc1-nightly.223504.3228d97
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

[bug]

**Comment by cwhitten** [comment]
@JonathanFingold did you follow the instructions to get a paid ngrok account? It is ngrok that is throttling you. Closing
