### ISSUE TITLE
Page not found after Azure Account Sign in

### ISSUE THREAD

**Issue by dguerin** [microsoft/BotFramework-Emulator#2247]
## Version
Just installed 4.12.0

## Describe the bug
Page not found on embedded window after Sign in to Azure, via the emulator under "My Bots"

## To Reproduce
1. Update to 4.12.0
2. Load Emulator
3. Click "Sign in with your Azure Account"
4. Authenticate with Azure (I'm using 2-FA with the Microsoft Auth App)
5. After successful login, embedded window page changed to "Page not found."

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
![Capture1](https://user-images.githubusercontent.com/748768/111901045-a1f0b400-8a2d-11eb-8f71-b09fa1ab39ce.JPG)

## Additional context
N/A

**Comment by ciph3rwoman** [comment]
Yeah - same issue for MSFT Employees as well.

**Comment by tonyanziano** [comment]
I can reproduce this issue locally and I am looking into it.

**Comment by tonyanziano** [comment]
This appears to only be a bug in version 4.12 (and some of the most-recent nightly versions), and it does not appear in 4.11.

I'd advise downgrading to version 4.11 in the meantime if the Azure sign-in flow is important to your work flow.

In the interim, we will work on fixing the issue in 4.12 and getting out a new build.

**Comment by carlosscastro** [comment]
Here is the 4.11 release link for folks that are blocked by this: https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.11.0

As @tonyanziano mentioned above, we're investigating but while we do, 4.11 fully supports azure login.

**Comment by tonyanziano** [comment]
This issue is fixed and should be available in tonight's nightly build.

**Comment by ciph3rwoman** [comment]
Thanks @tonyanziano much appreciated.

**Comment by zachgoz** [comment]
Any updates on this? I'm experiencing the same issue.

**Comment by richardlfs** [comment]
I got the same issue too! Couldn't sing in. "Page not found."
