### ISSUE TITLE
Custom Activity Editor Sends Placeholder Data When Reopened

### ISSUE THREAD

**Issue by jrpavoncello** [microsoft/BotFramework-Emulator#2249]
## Version
4.12.0

## Describe the bug
About the custom activity editor introduced in [this PR](https://github.com/microsoft/BotFramework-Emulator/pull/2213), if you close and reopen the dialog it visually saves the text that was entered, but if you send the event without changing the event data it will send the placeholder "Hello world!" event

## To Reproduce
1. Open custom event editor, notice the "hello world" event placeholder
2. Modify the event message to say "Hello to you too!"
3. Send the event
4. Close the dialog
5. Reopen the dialog, notice that it retains your modified event
6. Send the event without modifying anything, notice that the event that actually sends is the "hello world!" placeholder

## Expected behavior
The event sent in the custom event editor should match the text in the editor when the dialog is reopened after making changes.

## Screenshots
Full repro steps:
![custom_event_editor_bug](https://user-images.githubusercontent.com/2867338/112333486-08294100-8c91-11eb-9938-ca931a92e2ff.gif)

## Additional context

[bug]

**Comment by jrpavoncello** [comment]
#2213 is the original PR that introduced this new functionality (which is great)

**Comment by carlosscastro** [comment]
Thanks for reporting and for the detailed description @jrpavoncello. I think this is a bug so instead of routing to the support team, I'll route to the dev team for analysis. Next steps include have the dev team analyze the problem, its priority, and then assign a release if / when it makes the priority bar. We will update once the team investigates further.

**Comment by tonyanziano** [comment]
I just succeeded in reproducing this.

We are starting to prep the new Emulator release this week, so I'm going to see if this will be a quick fix and if so we can get it into the next release.

**Comment by tonyanziano** [comment]
The fix turned out to be incredibly simple, so I've opened #2255 to fix it.

**Comment by jrpavoncello** [comment]
Awesome, thanks!
