### ISSUE TITLE
I'm getting an error as  "POST Invalid protocol: null" while connecting bot in emulator

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [Microsoft/BotFramework-Emulator#225]
Hi,

I developed a simple bot framework in node.js using the below doc
[https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart](url)
After that i run the application using cmd and try to connect it using bot framework emulator.
While making connection i got an invalid protocol error i don't the issue behind it.
Anyone please assist me.

**Comment by eanders-MS** [comment]
Do you see this error in the bot's output or the emulator's?

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Bot emulator log.
![botemuerror](https://user-images.githubusercontent.com/10205100/27065932-260d6c7c-501e-11e7-91b7-7ce0f9192a9d.PNG)

**Comment by eanders-MS** [comment]
What is your OS?

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Windows7 64bit

**Comment by eanders-MS** [comment]
When you click on the hyperlinked `POST` of the log entry, what do you see in the Details panel?

**Comment by vitthalude** [comment]
I am facing same issue.

When clicked on the hyperlinked POST gets below details:

{
  "type": "conversationUpdate",
  "membersAdded": [
    {
      "id": "9933772k60nnmn5imc",
      "name": "Bot"
    }
  ],
  "id": "77297e3j898a46fn1c",
  "channelId": "emulator",
  "timestamp": "2017-07-14T09:48:42.441Z",
  "localTimestamp": "2017-07-14T15:18:42+05:30",
  "recipient": {
    "id": "9933772k60nnmn5imc",
    "name": "Bot"
  },
  "conversation": {
    "id": "a8995adeh2hh34ahf"
  },
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "serviceUrl": "http://127.0.0.1:58208"
}

Please assist me to remove the error.

**Comment by malwar** [comment]
I am facing the same issue in development VM which is a Windows 2012 R2 connected through the intranet proxy.  

1. Are there any fix? 
2. Is there way to change Bot framework emulator channel proxy setting in a intranet?
3. Are there any windows firewall rule port rule need to changed for the emulator to work in corporate network?

Please find the below error Log and attached screen prints for more details:
{
  "type": "message",
  "text": "Hi",
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "textFormat": "plain",
  "timestamp": "2017-07-17T07:46:03.756Z",
  "channelData": {
    "clientActivityId": "1500276937650.6137518773485307.0"
  },
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsTts": true,
      "supportsListening": true
    }
  ],
  "id": "retry"
}

![bot emulator error](https://user-images.githubusercontent.com/5756872/28260455-c0082caa-6af8-11e7-8bbc-d1372cf7ef0c.png)
