### ISSUE TITLE
Sign in Error in BotFramework Emulator

### ISSUE THREAD

**Issue by namanimsft** [microsoft/BotFramework-Emulator#2265]
@tonyanziano, I work with @mahathota and we are still having the issue with Sign In.  Could you please help us?

_Originally posted by @namanimsft in https://github.com/microsoft/BotFramework-Emulator/issues/2253#issuecomment-840772933_

**Comment by tonyanziano** [comment]
Hi @namanimsft , please do not open up a duplicate issue if you are experiencing the same issue as in #2253.

You can comment in the closed issue and I will reopen it.
