### ISSUE TITLE
Emulator does not clear the state - v4.14.0

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/BotFramework-Emulator#2280]
I have been trying to debug an authenticated skill and I have two different logins to test it out. How ever, it looks like the emulator picks up the credentials I logged in previously without prompting me to authenticate. I have tried clearing the state multiple times. I have noticed the same behavior with v4.13.X as well. I use the mac version. Any leads would be appreciated, thanks!

**Comment by anusharr** [comment]
Let me attempt a repro on my Mac and update the thread with my findings. Also, when you state that you have tried clearing the state multiple times, you used the `File > Clear state` menu option? Can you try using [Fiddler](https://www.telerik.com/download/fiddler) to capture the network traffic while attempting to sign in and attach the trace here?
