### ISSUE TITLE
aka.ms/botemulator link is broken in right hand nav pane

### ISSUE THREAD

**Issue by TheBluLion** [microsoft/BotFramework-Emulator#2283]
Clicking on link goes to https://www.bing.com/?ref=aka&shorturl=botemulator

**Comment by joshgummersall** [comment]
@TheBluLion where did you find this link?

**Comment by TheBluLion** [comment]
microsoft/BotFramework-Emulator: A desktop application that allows users to locally test and debug chat bots built with the Bot Framework SDK. (github.com)<https://github.com/Microsoft/BotFramework-Emulator>

[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by joshgummersall** [comment]
Fixed! Thanks for reporting.
