### ISSUE TITLE
how to use promise in the emulator

### ISSUE THREAD

**Issue by Timothee-Retailleau** [Microsoft/BotFramework-Emulator#232]
Hello,

I'm developing bots with nodejs and I tried using promise for API calls.
The promises neither execute or get error message.

Is there any specific way to use it within the bot framework emulator ?

Thank you,

**Comment by eanders-MS** [comment]
Hi @Timothee-Retailleau, This seems like a BotBuilder SDK question. This forum is for questions pertaining to the Bot Framework Emulator. I think you'll have better luck asking over at https://github.com/Microsoft/BotBuilder/issues.
