### ISSUE TITLE
Separating the directline feature into a standalone service

### ISSUE THREAD

**Issue by Brankec** [microsoft/BotFramework-Emulator#2351]
**Is your feature request related to a problem? Please describe.**
Our client wants to run the Bot onprem and use their own custom web chat to communicate to the Bot.

**Describe the solution you'd like**
We would like the feature in Emulator, that opens a directline port, to be separated in a standalone service that is open source, just like the Bot Framework Emulator, with an example on how to start it and where the port it opened is stored.

**Describe alternatives you've considered**
The only alternative we found is the offline-directline service that has the limitation of being unable to pass attachments, last update was 3 years ago and there aren't any tutorials on how to get it up and running and use it with postman or REST calls in general.

**Additional context**
an example of what I am talking about.
![image](https://user-images.githubusercontent.com/33580274/145544119-58bc5ed4-fbde-46b6-b41d-4d566420e082.png)

an example on how we would like to use the port.
![image](https://user-images.githubusercontent.com/33580274/145544372-06a5049e-ae8f-4157-83d7-81cc3ab43b4c.png)

**Comment by gabog** [comment]
Thanks for the suggestion, we currently don't have plans to implement this feature. You could fork the emulator project and direct line clients for dotnet or JS and customize them to fit your needs.
