### ISSUE TITLE
Ability to add values to the channel data

### ISSUE THREAD

**Issue by sunamc1** [microsoft/BotFramework-Emulator#2365]
**Is your feature request related to a problem? Please describe.**
For local testing at Nationwide, we need the ability to send security values on the channelData that are populated in the higher environments

**Describe the solution you'd like**
The ability to add to the bot configuration or to the settings, values that should be consistently populated in the channelData

**Describe alternatives you've considered**
We can try doing overwrites in the code, but that would require making testing specific hacks in our code.

**Additional context**
We are potentially willing to develop this ourselves and contribute it back to the main project.

[enhancement]

**Comment by stevkan** [comment]
@sunamc1, Emulator has the option to send a custom activity where you can define properties to be included in `channelData`. You can find this in the menu under Conversation => Custom activity (new).

![image](https://user-images.githubusercontent.com/18403946/151609506-53566d44-8e8d-4461-bfde-ba4ad8626d17.png)

![image](https://user-images.githubusercontent.com/18403946/151609512-873647ef-7260-4505-885e-8f3e090392e9.png)

Outside of that, there isn't any way to attach arbitrary channel data to each outgoing message. You are, of course, welcome to submit any PRs in support of this.

As an alternative, you could set up instance of Web Chat that _would_ allow you to send added values in `channelData`, consistently. Under the hood, both Emulator and Web Chat rely on Direct Line for connecting, so both use cases should produce similar results. Check out this sample, [04.api/b.piggyback-on-outgoing-activities](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/04.api/b.piggyback-on-outgoing-activities), if you are interested.

For clarity, Web Chat doesn't have to be published for it to work. In my development environment, I run a local 'token' server 
and web server. From the served page hosting Web Chat, I call an API on the token server which returns the token to be consumed by Web Chat for creating the DirectLine object. If your bot is also running locally, then you can use ngrok, or another tunneling service, to connect your bot to your Azure bot registration. In this way, both your bot and Web Chat are connected to the Direct Line channel connector.

**Comment by sunamc1** [comment]
Thanks that's very helpful!
