### ISSUE TITLE
401

### ISSUE THREAD

**Issue by jcnovoa** [Microsoft/BotFramework-Emulator#239]
Reviewed this:
https://docs.microsoft.com/en-us/bot-framework/troubleshoot-authentication-problems
Successfully ran this:
curl -k -X POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token -d "grant_type=client_credentials&client_id=7fdbd4b7-379e-4aa0-8063-xxxxxxxxxxx&client_secret=qExxxxxxxxx&scope=https%3A%2F%2Fapi.botframework.com%2F.default"
Got token
{
  "token_type": "Bearer",
  "expires_in": 3599,
  "ext_expires_in": 0,
  "access_token": "eyJ0eXAiOiJKV1QiL..."
}
Set Bot emulator accordingly with same App ID and secret and configure
ngrok.exe
Still, get this message:
POST 401 [conversationUpdate] 
Error: The bot's MSA appId or password is incorrect. 
Edit your bot's MSA info

**Comment by Jeffders** [comment]
Are you using the Node or the C# Bot Builder SDK?

Generally you don't need to issue calls to login.microsoftonline.com yourself, the SDK takes care of this for you (so you only need to do these kinds of calls if you are NOT using one of the SDKs).

If you are using the SDK, you only need to specify the appid and password in the web.config (C#) or the main.js file (Node) and then also specify these using the emulator.

**Comment by jcnovoa** [comment]
Jeff,
Thanks for the reply, I ran the CURL as indicated in the DOCs to verify the APP ID & Secret and it ran successfully; I built my bot in Azure and registered it in the botframework with a messaging endpoint of:
https://luisbotbuilder.azurewebsites.net/api/messages
The botframework recognized the speech recognition configurations 
This is based on https://github.com/Microsoft/BotBuilder-Samples where I selected the C# Intelligence-LUIS project and clicked "Deploy to Azure" button and went thru the wizard to deploy to Azure and generate the above URL/endpoint (Afterwards I got App ID and Password/Key from Azure and stored them under "My keys" within luis.ai)
The problem was that the Azure endpoint does not get generated until after deployment, so the credentialing within apps.dev.microsoft.com when registering the bot happens afterwards and it is required to then update azure cognitive services for the authentication to work via the emulator.
Once I updated Azure's App Settings MAppId & MAppPwd for my bot I got my 200 from the emulator.
All is working fine on the emulator now; just documenting in case someone else has a similar problem.
![step 1 azuredeploy](https://user-images.githubusercontent.com/1389127/27885854-88aca25e-61a7-11e7-87b1-148eda4d6b8a.PNG)
![step 2 botendpointcredentialing](https://user-images.githubusercontent.com/1389127/27885874-99bf31a6-61a7-11e7-830d-2f2a701a791a.PNG)
![step 3 azureapp](https://user-images.githubusercontent.com/1389127/27885885-a08852a6-61a7-11e7-8b1d-f12f3720b0ed.PNG)

**Comment by Jeffders** [comment]
This is fantastic. Thank you for the write-up!
