### ISSUE TITLE
Sign in with Azure - Page Not Found

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Emulator#2393]
## Version
Emulator 4.14.1
Platform: Windows 10

## Describe the bug
Attempting to login to Azure to access various services for a bot configuration file

## To Reproduce

1. Steps to reproduce the behavior:
2. Start the Emulator
3. Go to File > Sign in with Azure
4. The "Sign in with an Azure" panel appears.
5. Click on "Sign in with Azure" button
6. A window appears "Page not found."

## Expected behavior
There should be the Azure authentication window

## Additional context

This has worked on this specific machine in the past. 

Things that I've tried:

1. Reinstalling emulator
2. Verifying azure account - Full access via chrome & portal.azure.com & powershell
3. Reviewed other similar bug reports
4. Cleared the cache (emulator)
5. Reinstalling the emulator for everyone

[bug]

**Comment by anishprasad01** [comment]
Hi @dinobrago,

Could you try clearing the Emulator state (File -> Clear state) and try signing in again? I was able to sign-in to Azure on version 4.14.1 on Windows.

**Comment by dinobrago** [comment]
Yes, I tried that and it did not work. Tried it again per your request with no effect. Same “Page not found” result.

**Comment by anishprasad01** [comment]
Strange. We're unable to reproduce this scenario. Could you check the dev console when you try to sign in and show us what errors appear there?

**Comment by dinobrago** [comment]
When I open the console, I see the attached image. When I attempt to log in to Azure, I do not see any additional entries in the console. 
![image](https://user-images.githubusercontent.com/41213271/180074690-5d772937-2220-41d5-a970-03795d08e850.png)

**Comment by dinobrago** [comment]
I installed the emulator on another machine (a vm on the same machine actually) and I can log into Azure fine.

**Comment by dinobrago** [comment]
I understand. Any documentation on how to do a complete wipe?

**Comment by dinobrago** [comment]
To finish up:
1. I tried uninstalling and doing a deep clean of all emulator references. Reinstalled, same problem.

Finally some success:
2. Uninstalled 4.14. Downloaded 4.8 (picked a random). With this version, I can login to azure. 

I may spend some time working up through different versions but is that of any value?
