### ISSUE TITLE
Ngrok fails to spawn - no matter what (macOS)

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/BotFramework-Emulator#2394]
## Version
Version 4.14.1 (4.14.1.277373)

## Describe the bug
ngrok does not connect

## To Reproduce
Example steps to reproduce the behavior:
1. Open the Bot Framework Emulator bot endpoint configuration

## Expected behavior
I would expect the ngrok connection to work.

## Screenshots
<img width="1712" alt="Screen Shot 2022-08-10 at 19 16 38" src="https://user-images.githubusercontent.com/24418160/183976607-ae4814de-de2c-465a-89c3-d7b8f0a91224.png">

## Additional context
Path to ngrok on my system: `/usr/local/bin/ngrok` (installed with Homebrew)

ngrok version 3.0.6

macOS Version 12.5 (21G72)

Bot Emulator Settings:
<img width="599" alt="Screen Shot 2022-08-10 at 19 23 38" src="https://user-images.githubusercontent.com/24418160/183976952-d86b73f8-37ef-4c7f-95ec-b0c68ec982e2.png">
I tried all kinds of settings, nothing makes ngrok connect to the Bot Emulator.

[bug]

**Comment by tbrodbeck** [comment]
After hours of debugging I found a workaround. Using ngrok version 2: https://dl.equinox.io/ngrok/ngrok/stable/archive

**Comment by dmvtech** [comment]
Possibly related to: https://github.com/microsoft/BotFramework-Emulator/issues/2389

**Comment by axelsrz** [comment]
Closing due to issue fixed.

**Comment by libardolara** [comment]
Was it fixed? I still gave the same issue. I see that #2389 is still open.

**Comment by anishprasad01** [comment]
@libardolara

No, the issue with Ngrok 3 has not been fixed due to other priorities. For the time being, the workaround is to use Ngrok 2. I hope to have this fixed in the near future.

**Comment by anishprasad01** [comment]
Should be fixed once #2399 is merged.
