### ISSUE TITLE
Not able to get the attachment in the backend 

### ISSUE THREAD

**Issue by rahulyadav97185966** [microsoft/BotFramework-Emulator#2405]
## Version
v4

## Describe the bug
Hi Team,

I developed a bot that is currently deployed in MS Teams, For one use case I need to attach an attachment in it, I am able to attach the document using the "attach icon", But when I copy-paste the document directly into a chat, then I am not able to do Since in the backend I am not able to get any response.

In the backend we are getting the response in stepContext.context.activity.attachments when I attach a document through the attachment icon, But when I Copy and Paste it into the chat stepContext.context.activity.attachments are getting as null.

**Comment by dmvtech** [comment]
Closing in lieu of https://github.com/microsoft/botframework-sdk/issues/6560
