### ISSUE TITLE
userData is being cleared mid dialog

### ISSUE THREAD

**Issue by MrTortoise** [Microsoft/BotFramework-Emulator#242]
Hi, 

so i have strange behaviour on a user data object that causes it to be constantly cleared down mid conversation and mid dialog

the code it

``` javascript
var builder = require('botbuilder');

module.exports = [
  function(session) {
    console.log(`location info: start dialog: user data: ${JSON.stringify(session.userData)}`)
    builder.Prompts.text(session, `Enter data one?`);
    console.log(`location info: start dialog: dialog data: ${JSON.stringify(session.dialogData)}`)
  },
  function(session, results, next) {
    session.dialogData.dataOne = results.response;
    next();
  },
  function(session) {
    builder.Prompts.text(session, `What's data two?`);
  },
  function(session, results, next) {
    console.log(`location info: end dialog: user data: ${JSON.stringify(session.userData)}`)
    console.log(`location info: end dialog: dialog data: ${JSON.stringify(session.dialogData)}`)
    session.userData.data = {}
    session.userData.data.dataOne = session.dialogData.dataOne;
    session.userData.data.dataTwo = results.response;
    console.log(`location info: end dialog: after save: ${JSON.stringify(session.userData)}`)

    session.save();
    session.endDialog();
  }
];
```

when the first function is entered the user state is set - i can see previous fields that have been stored.
The dialog data is as it should be.

However when i enter the last function the userData is empty.
When i save the session - i therefor lose all the data that was already in the user data.

I was origionally thinking of using Object.assigns to preserve it but as it is empty that was fruitless.
This then causes conditions towards to route of the conversation as this is a dialog that happens only when previous data exists (but as it has been wiped i go into a loop).

Any ideas?

So the bug is either
1. the session userData should make it into the last function
2. the userData when saved should be combining with a call to get the persistent data and append overwrite at a field level?
3. im a muppet

**Comment by Jeffders** [comment]
This doesn't seem like an emulator issue, but an issue with your code or the Bot Builder SDK. It would be better to post this question either on stackoverflow.com or on the BotBuilder SDK GitHub issues list: https://github.com/Microsoft/BotBuilder

That being said, I'm not sure from the code you provided what the issue is. I don't see from the code where userData is populated in the first three methods (only dialogData). When you re-post to the BotBuilder SDK forum or stackoverflow, can you provide the rest of the issue repo? Thanks!
