### ISSUE TITLE
JSON previewer is not open

### ISSUE THREAD

**Issue by GRpy** [microsoft/BotFramework-Emulator#2427]
JSON previewer is not open, I can't find anything on the internet on how I can open it.
<img width="960" alt="Screenshot_1" src="https://github.com/microsoft/BotFramework-Emulator/assets/113759023/5e776ee7-beba-45f8-bfaa-54b7cca400ce">

**Comment by OEvgeny** [comment]
Clicking on log entries opens the JSON preview for the particular request or response

**Comment by GRpy** [comment]
@OEvgeny thank you, that was a dumb question it's my first type using a bot emulator.
