### ISSUE TITLE
Adaptive card not working on Emulator

### ISSUE THREAD

**Issue by jazzedge** [Microsoft/BotFramework-Emulator#244]
Hi, despite guidance to the contrary, it looks like the adaptive card isn't working on the latest version of the Emulator. I get the following error: [File of type 'application/vnd.microsoft.card.adaptive'] when trying to display the card from this repo: https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-AdaptiveCards/app.js#L138-L153. Any suggestions?

The code is as follows:

var bot = new builder.UniversalBot(connector, function (session) {
var card = {
'contentType': 'application/vnd.microsoft.card.adaptive',
'content': {
'$schema': 'http://adaptivecards.io/schemas/adaptive-card.json',
'type': 'AdaptiveCard',
'version': '1.0',
'body': [
{
'type': 'Container',
'speak': 'Hello!Are you looking for a flight or a hotel?',
'items': [
{
'type': 'ColumnSet',
'columns': [
{
'type': 'Column',
'size': 'auto',
'items': [
{
'type': 'Image',
'url': 'https://placeholdit.imgix.net/~text?txtsize=65&txt=Adaptive+Cards&w=300&h=300',
'size': 'medium',
'style': 'person'
}
]
},
{
'type': 'Column',
'size': 'stretch',
'items': [
{
'type': 'TextBlock',
'text': 'Hello!',
'weight': 'bolder',
'isSubtle': true
},
{
'type': 'TextBlock',
'text': 'Are you looking for a flight or a hotel?',
'wrap': true
}
]
}
]
}
]
}
],
'actions': [
// Hotels Search form
{
'type': 'Action.ShowCard',
'title': 'Hotels',
'speak': 'Hotels',
'card': {
'type': 'AdaptiveCard',
'body': [
{
'type': 'TextBlock',
'text': 'Welcome to the Hotels finder!',
'speak': 'Welcome to the Hotels finder!',
'weight': 'bolder',
'size': 'large'
},
{
'type': 'TextBlock',
'text': 'Please enter your destination:'
},
{
'type': 'Input.Text',
'id': 'destination',
'speak': 'Please enter your destination',
'placeholder': 'Miami, Florida',
'style': 'text'
},
{
'type': 'TextBlock',
'text': 'When do you want to check in?'
},
{
'type': 'Input.Date',
'id': 'checkin',
'speak': 'When do you want to check in?'
},
{
'type': 'TextBlock',
'text': 'How many nights do you want to stay?'
},
{
'type': 'Input.Number',
'id': 'nights',
'min': 1,
'max': 60,
'speak': 'How many nights do you want to stay?'
}
],
'actions': [
{
'type': 'Action.Submit',
'title': 'Search',
'speak': 'Search',
'data': {
'type': 'hotelSearch'
}
}
]
}
},
{
'type': 'Action.ShowCard',
'title': 'Flights',
'speak': 'Flights',
'card': {
'type': 'AdaptiveCard',
'body': [
{
'type': 'TextBlock',
'text': 'Flights is not implemented =(',
'speak': 'Flights is not implemented',
'weight': 'bolder'
}
]
}
}
]
}
};

var msg = new builder.Message(session)
    .addAttachment(card);
session.send(msg);
});

**Comment by Jeffders** [comment]
Hi jazzedge,

I tried your repo code and was able to get the card to render with the emulator version v3.5.29:

![image](https://user-images.githubusercontent.com/8527304/28136581-12aad2f8-66ff-11e7-8967-67e763a7af5f.png)


Can you double check the version you are running...when the emulator is open, click on the vertical three dots to bring up the context menu and choose "About". 

Jeff

**Comment by jazzedge** [comment]
I'm on 3.5.29

**Comment by jazzedge** [comment]
Interestingly, it works on my Mac, not on my Windows laptop. I'll try deleting and installing the Emulator and trying again.

**Comment by Jeffders** [comment]
Did this work once you reinstalled things on Windows?

**Comment by jazzedge** [comment]
Move from 3.5.27 to 3.5.29, now working, thanks!

**Comment by vishal4388** [comment]
Thank you jazzedge. your code worked for me...

**Comment by giorigor** [comment]
I'm having this issue with the latest version (4.0.15 alpha). It works on channels (Slack, Teams, etc) but it can't render the card in the emulator itself.

[Emulator](https://user-images.githubusercontent.com/10777906/43969905-07779842-9ca2-11e8-85ff-4c14957853b0.png) | [Teams](https://user-images.githubusercontent.com/10777906/43969866-e95cc5a8-9ca1-11e8-8e0a-b129c6dce066.png)

```c#
AdaptiveCard card = new AdaptiveCard();
card.Body = new List<AdaptiveElement>()
{
    new AdaptiveTextBlock()
    {
        Text = "Lorem ipsun"
    },
    new AdaptiveDateInput()
    {
        Value = DateTime.Now.ToShortDateString()
    },
    new AdaptiveTimeInput()
    {
        Value = DateTime.Now.ToShortTimeString()
    }
};

var msg = context.MakeMessage();
msg.Attachments.Add(
    new Attachment()
    {
        Content = card,
        ContentType = "application/vnd.microsoft.card.adaptive",
        Name = "Lorem Ipsun"
    }
);

await context.PostAsync(msg);
context.Wait(this.MessageReceived);
```
