### ISSUE TITLE
Bot Framework Emulator Login problem

### ISSUE THREAD

**Issue by miguefferreira** [microsoft/BotFramework-Emulator#2445]
When trying to login to my Azure account on the Bot Framework Emulator I get the following window:

![image](https://github.com/microsoft/BotFramework-Emulator/assets/155663200/571eb00b-3553-458e-a33d-a436d1357bb2)

I was successful the first time after installation and I do remember selecting the option to always stay logged in but upon restarting the app I have been getting this error ever since. CLearing the state does not change the behaviour. 

I have seen this issue mentioned here in an older post but it was left without a solution.

Any help is appreciated.

**Comment by dmvtech** [comment]
I am able to reproduce the same after clicking `Sign in with Azure`.

![image](https://github.com/microsoft/BotFramework-Emulator/assets/43397658/71f66080-e149-4f42-b68c-9c5843f3b3d3)

**Comment by tracyboehrer** [comment]
@ceciliaavila This happens for Dana too, but not others.  Can you help figure out what's going on?

**Comment by JhontSouth** [comment]
Hi @dmvtech, @tracyboehrer
We could reproduce the error with Emulator 4.14.1. But, we also tested with the latest [nightly](https://github.com/microsoft/botframework-emulator-nightlies/releases) version and the error does not occur here.
We suggest using the latest nightly version for the moment.
