### ISSUE TITLE
Support ngrok v3.1

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Emulator#2446]

**Comment by ceciliaavila** [comment]
@tracyboehrer, support for _Ngrok_ 3.1 is ready in the nightly version. 
We created issue #2450 to include support for _Azure Relay_ service as a nice-to-have feature.

**Comment by tracyboehrer** [comment]
[like]  Tracy Boehrer reacted to your message:
________________________________

**Comment by sambathrajv** [comment]
Hi, Any ETA on this request?? The  2.3 version of ngrok is not supported without paying additional fee. Ngrok changed this and it doesn't work any more.

**Comment by tracyboehrer** [comment]
@sambathrajv While not released yet, the latest version on https://github.com/microsoft/botframework-emulator-nightlies/releases will work.
