### ISSUE TITLE
"The bot's Microsoft App ID or Microsoft App Password is incorrect." after following Steps to Add Cosmos DB

### ISSUE THREAD

**Issue by HemantTiwariGitHub** [microsoft/BotFramework-Emulator#2449]
## Version
4.14.1

## Describe the bug
Follow the steps at https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp 

The memory bot works well with emulator.

After adding changes to use Cosmos DB from same tutorial, the code runs fine, 
However  emulator states 
 `{
  "message": "The bot's Microsoft App ID or Microsoft App Password is incorrect.",
  "status": 400
}`

The app id and password is exactly same as in appsettings.json.

## To Reproduce
1. Follow Steps at https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp 
and run the bot with Cosmos DB
2.  Start Emulator and Input URL, Microsoft App ID, Microsoft App Password (App ID and Password to be exactly same as in appsettings.json)
3. error "The bot's Microsoft App ID or Microsoft App Password is incorrect." is observed.

## Expected behavior
The Emulator would connect to bot process. 

## Screenshots
<img width="829" alt="image" src="https://github.com/microsoft/BotFramework-Emulator/assets/9350097/7b61ea9d-fda9-4338-ac6b-885723d8dc30">

[bug]

**Comment by HemantTiwariGitHub** [comment]
Workaround Fix: Use V 4.18.1 and not the latest version.
Azure Bot FW please fix the issue in later versions.

**Comment by dmvtech** [comment]
Hi @HemantTiwariGitHub 

What version of the SDK does the problem reproduce with? I just tested with `v4.18.1` and then upgraded to `v4.22.1` and both worked. This was with version `4.14.1` of Emulator.

**Comment by dmvtech** [comment]
Closing due to lack of response.
