### ISSUE TITLE
Refresh access token failed with status code: 401

### ISSUE THREAD

**Issue by arthurtina724** [Microsoft/BotFramework-Emulator#245]
Emulator Version: 3.5.29
BotBuilder Version 3.8.5 (.net sdk)

The error I am getting in the emulator when trying to connect to my bot is: Refresh access token failed with status code: 401. My microsoftAppId is "test" and my microsoftapppassword is "pass". I am also using a credential provider because I want the creds to be read from a config section vs appSettings: 
**[BotAuthentication(CredentialProviderType = typeof(BotCredentialProvider))]**

I've read that you can provide any text for the appid/pass when using the emulator as long as it matches what is configured in web.config. Is this true? I've tested this already and only the registered bots with generated  appid/passwords have worked for me in every version of emulator I've used.

**Comment by eanders-MS** [comment]
Hi @arthurtina724, Your Microsoft AppId and Password must be issued by the identify service at https://apps.dev.microsoft.com. They cannot be arbitrary. The simplest way to get an MSA appId and password assigned to your bot is to register it with the Bot Framework at https://dev.botframework.com/bots/new

**Comment by arthurtina724** [comment]
Thanks @eanders-MS. I will close this issue.

**Comment by arthurtina724** [comment]
@eanders-MS  when I do use a custom CredentialProviderType there is one functionality that does not work with the emulator. When creating a new bot project using the provided VS template the MicrosoftAppId and MicrosoftAppPassword are "" strings and even with the BotAuthentication decorator the emulator bypasses auth and seems to work correctly. If you provide a CredentialProviderType this scenario does not work and results in a 401 status. Its not a huge deal to generate a appid/pass, but is this a valid issue to put in the backlog of the sdk or emulator repo to support non-registered bot applications that we want to test using the emulator initially?

**Comment by eanders-MS** [comment]
You can generate an appId and password directly from https://apps.dev.microsoft.com. No strict need to register your bot with the Bot Framework.
