### ISSUE TITLE
I cant see my adaptive card on the Bot builder emulator, it appears as blank.

### ISSUE THREAD

**Issue by jpiabrantes** [microsoft/BotFramework-Emulator#2452]
## Version
4.14.1

## Describe the bug
My adaptive card does not show, it appears only a grey rectangle.

## To Reproduce
<details>
<summary>Here's the json of my adaptive card</summary>

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "Hello!"
    },
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "You can also use commands to my default language (!lang <desired language>). Type !help to see all the available commands!"
    },
    {
      "type": "TextBlock",
      "weight": "bolder",
      "text": "Choose a conversation starter:"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "How to close the cash register?",
      "data": {
        "value": "How to close the cash register?"
      }
    },
    {
      "type": "Action.Submit",
      "title": "How to handle a return?",
      "data": {
        "value": "How to handle a return?"
      }
    }
  ]
}
```
</details>

**Comment by OEvgeny** [comment]
@jpiabrantes please try the latest nightly release https://github.com/Microsoft/botframework-emulator-nightlies/releases

**Comment by stevkan** [comment]
@jpiabrantes - I just tested your adaptive card in Emulator (using the same version) and I am able to see the rendered card. Could you try some of the following tests:
- Can you try a different adaptive card. Perhaps one from the adaptive cards designer or from one of our samples?
- Can you try sending other attachments such as a hero card or a file?
- Can you provide the code for how you are sending your adaptive card?
