### ISSUE TITLE
Update set-up documentation

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/BotFramework-Emulator#2453]
## Description
We need to update the set-up documentation in [CONTRIBUTING.md](https://github.com/microsoft/BotFramework-Emulator/blob/main/CONTRIBUTING.md#how-to-build-from-source) to reflect the current requirements. 
E.g.: It recommends using Node.js version 10 to build the project, but it doesn't work.

**Comment by OEvgeny** [comment]
@ceciliaavila I had some changes stashed. Published them in #2454. It works for me. Feel free to reuse!

**Comment by ceciliaavila** [comment]
> @ceciliaavila I had some changes stashed. Published them in #2454. It works for me. Feel free to reuse!

Great, Thanks!!
