### ISSUE TITLE
Unable to install botframework emulator both 3.5.28 and 3.5.29 versions

### ISSUE THREAD

**Issue by aswinsriram** [Microsoft/BotFramework-Emulator#250]
![emulator issue](https://user-images.githubusercontent.com/25322395/28421633-5d029950-6d83-11e7-9f0f-557845628e5a.PNG)
Hi,
I am unable to install botframework emulator both 3.5.28 and 3.5.29 versions. I am getting error as attached. To check the logs i clicked on "Open Setup Log" and it is opening a notepad with no logs in it.

Please help me to install the right version of emulator.
 
![emulator issue](https://user-images.githubusercontent.com/25322395/28421503-029270bc-6d83-11e7-86dd-01ea92574866.PNG)

**Comment by eanders-MS** [comment]
Is your OS 32-bit? I ask because we don't yet support 32-bit Windows, but support for it is coming in a future release.

**Comment by aswinsriram** [comment]
@eanders-MS, I am using 64 bit OS and Windows 10 only.

**Comment by aswinsriram** [comment]
Here is the snap shot for the same

![capture](https://user-images.githubusercontent.com/25322395/28432477-ab17893a-6da5-11e7-966d-e191c4ba2389.PNG)

**Comment by eanders-MS** [comment]
Try opening this file in notepad: %LocalAppData%\SquirrelTemp\SquirrelSetup.log, e.g.:
```
C:\> start %LocalAppData%\SquirrelTemp\SquirrelSetup.log
```
All apps that use the Squirrel installer system write to this log. If you're able to open it, scroll to the bottom of the file and look for entries for botframework-installer. There may be an error listed there.

**Comment by aswinsriram** [comment]
@eanders-MS, As i mentioned in my original post, the log file is empty.

**Comment by aswinsriram** [comment]
I checked the "Event viewer" for any logs but still no luck. Any advice to install the Emulator in my system.

**Comment by eanders-MS** [comment]
I'm sorry you're having difficulty installing the emulator. The installer system we use right now does not provide tools for troubleshooting (no verbose logging mode, no ability to log to the console). The most expedient way to get the emulator working on your machine may be to build and run from source. https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#build-and-run-from-source

We will be moving off Squirrel to another installer technology in a near future release.

**Comment by aswinsriram** [comment]
Thanks for the update and when is the tentative release date for the new installer.

**Comment by eanders-MS** [comment]
Hi @aswinsriram, We released emulator v3.5.31 today. It is still Squirrel-based, but you might try it out anyway.

**Comment by aswinsriram** [comment]
Hi @eanders-MS , Thanks for the update and still i have the same issue with V3.5.31.

**Comment by eanders-MS** [comment]
It's a shot in the dark, but can you try this: delete the `C:\%LocalAppData%\SquirrelTemp\` folder and try the install again.

**Comment by aswinsriram** [comment]
@eanders-MS, Hmmm it worked :). Thanks for your help. I am able test my first bot.
