### ISSUE TITLE
Bot emulator does not send data from adaptive card inputs on submit

### ISSUE THREAD

**Issue by mrussell-curiosity** [Microsoft/BotFramework-Emulator#255]
The Bot Emulator version 3.5.29 does not send data from input fields with a submit action on an adaptive card. Given a form that looks like:
```
{
    "contentType": "application/vnd.microsoft.card.adaptive",
    "content": {
      "type": "AdaptiveCard",
      "body": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "size": 1,
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Enter a search term",
                  "weight": "bolder",
                  "size": "large"
                },
                {
                  "type": "Input.Text",
                  "id": "term",
                  "placeholder": "Science, philosophy, art...",
                  "style": "text"
                }
              ]
            }
          ]
        }
      ],
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Search",
          "data": {
            "type": "search"
          }
        }
      ]
    }
  }
```

The card renders as I would expect in the Bot Emulator. However, when I enter a string, like "science", in the text field with id `term`, and hit the submit action, the value of that field is never sent to my bot service.

When I receive a message from the Bot Emulator, this is what it looks like:
```
{
  "type": "message",
  "value": {
    "type": "search"
  },
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "id": "ji86436bbcc1jd9i",
  "channelId": "emulator",
  "timestamp": "2017-07-28T17:56:02.071Z",
  "localTimestamp": "2017-07-28T12:56:02-05:00",
  "recipient": {
    "id": "default-bot",
    "name": "Bot"
  },
  "conversation": {
    "id": "9h88n4945h3bblg2ac"
  },
  "serviceUrl": "http://127.0.0.1:54445"
}
```
You can see that the `value` field in the message above contains `{ "type": "search" }` but not the value of the field with id `term`. I'd expect to see `{ "type": "search", "term": "Science"'}` in the message value.

I've tested this card JSON in the adaptive card visualizer (http://adaptivecards.io/visualizer/), using the JSON within the `content` block above and it works perfectly fine in the visualizer. When I click the submit action it shows that I should be receiving the `term` value in the message value.

Please advise.

Thanks,

Mike

**Comment by eanders-MS** [comment]
This is likely due to the fact that we haven't release a new emulator in a while, and the version of adaptive cards it makes use of is now out of date. We have a new emulator release coming very soon. If you need the latest behavior immediately, you may choose to build and run the emulator from source https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#build-and-run-from-source

**Comment by eanders-MS** [comment]
Hi @mrussell-curiosity, Emulator v3.5.31 was released today. Please try it out and let us know if this issue no longer repros.

**Comment by eanders-MS** [comment]
Closing now. If you're still seeing this issue with the new emulator, reply here and we'll reopen.
