### ISSUE TITLE
Starting with F5 gives Node.js version error

### ISSUE THREAD

**Issue by nsantini** [Microsoft/BotFramework-Emulator#257]
Hi, im using Node v6.11.1. I followed the instructions to run locally. If I start it with F5 I get:

```
Error: The module './BotFramework-Emulator/node_modules/bunyan/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

**Comment by eanders-MS** [comment]
If you updated your version of Node recently, then you might need to rebuild the project's npm dependencies. Did you try running `npm rebuild`?

**Comment by nsantini** [comment]
@eanders-MS Is a fresh clone with npm install and npm build all done yesterday

**Comment by nsantini** [comment]
Although I still get the error message, I can actually run the emulator in debug mode if I change launch.json protocol to inspector

**Comment by eanders-MS** [comment]
Thanks for the update. I'm still unsure what the problem is, but glad to hear you're not blocked by it.
