### ISSUE TITLE
[Bug] HTML (using textFormat='xml') message formatting is broken in 3.5.31 release

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-Emulator#261]
Latest release of Emulator v3.5.31 has broken previously working HTML message formatting. 

**Before - v3.5.29**
<img width="804" alt="screen shot 2017-08-01 at 5 25 27 pm" src="https://user-images.githubusercontent.com/3075047/28852601-43e310c0-76df-11e7-83d9-79b0f6c13f22.png">

**After - v3.5.31**
<img width="795" alt="screen shot 2017-08-01 at 5 24 51 pm" src="https://user-images.githubusercontent.com/3075047/28852604-4cd00152-76df-11e7-99bf-c6da4b15abef.png">

**Code Example - Node.js SDK**
```js
bot.dialog('html_table', function (session) {
    var tableHTML = '<table style="padding:10px;border:1px solid black;"><tr style="background-color:#c6c6c6"><th>Countries</th><th>Capitals</th><th>Population</th><th>Language</th></tr><tr><td>USA</td><td>Washington D.C.</td><td>309 million</td><td>English</td></tr><tr><td>Sweden</td><td>Stockholm</td><td>9 million</td><td>Swedish</td></tr></table>';
    var message = {
        type: 'message',
        textFormat: 'xml', 
        text: tableHTML
    };
    session.send(message).endDialog();
});
```
**Expected:**
HTML message formatting is supported in Emulator.

**Comment by eanders-MS** [comment]
Looks like it's by design in the WebChat control: https://github.com/Microsoft/BotFramework-WebChat/commit/a5cd8cffb7a97fb925e4078dbe1085694fa92f80

**Comment by danmarshall** [comment]
@nwhitmont - can you provide a link to the test code above?

**Comment by nwhitmont** [comment]
@danmarshall 
https://github.com/nwhitmont/botframework-skype-support-dev/blob/master/server.js#L154

**Comment by vijaysaimutyala** [comment]
@danmarshall @nwhitmont Is HTML now supported by the emulator? I'm on v4.2.1 but still see the tags not rendered. The web chat is supporting HTML when u do a custom build enabling the html as in the [post](https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/). Do we have to do a custom build for the emulator as well to enable html ?

**Comment by tonyanziano** [comment]
Hello @vijaysaimutyala ,

We currently don't have a custom build for the emulator that has HTML enabled in the embedded Web Chat control. However, if you really need HTML support, you could fork the Emulator repo, and instead of using the provided version of Web Chat, use your own local custom build of Web Chat that enables HTML.
