### ISSUE TITLE
Microsoft Emulator stopped rendering HTML

### ISSUE THREAD

**Issue by tgparmar75** [Microsoft/BotFramework-Emulator#263]
This morning, when I ran my BOT on the Bot Framework Channel Emulator, The <b> "Bold" tag stopped rendering and as a result I see a markup rather than the formatted content.

**Comment by ejadib** [comment]
Check https://github.com/Microsoft/BotFramework-Emulator/issues/261

**Comment by EricDahlvang** [comment]
Hi @tgparmar75 

Thank you for reporting this.  Please provide feedback on this WebChat repo issue: https://github.com/Microsoft/BotFramework-WebChat/issues/604

**Comment by eanders-MS** [comment]
@tgparmar75 Once an updated WebChat control is published, we'll release a new emulator with the fix.
