### ISSUE TITLE
My Bot is not receiving audio recorded by microphone icon

### ISSUE THREAD

**Issue by mrctito** [Microsoft/BotFramework-Emulator#267]
My Bot is not receiving audio recorded by microphone icon.

When I press microphone icon and start to talk, the emulator imediatly translate what I am sayng to text and show it inside text writing box. Therefore, the bot emulator does not call my ApiController, as it should do. 

Thus, my method "public async Task<HttpResponseMessage> Post([FromBody]Activity activity)" is never called.

Thank you!

**Comment by eanders-MS** [comment]
Hi @mrctito, Your question pertains to BotFramework-WebChat control (used by the emulator).  It would be more appropriate to open an issue with that project. https://github.com/Microsoft/BotFramework-WebChat/

**Comment by mrctito** [comment]
OK. Thank you.
