### ISSUE TITLE
Messages not appearing in chat

### ISSUE THREAD

**Issue by michael-golfi** [Microsoft/BotFramework-Emulator#268]
Hi, I'm developing a bot using REST endpoints for the Bot Connector. I'm sending messages from the bot to the emulator and only the first message in the chat physically appears in the chat window but the rest of them are showing in the log.

Here's an image of I'm seeing on my end:
![image](https://user-images.githubusercontent.com/1388500/29227111-7027d0ba-7e89-11e7-836b-dce67a96c62b.png)

Furthermore, the messages are coming in swapped, I was wondering if this is intended. I'm getting the bots response in the log before the message I sent.

**Comment by eanders-MS** [comment]
Can you supply the entire error shown in the log? (you can enable word wrap to see the entire line)

Out of order log entries is a known bug: https://github.com/Microsoft/BotFramework-Emulator/issues/82

**Comment by michael-golfi** [comment]
Ok so I'm going to clear it all and show you the flow from start conversation.

![image](https://user-images.githubusercontent.com/1388500/29228112-66e9d652-7e8d-11e7-86f3-57a36f58c788.png)

The message appears after I type a character or click on a chat message, I was thinking some sort of UI event needs to occur for it to appear.

![image](https://user-images.githubusercontent.com/1388500/29228123-74d64ae8-7e8d-11e7-8bec-718af6acea7c.png)

No more replies coming from the bot
![image](https://user-images.githubusercontent.com/1388500/29228150-8939b9e8-7e8d-11e7-9082-7c9290797137.png)

On the other hand, if I start a new conversation and send a message then click on my message in the chat window, I get the following error. The error reappears every time I click on another chat message (so I've clicked four times on the difference messages.

![image](https://user-images.githubusercontent.com/1388500/29228236-da48957a-7e8d-11e7-9489-28f2b94c7192.png)

**Comment by eanders-MS** [comment]
The appearance of `react-redux` in the file path tells me the error is originating from within the webchat control. The emulator consumes this control as an npm package.

My hunch is that the message JSON has missing or malformed data. I can see one unexpected field in your JSON view: the "Action" field is not part of the message activity schema. Is that something you're adding to the activity?

Can you post the entire JSON of the message shown in the last screenshot?

**Comment by michael-golfi** [comment]
Here is the message the bot sends back:

```json
{
  "channelId": "emulator",
  "conversation": {
    "id": "dm96ggck03m4",
    "isGroup": false,
    "name": ""
  },
  "from": {
    "id": "default-bot",
    "name": "Bot"
  },
  "locale": "en-US",
  "localTimestamp": "2017-08-11T12:56:56.0157371-07:00",
  "recipient": {
    "id": "default-user",
    "name": "User"
  },
  "relatesTo": {
    "activityId": "h8cg3990l6fk",
    "bot": {
      "id": "default-bot",
      "name": "Bot"
    },
    "channelId": "emulator",
    "conversation": {
      "id": "dm96ggck03m4",
      "isGroup": false,
      "name": ""
    },
    "serviceUrl": "http://localhost:51129",
    "user": {
      "id": "default-user",
      "name": "User"
    }
  },
  "replyToId": "h8cg3990l6fk",
  "serviceUrl": "http://localhost:51129",
  "suggestedActions": {
    "to": null,
    "actions": null
  },
  "text": "Hello User!",
  "textFormat": "plain",
  "timestamp": "2017-08-11T19:56:56.0157371Z",
  "type": "message",
  "id": null
}
Log

```

**Comment by eanders-MS** [comment]
Closing this issue as it's getting tracked by the WebChat project now: https://github.com/Microsoft/BotFramework-WebChat/issues/636
