### ISSUE TITLE
Not seeing json under details section

### ISSUE THREAD

**Issue by sbrnag** [Microsoft/BotFramework-Emulator#27]
Not able to see the json under details section in emulator when i am connected to a bot running locally

**Comment by eanders-MS** [comment]
Hi @sbrnag The details pane should display the JSON of a chat message when it is clicked on in the chat window. Is this not working for you?

**Comment by sbrnag** [comment]
Yes.

**Comment by eanders-MS** [comment]
When a chat message is selected, it gets a black background color. Can you verify this happens when you click on a message in the chat window?

**Comment by sbrnag** [comment]
Yes clicking on message i am able to see the JSON. 
Thanks a lot for your quick reply
