### ISSUE TITLE
Microsoft bot framework emulator not working offline

### ISSUE THREAD

**Issue by HaythamBS** [Microsoft/BotFramework-Emulator#271]
Hi everyone am trying to run the default project sample that comes with the MS bot framework template , when am connected to the internet the bot runs normally but when am offline the bot doesnt work and i got this error in the console : **"POST getaddrinfo ENOENT localhost:3979"** .does the emulator needs internet connection to work???

**Comment by eanders-MS** [comment]
If you're in airplane mode then you might not be able to do DNS lookups... even for localhost. Try replacing localhost with 127.0.0.1 for your bot's endpoint:

![image](https://user-images.githubusercontent.com/12176807/29375122-c2ec1f58-8268-11e7-834d-8831ee086e34.png)

**Comment by HaythamBS** [comment]
Hi thanks for the answer, am not on airplane mode , and i tried replacing "localhost" with "127.0.0.1" the other error is gone and i get another one "POST 400 [ConversationUpdate]".

**Comment by eanders-MS** [comment]
A 400 error indicates the emulator was able to get some kind of response back from your bot (albeit an error code). Going ahead and closing this issue now. Please reply here or open a new issue if you'd like assistance working through the 400 error.

**Comment by elfico** [comment]
Hello @eanders-MS , can you please provide me some assistance on how to work through the 400 error when using the bot emulator offline? I replace the address with 127.0.0.1 and got "POST 400 [Converstion Update]. I have tried to figure it out with out success. Thanks
