### ISSUE TITLE
Error: Invalid channelId='facebook'

### ISSUE THREAD

**Issue by dundas** [Microsoft/BotFramework-Emulator#273]
Hi there,
 
I'm trying to send a proactive message but getting an error. I'm using the exact code from the docs. 

var bot = new builder.UniversalBot(connector);

function sendProactiveMessage(address) {
    var msg = new builder.Message().address(address);
    msg.text('Hello, this is a notification');
    msg.textLocale('en-US');
    bot.send(msg);
}

And here is my address which I have taken saved: 

var address = {
    "id": "REMOVED"
    , "channelId": "facebook"
    , "user": {
        "id": "REMOVED"
        , "name": "REMOVED"
    }
    , "conversation": {
        "isGroup": "false"
        , "id": "REMOVED"
    }
    , "bot": {
        "id": "REMOVED"
        , "name": "REMOVED"
    }
    , "serviceUrl": "https://facebook.botframework.com"
}

can anyone help me out here?

Thanks

**Comment by eanders-MS** [comment]
Hi @dundas, this page is for issues pertaining to the BotFramework-Emulator. Please post your issue at the BotBuilder SDK repo (https://github.com/Microsoft/BotBuilder/issues). Thanks.

**Comment by eanders-MS** [comment]
Or, did I misunderstand? Are you sending this message to the emulator?

**Comment by dundas** [comment]
Nope you're right. I'll repost. Thnx!
