### ISSUE TITLE
Install on macOS Sierra failed.

### ISSUE THREAD

**Issue by ZaurIsakov** [Microsoft/BotFramework-Emulator#274]
Is there any solution? Please, help!!!(((

**Comment by BKDaugherty** [comment]
Having the same problem ^^^

**Comment by circulon** [comment]
This is the Same as #208 and I have listed a workaround there in the recent comments

**Comment by eanders-MS** [comment]
Hi folks. Just wanted to post a status update to let you know we're working on a solution for this. My best estimate is the fix will be in the release after next.

**Comment by eanders-MS** [comment]
https://github.com/Microsoft/BotFramework-Emulator/issues/208 has a workaround that's been shown to work for multiple mac users. Closing now. If you're still hitting this issue, let us know and we'll reopen.
