### ISSUE TITLE
DateTimeOffset object is losing its offset when added to PrivateConversationData for the first time

### ISSUE THREAD

**Issue by gled4er** [Microsoft/BotFramework-Emulator#277]
Hello,

When adding DateTimeOffset in PrivateConversationData in the Emulator and Skype for Business by using the code:

context.PrivateConversationData.SetValue(Util.DataName.MeetingSelectedDateDatetimeOffset, defaultStartDate) // we input Date = {8/31/2017 12:00:00 AM} and  Offset = {09:00:00}

we are loosing the time offset. For retrieving the same value we are using the following code:

 var savedDateOffset = context.PrivateConversationData.GetValue<DateTimeOffset>(Util.DataName.MeetingSelectedDateDatetimeOffset); // we get Date = {8/30/2017 12:00:00 AM} and  Offset = {00:00:00}

This is happening only the first time after starting the emulator or after not using the bot in Skype for Business for a while.

Thank you!

**Comment by eanders-MS** [comment]
Items stored in private conversation data are not modified by the emulator. You may have better luck asking on the BotBuilder SDK issues page: https://github.com/Microsoft/BotBuilder/issues
