### ISSUE TITLE
Speech output chooses voice with incorrect locale

### ISSUE THREAD

**Issue by tiloc** [Microsoft/BotFramework-Emulator#279]
I am using the emulator on a Win 10 machine with the OS locale set to German. I click the microphone icon in the chat window and speak to my bot. The bot then responds with spoken language as expected.
I am seeing a difference between web chat and the emulator, though. When I do the same on web chat, the bot responds with an English voice (the bot is English). When I do it in the emulator, it reads the English texts from my bot through a German voice. This is entertaining but useless. I have made sure that during connection I set the locale to "EN". Seems that the bot locale is ignored and the locale of the OS is being used?

**Comment by danmarshall** [comment]
@shahidkhuram can you look into this?

**Comment by Tijo1011** [comment]
Same with my project. Is there a solution?

**Comment by compulim** [comment]
Looks similar to https://github.com/Microsoft/BotFramework-WebChat/issues/939.

We didn't pass OS locale to SpeechRecognition/SpeechSynthesis object.

**Comment by cwhitten** [comment]
Addressed in https://github.com/Microsoft/BotFramework-WebChat/issues/939. Closing.
