### ISSUE TITLE
Linux Bot Emulator on Ubuntu 14 Returns InternalError to Every Message

### ISSUE THREAD

**Issue by jjmontgo** [Microsoft/BotFramework-Emulator#280]
Emulator version: 3.5.31
Node version: 6.3.1
OS: Ubuntu 14.04

I'm trying to get started with the bot emulator, but I can't seem to get it to work.

I am sending it a POST message and it is replying with a 500 internal server error.

I'm able to repeat the error outside of my code from the command line in curl:

`curl -k -X POST localhost:44347/v3/conversations/1c2jbheg4egf/activities/044g77l59nf6m -d @payload.txt --header "Authorization: Bearer <MICROSOFT_APP_ID>"`

Here is the JSON content of the payload.txt file:

```
{"conversation":{"id":"1c2jbheg4egf"},"from":{"id":"0kmhi11ge90k9","name":"Bot"},"locale":"en-GB","recipient":{"id":"default-user","name":"User"},"rep
lyTold":"044g77l59nf6m","type":"message","text":"Normally I wouldnt say this but...","speak":"You aren't working!","textFormat":"plain"}
```

Here is the exact response I am receiving from the emulator:

`{"code":"InternalError","message":"Cannot read property 'header' of null"}`

I've searched this error message and haven't found this exact case.  I've also tested this in a live environment and the message is coming through properly there.

I'd really like to get going with the framework in my development environment, but this has brought progress to a stop.  If anyone can provide insight in how to get past this I would appreciate it.

**Comment by eanders-MS** [comment]
I recommend simplifying the scenario as much as possible, just to get your bot and the emulator talking. Take a look at this auth troubleshooting guide that can walk you through the steps: [Troubleshooting Bot Framework authentication](https://docs.microsoft.com/en-us/bot-framework/troubleshoot-authentication-problems). Please follow the steps in the section titled **Step 1: Disable security and test on localhost**, then report back here if you're still having trouble.

**Comment by jjmontgo** [comment]
Hi @eanders-MS !
Thank you for responding.  I have already disabled authentication and am using localhost.

**Comment by jjmontgo** [comment]
Hi @eanders-MS !

Thanks for the reply.  I have already disabled security and I am testing on localhost.  

My script is receiving conversation updates and messages from the emulator, but when my script sends a message to the emulator the situation is as described above.

**Comment by jjmontgo** [comment]
Thanks for the response!  Okay!

I removed the App ID and password from the emulator, and I stopped sending the emulator an Authorization header.

Now it works. :)

**Comment by eanders-MS** [comment]
Glad it worked! The troubleshooting guide may also prove helpful once you're ready to add auth back in.
