### ISSUE TITLE
Windows Store port?

### ISSUE THREAD

**Issue by manuelelucchi** [microsoft/BotFramework-Emulator#284]
Hi, I'm using your emulator to test my bots, but the electron apps update style is really painful. It would be awesome if you could port it in the Windows Store with the desktop bridge, to make it easy to download and update it

**Comment by eanders-MS** [comment]
Thanks for the good suggestion @manuelelucchi.

**Comment by manuelelucchi** [comment]
No problem!

**Comment by tonyanziano** [comment]
Hi @manuelelucchi ,

Thanks for the suggestion, but we currently have no plans to port the Emulator to the Windows Store.
