### ISSUE TITLE
BotFramework emulator is unable to give response back

### ISSUE THREAD

**Issue by anjalirathore** [Microsoft/BotFramework-Emulator#285]
I am creating a bot and using bot builder SDK 3.9.1. When I am connecting bot emulator to my bot, and typing message in it, it is not responding anything. And the cmd prompt showing following error - 

c:\luis_bot>node app3.js
restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
Error: Request to 'http://localhost:58202/v3/botstate/emulator/conversations/f6di42mc26ah/users/default-user' failed: [503] Service Unavailable
    at Request._callback (c:\luis_bot\node_modules\botbuilder\lib\bots\ChatConnector.js:524:46)
    at Request.self.callback (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)

Please tell me the possible reasons and how to solve it. 
Here is the code that I am using - 

var restify = require('restify');
var builder = require('botbuilder');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var bot = new builder.UniversalBot(connector, function (session) {
    
    session.send("You are dumb: %s", session.message.text);
    

});

**Comment by eanders-MS** [comment]
Hi @anjalirathore what do you see in the emulator log, if anything?

**Comment by rifaterdemsahin** [comment]
I also have the same error
receive - emulator running without security enabled.

There is no reply back

![image](https://user-images.githubusercontent.com/5270036/40051654-6fce34ae-5833-11e8-9527-b15577e97dd9.png)

**Comment by rifaterdemsahin** [comment]
Emulator log
[11:28:51]Emulator listening on http://localhost:64712
[11:28:51]ngrok not configured (only needed when connecting to remotely hosted bots)
[11:28:51]Connecting to bots hosted remotely
[11:28:51]Edit ngrok settings
[11:28:51]POST201directline.startConversation
[11:28:58]->messagehttps://github.com/Microsoft/BotFramework-Emulator...
[11:28:58]POST202directline.postActivity
[11:29:18]->messagechatops what is your purpose
[11:29:18]POST202directline.postActivity

**Comment by cwhd** [comment]
I am getting the same error, and originally posted another issue https://github.com/Microsoft/BotFramework-Emulator/issues/488
but closed it because for some reason it started working again.  For me when I test with c# bots locally everything works, but for bots written in node I get this behavior: the bot starts up, I can send messages to it, I get message received from the bot, but no answer.  Today the emulator stopped working again so while searching around I found this issue and am piling on.

My **guess** is this has something to do with the network.  As the only thing that's changed for me is I'm in a different location I think that my computer is for some reason blocking responses or causing something to not respond.  I'm also guessing this because I've seen other troubleshooting include "bypass ngrok for local address" which I have selected, but am getting behavior from the emulator as if I don't.  Is there any way to troubleshoot this or get you guys more info?

**Comment by AskYous** [comment]
I'm getting the same issue when following this tutorial:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-3.0#connect-to-a-bot-running-on-local-host

**Comment by AskYous** [comment]
I tested it in 3.5.36 instead of the latest release. Still fails.

**Comment by AskYous** [comment]
I also get this error in case it helps:

![image](https://user-images.githubusercontent.com/791996/43866682-79b9b99a-9b1b-11e8-8c3d-e1ebde34894d.png)

**Comment by cwhitten** [comment]
Closing in lieu of @AskYous 's workaround.
