### ISSUE TITLE
Inputs on adaptive cards are not visible

### ISSUE THREAD

**Issue by macrozone** [Microsoft/BotFramework-Emulator#286]
using the exact same code as in https://github.com/Microsoft/BotFramework-Emulator/issues/244, but all inputs are missing. only the actions are visible:

<img width="653" alt="bildschirmfoto 2017-09-13 um 15 28 37" src="https://user-images.githubusercontent.com/1972353/30379893-4cdf3958-9898-11e7-9142-bb0e57e446ac.png">

using latest emulator

**Comment by mgbennet** [comment]
I'm not able to reproduce the issue. With the code from #244, the inputs become visible after the "Hotels" button is pressed.

![emulator-adaptivecard](https://user-images.githubusercontent.com/5344804/30392695-6cd80efe-9872-11e7-8968-7cd1e06b6f97.png)

Is this not the intended effect? If you're expecting the inputs to be visible when the card is sent, you'll need to adjust the card's code.

**Comment by macrozone** [comment]
@mgbennet you are completly right, i did not notice that the buttons are supposed to show the formular hidden. Personally i think its not clear from a ux perspective that these buttons are supposed to show hidden content.
