### ISSUE TITLE
Error in log after Installing using windows 7 64 bit

### ISSUE THREAD

**Issue by shivamtandon11** [Microsoft/BotFramework-Emulator#287]
I am getting this error after installing. When I run the app in visual studio , I get error displaying unable to connect to port 3978, debugger not installed properly. Please help.

![image](https://user-images.githubusercontent.com/22115569/30400194-b2d0c42e-98f3-11e7-8a85-865b69d3902b.png)

![image](https://user-images.githubusercontent.com/22115569/30400069-5f7d6372-98f3-11e7-888f-0c66458f7236.png)

**Comment by jusso-dev** [comment]
This is a Visual Studio issue not Bot Framework Emulator issue. Can you run the project without starting in Debug mode? CTRL + F5

**Comment by eanders-MS** [comment]
Hi @shivamtandon11. Sorry you're having this problem. @jusso-dev is correct, this looks like something related to your Visual Studio install rather than the emulator. I recommend you address this issue first. You should be able to launch your bot in the debugger without error.

The error you're seeing in the emulator's log is a failure of the auto-update system to initiate. It is non-fatal (and will be fixed in a near-future release!)

**Comment by shivamtandon11** [comment]
@jusso-dev Yes I can run the project without starting in Debug mode. I got the web page open as required.
So the issue is with debugger for bot framework specifically as I am able to debug other applications like windows applicaton?

**Comment by eanders-MS** [comment]
Bot applications are just web services. Are you able to create and debug an Azure Web Service or other kind of web-based application?

**Comment by shivamtandon11** [comment]
@eanders-MS I havent tried that. I have just realized that I am not able to even run the Emulator after installing it once I close the window. I am not getting any application with the name "bot framework channel emulator". I am only getting the setup for it. I think I should be able to use it as an application right? Can you tell me where is the problem.
![image](https://user-images.githubusercontent.com/22115569/30443941-ec836432-999e-11e7-8ebb-d30b7d675e1d.png)

**Comment by shivamtandon11** [comment]
I am able to run it after installing the setup once again. But after closing it I cannot see the application.
![image](https://user-images.githubusercontent.com/22115569/30445360-5be72e0e-99a3-11e7-940d-8e2bef827747.png)

**Comment by eanders-MS** [comment]
Hey it looks like you're having better luck communicating with your bot now.

The emulator installer may be failing to register the app with Windows. The installer technology we use currently has proven to be unreliable in a few ways. We're switching to a more tried-and-true technology in a near-future release.

Until we have a fix in place, as a work around, you could create a desktop shortcut directly to the application's executable. Sorry for the inconvenience.

**Comment by shivamtandon11** [comment]
@eanders-MS Thanks a lot . Just one last issue, the debugger which was unable to install on running F5, do I have to install some other packages like web services that support asp.net or azure applications?  Currently I only have .net framework installed and no web application related application. Is the problem related to this?
![image](https://user-images.githubusercontent.com/22115569/30447185-e3970a7c-99a8-11e7-9bb8-942a92cb8ad9.png)
