### ISSUE TITLE
Url's are being url encoded in the chat view. &'s are becoming &amp; instead.

### ISSUE THREAD

**Issue by jtucker** [Microsoft/BotFramework-Emulator#29]
I've noticed this while playing with the AuthBot. In the new emulator, the Markdown coming from the bot that contains the generated URL is correct but when you click the link in the Chat window it opens a browser with an incorrectly formatted URL. 

For example, this is the returned JSON from the framework.
```
{
  "type": "message",
  "timestamp": "2016-12-01T15:20:03.597Z",
  "serviceUrl": "https://sss.ngrok.io",
  "channelId": "emulator",
  "from": {
    "id": "...",
    "name": "Bot"
  },
  "conversation": {
    "id": "..."
  },
  "recipient": {
    "id": ""
  },
  "text": "You must be authenticated before you can proceed. Please, 
click [here](https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/authorize?resource=https:%2F%2Fgraph.windows.net%2F&client_id=CLIENTID&response_type=code&haschrome=1&redirect_uri=http:%2F%2Flocalhost:3979%2Fapi%2FOAuthCallback&x-client-SKU=PCL.Desktop&x-client-Ver=3.13.7.964&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+10.0.14393.0&state=SOMESTATE) to log into your account.",
  "attachments": [],
  "entities": [],
  "replyToId": "...",
  "id": "....."
}
```
Except when clicking the link in the emulator the URL the result is an improper escaped url. The `&` are transformed to `&amp;` like this example:

> https://login.microsoftonline.com/tenant/oauth2/authorize?resource=https:%2F%2Fgraph.windows.net%2F&amp;client_id=CLIENTID&amp;response_type=code&amp;haschrome=1&amp;redirect_uri=http:%2F%2Flocalhost:3979%2Fapi%2FOAuthCallback&amp;x-client-SKU=PCL.Desktop&amp;x-client-Ver=3.13.7.964&amp;x-client-CPU=x64&amp;x-client-OS=Microsoft+Windows+NT+10.0.14393.0&amp;state=SOMESTATE

This result of clicking the link is an error about `client_id` being missing.

**Comment by eanders-MS** [comment]
Hi @jtucker We plan to release a new emulator later today with a fix for this issue.

**Comment by eanders-MS** [comment]
Hi @jtucker Emulator version 3.5.21 is out, which should fix this issue. Please report back if you're still seeing this after updating.
