### ISSUE TITLE
Unable to click on file hyperlink

### ISSUE THREAD

**Issue by JasonSowers** [Microsoft/BotFramework-Emulator#291]
When sending a file as in the code below, one is unable to click on the hyperlink to download the file.  It allows you to click on the chat bubble, but not the actual link.
```cs
replyMessage.Attachments.Add(new Attachment()
{
    ContentUrl = "https://some/url/SomeFile.docx",
    ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    Name = "SomeFile.docx"      
});
```

**Comment by eanders-MS** [comment]
Thanks for the report @JasonSowers!

**Comment by compulim** [comment]
Verified it is fixed. Tested with 2 links like this:

![image](https://user-images.githubusercontent.com/1622400/45532494-1d13e800-b7a9-11e8-96db-e82803a2b5d7.png)

I am able to click on each link to download each file. And no actions when I click on the bubble.
