### ISSUE TITLE
[Feature Request] Add Keyboard Shortcut for "Start New Conversation"

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-Emulator#292]
As a keyboard-shortcut savvy Bot Framework developer, I would like to have the option to start a new conversation in the Emulator using only a keyboard command (similar to "reload page" in browser).

Suggested keyboard shortcuts per platform:
- Windows: F5
- macOS: &#8984;R

**Comment by eanders-MS** [comment]
Excellent suggestion @nwhitmont, thank you!

**Comment by mgbennet** [comment]
This shortcut, along with a few others, has been implemented in 3.5.33. Thanks!
