### ISSUE TITLE
Is it possible now to change from id & from name in emulator?

### ISSUE THREAD

**Issue by LlewellynJones** [Microsoft/BotFramework-Emulator#298]
I want to test my code for handling different users by handling different from ids and names. I know this has been mentioned before but I haven't found a way to do it.

**Comment by eanders-MS** [comment]
This is not supported currently but is a planned feature. https://github.com/Microsoft/BotFramework-Emulator/issues/101

**Comment by droidpl** [comment]
I have opened a new pull request with the id from change. The name is set hardcoded to custom, since I don't need it from my purposes but fill free to change it. It is #303

**Comment by eanders-MS** [comment]
(_copied from my post in the PR_)
I sincerely appreciate you spending your valuable time implementing what is one of our most asked for features. Thank you for that. It is also one of our highest priority work items, and we have a design for it that I'm afraid goes in a different direction than the way you've implemented userId here. Because of this, I'm unable to accept your changes. To give an idea of how we're planning to support userId, here's an early comp:

![emulator_sidebar](https://user-images.githubusercontent.com/12176807/31478443-3f9feace-aec5-11e7-9357-f5ba1e25652c.png)

You will be able to add and remove users in the conversation on a per-bot basis, with the ability to edit names and userIds. You'll also be able to switch which user you are in the conversation.

Our team is occupied with other development work currently, but when we are able to turn attention back to the emulator, this will be among the first features we tackle.

**Comment by droidpl** [comment]
Thanks for the kind answer. Really nice to see the idea you have for that, although this feature is quite important. How about if, in the meanwhile, you leave in the official release the is until the moment you have the new one implemented? This will make a lot of people happy with a workaround solution.

Anyway if someone is interested I created an unofficial release of the not in my own repository for Mac. Just for my own interest but feel free to use it.

**Comment by Code1942** [comment]
Changing from ids and names should be possible in the source code and then run multiple instances I guess. If this is true can you guide where to change the code?

**Comment by JoeBuddha** [comment]
I was watching a Pluralsight video that had what he claimed to be the emulator with these actual features. Do you know where he got it, or was it an internal version? This was in 2016, AFAICT

**Comment by vishwacsena** [comment]
@mewa1024 - we should have restart conversation default to creating a new conversation and user id. we should have a L2 option to just create a new conversation but keep the same user id.

**Comment by mewa1024** [comment]
@vishwacsena Sounds good. We will need a new type of button, similar to the split buttons in Visual Studio and Office, where if you click on the main button it does the default behavior and when you click on the down caret you get both options:

<img width="69" alt="image" src="https://user-images.githubusercontent.com/39317542/48746423-2778b500-ec24-11e8-8209-d0697484f0dd.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/39317542/48746464-542ccc80-ec24-11e8-9f76-cf5b13b796fd.png">

**Comment by mewa1024** [comment]
@vishwacsena How is this?

![restart conv 01](https://user-images.githubusercontent.com/39317542/48803303-71b27280-ecc6-11e8-8bbc-da43d3ae471f.png)
![restart conv 02](https://user-images.githubusercontent.com/39317542/48803319-76772680-ecc6-11e8-9d0c-a4bfca68d42a.png)
![restart conv 03](https://user-images.githubusercontent.com/39317542/48803327-78d98080-ecc6-11e8-8532-4ea1f46367cc.png)
![restart conv 04](https://user-images.githubusercontent.com/39317542/48803333-7b3bda80-ecc6-11e8-85ca-2c66744886d3.png)

**Comment by mewa1024** [comment]
@vishwacsena Yes, I think we do. That seems to be the model that Visual Studio and Office are following. When the caret is expanded we can show the first option selected by default to make it more obvious what the default behavior is.

**Comment by mewa1024** [comment]
@tonyanziano Designs for the flow are [here](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/16077445).

Specs for all the hover states and themes are here:
[Light](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/319156795/preview)
[Dark](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/319156794/preview)
[High contrast](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/319156793/preview)

**Comment by mewa1024** [comment]
@tonyanziano Hi Tony, Can you change the size of the text to the same as the other commands? Should be 11px. Also, can the space between the two buttons be increased to 20px?

![image](https://user-images.githubusercontent.com/39317542/49673051-008ef100-fa22-11e8-831e-121ebcc972bd.png)

**Comment by tonyanziano** [comment]
@mewa1024  Fixed styling.

**Comment by isathish** [comment]
i want to change name is showing default user i want to change based on the user going to chat 

{
  "channelData": {
    "clientActivityId": "1551786671011.39306232803871444.0"
  },
  "entities": [
    {
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true,
      "type": "ClientCapabilities"
    }
  ],
  "from": {
    "id": "12985405-d364-4947-87a3-3066dffc38fe",
    **"name": "User"**
  },
  "id": "a6a35df0-3f3d-11e9-a80d-c9551d799865",
  "locale": "en-us",
  "text": "hi",
  "textFormat": "plain",
  "timestamp": "2019-03-05T11:56:03.267Z",
  "type": "message"
}
