### ISSUE TITLE
Suggestion: Use Emulator with Hotkeys

### ISSUE THREAD

**Issue by rinormaloku** [Microsoft/BotFramework-Emulator#304]
In the browser, we already have a lot of hotkeys that we are used to, e.g.:

* F6 for the address bar.
* Alt+F for the Menu (three vertical dots icon)
* F5 to refresh the conversation.

Working a lot with the bot lately and it gets tedious to use the mouse all the time.
If you agree and or have your suggestions to add, I could start to work on it immediately.

**Comment by eanders-MS** [comment]
That would be fantastic! My suggestions:

On Windows / Linux:
* F5 / Ctrl+R - Refresh the conversation
* F10 / Alt+F - Open the menu
* F6 / Ctrl+L - Focus the address bar

On Mac, I think it would be sufficient to replace Ctrl with ⌘.

We already have Ctrl++/-/0 for zoom level. You should be able to pattern your changes after the implementation of those shortcuts.

Thanks. Looking forward to the PR.

**Comment by mgbennet** [comment]
Related to #292, another request for keyboard short cuts.
