### ISSUE TITLE
Not able to connect because error: "The bot's MSA appId or password is incorrect"

### ISSUE THREAD

**Issue by manzajohn** [Microsoft/BotFramework-Emulator#306]
I have followed the instructions from this below link 
[https://docs.microsoft.com/en-us/bot-framework/debug-bots-emulator]

but am getting the below error
Am not using any Microsoft App ID and all, just created one local
What is the country code for India, in Locale ?
Is that the issue?

![28592117-682ad9da-715e-11e7-9f9f-9c65aec8782a](https://user-images.githubusercontent.com/30400777/31530944-69d84984-b001-11e7-8198-10c1f2517ce2.png)

**Comment by mgbennet** [comment]
The error indicates that your bot is expecting an app id and password but you're not entering them in the emulator. You should have something in your bot's code that looks like

```
var connector = new builder.ChatConnector({
	appId: "somestring",
	appPassword: "someotherstring"
});
var bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());
```

You need to set the appId and appPassword to empty strings, or you need to enter the app ID and password into the emulator.

The Locale shouldn't matter.

**Comment by joe90mizuno** [comment]
I have a same problem.
_

> For localhost debugging you will not typically need to enter MSA appId or password, although it is supported if your bot requires it.

_

https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started#connect-to-a-bot-running-on-localhost

Emulator is checking appId and password before connecting to bot.

_

**Comment by joe90mizuno** [comment]
I found that 401 error was generated by Auth proxy server.
host url = http://localhost:3979/api/messages , but emulator tried to connect with proxy.

**Comment by cwhitten** [comment]
closing in lieu of https://github.com/Microsoft/BotFramework-Emulator/issues/329
