### ISSUE TITLE
BotFramework-Emulator working but no detail

### ISSUE THREAD

**Issue by ranrinc** [Microsoft/BotFramework-Emulator#311]
Somehow it work however it doesn't show anything on the detail. 
Running HighSierra with the latest BotFramework-Emulator. Any help will be greatly appriciated

<img width="1047" alt="screen shot 2017-10-18 at 5 41 49 pm" src="https://user-images.githubusercontent.com/15801696/31714877-d10de8d8-b42b-11e7-9832-20a4853bcc54.png">

**Comment by mgbennet** [comment]
Click on a message that you or the bot sent. The Details pane will display the JavaScript Object that made that message.

**Comment by eanders-MS** [comment]
This has tripped up a few users. We should consider adding some help text when nothing has been selected. "Select a message or click a link to view details"
