### ISSUE TITLE
Attachment type "application/json" doesn't get passed to browser

### ISSUE THREAD

**Issue by Matti-Koopa** [Microsoft/BotFramework-Emulator#313]
When I send a JSON file over the bot, the emulator displays it as a link, but the browser doesn't get the content type or file name when I click in it. This results in a file without extensiom, that I have to rename ".json" manually after download.

Server code:

```
var message = context.MakeMessage();
var content = File.ReadAllBytes(path);
var fileName = $"{Guid.NewGuid()}.json";

using (var connector = new ConnectorClient(new Uri(message.ServiceUrl)))
{
	var attachments = new Attachments(connector);
	var response = await attachments.Client.Conversations.UploadAttachmentAsync(
		message.Conversation.Id,
		new AttachmentData
		{
			Name = fileName,
			OriginalBase64 = content,
			Type = "application/jsonstream"
		});

	var attachmentUri = attachments.GetAttachmentUri(response.Id);

	message.Attachments.Add(new Attachment
	{
		Name = fileName,
		ContentType = "application/json",
		ContentUrl = attachmentUri
	});
}
await context.PostAsync(message);
```
Output:
![image](https://user-images.githubusercontent.com/10476794/31881181-1445df60-b7e3-11e7-977b-fd01c49f1a57.png)

Firefox Download Dialog (showing octet-stream as content type):
![image](https://user-images.githubusercontent.com/10476794/31881216-2e84ad16-b7e3-11e7-82a3-7da8e689dde7.png)

**Comment by eanders-MS** [comment]
The code responsible for file download exists in the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat) control, which has its own issues page.  I think you'll have better luck raising your issue there.
