### ISSUE TITLE
MS bot emulator issues

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotFramework-Emulator#318]
When I did npm update on my node.js ms bot service I was having issue mentioned here https://github.com/Microsoft/BotFramework-Emulator/issues/262 so I followed all steps mentioned in the thread to fix it. finally, 500 error was fixed but seeing new issue. 

 I'm on + botbuilder@3.11.0

[21:56:21] -> POST connect ECONNREFUSED 127.0.0.1:3979 
[21:56:27] -> POST connect ECONNREFUSED 127.0.0.1:3979 
[21:56:27] -> POST connect ECONNREFUSED 127.0.0.1:3979 

not sure what is happing.

**Comment by eanders-MS** [comment]
Hi @rjgmail88, A few questions to help me understand the context:
- When you tried to connect using the emulator, was your bot running on localhost (and listening on port 3979)?
- Are you using the Node or the C# SDK?

**Comment by rjgmail88** [comment]
Hi,
I am using Node sdk. I downloaded latest version of emulator and it fixed the issue. So I believe we should always be using latest botbuilder and emulator. Thank you.
