### ISSUE TITLE
Microsoft App ID is null

### ISSUE THREAD

**Issue by kurthamilton** [Microsoft/BotFramework-Emulator#321]
When posting a message from the channel emulator, the Microsoft App ID is now null in the latest release.

`
var appCredentials = ((ClaimsIdentity)User.Identity).GetCredentialsFromClaims();
var msAppId = appCredentials.MicrosoftAppId; // null
`

I can see the App ID is being sent in the User claim aud, but is not being correctly resolved via the MicrosoftAppCredentials class.

Edit: This relates to v3.5.32

**Comment by etharreef** [comment]
@kurthamilton thanks for posting this issue, I am hunting this issue down since morning after updating the emulator to v3.5.32 we are using the same as we have our custom Credential provider

**Comment by etharreef** [comment]
The bug is in ClaimsIdentityEx searching for claim type appid rather than  aud

**Comment by Jeffders** [comment]
You are right, that class ClaimsIdentityEx is only searching for the appid claim, and this is correct for v1.0 tokens. The release of the emulator for v3.5.32 removed a flag that forced the emulator to use v1.0 tokens but instead relied on whatever version of token is associated with that appid. To explain this a bit better: v1.0 tokens included a claim for 'appid', but v2.0 tokens included a claim for 'azp'. That class ClaimsIdentityEx needs to be updated to check for these things.

As a work around, if you are comfortable building your own emulator, you can do this:

1. Find the file src\server\conversationManager.ts
2. uncomment line 521 to include the "atver: 1" parameter when the emulator requests tokens

In the mean time, I'll submit a PR to the C# bot builder SDK to have the ClaimsIdentityEx class updated.

**Comment by eanders-MS** [comment]
Thank you @Jeffders! C# BotBuilder PR is here: https://github.com/Microsoft/BotBuilder/pull/3681.
