### ISSUE TITLE
Credentials not set - 'appid' is no longer present in the authenticated user's claims

### ISSUE THREAD

**Issue by stuprice** [Microsoft/BotFramework-Emulator#322]
Hi

v3.5.32 of the Emulator no longer sets the appid claim for the authenticated user causing my .NET bot to fail.  This works fine in v3.5.31 of the Emulator,  This problem only shows itself when using your own CredentialProvider.  It works fine if you have the bot credentials stored in the web.config.   

My bot is multi-tenant based on the example here: https://github.com/Microsoft/BotBuilder/issues/2258.  The authenticated user's password is from claims set but their username is always null.

Is there a way to prevent the Emulator from auto-updating until this issue is solved?

Cheers

Stu

**Comment by eanders-MS** [comment]
We have a PR out to the BotBuilder project to fix the issue: https://github.com/Microsoft/BotBuilder/pull/3681

In the meantime, you can prevent the emulator from updating by passing the `--no-update` command line argument. The emulator's handling of command line args has its own bug you'll have to work around: The first argument is ignored, so send a placeholder for it, like `"Bot Framework Emulator.exe" --foo --no-update`.

Related: https://github.com/Microsoft/BotFramework-Emulator/issues/321

**Comment by stuprice** [comment]
OK thanks.

**Comment by eanders-MS** [comment]
Another update: We will be releasing a new emulator later this week with a workaround to re-enable auth v1.0 tokens.

**Comment by eanders-MS** [comment]
An updated emulator has been released (v3.5.33) with a new option on the App Settings dialog to force v1.0 tokens. An updated C# SDK with a proper bugfix is in the release pipeline.

**Comment by stuprice** [comment]
Using v1.0 tokens in v3.5.33 works for me, thanks.
