### ISSUE TITLE
Can't open dev.botframework.com

### ISSUE THREAD

**Issue by manishdwibedy** [Microsoft/BotFramework-Emulator#323]
Hi,

I am trying to make a new bot. However the dashboard won't open for me.
<img width="1280" alt="screen shot 2017-10-28 at 11 08 33 pm" src="https://user-images.githubusercontent.com/8343764/32141113-09286052-bc35-11e7-8a09-1e772428afb1.png">

**Comment by mgbennet** [comment]
This forum is for questions pertaining to the Bot Framework Emulator. If you're still getting 403's from the website, the [BotBuilder](https://github.com/Microsoft/BotBuilder/issues) project is a better place to raise this issue.
