### ISSUE TITLE
Suggestion: Cycle through history with Up and Down Arrow 

### ISSUE THREAD

**Issue by rinormaloku** [Microsoft/BotFramework-Emulator#325]
When we use the Bot Emulator we quite often want to debug one specific part during the conversation.
Getting up to there requires a lot of typing. And this process get's repeated until we get our bot run correctly.

Writing the messages with the bot would be much easier if we would be able to cycle through the history with <kbd>↑</kbd>  and <kbd>↓</kbd> arrow. 

**This should work in the same way cycling through history works in cmd line interfaces.**

If you find this a good suggestion I would be more than happy to start working on it. And would be very helpful if you give me directions and suggestions on how to approach solving this.

**Comment by danmarshall** [comment]
Hi @rinormaloku we already have a feature request for this in Web Chat (which is the component used by the emulator). I will close this issue in Emulator and we can track this issue in Web Chat here: https://github.com/Microsoft/BotFramework-WebChat/issues/58

Also, we need to find a way to trigger "dev mode" such that end users do not get this behavior.
