### ISSUE TITLE
url cannot be changed

### ISSUE THREAD

**Issue by mironmat** [Microsoft/BotFramework-Emulator#327]
Hi, Not sure if anyone faced such issue, but when I'm trying to type url I'm receiving error msg in log: 
[err-client] Uncaught TypeError: Cannot read property 'toLowerCase' of undefined C:\Users\a\AppData\Local\botframework\app-3.5.32\resources\app.asar\app\client\addressBar\addressBarOperators.js 14 45 {} 

If I ignore the message and provide new url, emulator is still trying to access old url: 127.0.0.1: 397**8** instead of 127.0.0.1: 397**9**
any suggestions?

**Comment by mironmat** [comment]
here you can find step by step guide
[chatbot emulator.docx](https://github.com/Microsoft/BotFramework-Emulator/files/1432461/chatbot.emulator.docx)

**Comment by eanders-MS** [comment]
I followed your steps closely but could not repro. Here's what I did:
1. Run the emulator
2. Click in the address bar
3. Type an `s` character

Does that sound right? I did not get an error at this point. Regardless, I will add null reference protection to the code. We're releasing a new emulator this week, so this is good timing.

**Comment by mironmat** [comment]
yes, the steps you performed are correct. 
fyi, i tried with previous version and faced the same issue. 

Thx and waiting for new ver.

**Comment by eanders-MS** [comment]
OK, we've released a new version (3.5.33) with defensive coding around the line that reported the error. Please give it a try and post back here if you're still seeing a problem.

**Comment by mironmat** [comment]
many thanks, it's working ok now.
