### ISSUE TITLE
Bot Framework Channel Emulator should remember App Id, password, connection state

### ISSUE THREAD

**Issue by arturl** [Microsoft/BotFramework-Emulator#328]
Once connected, I can start a new conversation and click on the address bar again. Now I'm prompted to re-enter the app id and password and reconnect:

![image](https://user-images.githubusercontent.com/1875734/32257370-feb5f85c-be71-11e7-8f52-095465a06ff5.png)

I expect the App ID and the password to already be filled in (show up as asterisks). Also provide some indication that the emulator is already connected to the endpoint.

**Comment by eanders-MS** [comment]
This is the first time this issue has been reported. It should always remember the appId and password. I'm not able to repro. Can you provide more detail and repro steps?

We do not have a connection state indicator in the UI other than the fact that the webchat control is visible when you're connected.

**Comment by arturl** [comment]
I believe the functionality is not broken -- the appid and password are actually remembered, but to the user  it looks like they need to be re-entered. This gets even more confusing when switching between different service endpoints -- how can I remember which ones are connected and which aren't?

**Comment by eanders-MS** [comment]
When an entry in the endpoint list has an associated App ID and Password, they should always display in the textboxes of the connect dialog (your screenshot above). Do these values ever show up for you, or are the textboxes always empty?

**Comment by arturl** [comment]
My steps are: fill in the App ID and password text boxes, enter a message, go back to the address bar and observe the text boxes -- they are empty. Like I said, this is a UI issue only -- the user is unnecessarily prompted for data that's already in the system.

**Comment by tonyanziano** [comment]
Closing because users should be moving to v4. If the issue persists in v4 it can be reopened.
