### ISSUE TITLE
Authorization issue - version 3.5.32

### ISSUE THREAD

**Issue by arthurtina724** [Microsoft/BotFramework-Emulator#332]
When debugging a local bot via the emulator we cannot authorize using the bot Id and password. Here is a screen shot of what we're seeing: 
![image](https://user-images.githubusercontent.com/20215260/32298746-5a6caa58-bf10-11e7-9837-e295fa700b50.png)

Here is the output from visual studio: 

> Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException: Bad Request ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

Bot Emulator version: 3.5.32
Bot Builder version: 3.9.0
OS/IDE: Windows 10, VS Prof 2015 Version 14.0.25431.01 Update 3

Note: This is working from the web test channel in the portal, but only giving this 400 error from the emulator. We are also using a  custom Credential provider, but have confirmed it is still reading the credentials from our repo correctly: 
`[BotAuthentication(CredentialProviderType` = typeof(BotCredentialProvider))]

**Comment by ryanbatsa** [comment]
I'm also having this issue. Looks to be similar to [#1938](https://github.com/Microsoft/BotBuilder/issues/1938).

**Comment by eanders-MS** [comment]
We released version 3.5.33 of the emulator today with a new option in App Settings to use v1.0 authorization tokens. Can you try this?

**Comment by brandmanager2017** [comment]
Also having the same issue. Already updated to 3.5.33 and Used v1.0 authorization tokens.
![untitled](https://user-images.githubusercontent.com/25189214/32321115-0790cc10-bffb-11e7-9182-5cff6de964cf.png)

**Comment by sajal2692** [comment]
Also having said issue.

**Comment by eanders-MS** [comment]
Thank you for reporting this! The emulator's auth endpoint is returning errors for a small percentage of users. We're actively working to solve the problem, and a fix is in validation at this time. I will post back here when the fix is live.

**Comment by eanders-MS** [comment]
@brandmanager2017 You're seeing a different issue, I believe. You're receiving a 401 error code. Can you verify a few facts for me:
- Are you using the C# BotBuilder SDK?
- Are you using your own CredentialProvider?

If these two things are true, then you're likely hitting a bug in the C# SDK related to parsing the v2.0 auth token. The workaround is to open the emulator's App Settings dialog and check the "use v1.0 authentication tokens" checkbox. A proper fix for this has been made in the C# SDK and is currently in the release pipeline.

**Comment by eanders-MS** [comment]
@arthurtina724 Does forcing the use of v1.0 auth tokens resolve the issue for you?

**Comment by arthurtina724** [comment]
@eanders-MS looks like that solution will work for us, but there are some warnings to move up to the bot builder 3.11.0 or greater. thanks for the help
------------------------------------------------------------------------------------
06:15:39] Warning: The bot is using SDK version 3.9.1. 
[06:15:39] Warning: SDK versions earlier than 3.11.0 use an authentication configuration that will no longer work with the emulator after November 15, 2017. 
[06:15:39] Warning: For your bot to continue working with the emulator, please update your bot to use an SDK version greater than or equal to 3.11.0.
