### ISSUE TITLE
401 bot's MSA appId or password is incorrect

### ISSUE THREAD

**Issue by skandyrocks** [Microsoft/BotFramework-Emulator#333]
I cannot connect to any bot anymore with the emulator. I did not change the appId or password and stopped working about 4 hours ago.

When I try to connect to my bot, the messaging endpoint returns 401 with the message "BotAuthenticator failed to authenticate incoming request!"

My WebChat via directLine works fine, but I cannot connect to the same bot with the emulator.
I can connect to a locally hosted bot, when I leave appId and password blank (in the running solution and the emulator).

AppId: 7a3cc1cc-a41a-4efa-9ec6-484e4f04fbb9

Is there a known problem with the authenticator?
I also tried to register a new bot - same issue. I also downloaded the latest emulator - nothing.

**Comment by skandyrocks** [comment]
Okay - I now enabled the checkbox to use version 1.0 authentication tokens and this works. But what do I need to change to get my bot to work without to set this checkbox?

**Comment by eanders-MS** [comment]
There are a few possible explanations for what you're seeing:
- Possibility 1: If you are using the C# BotBuilder SDK, and you are using your own CredentialProvider, then what you might be seeing is a manifestation of a bug in the C# SDK where it isn't reading the v2.0 auth token correctly. An updated C# SDK is in the release pipeline, and the checkbox in the emulator was added specifically to workaround this in the meantime. If unchecking the v1.0 token checkbox causes your bot to fail again, then you're definitely hitting this bug. The solution is to update to the new C# SDK when it is released.
- Possibility 2: Last night (PST) the emulator's auth endpoint started returning errors for a small percentage of users. We are actively working to get this corrected.
