### ISSUE TITLE
Order of downloads isn't very intuitive; the main download should be listed first

### ISSUE THREAD

**Issue by pedasmith** [Microsoft/BotFramework-Emulator#337]
The order of the downloads drive people to download the ARM versions (since it's listed first).  In reality, most people will probably want the "botframework-emulator-Setup-3.5.33.exe " download, but it's almost hidden in the middle of everything else.

This seems like a small thing, but it's one of those little "fit and finish" things that make software easy to download and use instead of being a chore.

**Comment by eanders-MS** [comment]
Thank you for the feedback. GitHub does not offer a way to reorder or group the downloads. It would be nice to be able to group release files by operating system.
