### ISSUE TITLE
How to change the "from" user used in the emulator?

### ISSUE THREAD

**Issue by wbreza** [Microsoft/BotFramework-Emulator#34]
Right now it appears that the "from" user is statically set to "default-user". I'm unable to find a way to modify this in the UI.

**Comment by eanders-MS** [comment]
Hi @wbreza The ability to change the user name is a planned feature that will be coming out early in the new year. It is part of a larger redesign of the way bot connections are managed in the app.

**Comment by McGern** [comment]
Hi,

Has there been any update on this?

Thanks,
Jarrod

**Comment by eanders-MS** [comment]
This work is still planned, but taken a back seat to higher priority work.

**Comment by satyansh-sagar** [comment]
Hi, Any updates on this? @eanders-MS

**Comment by soso-maitha** [comment]
So we can't change default user in Bot emulator v3 ?

**Comment by tonyanziano** [comment]
Currently, in V4 of the Emulator, we provide the ability to change the `id` of the user through the app settings page:

![image](https://user-images.githubusercontent.com/3452012/64555763-e5277e00-d2f2-11e9-89a5-8789595e84a1.png)

![image](https://user-images.githubusercontent.com/3452012/64555983-5cf5a880-d2f3-11e9-8ed8-563f21280e56.png)


However, we have no way of changing the `name` of the user through the UI in V4 as well as in V3. We have no plans of adding any new features to V3.

**Comment by vaibhav1408** [comment]
Can we pass this user-id runtime by using python code?
