### ISSUE TITLE
Version 3.5.33

### ISSUE THREAD

**Issue by FiodorTretyakov** [Microsoft/BotFramework-Emulator#340]
![image](https://user-images.githubusercontent.com/6492380/32503828-2374119c-c3d6-11e7-8a69-369f68ed0b28.png)

3.5.31 version is working. I think, it is connected with Electron.

Windows 10 Enterprise x64.

Text size is 125%.

**Comment by EricDahlvang** [comment]
Hi @FiodorTretyakov 

This looks like a window sizing/positioning issue.

Please try shutting down the emulator, navigate to C:\Users\[YourUserName]\AppData\Roaming\botframework-emulator\botframework-emulator  in Windows Explorer and delete **client.json** and **server.json**, then restart the emulator.

Let us know if this helps.

**Comment by FiodorTretyakov** [comment]
No, still black screen.

**Comment by EricDahlvang** [comment]
I'm sorry that didn't help.  I assume you installed botframework-emulator-Setup-3.5.33.exe from https://github.com/Microsoft/BotFramework-Emulator/releases  Maybe the install logs have some information.

Please try opening this file in notepad: %LocalAppData%\SquirrelTemp\SquirrelSetup.log, e.g.:

`C:\> start %LocalAppData%\SquirrelTemp\SquirrelSetup.log`

All apps that use the Squirrel installer system write to this log. If you're able to open it, scroll to the bottom of the file and look for entries for botframework. There may be an error listed there.

**Comment by eanders-MS** [comment]
@FiodorTretyakov sorry you're seeing this, and thanks for reporting it. We did update to Electron 1.8.1 in this release. If you need to rollback to an earlier version while we sort this out, you can disable auto-update by passing `--no-update` as a command line argument. If you choose to do this, you'll have to work around a bug in Electron's handling of command line parameters: it skips the first one, so pass something like
`--foo --no-update`

**Comment by FiodorTretyakov** [comment]
Hi, Thanks - using 31 version, and there are no errors in SquirrelSetup.log

**Comment by EricDahlvang** [comment]
Hey @FiodorTretyakov ,

Would you please try starting the emulator with the --disable-gpu command line parameter. As eanders-MS mentioned, you'll need to pass it as the second parameter due to a bug in Electron.  So, something like:
--foo --disable-gpu

This option worked for a different user who was also seeing a black screen: https://github.com/Microsoft/BotFramework-Emulator/issues/357

**Comment by tonyanziano** [comment]
Please try version 3.5.37 on the [Releases Page](https://github.com/Microsoft/BotFramework-Emulator/releases).
