### ISSUE TITLE
Webchat does not show text from HTTPS Response despite HTTP Code 200

### ISSUE THREAD

**Issue by holgerkyas** [Microsoft/BotFramework-Emulator#341]
Hello
I'm calling a remote https service via the bot emulator by typing a text into the webchat, here "Hello". The response is coming back correctly with HTTP code 200, but the webchat does not show the response. What did I miss?

Bot Emulator version is 3.5.33

Startup Log
[11:16:23] Emulator listening on http://[::]:63840
[11:16:23] ngrok listening on https://08a7372a.ngrok.io
[11:16:23] ngrok traffic inspector: http://localhost:4040
[11:16:23] Will bypass ngrok for local addresses
[11:16:23] Checking for new version...
[11:16:25] Application is up to date.

I added the screenshots and the json files from the webchat in the bot emulator.

REQUEST
![request](https://user-images.githubusercontent.com/11524496/32506108-09895d24-c3e4-11e7-857c-a07f49c2aef7.jpg)

RESPONSE
![response](https://user-images.githubusercontent.com/11524496/32506119-0ebf06ae-c3e4-11e7-8a11-2b7d6043923a.jpg)

REQUEST
{
"type": "message",
"text": "Hello",
"from": {
"id": "default-user",
"name": "User"
},
"locale": "en-US",
"textFormat": "plain",
"timestamp": "2017-11-05T09:49:50.451Z",
"channelData": {
"clientActivityId": "1509875028121.6653353473116588.0"
},
"entities": [
{
"type": "ClientCapabilities",
"requiresBotState": true,
"supportsTts": true,
"supportsListening": true
}
],
"id": "aiend6j0klk6",
"channelId": "emulator",
"localTimestamp": "2017-11-05T10:49:50+01:00",
"recipient": {
"id": "akd08b141n47chj3dc",
"name": "Bot"
},
"conversation": {
"id": "bc4lk7ell0d"
},
"serviceUrl": "https://242f7bb7.ngrok.io"
}

RESPONSE
{
"type": "message",
"from": {
"id": "akd08b141n47chj3dc",
"name": "Bot"
},
"conversation": {
"id": "bc4lk7ell0d",
"name": "Conversation Name"
},
"recipient": {
"id": "default-user",
"name": "User"
},
"channelData": {
"clientActivityId": "1509875028121.6653353473116588.0"
},
"channelId": "emulator",
"text": "I understood: Hello",
"speak": "I understood: <break time="1s"/>Hello<break time="1s"/>",
"inputHint": "expectingInput",
"replyToId": "aiend6j0klk6"
}

thanks
Holger

**Comment by nwhitmont** [comment]
test

**Comment by eanders-MS** [comment]
Interesting! Did you build your bot using the BotBuilder SDK? Or are you generating the reply message manually?

**Comment by holgerkyas** [comment]
I used neither one of those two options. The external cloud service I'm calling generates the response.

**Comment by eanders-MS** [comment]
Can you tell me how you created your bot? What platform or generation tool? I'm wondering because the reply it generated is a little different than what I typically see. It is possibly invalid in some way.

**Comment by holgerkyas** [comment]
It‘s a cloud service and I defined the JSON format myself based on what I know about the response format. Would you share the response you see and think it‘s correct? thx

**Comment by cwhitten** [comment]
@holgerkyas were you able to resolve your issue?

**Comment by cwhitten** [comment]
Closing, stale.

**Comment by holgerkyas** [comment]
No, I didn’t.

**Comment by cwhitten** [comment]
@holgerkyas can you update your version of the Emulator to v4.2.1 (latest) and see if the issue persists? Happy to reopen if so.
