### ISSUE TITLE
When I'm running the emulator it shows error like, I have reinstalled it again, still show the same kind of error

### ISSUE THREAD

**Issue by SaranrajK** [Microsoft/BotFramework-Emulator#343]
![capture](https://user-images.githubusercontent.com/26340573/32727728-a125b2fe-c8a3-11e7-9915-1b73bcbd1c87.PNG)

**Comment by EricDahlvang** [comment]
Hi @SaranrajK 

Is a bot running on port 3979 on the same computer?    

This documentation discusses how to debug a local bot using the emulator:

.net: 
https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-quickstart#start-your-bot

nodejs: 
https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-quickstart#start-your-bot-1

Please let us know if you've already tried these steps or if you have questions.
