### ISSUE TITLE
Attachment button don't work

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/BotFramework-Emulator#344]
Sometimes the attachment button stop working (i.e. it does nothing when clicked).
Restarting the emulator fixes the problem.

**Comment by EricDahlvang** [comment]
Hi @JCKodel 

Thanks for reporting this.   It appears we have a prior issue tracking the bug: https://github.com/Microsoft/BotFramework-Emulator/issues/133 "Attachment buttons stops responding"
