### ISSUE TITLE
No Log Info displaying, even though bot is working through emulator

### ISSUE THREAD

**Issue by Quircus** [Microsoft/BotFramework-Emulator#347]
![botbuilder no log](https://user-images.githubusercontent.com/23024826/32868339-b45e4e22-ca69-11e7-8e0b-bf9eeca9233f.png)
Testing this issue locally to reproduce it with the sample MS Echobot, which is working fine (and must be sending and receiving HTTP requests via the right port) but no "Emulator listening in" script to open or any log info being displayed. What am I missing, please?

**Comment by EricDahlvang** [comment]
Hi @Quircus 

Are you able to resize the Log window by clicking on the separator line and holding the mouse down while dragging up?  

Here is a .gif as an example:

![emulatorlogwindow](https://user-images.githubusercontent.com/11055362/32868537-a2f8e080-ca27-11e7-9a47-d44c1c5b2212.gif)

**Comment by Quircus** [comment]
Ha, I'd tried resizing it by holding down on the bar, with no joy (just a "No Go" icon flashing up for trying to move a graphic). The little resizer icon flickers and disappears unless my cursor is in exactly the right spot so I must have missed it. Doh. Thanks!
