### ISSUE TITLE
Cannot connect to localhost bots

### ISSUE THREAD

**Issue by dejmjin** [Microsoft/BotFramework-Emulator#350]
HI all,

I upgraded to version 3.5.33 this morning and now I cannot connect anymore to localhost bots. I went through the following steps based on other similar posts but nothing was successful so far:

1) deleted files found in C:\Users\USER\AppData\Local\Temp
2) Ran Fiddler while trying to connect to bot

There is no AppID or password, all is blank. I even tried a new blank project but still cannot connect. Whenever I enter the url and hit connect, nothing happens on the emulator (visually).

From Fiddler, I can see that when I am running the emulator, it is constantly sending posts to localhost:63988 and the log says: '14:46:22:6999 HTTPSLint> Warning: ClientHello record was 508 bytes long. Some servers have problems with ClientHello's greater than 255 bytes. https://github.com/ssllabs/research/wiki/Long-Handshake-Intolerance'

Anyone else came across this issue before?

**Comment by dejmjin** [comment]
I also deleted everything from C:\Users\USER\AppData\Roaming\botframework-emulator, uninstalled and installed the emulator but still same issue. Nothing happens when I click connect

**Comment by FranciscoPonceGomez** [comment]
Hi @dejmjin,

Thanks for reporting this. We will investigate the issue. 
Can you send a screenshot of the UI? Do you get anything on the log window?

Regards,
Francisco

**Comment by dejmjin** [comment]
Hi @FranciscoPonceGomez ,

Thanks for replying. No I do not get anything in the log on the right hand side of the emulator.

This is what I get after I click on the connect button.
![image](https://user-images.githubusercontent.com/17178811/33142501-b2b23242-cfae-11e7-9d4d-004f9f250864.png)

I also noticed that if I type nonsense in the URL and hit the connect button, nothing happens in the log (same behaviour noticed in Fiddler though...the constant posts to port 63988

![image](https://user-images.githubusercontent.com/17178811/33142604-ff8f0126-cfae-11e7-8c2d-18a291ee99b6.png)

**Comment by FranciscoPonceGomez** [comment]
Hi @dejmjin,

Try dragging the log windows up:
![32868537-a2f8e080-ca27-11e7-9a47-d44c1c5b2212](https://user-images.githubusercontent.com/16775093/33143015-4dde06b6-cf6d-11e7-8c7a-375f4c7b0d89.gif)

**Comment by dejmjin** [comment]
*facepalm* really sorry, thanks for the help!

On an unrelated thing, I noticed I have to run the setup every time I need to run the emulator now. Is there a fix for it?

Thanks again

**Comment by mgbennet** [comment]
What exactly do you mean by "run the setup"? Do you mean it runs an installer every time you run the emulator? Or that you need to drag up the log panel?

**Comment by dejmjin** [comment]
No, never happened in other versions before. I used to have a shortcut in the start bar, but now it doesn't create anything there. It's not a big deal though - pinned it to taskbar when it was running.
