### ISSUE TITLE
Fail to install botframework-emulator on Linux

### ISSUE THREAD

**Issue by pickfire** [Microsoft/BotFramework-Emulator#354]
I tried installing the botframework-emulator but it doesn't work. Step to reproduce:
```
> aria2c https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.34/botframework-emulator-3.5.34-full.nupkg
...
> nuget install botframework-emulator-3.5.34-full.nupkg
Unable to find package 'botframework-emulator-3.5.34-full.nupkg'.
> uname -a
Linux tank 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
```

**Comment by eanders-MS** [comment]
Install using botframework-emulator-Setup-3.5.34.exe. The nupkgs are a build artifact necessary for the updater, but not meant to be installed directly.

**Comment by pickfire** [comment]
@eanders-MS Can you please explain more? How do I run `botframework-emulator-Setup-3.5.34.exe`?

**Comment by EricDahlvang** [comment]
Hi @pickfire 

Here is the link to download the installation file: https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.34/botframework-emulator-Setup-3.5.34.exe

It can be found on this page: https://github.com/Microsoft/BotFramework-Emulator/releases

**Comment by eanders-MS** [comment]
Oh you’re on Linux! I missed that detail. Here’s a blog post that explains it well: http://www.startertutorials.com/blog/microsoft-bot-framework-ubuntu.html

**Comment by pickfire** [comment]
@eanders-MS Ah, thanks a lot. That works. I didn't know the file extension for linux executable is `.Appimage`.

Note: I saw nothing mentioned about it in README.
