### ISSUE TITLE
Emulator handles the zoom keyboard shortcuts even when minimized, not allowing other apps to handle it

### ISSUE THREAD

**Issue by artemious7** [Microsoft/BotFramework-Emulator#355]
I noticed a few times already that when the Emulator is open, **it handles the zoom shortcuts itself (Ctrl+-, Ctrl+=, Ctrl+0) when its window is not active or is minimized**. This is really annoying, because when I try to use the same shortcuts in Visual Studio or a web browser (for example, Google Chrome), these apps don't react at all. 
I couldn't reproduce the issue, but it seems it happens randomly. I've experienced this 3-4 times already, and as soon as I close the Emulator app, the shortcuts start working again in the other apps, and continue to work after I restart the Emulator app. 
Once, I even noticed that the Emulator got zoomed-in too much, apparently because of me trying to use the Ctrl+= shortcut in another app, though the Emulator app's window was not in focus.

I'm using Windows 10 Fall Creators update x64 (build 16299.64) and Emulator v3.5.34.

**Comment by eanders-MS** [comment]
A fix was made for this issue in 3.5.34. PR: https://github.com/Microsoft/BotFramework-Emulator/pull/349
Are you certain you're seeing this behavior in 3.5.24? Maybe our fix didn't fix it.

**Comment by artemious7** [comment]
@eanders-MS well, unless the Emulator got auto-updated after I restarted it when I encountered the issue last time. But I didn't notice it updating. It started as usual.
However, after that I didn't notice this bug any more. So maybe it got fixed after an auto-update.

**Comment by mgbennet** [comment]
@artemious7 The emulator's update is pretty stealthy, so unless you're watching the Log panel, you might not notice that it found a new version and will update next restart. Glad to hear you're not seeing the issue any more. If you find a case where it still isn't behaving properly, let us know.

**Comment by artemious7** [comment]
This has just happened again on version 3.5.35. 
I ran the emulator, minized it, went to Google Chrome, hit Ctrl+= a few times, and nothing. I made sure the focus was in the Chrome window, hit the combination again - nothing! Switched to the Emulator - it's zoomed in. Switched back to Chrome - the Ctrl+= now works in Chrome again.
Quite frustrating
