### ISSUE TITLE
Unable to connect Emulator to local bot running in Docker container

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-Emulator#356]
**User Story**
As a Bot Framework developer, I'd like to have the ability to locally test my bot in a Docker container using the Emulator. 

**Issue Description**
When attempting to connect bot running in Docker container via Emulator, connection is established (shown by the two `conversationUpdate` events that fire on connection) -- but when I try to send the first message to the bot, the bot crashes with error: `Error: connect ECONNREFUSED 127.0.0.1:50202`.  I'm guessing this is something to do with the Emulator's ngrok config that doesn't play nicely with Docker?

**Expected**
Developer can use Emulator to connect to bot running in local Docker container.

**Actual**
Bot crashes in Docker container when sending messages via Emulator

![docker emulator error](https://user-images.githubusercontent.com/3075047/33584424-2e42d0ec-d914-11e7-998f-c8f5a4560083.png)

**Comment by nwhitmont** [comment]
Answer:  To test bot in Docker container, you need to go into the App Settings and **uncheck "Bypass ngrok for local addresses"** - then it works as expected.

**Comment by SeanSobey** [comment]
I came across this same issue, then applied the workaround. This did indeed work for a few interactions until the app consistently throws this exception:
` Message: GET to 'https://276131ff.ngrok.io/v3/botstate/emulator/conversations/de2ed7mi6m48' failed: [429] Too Many Requests`

It seems to be the same as [this](https://github.com/Microsoft/BotFramework-Emulator/issues/70 )and [this](https://github.com/Microsoft/BotFramework-Emulator/issues/107).
