### ISSUE TITLE
Can not start the app (black screen)

### ISSUE THREAD

**Issue by Morhpeuss** [Microsoft/BotFramework-Emulator#357]
Hi,

I installed the emulator, but I see only the black screen.
![bot-framework](https://user-images.githubusercontent.com/5184685/33595530-b6e3d4c6-d998-11e7-9b05-5626266d2435.png)
[SquirrelSetup.log](https://github.com/Microsoft/BotFramework-Emulator/files/1530080/SquirrelSetup.log)
[SquirrelSetup.log](https://github.com/Microsoft/BotFramework-Emulator/files/1530081/SquirrelSetup.log)

I have WIN10 x64 and 3.5.34 version.

Thanks.

**Comment by EricDahlvang** [comment]
Hi @Morhpeuss 

Interesting problem.  Please try starting the emulator with the --disable-gpu command line parameter.  If you choose to try this, you'll have to work around a bug in Electron's handling of command line parameters: it skips the first one, so pass something like
--foo --disable-gpu

The shortcut is located here: C:\Users\[YourWindowsUserName]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft Corp  The command line parameters can be added to the end of the Target field.  

![image](https://user-images.githubusercontent.com/11055362/33638037-ed07a63c-d9d8-11e7-9047-27bd88458ba5.png)

Please let us know if this works for you.

**Comment by Morhpeuss** [comment]
Thanks, it is the solution
