### ISSUE TITLE
faild to load AppImage on ubuntu

### ISSUE THREAD

**Issue by geeksesi** [Microsoft/BotFramework-Emulator#358]
Hi, i want to load emulator on linux.
when try to execute this app get an error : 
```
./botframework-emulator-3.5.34-i386.AppImage: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory
```

**Comment by eanders-MS** [comment]
It may be that the AppImage you selected doesn't match your architecture. Have you verified your architecture is i386? Here's a blog post with instructions for installing on Linux: 

http://www.startertutorials.com/blog/microsoft-bot-framework-ubuntu.html

Skip to the titled *Installing Bot Framework Emulator on Ubuntu (Linux)*

**Comment by eanders-MS** [comment]
Seems like the issue is resolved. Post here if you'd like it reopened.
