### ISSUE TITLE
Not receiving response from Bot Emulator

### ISSUE THREAD

**Issue by swayamghodke** [Microsoft/BotFramework-Emulator#359]
I have created a BOT in node.js using node.js and RESTIFY. Below is my code.

=====================================

var restify = require('restify');
var builder = require('botbuilder');

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});

// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MICROSOFT_APP_ID,
    appPassword: process.env.MICROSOFT_APP_PASSWORD
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

// Receive messages from the user and respond by echoing each message back (prefixed with 'You said:')
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("You said: %s", session.message.text);
});

=====================================
However when I run in Emulator, Bot does NOT responds to each message you send by echoing back your message prefixed with the text "You said:".

I have not given MS APP ID and PASSWORD. Please help.

**Comment by EricDahlvang** [comment]
Hi @swayamghodke 

What endpoint url are you using in the emulator?   Are there any errors in the Log window when you connect, or send a message?

**Comment by swayamghodke** [comment]
Eric Will check and reply you back.

regards
Geeta

**Comment by swayamghodke** [comment]
Hi I am using http://localhost:3978/api/messages as endpoint URL. 
I don't see any errors in the log window. Attached an image file of an issue .

![bot_issue](https://user-images.githubusercontent.com/33744455/33645628-cbd3ee5a-da71-11e7-9aa9-6ba7c5082039.png)

**Comment by swayamghodke** [comment]
![npm_install_restify_issue](https://user-images.githubusercontent.com/33744455/33659876-e4166fde-daa7-11e7-8782-d41e243f7bfb.png)
One more input  -> when I installed Botbuilder and Restify , I got following warnings.. Is Emulator not echoing my inputs due to this installation issue?
![npm_install_botbuilder_issue](https://user-images.githubusercontent.com/33744455/33659869-de7bfb70-daa7-11e7-843a-1ce87b1df67a.png)

**Comment by EricDahlvang** [comment]
I believe those warnings are related to having no package.json file in the directory.  I get them too:

![image](https://user-images.githubusercontent.com/11055362/33689292-b98d893c-da93-11e7-9112-4a486f6336be.png)


Do you see errors in the log window if you make it larger?

![emulatorlogwindow](https://user-images.githubusercontent.com/11055362/33689320-d7d86b82-da93-11e7-8ce2-636fde3475aa.gif)

**Comment by swayamghodke** [comment]
Hello thanks for your reply ,, Yes I have got an error, after making it larger I could see the error.
![bot_eumlator_issue](https://user-images.githubusercontent.com/33744455/33702742-00e77a24-db4b-11e7-8042-cf9923651f8c.png)

**Comment by swayamghodke** [comment]
Eric also I am not giving Microsoft APP ID and Microsoft APP password as of now as mentioned in the documentation.

**Comment by EricDahlvang** [comment]
It looks like checking for emulator updates is failing.  That should not affect connecting to a bot.

Do you see something like this, when you navigate to http://localhost:3978/api/messages in a web browser:
```
{
"code": "MethodNotAllowed",
"message": "GET is not allowed"
}
```

**Comment by swayamghodke** [comment]
Hello Eric 
1. Today I saw issue below while connecting 
![bot_emulator_connection_issue](https://user-images.githubusercontent.com/33744455/33751391-9c21829a-dc00-11e7-91b7-1c1a18ca0192.png)

2. Also when I tried navigating to http://localhost:3978/api/messages in a web browser I get an error 
![bot-navigating-to-site-error](https://user-images.githubusercontent.com/33744455/33751939-5ec5abde-dc04-11e7-9733-f85e03c47ccd.png)

**Comment by EricDahlvang** [comment]
How are you running the bot itself?  For instance, in the example above I placed my bot's code in a file named app.js and ran it from the command line with the following: 

> node app.js

![image](https://user-images.githubusercontent.com/11055362/33779850-6bc7d31c-dc03-11e7-8f27-46b34c9cb532.png)

**Comment by swayamghodke** [comment]
Eric it is working fine now.. 
I ran it the way you have mentioned.. I think directory permission was an issue
![running_bot_emulator](https://user-images.githubusercontent.com/33744455/33793619-70593a3c-dce0-11e7-90ec-08b7361ec3db.png)

Result is as below 

![bot_emulator_successful](https://user-images.githubusercontent.com/33744455/33793607-14e7e586-dce0-11e7-8b0d-4114fbbd7220.png)

**Comment by swayamghodke** [comment]
Thanks a lot for your help.. and patience... with my queries.

**Comment by EricDahlvang** [comment]
You are very welcome.  I'm glad you've got it working.

**Comment by dossjj** [comment]
Hi, I am seeing the same error as the comment above. Using the botframework emulator, I do not receive a response from LUIS or the bot. Just "message received" and nothing else. I do receia json back when pasting my endpoint uri with a message, though. Any ideas?

**Comment by AakashSanjayMehta** [comment]
I have the same problem. It works if I am testing the bot in the Microsoft azure portal but when I try to use the continuous deployment on VSCODE and test it on bot framework emulator it does not work

**Comment by idhruvs** [comment]
I am facing the same issue. The Bot Emulator sends my message, I can see a 'message received' info in the app, but unable to receive message from the bot. Please advice.

Following are the version details
1. Bot Framework Emulator V4.0.11
2. Bot Builder-Azure ^3.0.4
