### ISSUE TITLE
Reseting the emulator session

### ISSUE THREAD

**Issue by almirbi** [Microsoft/BotFramework-Emulator#36]
I am trying to test the ```firstRun``` middleware, but the session persists even after restarting both, the bot server and the emulator.

```javascript
bot.use(builder.Middleware.firstRun({ version: 1.0, dialogId: '*:/firstRun' }));
```

 So, ironically, I can get to the first run dialog only once. 

Is there any way to clear the session?

**Comment by eanders-MS** [comment]
Hi @almirbi, A feature for this will be added to the emulator next week. In the meantime, restarting the emulator will clear the state. Sorry for the inconvenience and thanks for your patience.
