### ISSUE TITLE
Enhancement: Use Electron's net module instead of Node's http

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-Emulator#363]
Electron's `net` module has better support for web proxies, including:
* Automatic management of system proxy configuration, support of the wpad protocol and proxy pac configuration files.
* Automatic tunneling of HTTPS requests.
* Support for authenticating proxies using basic, digest, NTLM, Kerberos or negotiate authentication schemes.
* Support for traffic monitoring proxies: Fiddler-like proxies used for access control and monitoring.

**Comment by cwhitten** [comment]
Addressed in https://github.com/Microsoft/BotFramework-Emulator/pull/408, closing.
