### ISSUE TITLE
Currently my bot framework emulator can't send messages 

### ISSUE THREAD

**Issue by mohammadamer** [Microsoft/BotFramework-Emulator#366]
Currently my bot framework emulator can't send messages and I can't be able to debug although previously it was working. 
![untitled](https://user-images.githubusercontent.com/19314043/34061185-beec59e0-e1ef-11e7-8c04-0043e20a9365.png)

**Comment by mgbennet** [comment]
Could you drag up the log panel? There should be information there that can help to diagnose the issue.
![emulator-drag-panel](https://user-images.githubusercontent.com/5344804/34065777-8088e0ea-e1ba-11e7-94ac-7689c3b75ada.gif)

**Comment by mohammadamer** [comment]
Here is the log
i double check the password but the same
![untitled](https://user-images.githubusercontent.com/19314043/34070598-74b00246-e271-11e7-99ce-97fa82cad5e3.png)

**Comment by mohammadamer** [comment]
It was resolved after check the following option

![untitled](https://user-images.githubusercontent.com/19314043/34093208-b7251404-e3cf-11e7-9333-0fe49e5542a7.png)

**Comment by EricDahlvang** [comment]
@mohammadamer I'm glad you've got it working.  Closing this issue.

**Comment by uherrmann3** [comment]
thanks this helps,
