### ISSUE TITLE
proposal: choosable ngrok region

### ISSUE THREAD

**Issue by Makopo** [microsoft/BotFramework-Emulator#369]
Current implementation of ngrok.ts looks like that, ignoring region option specified by ngrok.yml.

https://github.com/Microsoft/BotFramework-Emulator/blob/17b6163e9bf4e1aeabc3f04dc98d25ea059a6f31/src/server/ngrok.ts#L112-L114

I believe those who have app services on international region will prefer other than `us`. e.g. prefer `ap` if deployed on app services in Japan East.

The possibilities that come to my mind are:

a. Allow ngrok.yml choose region
b. Add an item on `App Settings`

**Comment by eanders-MS** [comment]
That is an odd bit of code in ngrok.ts. Thanks for bringing it up. I think that code could just be removed. I will research it.

**Comment by cwhitten** [comment]
this is fixed in the current version of the emulator
