### ISSUE TITLE
Cannot open more than one emulator window

### ISSUE THREAD

**Issue by roman-polunin-medamerica** [Microsoft/BotFramework-Emulator#37]
Windows 10 Universal, Emulator build 3.5.21.
Can't find any way to launch more than one window of Bot Framework Emulator.

**Comment by eanders-MS** [comment]
@roman-polunin-medamerica thanks for taking the time to report this. Based on user feedback like yours, it's clear we need to support multiple running instances of the emulator. You can expect to see this in the next release. We're on a weekly release cycle right now, with a new emulator released each Thursday.
