### ISSUE TITLE
Separation strong being added when not requested

### ISSUE THREAD

**Issue by yogiderek** [Microsoft/BotFramework-Emulator#379]
Emulator version: 3.5.34

The following c# code

```
                container.Items.Add(
                    new AdaptiveTextBlock
                    {
                        Text = "Some text goes here.",
                        HorizontalAlignment = AdaptiveHorizontalAlignment.Center,
                        Weight = AdaptiveTextWeight.Bolder,
                        Wrap = true,
                        Size = AdaptiveTextSize.Medium,
                        Spacing = AdaptiveSpacing.Large
                    }
                );
```

produces the following json in the Details view in the emulator. 

```
              {
                "type": "TextBlock",
                "size": "medium",
                "weight": "bolder",
                "text": "Some text goes here.",
                "horizontalAlignment": "center",
                "wrap": true,
                "spacing": "large",
                "separation": "strong"
              }
````
I have not specified a separator in the c# code but one is being produced. I have tried adding Separator = false but the same json is still produced. 

![issue1](https://user-images.githubusercontent.com/2614368/34342117-8eda7348-e99e-11e7-9f3b-6deed5315f8e.png)

**Comment by eanders-MS** [comment]
What version of Adaptive Cards is your project using? The emulator is on Adaptive Cards 0.5 (the work to update to 1.0 is in progress).

**Comment by yogiderek** [comment]
Version 1.0.0-beta11

**Comment by cwhitten** [comment]
@yogiderek is this still an issue for you in the latest version of the Emulator?

**Comment by cwhitten** [comment]
Closing, stale.
