### ISSUE TITLE
Emulator is not working with speech

### ISSUE THREAD

**Issue by TestUsetGitHubUser** [Microsoft/BotFramework-Emulator#402]
When i try to test speech with empty **MicrosoftAppId** and **MicrosoftAppPassword** i have this error as below:
 Could not retrieve Cognitive Services speech token 
[14:57:51] Error: Unauthorized 
[14:57:51] Details: To use speech, the bot must be registered and using a valid MS AppId and Password. 
[14:57:53] Could not retrieve Cognitive Services speech token 

When I add MS app id and password that are valid because i tested and they work good in published web i get this error "The bot's MSA appId or password is incorrect" and those are correct.
I am using sdk version 8.0 and latest version of emulator.

**Comment by EricDahlvang** [comment]
Hi @TestUsetGitHubUser 

Please upgrade your bot's SDK version to the latest version.

Bot Builder sdk versions lower than 3.9 were using a different authentication scheme.  This blog post provides more information: https://blog.botframework.com/2017/05/07/bot-framework-auth-change/
