### ISSUE TITLE
Allow multiple emulators to join the same conversation

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Emulator#403]
I'd like to test logic for managing multiple participants in a conversation.
* Currently, each emulator opens a separate conversation.
* I was hoping to connect to the same bot using multiple emulator instances to simulate the multiple participants.

**Comment by live-abhishek** [comment]
I would like that too! When starting a new conversation, can we specify the conversationID which we want to join. This will help in testing for clients like slack, skype, etc. where there are multiple users in a conversation.

**Comment by tonyanziano** [comment]
This would depend on multi-user conversation capability which is being tracked at #197
