### ISSUE TITLE
Version 3.5.35 is not working.

### ISSUE THREAD

**Issue by TestUsetGitHubUser** [Microsoft/BotFramework-Emulator#404]
When ever i try to send a message i got error 500.
[09:21:36] -> POST 200 [conversationUpdate] 
[09:21:36] -> POST 200 [conversationUpdate] 
[09:21:45] -> POST 500 [message] hi

**Comment by EricDahlvang** [comment]
Which version of the SDK is the bot using?

**Comment by TestUsetGitHubUser** [comment]
Version 3.8.0

**Comment by EricDahlvang** [comment]
Please upgrade your bot's SDK version to the latest version.

Bot Builder sdk versions lower than 3.9 were using a different authentication scheme. This blog post provides more information: https://blog.botframework.com/2017/05/07/bot-framework-auth-change

**Comment by TestUsetGitHubUser** [comment]
Thank you @EricDahlvang  I updated the latest version is working good now.

**Comment by EricDahlvang** [comment]
Oh good!
