### ISSUE TITLE
Speech input for Bot Framework Emulator not working

### ISSUE THREAD

**Issue by vivekrao4689** [Microsoft/BotFramework-Emulator#405]
Hi,
I am working with  Bot Framework Emulator V. 3.5.35. The bot is working fine with text inputs. But when I am trying to pass speech input to emulator by clicking on mic button, it gives me following error-

Could not retrieve Cognitive Services speech token 
Error: Exception 
Details:  System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: MSIS3125: The password for bcsvcin2@microsoft.com has expired. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (InternalServerError). ---> System.Exception: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2018-01-23T07:29:40.829Z</u:Created><u:Expires>2018-01-23T07:34:40.829Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://schemas.microsoft.com/ws/2009/12/identityserver/">a:FailedAuthentication.ExpiredPassword</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">MSIS3125: The password for bcsvcin2@microsoft.com has expired.</s:Text></s:Reason><s:Detail><UserAccountPasswordExpiredFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><PasswordChangeEndpoint i:nil="true"/><UserAccountName>bcsvcin2@microsoft.com</UserAccountName></UserAccountPasswordExpiredFault></s:Detail></s:Fault></s:Body></s:Envelope> --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.WsTrustRequest.<SendRequestAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__52.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at SpeechServices.TokenClient.InitSigningKeys(String speechAppId, String userName, String userPassword) at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at SpeechServices.TokenClient.InitSigningKeys(Boolean block) at SpeechServices.TokenClient.GetToken(String appId, Int32 goodForInMinutes) at Intercom.Switch.Controllers.SpeechTokenController.GetToken(Int32 goodForInMinutes) ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: MSIS3125: The password for bcsvcin2@microsoft.com has expired. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (InternalServerError). ---> System.Exception: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2018-01-23T07:29:40.829Z</u:Created><u:Expires>2018-01-23T07:34:40.829Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://schemas.microsoft.com/ws/2009/12/identityserver/">a:FailedAuthentication.ExpiredPassword</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">MSIS3125: The password for bcsvcin2@microsoft.com has expired.</s:Text></s:Reason><s:Detail><UserAccountPasswordExpiredFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><PasswordChangeEndpoint i:nil="true"/><UserAccountName>bcsvcin2@microsoft.com</UserAccountName></UserAccountPasswordExpiredFault></s:Detail></s:Fault></s:Body></s:Envelope> --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.WsTrustRequest.<SendRequestAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__52.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at SpeechServices.TokenClient.InitSigningKeys(String speechAppId, String userName, String userPassword) at System.Threading.Tasks.Task.Execute() ---> (Inner Exception #0) Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/usernamemixed returned error: MSIS3125: The password for bcsvcin2@microsoft.com has expired. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (InternalServerError). ---> System.Exception: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/soap/fault</a:Action><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><u:Timestamp u:Id="_0"><u:Created>2018-01-23T07:29:40.829Z</u:Created><u:Expires>2018-01-23T07:34:40.829Z</u:Expires></u:Timestamp></o:Security></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value xmlns:a="http://schemas.microsoft.com/ws/2009/12/identityserver/">a:FailedAuthentication.ExpiredPassword</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">MSIS3125: The password for bcsvcin2@microsoft.com has expired.</s:Text></s:Reason><s:Detail><UserAccountPasswordExpiredFault xmlns="http://schemas.microsoft.com/ws/2009/12/identityserver/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><PasswordChangeEndpoint i:nil="true"/><UserAccountName>bcsvcin2@microsoft.com</UserAccountName></UserAccountPasswordExpiredFault></s:Detail></s:Fault></s:Body></s:Envelope> --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__29.MoveNext() --- End of inner exception stack trace --- at Microsoft.IdentityModel.Clients.ActiveDirectory.WsTrustRequest.<SendRequestAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__52.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() ErrorCode: federated_service_returned_error StatusCode: 500<--- <--- 

Could you please guide me with this error?

Thanks

**Comment by EricDahlvang** [comment]
Hi @vivekrao4689 

Thank you for reporting this problem.  We are working on a resolution.  I'll let you know once the release is completed.

**Comment by EricDahlvang** [comment]
This issue is no longer occurring.  Let us know if you run into any other problems.

**Comment by vivekrao4689** [comment]
Hi Eric,
Thank you so much for looking into this problem. The issue is resolved now.

**Comment by EricDahlvang** [comment]
@gouravbeyondBGCM Do you see any messages related to speech in the log window?
