### ISSUE TITLE
Emulator not sending user's Locale in conversationUpdate activities

### ISSUE THREAD

**Issue by michaelkoss** [microsoft/BotFramework-Emulator#415]
When connecting to a bot with the emulator and specifying the `Locale`, the `conversationUpdate` `Activity` that is passed to the bot has a null `Locale`. Only when `MessageActivity`s are sent is the `Locale` specified.

**Comment by EricDahlvang** [comment]
Hi @michaelkoss 

I believe this is by design.  The `Locale `property is on `IMessageActivity `not `IConversationUpdateActivity`: https://github.com/Microsoft/BotFramework-Emulator/blob/f58fd395526d509d98cab2931e50b8c84ec1e89f/src/types/activityTypes.ts

**Comment by michaelkoss** [comment]
My expectation came from building a bot in C#. When my `BotReceiveHandler` method is called with a `Request.Type` equal to `"updateConversation"`, there is a property on `Request` called `Locale` which is `null`. See the attached screenshot of a debugging session.

I am trying to detect the user's `Locale` when they join the conversation in my translation middleware so I can provide the welcome message in their native language. Without this property being set, the welcome message is in English and then suddenly switches when they sent their first `MessageActivity`.

I believe this is a solid enough use case to warrant changing the `IConversationUpdateActivity` to include and populate the `Locale` property.


![image](https://user-images.githubusercontent.com/21314810/36343911-25049714-13d8-11e8-85f5-43ff08ef5150.png)

**Comment by stevengum** [comment]
@michaelkoss and @ericdahlvang can we frame this issue in the v4 Emulator context? 

If I understand correctly these are some of the action items:
- We need to add the UI for specifying a locale when connecting to a bot (at least for endpoints).
- If the locale is specified, it should be sent in the conversationUpdate activity.

Can either of you chime in on this?

___

@cwhitten how should we consider botfiles and locale in this scenario? I think we should wait to see _"Connect via Endpoint w/ locale"_ telemetry. We would have some usage data to back decisions, and we would be able to see how many people still use botfiles.

**Comment by tonyanziano** [comment]
@stevengum there is already a global locale setting in the Emulator that defaults to `en-US`:

![image](https://user-images.githubusercontent.com/3452012/62964453-e0d17900-bdb7-11e9-8e0b-98176b5f0cc4.png)

So it would be as simple as grabbing the setting value from the settings at the time of sending the conversationUpdate activity and appending it to the activity payload.

**Comment by tonyanziano** [comment]
We should consider setting the Emulator's default locale to the locale of the user's machine using Electron's [`app.getLocale()`](https://electronjs.org/docs/api/app#appgetlocale) API

**Comment by cwhitten** [comment]
We'll keep this on our long-term backlog. No ETA, but we would happily accept a community contribution.
