### ISSUE TITLE
My bot doesn´t work

### ISSUE THREAD

**Issue by CONSORGIO** [Microsoft/BotFramework-Emulator#418]
Exception: Referencia a objeto no establecida como instancia de un objeto.
[Archivo de tipo 'text/plain']

**Comment by FranciscoPonceGomez** [comment]
Hi CONSORGIO,

Can you provide more information about your bot? A sample of your bot would also be very useful.
My guess is that if you step by step debugging your code you would probably will find the issue.
----

Hola CONSORGIO,

Podrias incluir más información acerca de tu bot? Si pudieras incluir un ejemplo de tu código eso sería muy útil. Creo que si debugueas el código paso a paso podrías encontrar el error.

Francisco
