### ISSUE TITLE
Emulator does not have functionalities displayed

### ISSUE THREAD

**Issue by ZakiaSalod** [Microsoft/BotFramework-Emulator#420]
Hi there!

Please could someone assist me.
When I run the Microsoft BOT Emulator on my local machine, trying to point to my localhost: as soon as the Emulator opens, it comes up with this:

![emulatorissue](https://user-images.githubusercontent.com/17802823/36601013-b242ff38-18bc-11e8-9425-d725a17a3168.png)

I am not able to select anything at all. Please help. Thank you!

**Comment by EricDahlvang** [comment]
Hi @ZakiaSalod 

Please try resizing the window:

![emulator_resizewindows](https://user-images.githubusercontent.com/11055362/36611481-6ec76318-1888-11e8-9d46-ad52f5a3ee8e.gif)

**Comment by EricDahlvang** [comment]
Closing this.  If you require further assistance, please @mention me or open a new issue.
