### ISSUE TITLE
Remove/Delete Endpoint URL

### ISSUE THREAD

**Issue by MovGP0** [Microsoft/BotFramework-Emulator#423]
I want to remove an Endpiont URL that was added by accident. Unfortunately, there seems no obvious way to do so. 

To solve this, there should be the list of endpoint configurations visible in settings, such that the developer can remove endpoint URLs when needed.

**Comment by eanders-MS** [comment]
In the URL bar, start typing the endpoint you want to delete. When you see it listed, hover over it with the mouse pointer. You should see an 'x' icon appear on the line on hover. Clicking the 'x' will delete it.

**Comment by eanders-MS** [comment]
![2018-03-15_8-46-01](https://user-images.githubusercontent.com/12176807/37474432-88141eec-282d-11e8-8a16-15aeb36f0948.gif)

**Comment by MovGP0** [comment]
Thanks. I guess this one should be more obvious. Closing the issue.
