### ISSUE TITLE
could not get response from bot 

### ISSUE THREAD

**Issue by ajaykumar1452** [Microsoft/BotFramework-Emulator#424]
hi , i have created a sample bot and integrated with LUIS by creating intents and mappings, u see can code in below screen shot, the issue is i could not get response from bot to Emulator.
![node js bot code](https://user-images.githubusercontent.com/36725410/37822112-8d860bcc-2eab-11e8-8652-75c4bca247c3.PNG)

----------------------------------Emulator--------------------------------------
![response from bot](https://user-images.githubusercontent.com/36725410/37822128-a0d31756-2eab-11e8-90fe-6bcaf3ff5293.PNG)

**Comment by JasonSowers** [comment]
Please post actual code and not pictures of code.  GitHub uses [Markdown](https://guides.github.com/features/mastering-markdown/)  for this.

**Comment by JasonSowers** [comment]
@ajaykumar1452 Would you please post this question in the main [botbuilder repository](https://github.com/Microsoft/BotBuilder/issues/new).  We will be happy to assist you over there in diagnosing your issue.
