### ISSUE TITLE
How integrate stt without cognitive services? [Question]

### ISSUE THREAD

**Issue by iformas** [Microsoft/BotFramework-Emulator#425]
Hi, I want to integrate BotFramework-Emulator with external services for stt like watson without cognitive services. I can’t find documentation about that

**Comment by JasonSowers** [comment]
This is outside the scope of this forum.  This repository is for Issue and bugs within the emulator.  For a question like this please ask over on [StackOverflow](https://stackoverflow.com) where the community can probably help you.
