### ISSUE TITLE
'http://localhost:3979/api/messages' failed: [500] Internal Server Error 

### ISSUE THREAD

**Issue by adamdharris** [Microsoft/BotFramework-Emulator#427]
Hi, I keep getting failed: [500] Internal Server Error.

Using:
- bot emulator v3.5.35
- Bot SDK 3.14.1.1
- C# bot
- OS Windows 10

**Comment by Quico20** [comment]
Could you provide a sample of your code and screenshots,I might be able to help you.

**Comment by EricDahlvang** [comment]
Hi @adamdharris 

Internal Server Error generally indicates an issue with the bot's code.  Are you running the bot in debug mode in Visual Studio?  Do you see an exception or stack trace in the output window?

**Comment by adamdharris** [comment]
Hi @EricDahlvang 

I am running in debug mode.  Is this the exception you are referring to?

```'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/6/ROOT-1-131668361144271436): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.ArgumentNullException' in System.dll
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll```

Interestingly sometimes it connects after a few minutes if I keep sending messages.  Other times it does not and keeps throwing the error.  

I am in Australia and luis is published to Australian region.

**Comment by adamdharris** [comment]
Hi @Quico20 

```
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {

            Common.CommonConversation.Connector = new ConnectorClient(new System.Uri(activity.ServiceUrl));
            Common.CommonConversation.CurrentActivity = activity;

            Activity reply = null;

            if (activity.Type == ActivityTypes.Message)
            {
                var userId = Common.CommonConversation.CurrentActivity?.From?.Id;
                // var token = _credentialStore.GetToken(userId);

                var userInput = await Helpers.InputHelper.ParseUserInput(Common.CommonConversation.CurrentActivity.Text);


                    if (userInput.intents.Where(w => w.score > 0.3).Count() <= 0)
                {
                    await Conversation.SendAsync(activity, () => new QnaDialog());
                }
                else
                {
                    UserIntentType userIntent = UserIntentType.None;
                    Enum.TryParse(userInput.intents.First().intent, true, out userIntent);

                    switch (userIntent)
                    {
                        case UserIntentType.greeting:

                            await Conversation.SendAsync(activity, () => new LuisDialog());

                            break;
```

```
[LuisModel("******", "*****")]
[Serializable]
public class LuisDialog : LuisDialog<object>
{

    [LuisIntent("greeting")]
    public async Task Greeting(IDialogContext context, LuisResult result)
    {
        string reply = "Hello...";
        await context.PostAsync(reply);
        context.Wait(MessageReceived);
    }
```

**Comment by EricDahlvang** [comment]
While running the bot in debug mode, can you set a breakpoint in the Post method you shared above, and step through the code, to determine exactly where the error is occurring?

**Comment by adamdharris** [comment]
Seems to be in WebApiConfig, take a screengrab for you

###WebApiConfig snippet
![image](https://user-images.githubusercontent.com/12539463/38117182-fac2877e-33f6-11e8-8c1a-d31d8e8e28fa.png)

###bot emulator snippet
![image](https://user-images.githubusercontent.com/12539463/38117208-193773b8-33f7-11e8-9c5a-081b2c4e75bf.png)

**Comment by adamdharris** [comment]
@EricDahlvang My bot emulator settings for reference

![image](https://user-images.githubusercontent.com/12539463/38117405-1c784038-33f8-11e8-99ef-ddc9bdcc6d65.png)

![image](https://user-images.githubusercontent.com/12539463/38117420-2bcc06b4-33f8-11e8-893e-69dc0bdc8738.png)

**Comment by EricDahlvang** [comment]
What is the exception in WebApiConfig?

**Comment by adamdharris** [comment]
I am not seeing the exception, is there a setting I need to activate in the exception settings?  Sorry only fairly new to VS

**Comment by adamdharris** [comment]
@EricDahlvang I have found the error, the code Intent["greeting"] and for QnA dialog is not recognizing greeting or QnA dialog

**Comment by EricDahlvang** [comment]
@adamdharris That sounds like a coding issue.  This repository is specifically for Emulator bugs/issues and feature requests.  Please post your question on StackOverflow with the botframework tag stackoverflow.com/questions/tagged/botframework and the Bot Framework Support engineers will assist you there.
