### ISSUE TITLE
Speak is not triggering text to speech

### ISSUE THREAD

**Issue by bontibon** [Microsoft/BotFramework-Emulator#428]
I am trying to get text to speech to work in the emulator without success.  I am using my microphone as input which, according to #412, is required, but I still don't hear the text being read. I am also using a Microsoft App ID and password with my bot.

The message I get back from my bot looks like:

```json
{
  "type": "message",
  "text": "Sorry, I don't understand",
  "speak": "<speak>Sorry, I don't understand</speak>",
  "locale": "en-US",
  ...
```

Node botbuilder: 3.14.1
OS: Linux
Emulator: v3.5.35

**Comment by EricDahlvang** [comment]
Hi @bontibon 

So, speech to text works but text to speech does not?  Are you seeing any errors in the log window?

**Comment by bontibon** [comment]
@EricDahlvang 
That is correct.  No errors.

**Comment by bontibon** [comment]
> Does the bot at this site speak back to you using the chrome browser on that same machine: https://eric-testspeech.azurewebsites.net/default.htm ?

Yes, that works.

**Comment by EricDahlvang** [comment]
The emulator uses the WebChat control internally, so if speech works on the site it should technically work in the emulator also.  I don't know why it isn't, but something you could try is downloading the emulator's source and debugging the render process locally.  This page describes how to do this: https://github.com/Microsoft/BotFramework-Emulator/wiki/How-to-Contribute#clone-and-build

**Comment by bontibon** [comment]
I put in a dummy implementation of `BotChat.ChatProps.speechOptions.speechSynthesizer`, and the log is showing that only `stopSpeaking` is ever called, never `speak`.

**Comment by bontibon** [comment]
Sorry, `speak` is getting called; I was typing instead of speaking, which wasn't triggering it.

The `speak` function is only being passed the first argument set to `"404"`.

**Comment by bontibon** [comment]
My last comment was incorrect in that the `speak` function is being invoked with the correct arguments.

I was able to get TTS to speech to work by adding the following line after the imports in `main.ts`:

```javascript
Electron.app.commandLine.appendSwitch('enable-speech-dispatcher');
```

However, TTS only starts working after the 2nd message is received from the bot; the first speech message the emulator receives after starting is always discarded.

**Comment by EricDahlvang** [comment]
@bontibon  Are you able to provide a small sample bot that demonstrates the issue you are experiencing, so we can reproduce it here?

**Comment by EricDahlvang** [comment]
Closing this issue due to no response.

**Comment by Toemsel** [comment]
Greate, same issue
