### ISSUE TITLE
Add Custom Speech Service support

### ISSUE THREAD

**Issue by bontibon** [microsoft/BotFramework-Emulator#429]
It would be useful if we could use our Custom Speech Service endpoint in the emulator, without having to modify the source code.

**Comment by compulim** [comment]
## Note to fixer

- [ ] Add UI to able to set few things in UI
   - [ ] Speech Services subscription token
   - [ ] CRIS endpoint
   - [ ] Voice font

**Comment by JamesEarle** [comment]
@compulim Are there any updates on this request? It would be great if we could add our Custom Speech endpoint to easily test here.

**Comment by cwhitten** [comment]
Hello. We have provided this functionality through the use of the Direct Line Speech channel, where you can provide your speech credentials to connect to the service. Closing.
