### ISSUE TITLE
Error: Refresh access token failed with status code: 400

### ISSUE THREAD

**Issue by advl03** [Microsoft/BotFramework-Emulator#431]
Hi everybody,
We have started to receive this error in all of our three environments (Development, integration, production). This issue happened a couple of times in the past:
https://github.com/Microsoft/BotBuilder/issues/3197
https://github.com/Microsoft/BotBuilder/issues/1938

Environment:
- SDK Language: Node
- SDK version: 3.7.0

Using Facebook Messenger channel. This is what appears in the logs when I try to send a message:
Message:
{"type":"message","agent":"botbuilder","source":"facebook","address":{"id":"mid.$cAAX3CT72CJBoy3pL_limjUDtdovY","channelId":"facebook","user":{"id":"1046304145498637","name":"Alberto De Vega"},"conversation":{"isGroup":false,"id":"1046304145498637-1678993359058347"},"bot":{"id":"1678993359058347","name":"botcorn-dev"},"serviceUrl":"https://facebook.botframework.com","useAuth":true},"text":"Hola! No sabía que estabas por aquí...","time":"2018-04-06T09:06:29.867Z","lvl":"INFO","msg":"Message OUT"}

ERROR:
{"time":"2018-04-06T09:06:30.084Z","lvl":"ERROR","err":{"message":"Refresh access token failed with status code: 400","name":"Error","constructor":"Error","stack":"Error: Refresh access token failed with status code: 400\n    at Request._callback (/opt/botcorn/node_modules/botbuilder/lib/bots/ChatConnector.js:489:28)\n    at Request.self.callback (/opt/botcorn/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/opt/botcorn/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/opt/botcorn/node_modules/request/request.js:1085:12)\n    at IncomingMessage.g (events.js:292:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"Error: Refresh access token failed with status code: 400"}

**The same happens with demo-facebook example from botbuilder/node/examples/demo-Facebook, even when updated with the latest release from master (git pull - npm install - node app.js). 
Tested with FB Messenger and Web Chat Client from Azure Portal**

**Comment by HighSoftWare96** [comment]
Same for me...

**Comment by HighSoftWare96** [comment]
[Reports](https://outage.report/microsoft) Microsoft servers are down?

**Comment by advl03** [comment]
Following the problem in https://github.com/Microsoft/BotBuilder/issues/4432 as this issue happens with other clients as well

**Comment by EricDahlvang** [comment]
@advl03 Thank you for reporting this.  

You care correct that https://github.com/Microsoft/BotBuilder/issues/4432 is tracking the issue.  I'm going to close this one, since the underlying problem is not related to the Emulator specifically.
