### ISSUE TITLE
Forced to pick folder when creating a new Bot (Consider a Default)

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotFramework-Emulator#435]
Using the latest emulator, when I add a Bot, I'm forced to pick a folder. 

This is non-obvious.

On Windows, this should default to "MyDocuments/Bots" or similar. On other platforms, similar defaults should apply. As the "Simplist" solution, just default to the same folder (+/bots/) the application is running out of. 

![image](https://user-images.githubusercontent.com/1165321/39077018-b5198272-44b3-11e8-99af-e92b1097be87.png)

**Comment by eanders-MS** [comment]
Yes, this is planned. Please log v4 issues and suggestions on the internal site for now. Thanks!

Sent from 📱
________________________________

**Comment by vishwacsena** [comment]
By default emulator creates a .bot file that needs a home. There are no default location for them since you typically want to keep the .bot file with the rest of your bot code.
