### ISSUE TITLE
Can't use with self signed certs on Ubuntu

### ISSUE THREAD

**Issue by michaelsrichter** [microsoft/BotFramework-Emulator#436]
I am trying to use the emulator on Ubuntu. I start restify with self signed certs. I can get this to work on Windows, but not Ubuntu.

The emulator doesn't give any error messages, but nothing happens in the logs; it's like the message is never sent to my bot. Do I need to enable something within Ubuntu to trust the self signed certs? Is there a way to get the emulator to trust the certs? 

Thanks!

**Comment by OEvgeny** [comment]
Should be possible in v4 if the self-signed certificate is trusted on the machine.

Closing for now, feel free to reopnen
