### ISSUE TITLE
Log Text Warped on Linux Version  #helpwanted

### ISSUE THREAD

**Issue by dominickm** [Microsoft/BotFramework-Emulator#438]
Running the latest Bot Framework emulator on a Gnome Ubuntu 18.04 release shows the log test to be scrunched together as shown here. I've tried re-sizing the window but that doesn't seem to change it. 
![screenshot from 2018-04-29 19-44-01](https://user-images.githubusercontent.com/455193/39412194-821e2e6a-4be6-11e8-8f4c-b721dc0b717f.png)

I'm curious if anyone else is seeing this or is it something local for me.

**Comment by dominickm** [comment]
![screenshot from 2018-04-29 19-56-34](https://user-images.githubusercontent.com/455193/39412244-6fe35fb2-4be7-11e8-9fbb-938d67894589.png)
Here's a screenshot of the Detail view also. I'm wondering if it's a Gnome issue.

**Comment by tonyanziano** [comment]
This is an issue in v4 as well and should be addressed.

![image](https://user-images.githubusercontent.com/3452012/48280652-12707a80-e409-11e8-964d-c64971f0fbed.png)

**Comment by justinwilaby** [comment]
This looks like a line hight issue.

**Comment by cwhitten** [comment]
see #524 for updates on the log ui/ux
