### ISSUE TITLE
POST Refresh access token failed with status code: 400

### ISSUE THREAD

**Issue by Dwarakanath** [Microsoft/BotFramework-Emulator#439]
There is an issue -POST Refresh access token failed with status code: 400 when Iam connecting the QnAMaker bot from emulator. Seems the time stamps are different. Not sure from where the timestamp is picked up?

**Comment by Dwarakanath** [comment]
attaching the screenshot
[Emulator connectivity issue.docx](https://github.com/Microsoft/BotFramework-Emulator/files/1959570/Emulator.connectivity.issue.docx)

**Comment by EricDahlvang** [comment]
Hi @Dwarakanath 

Please post the image as a comment.  I'm unable to see it within the docx (text is very small).

**Comment by EricDahlvang** [comment]
Closing due to no response.  If you require further assistance, please @mention me or open a new issue.
