### ISSUE TITLE
Uploading attachment

### ISSUE THREAD

**Issue by waglik** [Microsoft/BotFramework-Emulator#44]
Hi guys

Today I've noticed that it is impossible to send attachment inside Emulator. Every time I send something to the bot emulator end up in "sending" state while bot did not receive any message. I tried videos, pictures and images, nothing was received. 

Emulator version :  3.5.20

build from source on RHEL 7

**Comment by eanders-MS** [comment]
Can you pull latest and try again? We've fixed some bugs around uploading since 3.5.20.

**Comment by waglik** [comment]
@eanders-MS Hi Eric. Thanks, downloading new version helped. Though  I had some issues with it. Latest release does not come with ./app directory. App was failing with message : 

Error launching app
Unable to find Electron app at /home/waglik/Applications/BotFramework-Emulator-3.5.22

Cannot find module '/home/waglik/Applications/BotFramework-Emulator-3.5.22'

It worked only after I copied ./app dir from 3.5.20 package. Emulator now starts and upload seems to be working but window label says it is v3.5.21. Thought you might want to know that.

**Comment by eanders-MS** [comment]
Thank you for reporting this. I will take a look at our OS X release tomorrow and ensure it has everything included.
