### ISSUE TITLE
Support Testing `Microsoft.Launch` Request

### ISSUE THREAD

**Issue by amckibben** [microsoft/BotFramework-Emulator#440]
I suppose this is a channel-specific thing (Cortana). But the ability to simulate a 'launch request' in BotFramework Emulator would greatly aid in local development of a Cortana skill. A launch request is when a user doesn't specify an intent and instead says something like:
> Cortana, open \<skill name\>

Perhaps something like "send launch request" could be added to this context menu:
![image](https://user-images.githubusercontent.com/2603159/39491133-3ca214ea-4d59-11e8-8814-b06efe77641c.png)

**Comment by tonyanziano** [comment]
This could be accomplished by #416 . This can be tracked there.
