### ISSUE TITLE
builder.Prompts.choice() leave blank menu option

### ISSUE THREAD

**Issue by haganbt** [Microsoft/BotFramework-Emulator#45]
Im using node.js SDK and using:

```javascript
 builder.Prompts.choice(session, "Choose a topic of interest:", "Cloud|Telecoms|...
```
Always leaves a blank space at the top of the menu list items:

![image](https://cloud.githubusercontent.com/assets/144374/21057393/61479b40-bdee-11e6-9806-3c4f40769fc5.png)

Is this a bug or by design?

**Comment by eanders-MS** [comment]
I believe a fix for this has been made. @danmarshall?

**Comment by eanders-MS** [comment]
@haganbt Can you update to latest and try again?

**Comment by haganbt** [comment]
Many thanks @eanders-MS - updated to v3.5.22.

Looks like the handling of different width sizes is much improved which is great :)

There is still a good deal of white space at the top - clearly not a serious issue but might be room for improvement to make sure the bottom and top widths are identical.

![image](https://cloud.githubusercontent.com/assets/144374/21060477/7129b12a-bdfc-11e6-8092-e548656f55ff.png)

![image](https://cloud.githubusercontent.com/assets/144374/21060483/7ae34082-bdfc-11e6-8776-857ff7a8ab8a.png)

Feel free to close if this is a not fix.

**Comment by danmarshall** [comment]
Hi @haganbt - appreciate the bug report. This was indeed a regressed bug. I've sent a PR to the WebChat repo: https://github.com/Microsoft/BotFramework-WebChat/pull/222

**Comment by haganbt** [comment]
Wonderful, thanks @danmarshall
