### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotFramework-Emulator#452]
Hi. This is a minor issue.
The current version does not build and throws the error for **adaptiveCardsHostConfig** in **client/mainView.tsx** since the adaptiveCardsHostConfig property is not defined in the interface. Commenting out the line in mainView fixes the build issue.

**Comment by eanders-MS** [comment]
You may need to `npm install` to grab the latest webchat control. Have you tried this?
