### ISSUE TITLE
The bot's MSA appId or passsword is incorrect

### ISSUE THREAD

**Issue by bGoovaerts** [Microsoft/BotFramework-Emulator#46]
Log
[14:44:56] ngrok listening on https://68752c9a.ngrok.io 
[14:44:56] ngrok traffic inspector: http://localhost:4040 
[14:44:56] Application is up to date. 
[14:44:56] Emulator listening on http://[::]:58607 
[14:46:43] -> POST 401 [conversationUpdate] 
[14:46:43] Error: The bot's MSA appId or passsword is incorrect. 
[14:46:43] Click here to edit your bot's MSA info. 

Web.config

<configuration>
  <appSettings>

    <add key="BotId" value="MyBot" /> 
    <add key="MicrosoftAppId" value="" />
    <add key="MicrosoftAppPassword" value="" />
 
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
  </appSettings>

**Comment by eanders-MS** [comment]
Hi @bGoovaerts a few questions
- Is your bot running locally?
- Has this worked successfully for you in the past?

**Comment by bGoovaerts** [comment]
Hello Eric,

the bot is running locally and with an other project is it working. I've integrated the bot in a MVC project and I use windows authentication.

**Comment by eanders-MS** [comment]
Sorry for the slow response. Is your bot endpoint a localhost URL?

**Comment by eanders-MS** [comment]
Hi @bGoovaerts Closing this issue now due to inactivity. If you're still seeing this problem, please open a new one and we'll continue troubleshooting. Cheers.

**Comment by akontsevich** [comment]
Have same issue running locally, could You reopen please?
