### ISSUE TITLE
Bot.Builder version 3.15.2 not work for bot emulator

### ISSUE THREAD

**Issue by iangithub** [Microsoft/BotFramework-Emulator#477]
I use the bot framework template project (https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-quickstart?view=azure-bot-service-3.0) to create a bot , if i don't upgrade Bot.Builder to ver.3.15.2 (use ver.3.8.0), the  bot emulator work fine , but if i  upgrade Bot.Builder to 3.15.2 , the emulator always show can't send message

Can't work environment :
1.Bot.Builder ver.3.15.2
2. .Net framework 4.6
3. bot emulator 3.5.36

work fine environment 
1.Bot.Builder ver.3.8.0
2. .Net framework 4.6
3. bot emulator 3.5.36

**Comment by eanders-MS** [comment]
This sounds like an issue with BotBuilder rather than the emulator itself. Could you post your issue at their repo? https://github.com/Microsoft/BotBuilder

**Comment by iangithub** [comment]
Hi ;

Thank you , yes , i post this issue to https://github.com/Microsoft/BotBuilder

**Comment by eanders-MS** [comment]
ref: https://github.com/Microsoft/BotBuilder/issues/4571#issuecomment-386942580
