### ISSUE TITLE
ReceiptCard rendering issue

### ISSUE THREAD

**Issue by BrodaUa** [Microsoft/BotFramework-Emulator#48]
I am using the the next block of code to create and post receipt card:
`var reply = context.MakeMessage();

            var items = new List<ReceiptItem>();
            items.Add(new ReceiptItem(subtitle: "some text 1", text:"some text 2", price: ""));
            items.Add(new ReceiptItem(subtitle: "some text 3", text: "some text 4", price: ""));

            var confirmBtn = new CardAction("postBack", "some text 5", value: "some text 6");
            var editBtn = new CardAction("postBack", "some text 7", value: "some text 8");

            reply.Attachments.Add(new ReceiptCard(
                title: "OrderInfo",
                items: items,
                total: "0.0",
                buttons: new[] { editBtn, confirmBtn }).ToAttachment());

            await context.PostAsync(reply);`
but in the new bot emulator (3.5.22) i am facing the next issue: 
the card is not rendering my items and buttons
![image](https://cloud.githubusercontent.com/assets/9928101/21188506/4e1e7662-c224-11e6-9b35-9523975b8016.png)

**Comment by eanders-MS** [comment]
Hi @BrodaUa Can you please post the JSON of the message containing the ReceiptCard?

**Comment by BrodaUa** [comment]
`
{
  "type": "message",
  "timestamp": "2016-12-15T08:12:32.023Z",
  "serviceUrl": "https://3781fa57.ngrok.io",
  "channelId": "emulator",
  "from": {
    "id": "i12e7b1h5m9ge58jc",
    "name": "Bot"
  },
  "conversation": {
    "id": "kgbh1am2kfb93fkci"
  },
  "recipient": {
    "id": "default-user"
  },
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.receipt",
      "content": {
        "title": "Order info",
        "items": [
          {
            "subtitle": "Some title 1",
            "text": "description",
            "price": "0.0"
          },
          {
            "subtitle": "Some title 2",
            "text": "description",
            "price": "0.0"
          }
        ],
        "total": "0.0",
        "buttons": [
          {
            "type": "postBack",
            "title": "Confirm",
            "value": "Confirm"
          },
          {
            "type": "postBack",
            "title": "Edit",
            "value": "Edit"
          }
        ]
      }
    }
  ],
  "entities": [],
  "replyToId": "3538nd99bl1j5245jc",
  "id": "75cegj12f4c8a7626"
}
`

**Comment by eanders-MS** [comment]
@BrodaUa It appears the webchat control is not rendering some of the item fields. I've logged an issue with that project. Will leave this open until it is resolved and integrated into the emulator.

**Comment by danmarshall** [comment]
@BrodaUa thanks for the report. Meanwhile, can you use the 'title' field for your items instead of 'subtitle', just to get your receipt working?

**Comment by BrodaUa** [comment]
@danmarshall the 'title' field working fine, but still 'subtitle' and 'text' does not working. The 'text' is the most important in this case....

**Comment by eanders-MS** [comment]
Referencing PR https://github.com/Microsoft/BotFramework-WebChat/pull/286, which contains Receipt Card rendering fixes. Will be included in the next emulator release.

**Comment by eanders-MS** [comment]
A new emulator build is available (v3.5.25) utilizing the latest WebChat control. Please give it a try and let us know if the new Receipt Card rendering doesn't suit your needs.
