### ISSUE TITLE
Markdowns not working after latest update v3.5.36

### ISSUE THREAD

**Issue by keshavnagpal** [Microsoft/BotFramework-Emulator#480]
Hi,
After the latest update, the markdowns are not working in the emulator. Instead of getting **Bold** , I'm getting ** Bold ** etc.

In the webChat of Azure Portal, they are still working fine.

**Comment by eanders-MS** [comment]
@compulim Can you take a look?

**Comment by Srinath-Sadda** [comment]
Verified. v3.5.36 not honoring Markdown syntax anymore.

**Comment by Amintasn** [comment]
+1 
I've also getting issues with adaptive cards.  
Not sure if it's an emulator issue, Bot framework 3.15 or both

**Comment by keshavnagpal** [comment]
@Amintasn I think it's the emulator issue. I'm currently using v3.5.35 for testing and markdowns are working fine on it. And same project when accessed through v3.5.36 , markdowns don't work.

**Comment by Amintasn** [comment]
@keshavnagpal Thanks for the feedback. I've downloaded the v.3.5.35 to see how the bot would behave.  However, my emulator automatically updates it to v3.5.36 before I can start working. Do you know how I can prevent that? Thx

**Comment by JasonSowers** [comment]
Relates to https://github.com/Microsoft/BotFramework-WebChat/issues/972

**Comment by alexknipfer** [comment]
It's not working for me either on the newest version using adaptive cards. It's still working in prod though, therefore I would assume it's emulator related.

**Comment by compulim** [comment]
Will fix in Web Chat PR [#1034](https://github.com/Microsoft/Botframework-WebChat/pull/1034) by exposing Markdown-It engine bundled in Web Chat to `window.markdownit`, so Adaptive Cards 1.0 can use it.

**Comment by vishwacsena** [comment]
@compulim - what's the ETA for this fix in Emulator?

**Comment by compulim** [comment]
Checked today with @vishwacsena, Markdown is working in latest Emulator.

We are using [`markdown-it@8.3.1`](https://www.npmjs.com/package/markdown-it).

Easiest way to check if Markdown is working or not. Write this sentence, `My name is "bot"`. If you see the double-quote become smart quotes (curly double-quote, like `My name is “bot”`), the Markdown-It engine is running.
