### ISSUE TITLE
No response from Python SDK

### ISSUE THREAD

**Issue by Sakshams** [Microsoft/BotFramework-Emulator#484]
I am able to connect to Python SDK  bot ** https://github.com/Microsoft/botbuilder-python**
The bot is ran on localhost using python main.py as mentioned in SDK docs.
The emulator is able to connect to bot because the bot does receive the request but when the bot tries to send the response back on
http://localhost:56061/v3/conversations/08ee4db0-52ba-11e8-8711-a713da8c5c08%7Clivechat/activities ,   it fails with 401 unauthorized.
Exact log:
botbuilder.schema.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'

Emulator is set to default local settings, no app-id or key/password.

Emulator version :  4.0.15-alpha (4.0.15-alpha.33986)

**Comment by stevengum97** [comment]
Thank you for reporting! We're currently investigating this issue.

**Comment by stevengum97** [comment]
@Sakshams we have a fix for this issue and are planning on doing a new release tomorrow. Sorry for the inconvenience. In the mean time the v4 python bots are still able to work with the v3 emulator.

**Comment by stevengum97** [comment]
We've released version 4.0.0.a4 which fixes this issue. Please try out the new version and let us know if it doesn't work for you.

Links to PyPI:
https://pypi.org/project/botframework-connector/
https://pypi.org/project/botbuilder-core/
