### ISSUE TITLE
Emulator Preview doesn't show "trace LUIS"

### ISSUE THREAD

**Issue by NiteLordz** [Microsoft/BotFramework-Emulator#486]
I have configured the emulator to work with my bot both locally and remote.  I have also added in the LUIS service under the services section.  When I left click on the Luis service, it opens in the browser window to the correct application.

However, when i execute an utterance that requires LUIS, it does not display the trace luis log message.

I am not using a LUISDialog, i have my bot configured to handle the luis querying and parsing in my own code.

**Comment by stevengum97** [comment]
Which language and version SDK are you using right now? Also, if you're using custom calls to LUIS, then your bot is most likely not sending the trace activities that the SDKs send when they perform calls to LUIS or QnA Maker.

Can you provide an example of how you're calling LUIS?

**Comment by NiteLordz** [comment]
@stevengum97  That makes sense. No i am not doing any trace calls within the luis service. I wasn't sure if this was something the emulator was "hooking" into, or if it was the internal LUISDialog that enabled all of the extra features for LUIS to be trained on.

I will look into the LUISDialog source, and see what calls need to be made and what not.

Just to answer your questions, i am using Builder SDK 3.15.2.2 and C#.

Thanks much.

**Comment by stevengum97** [comment]
No problem! If you want to examine the code that has these new trace activities in the v3 SDK, you can find them on commit [558f1fa](https://github.com/Microsoft/BotBuilder/commit/558f1f5a154f7a4d1f0832d70dce485f70c0a8fb). 

If you're curious about the v4 implementation, you can find it on these two PRs: [#380](https://github.com/Microsoft/botbuilder-dotnet/pull/380) and [#422](https://github.com/Microsoft/botbuilder-dotnet/pull/422).

Closing issue.
