### ISSUE TITLE
Emulator works fine for c# bots, but not for Node bots

### ISSUE THREAD

**Issue by cwhd** [Microsoft/BotFramework-Emulator#488]
For some reason when you test a bot in c# in the emulator everything works great.  However when you test a bot written in Node you can connect to the bot, but the bot never responds to the conversation.  I've gone into settings and checked bypass ngrok for local addresses, the bot works great when I publish it to Azure, so I'm not sure what the problem is since there is no error message.  Any ideas?

**Comment by JasonSowers** [comment]
Which version of the emulator is this occurring in?

**Comment by nodeomega** [comment]
What storage are you using for the nodejs bot?

**Comment by cwhd** [comment]
Emulator version 3.5.36
I created the bot in the portal and downloaded the code from there.  However this seems to happen with any bot written in Node running from VS 2017 (version 15.7.1)
Here is the code for the storage setting:
var azureTableClient = new botbuilder_azure.AzureTableClient(tableName, process.env['AzureWebJobsStorage']);
var tableStorage = new botbuilder_azure.AzureBotStorage({ gzipData: false }, azureTableClient);

**Comment by cwhd** [comment]
I'm not sure what changed, but suddenly things started working.  Strange, I'll close the issue.  Thanks!

**Comment by cwhd** [comment]
Just a comment that this started happening again, but it seems https://github.com/Microsoft/BotFramework-Emulator/issues/285 is the same problem so I'm adding info there.

**Comment by cwhd** [comment]
Even though this is a duplicate I'm going to leave this open until a solution is found.

**Comment by angadp** [comment]
I'm also getting the same issue. Did you get any solution yet?

**Comment by cwhitten** [comment]
Try setting `process.env.AzureWebJobsStorage`. See https://github.com/Microsoft/BotFramework-Emulator/issues/285 for more context.
