### ISSUE TITLE
Any plans for headless execution?

### ISSUE THREAD

**Issue by etiago** [Microsoft/BotFramework-Emulator#49]
Hi,

We're doing something a bit more serious with the BotFramework and we're now starting to write SpecFlow tests to perform behavior-driven testing of the bot functionality. Since we would like to run these tests locally without having a dependency on the Bot Connector service, we thought it would be nice to use the emulator's backend as the supporting backend. However, what we found is that the server code is coupled with the client's Electron GUI code. What we'd like to have is a way to run it headless, meaning, a way to run just the server-side without the GUI (to integrate in a build/test pipeline).

Is this something that is coming up soon?

Thanks!

**Comment by eanders-MS** [comment]
Hi @etiago. Yes, a headless mode is on our roadmap. We still have some planning and designing to do before we can say how and when it will be done, but we've had multiple requests for this from users. The rough idea is we'd provide the headless emulator as an npm package. The emulator electron app would take a dependency on this package, adding the UI.

**Comment by etiago** [comment]
Awesome :wink: for now we butchered it ourselves to decouple Electron out of the client/server communication, but we've already noticed that this our changes (made a while back), break with the latest commits. Good to know that you have it on your roadmap at least 👍
