### ISSUE TITLE
Implement theming support (Light / Dark)

### ISSUE THREAD

**Issue by tonyanziano** [Microsoft/BotFramework-Emulator#496]
Need to add theming support to the app and some components

Ex.

Checkbox component on current modal dialogs (light theme) does not work on the dark theme app settings page and needs to have text color overridden.

**Comment by vishwacsena** [comment]
1. we will support light, dark and high contrast theme
2. light weight affordance to select a theme.

**Comment by mewa1024** [comment]
Colors for light and dark themes on Zeplin: [https://zpl.io/be48JRz]
Common controls showing light and dark themes: [https://app.zeplin.io/project/5ac7a7e12d8fbf0a240769db?seid=5ace6cd0ed7ba59a38f8296a](url)

**Comment by mewa1024** [comment]
Updated colors to have border and outline colors for high contrast theme: [https://zpl.io/be48JRz](url)
Added high contrast version of nav bar controls: [https://zpl.io/bLOjZjG](url)

**Comment by justinwilaby** [comment]
#679  fixes this issue
