### ISSUE TITLE
Transcript explorer performance issue

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#497]
Opening a folder with many files locks up the whole application

**Comment by emadelwany** [comment]
@hailiu2586 can you please take a look at this one?

**Comment by jwood803** [comment]
I believe I'm seeing this as well. As soon as I open up the emulator it will randomly freeze and when monitoring the CPU I haven't seen it go below 15% and have seen it stay within the 30s.

![image](https://user-images.githubusercontent.com/1578160/41602295-81aa2d78-73a8-11e8-8f31-dc1252cadd69.png)

**Comment by nk111** [comment]
Why not just make the directory nodes lazy load subdirs on click only? In my case it was running over an hour to scan all the subdirs and was still not ready.

**Comment by vishwacsena** [comment]
This has been addressed in the latest emulator release. https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.0.0-preview.40025
