### ISSUE TITLE
Suggestion: configurable default user data

### ISSUE THREAD

**Issue by cesarvarela** [Microsoft/BotFramework-Emulator#50]
Right now I only need to change the default user id, but I guess it could be useful (not sure is easy or even possible), to emulate different channel ids, and similar stuff.

**Comment by eanders-MS** [comment]
Hi @cesarvarela, This is a planned feature. We have an improved bot connection UI in the works that allows for editing of the user list (both name and id). In the meantime, it is possible to edit this value directly in the server.json of the app. The location of this file is depends on your platform. On Windows, it is located below `%APPDATA%\botframework-emulator`
