### ISSUE TITLE
Migrate v3 endpoints to v4 bots

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#505]

**Comment by emadelwany** [comment]
Needs a spec

**Comment by vishwacsena** [comment]
[Spec](https://raw.githubusercontent.com/wiki/Microsoft/BotFramework-Emulator/content/Specs/v3-to-v4-migration.md)

**Comment by mewa1024** [comment]
@vishwacsena For this part of the spec in bold:
On V4 first launch, present Emulator V4 overview doc page that includes
        - Walkthrough of new features in the V4 Emulator
        - Provide an overview of the .bot files that were automatically created and ### **how developers can consolidate the endpoints into meaningful bot file structure**

Users need to be able to move their .bot files and not break the MRU. Can we move files through the UI?

**Comment by sgellock** [comment]
we need V3 emulator packages built so we can set SxS

**Comment by mewa1024** [comment]
@tonyanziano Comps of the entire flow are on Invision here: [https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15122715](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15122715)

Sorry--I thought I'd linked to them earlier. I opened a new ticket to add the context menus to the Welcome page: #986

**Comment by tonyanziano** [comment]
Improved by #1020 #1021
