### ISSUE TITLE
LUIS and QnA Inspectors responsive behavior

### ISSUE THREAD

**Issue by emadelwany** [microsoft/BotFramework-Emulator#518]

**Comment by compulim** [comment]
Some nice ideas:
* An always-on-top counter to show "number of Redux-connected components"
* A counter to show "number of Redux actions per seconds (or in the last minute)"

(We can open source them as a separate package too)

**Comment by mewa1024** [comment]
This seems to affect the LUIS and QnA inspectors most. The other UI seems to follow common app patterns: As window width changes, nav pane width stays fixed and webchat stays fixed while inspector panes reflows until it hits a mininum width. At that point horizonal scroll bar appears. Comps for inspector panes to come.

**Comment by tonyanziano** [comment]
I'm not sure if UI polish falls into this category or if we should create a new item, but there are a few un-themed areas that need to be fixed so I will consolidate them here:

- File explorer items are always darkly colored
- Drag states on tabs / dragging over the content area to split tabs to other editor screens is darkly colored
- The scrollbar that we use is lightly colored and is barely visible in the light theme

**Comment by vishwacsena** [comment]
@mewa1024 can you please break this down into individual issues for responsiveness that we need to track and close this?

**Comment by mewa1024** [comment]
![responsive-widths](https://user-images.githubusercontent.com/39317542/43602136-ea5bd3ae-9643-11e8-9702-2e07618c865f.png)

**Comment by vishwacsena** [comment]
@tonyanziano - can you take a look at this and comment if you are able to address this in 8-B? Assigning this to you.
