### ISSUE TITLE
Show a warning if the user deletes the /api/messages portion of the endpoint in the bot config

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#532]

**Comment by vishwacsena** [comment]
Flow this through notifications

**Comment by mewa1024** [comment]
@vishwacsena @tonyanziano Can we do this with a validation error in the modals where the endpoint field appears?

**Comment by tonyanziano** [comment]
@mewa1024 yes we can do that

**Comment by tonyanziano** [comment]
Addressed in #733
