### ISSUE TITLE
Can't upload picture of large size

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#533]
Works fine with images less than 2Mb. The large one I used to test was 3.15Mb (I attached this picture here) and it failed to upload.

**Comment by compulim** [comment]
I think it is related to Restify `bodyParser` plugin, see [`options`](http://restify.com/docs/plugins-api/#bodyparser)`.maxFieldsSize`, currently set to `2 * 1024 * 1024` (2 MB).

**Comment by compulim** [comment]
Tried to upload a > 100 MB video and I can retrieve it from the emulator attachments controller, e.g. [http://localhost:50491/v3/attachments/582b2100-6de5-11e8-817b-316de62c1ab9/views/original](http://localhost:50491/v3/attachments/582b2100-6de5-11e8-817b-316de62c1ab9/views/original). So I think it's not repro now.
