### ISSUE TITLE
Expose Direct Line endpoint

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-Emulator#54]
Many folks want to run WebChat against a bot running locally. It would be extremely convenient if the Emulator could expose its Direct Line connector to any clients. As a stretch goal, it would be great to extract out said connector as an independent project that can be run by itself as "headless" emulator.

**Comment by billba** [comment]
This idea is being discussed at increasing length over at https://github.com/Microsoft/BotFramework-WebChat/issues/243

**Comment by forensicsguy20012004** [comment]
has there been any movement on this?

**Comment by eanders-MS** [comment]
@forensicsguy20012004 This feature is not on the Emulator roadmap currently. It would be good if you could provide information about your scenario.

**Comment by ChrisMiskowiec** [comment]
@eanders-MS We have a web application which calls a bot using Direct Line. Currently our team cannot do local development along the full chain, because the direct line client calls out to the Bot Connector. It would be very helpful to have a way for the direct line client call to a local bot, via the emulator or some other endpoint, so that we can have our local web app call to our local bot.

**Comment by gareththackeray** [comment]
@ChrisMiskowiec I'm using the Emulator in exactly this way.  If I'm understanding you right you just need to:

- connect to your locally-hosted bot in the emulator by entering a localhost URL
- see what port the emulator is listening on from the hosted log
- make directline calls to http://localhost:<emulator port>

There are issues open to make the port configurable from the command line; I've done this in a hacky way in my fork at https://github.com/gareththackeray/BotFramework-Emulator

**Comment by SomaSharathSurya** [comment]
Hi @gareththackeray ,

                      Can you please explain how to make direct line calls to  http://localhost: . Can we hit it in postman if so what are the request formats ?

Please help ! Thanks in advance .

**Comment by gareththackeray** [comment]
@SomaSharathSurya I just updated my comment to show the emulator port should go after the :

The api reference is here https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-api-reference

**Comment by csalexwilliams** [comment]
Just a quick follow-up per all of the above comments.

Will this particular item ever be added to the official roadmap? It's a pretty crucial piece of functionality for individuals who use the DirectLineAPI as their primary pathway for bot communication.

**Comment by billba** [comment]
Here is a helpful workaround: https://www.npmjs.com/package/offline-directline

**Comment by cwhitten** [comment]
Closing, no plans to implement.
