### ISSUE TITLE
Can any one explain what is a server and client inside the src path of the emulator code.

### ISSUE THREAD

**Issue by siddiq-rehman** [Microsoft/BotFramework-Emulator#55]

**Comment by eanders-MS** [comment]
The emulator is an Electron application (http://electron.atom.io/). The Electron architecture is multi-process: a Node.js "main" process, and a Chromium "renderer" process. The code in the src/server folder runs in Electron's main process. The code in the src/client folder runs in Electron's renderer process.

Here's a quick overview of the Electron architecture: https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md

**Comment by eanders-MS** [comment]
Closing this issue now. @siddiq-rehman if you have further questions I'm happy to go into more detail with you.
