### ISSUE TITLE
Show a modal dialog when transcript file(s) have been refreshed on disk

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#557]
We need to decide what this looks like and how it behaves when multiple files in different folders change (e.g. on branch switch)

**Comment by compulim** [comment]
## VSCode

### Unmodified file

1. Open the file
2. Make sure it is unchanged
3. Switch to another app to modify the file
4. Switch back to VSCode

The file will automatically get refreshed.

### Modified file

1. Open the file
2. Change a line, but not saving it
3. Switch to another app to modify the file
4. Switch back to VSCode

The file will not automatically refreshed. When you press "Save", VSCode will complain (show up a modal). And then you can select to show a diff viewer.

**Comment by tonyanziano** [comment]
Addressed in #660
