### ISSUE TITLE
Menubar should match wireframes

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#562]

**Comment by vishwacsena** [comment]
@mewa1024 can you please break this into actual list of issues and close this?

**Comment by mewa1024** [comment]
Changed title since this applies to Windows, Mac, and Linux. Windows menubar is on Invision: https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/315600750/preview

Mac version TK.

**Comment by vishwacsena** [comment]
Current implementation matches this specification.
