### ISSUE TITLE
Support Transcript playback

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#567]

**Comment by emadelwany** [comment]
@vishwacsena this needs a spec

**Comment by mewa1024** [comment]
Does this issue refer to stepping through each message of the transcript or to sending the user messages of the transcript to a live bot?

**Comment by tonyanziano** [comment]
@mewa1024 I believe we tagged @vishwacsena on the issue to add clarification for exactly that.

I think this might encompass both of those flows.

**Comment by cwhitten** [comment]
See #598 for progress on transcript playback
