### ISSUE TITLE
Add back support for adding services via login UI (vs modal)

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#569]

**Comment by emadelwany** [comment]
Get more clarity and break this into more items as part of one user story

**Comment by vishwacsena** [comment]
1. Azure login
2. Get keys from ARM token
3. Select KB/ Model to add to .bot file.

**Comment by vishwacsena** [comment]
@mewa1024 I believe as long as we support fall back UX to be able to add an app by ID we should be fine here. The login experience will show everything that you have access to; but otherwise you can add by explicit ID.
