### ISSUE TITLE
No "Callback URL" in Settings (OSX)

### ISSUE THREAD

**Issue by toyg** [Microsoft/BotFramework-Emulator#57]
The wiki says:

> If you prefer to use alternate tunneling software, you may configure a custom `Callback URL` in the emulator's App Settings dialog.

There is no such option in OSX (emulator version 3.5.23).

(Can I also respectfully suggest: next time you need to integrate this sort of utility software, pick something that is *really* free, not freemium stuff like ngrok. It makes everyone's life easier.)

**Comment by eanders-MS** [comment]
@toyg Apologies and thank you for reporting this. Our documentation is out of date. We removed this setting a few versions back. It was a source of confusion for many users. Do you have need for this setting?

**Comment by toyg** [comment]
I worked around it by creating a second bot for testing purposes, which is a more realistic scenario overall although it's a bit cumbersome having to create many different bots for a single team.

As long as you remove that bit from docs, I'm fine to close this.

**Comment by eanders-MS** [comment]
Ok, great. I've updated the wiki page to remove the reference. Closing this issue now.
