### ISSUE TITLE
Bot Configuration + Services provide hyperlinks/pointers to where the user can find information

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#573]
Not major but we can make usability a little easier.

When creating a Bot we have Endpoint URL as required (*). I'd suggest providing a little hint that it should have a suffix of /api/messages to avoid confusion.

![image](https://user-images.githubusercontent.com/33519520/40175332-ab214c9c-59cf-11e8-8891-812917e2baf1.png)

Same for Connect to Azure Bot Service - took me a while to find my azure tenant ID (subscriptionID is fairly easy on the Az Portal). az CLI helps here - perhaps a hyperlink to a documentation page or point to az cli to make it easy (in time lookup inside the emulator would be nice)

![image](https://user-images.githubusercontent.com/33519520/40175172-32f1b9dc-59cf-11e8-88cd-83f7f9cc60c0.png)

Same for Dispatch and LUIS. not everyone knows authoring key == LUIS authoring key and where to find it:

![image](https://user-images.githubusercontent.com/33519520/40175282-877ef370-59cf-11e8-9e33-745fa064f208.png)

QnA: perhaps provide an example of a host name ?

![image](https://user-images.githubusercontent.com/33519520/40175317-a078d666-59cf-11e8-9295-b5f127714fcb.png)

**Comment by emadelwany** [comment]
We won't need this after we implement #569
