### ISSUE TITLE
UX consolidation: Services .vs. file explorer .vs. live chat - rationalize

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#592]

**Comment by mewa1024** [comment]
This needs to take into consideration the Ibiza nav we discussed 7.30. (Note to self)

**Comment by mewa1024** [comment]
New designs with "Bot Components" and "Script" panes: [https://microsoft-fuse-design.invisionapp.com/d/#/projects/prototypes/15012340](url)

**Comment by vishwacsena** [comment]
This should include adding links to the panel to point to other cognitive services that are useful when building a bot.

**Comment by mewa1024** [comment]
@justinwilaby For any of the individual services, please change the first right-click menu from "Open in web portal" to "Manage service": 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/39317542/44737634-6674ef80-aaa7-11e8-865f-d26c07dfa941.png">
