### ISSUE TITLE
Ability to open a .chat file and convert to transcript file within emulator

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#597]

**Comment by emadelwany** [comment]
We also want to be able to detect changes to the imported chat file, so that a conversation design can update the chat file, and see the changes reflected directly in the emulator.

**Comment by emadelwany** [comment]
@tomlm - this is the feature you requested.
@vishwacsena  - FYI I pulled this to 6B as we want to run some usability studies using it.

**Comment by vishwacsena** [comment]
File explorer shows .chat and .transcript files
Automatically convert .chat to .transcript (in memory) and render

Design: How do we notify on errors with conversion/ rendering?

**Comment by tonyanziano** [comment]
Addressed in #660
