### ISSUE TITLE
Integrate channel inspector capabilities to Emulator (emulate channel)

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Emulator#599]

**Comment by scheyal** [comment]
This has come up again. The emulator should emulate the e2e user experience so that developers don't have to deploy (late in cycle) to discover incompatibilities. Add ability to switch to corresponding "native" client controls (Teams, facebook msgr, etc).

**Comment by cwhitten** [comment]
There are no plans to introduce mirrored client/channel experiences built-in to the BF Emulator. 

To provide a view on external (non DirectLine/WebChat) UX, we have the following guidance:

1. Use the [Bot Inspector](https://github.com/microsoft/BotFramework-Emulator/blob/master/content/CHANNELS.md)
2. Use in-proc channel protocol adapters

Closing as wont-fix for now.
