### ISSUE TITLE
Any way to clear a cache under heavy testing

### ISSUE THREAD

**Issue by davidlfox** [Microsoft/BotFramework-Emulator#60]
Use case: when doing a lot of heavy integration testing over long periods, the emulator slows down a lot. I need to keep the same conversation going, so I don't think closing the emulator is an option unless I can copy the conversation id and paste it after restarting. 

Clearing the log pane doesn't seem to help.

**Comment by danmarshall** [comment]
Thanks for reporting this David, can you give us an idea of the size and type of loads you are using?

**Comment by danmarshall** [comment]
@billba @reyesrico these load scenarios may be of interest to you.

**Comment by billba** [comment]
@davidlfox can you say more about what specifically becomes slow?

**Comment by davidlfox** [comment]
@billba @danmarshall I built a [chat game](https://github.com/davidlfox/DrugBot) that requires a lot of interaction e.g. buying, selling, traveling, etc. I'm mostly sending hero cards with 5-7 buttons or just a simple text response. I guess i first notice the slowness around the 40th or 50th command (maybe two dozen hero cards have been sent at this point and about the same plain text responses,) and it continues to degrade from there. 10%+ CPU usage, delayed response to typing, etc. I'll concede that it's in a Parallels VM, but none of the other Windows applications display any sluggishness. After 100 or so commands, it's incredibly slow.

**Comment by billba** [comment]
I made a number of perf improvements lately, will you let me know if things are better?

**Comment by eanders-MS** [comment]
We're planning to release an update this Thursday.

**Comment by davidlfox** [comment]
@billba @eanders-MS built from source and used emulator tonight for a few hours. feeling a little quicker. it felt smooth-ish til ~100 commands, then it was slowing down. After 200 or so, it still wasn't as slow as before.

**Comment by billba** [comment]
I'm not sure that's using the latest WebChat build. @eanders-MS?

**Comment by eanders-MS** [comment]
@davidlfox @billba That's correct. The emulator pins to a specific commit of the webchat control. I am planning to update it to the latest version today.

**Comment by eanders-MS** [comment]
@billba I think I need to wait for the npm before I can update the emulator to the latest webchat. I'm having issues building the control in-place from the node_modules folder. Specifically, the build is picking up some unwanted .d.ts types from the Emulator's @types folder higher up the hierarchy. When do you think the npm package will be published?

**Comment by eanders-MS** [comment]
@davidlfox I've updated the emulator to use the latest webchat. Would you care to pull latest and try your performance testing again?

**Comment by eanders-MS** [comment]
A new emulator build is available (v3.5.25) containing the latest WebChat control. Please give it a try and let us know if performance has not improved.

**Comment by infact** [comment]
I am using bot emulator version 4.4.0 .  The bot emulator session is not getting cleared. 
I verify my chat bot on my emulator, then closed my emulator. Made some code changes, restarted my emulator again ,but still it is showing my previous session.
