### ISSUE TITLE
Microphone is not working in bot Emulator

### ISSUE THREAD

**Issue by gouravbeyondBGCM** [Microsoft/BotFramework-Emulator#606]
my microphone is not working in bot emulator 

I have registered it , and also have given AppID and password . but microphone doesnt work 

need your input

**Comment by JasonSowers** [comment]
Which version of the emulator are you using?

**Comment by gouravbeyondBGCM** [comment]
3.5.35

**Comment by gouravbeyondBGCM** [comment]
I think 3.5.36 is the latest version and others are in alpha version , do you think it is something to do with version of emulator , please suggest .

**Comment by gouravbeyondBGCM** [comment]
hi 
any input possible on this query ...?

**Comment by gouravbeyondBGCM** [comment]
@eanders-MS can you please give  your inputs here

**Comment by tonyanziano** [comment]
@compulim Any ideas?

Also, @gouravbeyondBGCM , please refrain from commenting multiple times in a row for visibility. You can edit your original comment if you need to add more information.

Thanks.

**Comment by compulim** [comment]
v3: need investigate
v4: need a fix

Will do it.

**Comment by DeniseMak** [comment]
FYI, I had no issue with speech in 3.5.36, but had the same issue in the V4 emulator.

**Comment by compulim** [comment]
@tonyanziano @justinwilaby @emadelwany @vishwacsena 

Despite the bug, currently, I think speech is flighted: flighted bot will be able to use our key for a short period of time, please correct me if I am wrong.

Do you think we should provide a dialog so you can bring your Cognitive Service key or a switch to change the speech recognition engine to WebSpeech (browser speech)?

**Comment by compulim** [comment]
Verified speech recognition and synthesis is working in v4. But I cheated by putting my own Bing Speech key in (skipping token exchange part, which requires a flighted bot, etc).

v3: need investigate
v4: need to verify speech token exchange is good

**Comment by vishwacsena** [comment]
@compulim please feel free to pull in Khuram/ Dan for the token exchange issue.
