### ISSUE TITLE
Emulator UI

### ISSUE THREAD

**Issue by Zhashkha** [Microsoft/BotFramework-Emulator#607]
Hi guys,

now after I've updated to the latest version, next issue appeared: when I enter some text, emulator stays on the same level, it doesn't move down to show me response from bot, as it naturally should do. Thanks in advance.

**Comment by tonyanziano** [comment]
Hey @Zhashkha ,

Could you please let us know what version you are on by navigating to the application menu at the top of the Emulator, opening the `Help` section, and then clicking `About`.

It would also be helpful if you could post some screenshots of before and after you send a message, or tell us what you are seeing in the Log Panel. Thanks.

**Comment by Zhashkha** [comment]
Hi Tony,

thanks for reply. The version is 3.5.36
http://prntscr.com/jmnfys

here are the screenshots:

initial state:
https://prnt.sc/jmnjpp

after click:
https://prnt.sc/jmnk3a

as it should be, after I scrolled it down:
https://prnt.sc/jmnkwt

sorry messages are in Georgian :)

tell me if you need more info. Thanks in advance

**Comment by tonyanziano** [comment]
I see. So the response is coming through the webchat control, but it is not automatically scrolling the content to make the response visible in the control. Is that correct?

**Comment by Zhashkha** [comment]
Yes, that's correct !
