### ISSUE TITLE
Https on Localhost connection issues

### ISSUE THREAD

**Issue by ladeak** [microsoft/BotFramework-Emulator#608]
Cannot connect to https service running on localhost with version 3.5.36. This used to work fine in previous releases.
I cannot see much on the logs, it seems my service is  not even hit (service works fine with Postman requests).
When I switch back to http with localhost, it just works fine.

![image](https://user-images.githubusercontent.com/10052368/40555634-08a68190-604a-11e8-987e-11ded4af55c3.png)

**Comment by nodeomega** [comment]
As I'm not seeing a port number in your URL, I am assuming that you are running this via local IIS?  Or are you setting your port number to 80 some other way?

Also which SDK are you using?

**Comment by ladeak** [comment]
I am using port 443, but when tested on different port I see the same issue.
Using the latest SDK 3.15.2.2 bit I experienced it before updating the  nuget packages from 3.15.0 as well.

Using the external IP or dns name of the same service instance same port works fine.

As far as I remember iso

**Comment by nodeomega** [comment]
Do you have localhost mapped to anything else in your hosts file?

**Comment by ladeak** [comment]
Not sure which hosts file I shall check that, but I have not changed any hosts files recently. Note, it works with http and localhost.

**Comment by nodeomega** [comment]
@emadelwany is there a workaround for this, since this has been tagged as a bug?

**Comment by nodeomega** [comment]
@emadelwany double-checking on this one, as it was tagged a bug.  Can you advise a workaround or is this a wont-fix?

**Comment by tonyanziano** [comment]
This was addressed in #1779
