### ISSUE TITLE
Link to Dispatch service doesn't work (v4)

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/BotFramework-Emulator#611]
https://github.com/Microsoft/BotFramework-Emulator/blob/1da9ab269d79723e3baefbd441a2eb24a1c3662e/packages/app/client/src/ui/shell/explorer/dispatchExplorer/dispatchEditor/dispatchEditor.tsx#L57

https://github.com/Microsoft/BotFramework-Emulator/blob/1da9ab269d79723e3baefbd441a2eb24a1c3662e/packages/app/client/src/data/sagas/dispatchSagas.ts#L51

When using the beta version of the emulator (v4) I noticed that there is a link to dispatch.ai, which doesn't look like a Microsoft domain. (yet?). Is this something that is in the works or is this a mistake? At the moment it is confusing.

**Comment by iMicknl** [comment]
Okay, thanks for your quick reply. Linking to a placeholder which is another company is maybe not something we should do? I guess we can come up with another placeholder link that isn't in use by an active company.

Should I close this issue for know? Or do you want to keep it open for tracking purposes. 👍

**Comment by tonyanziano** [comment]
I agree with you, and think we should change the link. We can keep it open until that work is done. Thanks for your feedback. 👍

**Comment by tonyanziano** [comment]
Addressed in #640

**Comment by iMicknl** [comment]
@tonyanziano thanks! Dispatch.ai is also still visible in the `detailedDescription` as described in this issue. Maybe also change it there for a placeholder?

**Comment by tonyanziano** [comment]
@iMicknl Oh right! Good catch. I'll change that. 👍
