### ISSUE TITLE
UI needed to edit bot list (bots.json)

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#619]

**Comment by vishwacsena** [comment]
Let's do the clear part for my bots MRU

**Comment by tonyanziano** [comment]
Confirmation prompt has been added. Just need final UI design.

**Comment by mewa1024** [comment]
@tonyanziano Let's follow the VS Code pattern: show remove button on hover, use the X (same as the file tab X) as the icon:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/39317542/44073746-4a9a353a-9f4a-11e8-90b8-a67ff74ca960.png">

**Comment by tonyanziano** [comment]
Sounds good, will do. 👍

**Comment by tonyanziano** [comment]
Addressed in #767
