### ISSUE TITLE
Problem with Bot Framework Emulator

### ISSUE THREAD

**Issue by andrzejsobczak** [Microsoft/BotFramework-Emulator#62]
Hi All,

I generate very simple bot (using C# template which I downloaded from http://aka.ms/bf-bc-vstemplate), but I'm having issues trying to get the emulator recognize my bot (I use 3.5.23 version of emulator).
Log from emulator:
[20:42:11] Emulator listening on http://[::]:16188 
[20:42:16] -> POST Refresh access token failed with status code: 400 
[20:42:25] -> POST Refresh access token failed with status code: 400 
[20:42:27] -> POST Refresh access token failed with status code: 400 

Any idea what’s wrong?

**Comment by eanders-MS** [comment]
Hi @andrzejsobczak, sorry you're having this problem. Can you please check your system clock date and time. The authentication scheme we use requires the timestamp be accurate within 5 minutes.

**Comment by andrzejsobczak** [comment]
Hi Eric,

Many thanks for quick replay, but I'm afraid that my system clock date and time is OK.
Please see screenshot.
![screen_2](https://cloud.githubusercontent.com/assets/24848210/21744818/afdeae56-d51d-11e6-8ed4-993e36900c75.png)

Any other ideas?

Best Regards,
Andrzej

**Comment by eanders-MS** [comment]
Ok. Just to double-check another way, does the time on your computer match the time on your phone?

**Comment by eanders-MS** [comment]
Assuming they do match, the next thing to check is your bot's appId and password. Is your bot configured with an appId and password? Here's an auth troubleshooting guide that you might find helpful:
https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by andrzejsobczak** [comment]
Hi Eric,

1. It's amazing your Time2Respond. Many thanks for your involvement.

2. Time at my phone is the same as on my computer.

3. Yes, my bot configured with an appId and password (please see screenshot). But I checked 3-times correctness of them during type them on emulator. 

![error](https://cloud.githubusercontent.com/assets/24848210/21745315/4ce7d5be-d529-11e6-9d2f-743c409c290c.png)

4. Blank appId and password in code [Web.config] = diffrent type of log error:
[22:31:55] -> POST 401 [conversationUpdate] 
[22:31:55] Error: The bot's MSA appId or passsword is incorrect. 
[22:31:55] Click here to edit your bot's MSA info. 

Any other ideas?

Best Regards,
Andrzej

**Comment by abhishan** [comment]
@andrzejsobczak ,
Instead of downloading the template, please check by using the following nuget package:
https://www.nuget.org/packages/Microsoft.Bot.Builder/
See this thread for more details:
https://github.com/Microsoft/BotFramework-Emulator/issues/51

**Comment by eanders-MS** [comment]
@andrzejsobczak When trying to connect without MSA, please make sure you've cleared out the appId and password from the bot's configuration in the emulator, in addition to removing them from the bot's web.config. I'm referring to these fields:
![image](https://cloud.githubusercontent.com/assets/12176807/21776560/088d9ff2-d650-11e6-9409-d527c7d18671.png)

Please make sure those two fields are empty before connecting.

**Comment by andrzejsobczak** [comment]
Hi Abhishek,

Many thanks for our information.

I have one question: before I import Microsoft.Bot.Builder (using Package Manager Console at my Visual Studio) should I create an empty Project Template for C#? Or in other words: should I open any project at VS before I import Microsoft.Bot.Builder ?

Best Regards,
Andrzej

**Comment by Kothakapu** [comment]
@andrzejsobczak 

Create an empty project with Bot template(or use existing bot project) and update the bot builder version from Visual studio NuGet package to latest version. Try to test it with latest bot emulator (https://docs.botframework.com/en-us/tools/bot-framework-emulator/)

**Comment by andrzejsobczak** [comment]
@abhishan many thanks for your help. It works now.
I will close  this issue.

**Comment by andrzejsobczak** [comment]
@Kothakapu many thanks for your help. It works now.
I will close  this issue.
