### ISSUE TITLE
 Settings page should have UI for keys instead of secrets

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#620]

**Comment by mewa1024** [comment]
Hmm. This might move to the components overflow menu.

**Comment by vishwacsena** [comment]
@mewa1024 - what's missing right now? any update here?

**Comment by mewa1024** [comment]
@vishwacsena From the new Bot Explorer design, all the service configurations can be changed from right-click menus, but we don't have a way to change the bot name or secret.

**Comment by mewa1024** [comment]
@vishwacsena Just want to check that this is the flow:

1. User selects "New bot configuration"
2. "New bot configuration" modal opens, with these fields and checkbox:
        - Bot name *
        - Endpoint URL *
        - Microsoft App ID (optional)
        - Microsoft App password (optional)
        - Encrypt your keys [checkbox]
3. User check "Encrypt your keys".
4. "Key" text field appears with a link to the side to show/hide key:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/39317542/44368140-bb50ae80-a486-11e8-863b-8a0f4530c5d7.png">

Questions:
- Does the user need to fill out the name and endpoint before checking "Encrypt your keys"?
- Does generating a key <1.5 seconds? If not, we'll need a progress indicator.
- Do we need a modal to warn people when they turn off encryption?

**Comment by vishwacsena** [comment]
Thanks Melanie. Responses to questions - No; No; No. 

When opening a bot file, if it is encrypted, we should prompt for secret. If invalid secret, we should let users know and prompt again for secret w/ option to abandon and possibly a link to learn about how to reset the secret - this link could just be a doc topic in the emulator github. 

In the bot settings, we should provide a way for users to view the secret as well as generate a new secret.

**Comment by mewa1024** [comment]
@vishwacsena Can we close this issue since it's now tracked in #770 ?

**Comment by vishwacsena** [comment]
Closed.
