### ISSUE TITLE
Can't launch the emulator with macOS 10.13.2 

### ISSUE THREAD

**Issue by kirinrin** [Microsoft/BotFramework-Emulator#624]
Process:               Bot Framework Emulator [2867]
Path:                  /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
Identifier:            F3C061A6-FE81-4548-82ED-C1171D9856BB
Version:               4.0.15-alpha (4.0.15-alpha.33986)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bot Framework Emulator [2867]
User ID:               501

Date/Time:             2018-06-01 01:28:30.183 +0800
OS Version:            Mac OS X 10.13.2 (17C205)
Report Version:        12
Anonymous UUID:        A6256218-6B9B-5738-1732-49E1BBDF4CE0

Time Awake Since Boot: 3900 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
  Reason: no suitable image found.  Did find:
	/Applications/Bot Framework Emulator.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Bot Framework Emulator.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x108792000 -        0x108792ff7 +F3C061A6-FE81-4548-82ED-C1171D9856BB (4.0.15-alpha - 4.0.15-alpha.33986) <5AC448E8-732C-3E93-8EE4-4B8DEEC0D3C4> /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
       0x117625000 -        0x11766f98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld

Model: MacBookPro8,1, BootROM MBP81.004D.B00, 2 processors, Intel Core i7, 2.7 GHz, 16 GB, SMC 1.68f99
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142314737334248302D434B300020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142314737334248302D434B300020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.16.1a2)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: ST2000LM007-1R8174, 2 TB
Serial ATA Device: Samsung SSD 850 EVO 250GB, 250.06 GB
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: BUP Slim WH
USB Device: Hub
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1

**Comment by kbni** [comment]
The same occurs for me on 10.13.3 (Electron Framework unable to load)

```Process:               botframework-emulator [74289]
Path:                  /Users/USER/*/botframework-emulator.app/Contents/MacOS/botframework-emulator
Identifier:            botframework-emulator
Version:               3.5.36 (3.5.36)
Code Type:             X86-64 (Native)
Parent Process:        bash [70159]
Responsible:           botframework-emulator [74289]
User ID:               501

Date/Time:             2018-06-05 21:48:58.020 +1000
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Bridge OS Version:     3.0 (14Y661)
Anonymous UUID:        F437F82D-CB30-BD30-26CD-B97D6D4403F4

Sleep/Wake UUID:       A8DDC11A-B9F3-46AA-A508-F4CDAD1BB10F

Time Awake Since Boot: 150000 seconds
Time Since Wake:       4500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/*/botframework-emulator.app/Contents/MacOS/botframework-emulator
  Reason: no suitable image found.  Did find:
	/Users/kbni/projects/tools/emulator/botframework-emulator.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/kbni/projects/tools/emulator/botframework-emulator.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x101d20000 -        0x101d20ff7 +com.electron.botframework-emulator (3.5.36 - 3.5.36) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Users/USER/*/botframework-emulator.app/Contents/MacOS/botframework-emulator
       0x109011000 -        0x10905b98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
```

**Comment by penkin** [comment]
Having the same issue. Any resolution on this?

**Comment by michaelberkhahn** [comment]
Hi there,

i do get the same error when starting the app on mac os 10.13.x ... any update about what the root cause could be?

Thanks, Michael

**Comment by michaelberkhahn** [comment]
I found the issue in my situation: Was copying the app directly from server to my local machine ... something went wrong ... when creating an archive and copy/extract this to/on my local machine everything was working fine.

**Comment by sgellock** [comment]
thanks for the update @michaelberkhahn.  we'll consider the issue resolved.
