### ISSUE TITLE
Getting numbered list in PromptDialog.choice

### ISSUE THREAD

**Issue by gouravbeyondBGCM** [Microsoft/BotFramework-Emulator#625]
hi 

how can I have numbered list in PromptDialog.Choice in C# chat bot.

PromptStyle.PerLine, shows bulleted list like 
 
•	Item 1 
•	Item 2 
•	Item 3 
•	Item 4 

I need  as  
1.	Item 1 
2.	Item 2 
3.	Item 3 
4.	Item 4 

please suggest.

**Comment by stevkan** [comment]
Hi @gouravbeyondBGCM,

The ability to have a numbered list is not a supported feature at this time. However, as the BotBuilder SDK is open source, you are free to make changes to the code to meet your specific needs.

The following code is an example of a custom PromptStyler that generates ordered lists. This addition would live in the [PromptDialog.cs](https://github.com/Microsoft/BotBuilder/blob/4621a4c611889a6ebade4717329f8e6ea62f2f7f/CSharp/Library/Microsoft.Bot.Builder/Dialogs/PromptDialog.cs) file of the SDK.

As I believe this should solve your question I am going to close this issue. If you have further related questions, you can reopen.

Hope of help!
Steve.

```
[Serializable]
        public class OrderedListPromptStyler : PromptStyler
        {
            public override void Apply<T>(ref Message message, string prompt, IList<T> options)
            {
                var builder = new StringBuilder();
                var pos = 0;
                foreach (var elt in options)
                {
                    builder.Append($"{++pos}. {elt.ToString()}\n");
                }
                message.Text = $"{prompt}\n{builder.ToString()}";
            }
        }
```

**Comment by gouravbeyondBGCM** [comment]
hi 

I can see the file , but since its open source , how can I download the complete library code here to change the same , as you mentioned, please suggest .
