### ISSUE TITLE
Making LUIS response Intelligent 

### ISSUE THREAD

**Issue by gouravbeyondBGCM** [Microsoft/BotFramework-Emulator#632]
I have LUIS , which responds to query which answer is not available in its database in very dumb way - such that no data available .
how Can I make it say some intelligent things , such as **"there is no record available for your query , I have some other information matching for this are you interested ."**

LUIS doesnt hit to the default intent which we have designed for this case

**Comment by fanidamj** [comment]
You have to train you LUIS app with few examples in None intent and you have to include the following in your None method:

```
[LuisIntent("None")]
[LuisIntent("")]
public async Task None(IDialogContext context, LuisResult result)
{
    string message = $"There is no record available for your query, '{result.Query}'.";

    await context.PostAsync(message);

    context.Wait(this.MessageReceived);
 }
```
