### ISSUE TITLE
Refresh access token failed with status code: 400

### ISSUE THREAD

**Issue by sepulchered** [Microsoft/BotFramework-Emulator#64]
I was trying out code from getting started for node.js (https://docs.botframework.com/en-us/node/builder/overview/)
```javascript
const restify = require('restify');
const botBuilder = require('botbuilder');


let server = restify.createServer();
server.listen(3978, function () {
    console.log('%s listening to %s', server.name, server.url);
});

let connector = new botBuilder.ChatConnector({
    appId: '123',
    appPassword: '123'
});

let bot = new botBuilder.UniversalBot(connector, function (session) {
    session.send('You said: %s', session.message.text);
});

server.post('/api/messages', connector.listen())
```

node.js server is definitely running on the port 
![image](https://cloud.githubusercontent.com/assets/1381173/21947053/1ee00a2c-d9f4-11e6-95c6-31785eb3e673.png)

I tried to clean and reenter app id & app password several time - didn't help.
Time and date are properly set.

**Comment by dhanala89** [comment]
Hi Is there a solution to this?

**Comment by eanders-MS** [comment]
@dhanala89 Can you try it with no MSA appId or password on both sides (bot and emulator)?

**Comment by dhanala89** [comment]
Strange! That worked. So is the solution going forward?

**Comment by sepulchered** [comment]
@eanders-MS yep, it works. But question is: Is it a bug or expected behaviour?

**Comment by eanders-MS** [comment]
Hi @dhanala89 No this doesn't have to be the solution going forward, it should work with a valid appId/password pair. In your code snippet, you're using '123' and '123' as your appId and password. This isn't a valid appId/password pair. I want to check with you to make sure you were testing with a valid appId and password, generated for you by the MSA service.

To generate valid MSA appId and password, just register your bot at botframework.com.

**Comment by sepulchered** [comment]
@eanders-MS I did try with registered app Id and password - result was the same. But anyway why validate appId/password for bot when you provide it in both bot and emulator? Ain't it enough that they just match? And if I just want to play with it and create several bots is it reasonable to make people register each of them, in order to properly test them in emulator?

**Comment by eanders-MS** [comment]
@sepulchered We don't send password over the wire, so it is impossible to simply compare them. We rely on the MSA service to generate a token for us, which requires a valid MSA-generated appId and password.

**Comment by sepulchered** [comment]
@eanders-MS so there is no way to check your bot via emulator while you're offline?

**Comment by eanders-MS** [comment]
@sepulchered MSA authentication requires internet connectivity. You can test your bot with the emulator offline by clearing out your MSA info on both sides of the connection (bot and emulator)

**Comment by sepulchered** [comment]
@eanders-MS I see. Thank you for explanation. Think it should be somewhere in the docs.
Also we can close this issue now, I think.
