### ISSUE TITLE
Add open bot button to explorer pane when no bot is open

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#645]
At the moment, there is no text in the explorer pane when no bot file is open. Should we snap to VS code and show an open bot button in the explorer? 

![image](https://user-images.githubusercontent.com/20918136/41559152-0784eafc-72f8-11e8-8aca-9a844918cfec.png)

**Comment by tonyanziano** [comment]
We actually used to have this and then we removed it. Maybe @mewa1024 can add some insight.

**Comment by tonyanziano** [comment]
Addressed in #689
