### ISSUE TITLE
Get speech recognition and TTS support for V4 Emulator

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#646]
At the moment, the new emulator does not support speech in/ out. V3 does. we need to add support for this.

**Comment by compulim** [comment]
Speech recognition and synthesis is currently working (I don't have a bot flighted to speech, so I forcibly put my subscription key there).

We need to verify if token exchange is done correctly.

**Comment by SanaWaseem** [comment]
Does the new emulator accepts speech now?
