### ISSUE TITLE
emulator using ngrok for localhost

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotFramework-Emulator#65]
It seems that the emulator is using for no reason ngrok when testing localhost bot.
the issue is that ngrok has limitation on traffic frequency, and i'm being denied using it.

**Comment by eanders-MS** [comment]
Agreed, it shouldn't do this for localhost.

**Comment by eanders-MS** [comment]
Referencing commit https://github.com/Microsoft/BotFramework-Emulator/commit/a4457d2282d95f1daeea3852fe2408c209e9e53a, which contains a fix for this issue. Will be included in the next emulator release.

**Comment by amitbend** [comment]
Great, i believe we can close the issue.

**Comment by kbremner** [comment]
If an ngrok path is set, the emulator reports in the logs that it is accessible at the ngrok URL. It is expected that if an ngrok path is set, the ngrok URL will be reported as the service URL.

This new behaviour is unexpected and also causes dockerised bots to report a 500 error when attempting to start a new conversation, as they are unable to, by default, connect to the localhost service URL.

In my opinion, a change should be made in one or more of the following ways:
1 - At least log that this is the behaviour (localhost service URL being used for localhost bot). At the moment, it is hidden, unexpected and confusing
2 - Remove the check [here](https://github.com/Microsoft/BotFramework-Emulator/blob/master/src/server/conversationManager.ts#L119). If the user doesn't want to use ngrok for a localhost bot, they can remove the ngrok path from app settings
3 - Make the behaviour configurable via app settings

**Comment by kbremner** [comment]
Any response to my previous comment?

**Comment by eanders-MS** [comment]
@kbremner Thanks for the feedback. It's definitely a rough edge in the design. Addressing your points:
1 - Good suggestion, thanks.
2 - Deleting the ngrok path feels inappropriate since it would break remote connections as well. I think a checkbox in App Settings might be better: "Bypass ngrok for localhost connections".
3 - Is this covered by the checkbox suggestion?

**Comment by kbremner** [comment]
Thanks for taking it in to consideration :)

I agree in terms of the best course of action being to add a checkbox to app settings, with the logging mentioned in point 1.

I can open a pull request if you agree with those changes?

**Comment by eanders-MS** [comment]
Certainly, that would be fantastic.
