### ISSUE TITLE
Download the Bot Framework Emulator

### ISSUE THREAD

**Issue by HadasBrown** [Microsoft/BotFramework-Emulator#651]
Hello. I don't quite understand what I should download to get the Bot Framework Emulator (for windows). Please help!

**Comment by EricDahlvang** [comment]
Hi @HadasBrown 

This link is the latest Emulator installer: 
https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.36/botframework-emulator-Setup-3.5.36.exe
