### ISSUE TITLE
error opening bot framework emulator in Ubuntu 14.04 

### ISSUE THREAD

**Issue by joisarjignesh** [Microsoft/BotFramework-Emulator#653]
bot emulator install as a root user and aslo try to install as a normal user  in  last three version i have tryed..
1.botframework-emulator_4.0.15-alpha_amd64.deb
2.botframework-emulator_4.0.14-alpha_amd64.deb
3.botframework-emulator_4.0.13-alpha_amd64.deb

> Installation done successfully all version .
   My ubuntu version is 14.04 and Codename : trusty and x86_64 
   but when i open the bot framework emulator using commad line bot framework emulator successfully 
  but  it's show error on the console in ubuntu terminal like .. 

1. Failed to read file: /home/xyz/.config/botframework-emulator/botframework-emulator/server.json SyntaxError: Unexpected end of JSON input

2. HttpError: 404 Not Found
"method: undefined url: https://github.com/Microsoft/BotFramework-Emulator/releases/download/v4.0.15-alpha/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"

**Comment by nlw0** [comment]
Just gave it a try, apart from seeming quite slow (interface not responsive), I also get this latest-linux.yml message. Is there anything I could do, or is the Linux emulator just broken?

```
$ botframework-emulator 
Adding extension JSON
Adding extension LUIS
Adding extension QNAMaker
{ HttpError: 404 Not Found
"method: undefined url: https://github.com/Microsoft/BotFramework-Emulator/releases/download/v4.0.15-alpha/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [

```

**Comment by tonyanziano** [comment]
@nlw0 I believe that error is just from our Auto-Updater polling GitHub for the latest version of the emulator, and then coming back with a 404. Errors from the Auto-Updater shouldn't prevent the emulator from starting. So I would just ignore that message for now.

If you're emulator isn't starting then there is some other error that's occurring during startup.

We have just published an updated Linux build that is months ahead of **v4.0.15-alpha**, so I would install that version and give it a try and see if you still get the same issue.

Link:
https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.0.0-preview-2-linux

**Comment by tonyanziano** [comment]
Just tried the newest version **(v4.0.0-preview-2-linux)** on **Ubuntu 16.04.5 LTS** and it is working.

![image](https://user-images.githubusercontent.com/3452012/46101870-dd260b00-c181-11e8-8944-897522422b3d.png)

You will still get that same error within the terminal, but it should not stop the Emulator from starting.

**Comment by tonyanziano** [comment]
Just tried it on **Ubuntu 14.04.5 LTS** as well and it also works.

![image](https://user-images.githubusercontent.com/3452012/46106433-7f97bb80-c18d-11e8-9f15-ee6acd091970.png)
