### ISSUE TITLE
Emulator stopped displaying responses on MacOSX

### ISSUE THREAD

**Issue by scottmcconnell** [Microsoft/BotFramework-Emulator#66]
I've been using the emulator for a couple of weeks now and it has decided to stop relaying messages from my bot application. The logs in my terminal when running the application say that I have sent messages (batched and not batched) and I've also pulled back the entirety of my app so all it does it receive a message and send back "ok", still with issues. 

Things to note:
 - OSX El Capitan 10.11.6
 - I have uninstalled (and deleted as many files relating to it as possible) and reinstalled
 - If I deploy my project onto a server, it works fine if using Facebook Messenger

Thanks in advance for any support on this issue. 

Scott

**Comment by AndrewALatham** [comment]
I have a similar problem. I downloaded version 3.5.23 as a new user last night onto a windows 10 laptop.
Running a Hello World bot on localhost nothing displays in the details pane although the bot works and the log shows the message flow.
Andy

**Comment by eanders-MS** [comment]
Hi @scottmcconnell A few questions... When you saw the failure:
- Was your bot running locally or remotely?
- Was it configured with MSA appId and password, or running without authentication?
- Were you able to determine the http status code of the reply message sent from your bot?

Hi @AndrewALatham Yours sounds like a different problem. It might be that you haven't selected anything to view. Could you try clicking on a message in the chat window, or clicking on one of the hyperlinked elements in the log pane?

**Comment by scottmcconnell** [comment]
Hi @eanders-MS, thanks for getting back to me. 

 - I was running the emulator locally. 
 - It was configured with the appID and password
 - I'm unsure about this one. If you mean in the logs next to the chat window, then no there is no response from my bot showing up in there. As for in the console window where my app is running locally, it displays all my session.send()'s and sendBatch()'s when the emulator passes messages onto it. 

Let me know if you need any more information. 

Scott

**Comment by eanders-MS** [comment]
@scottmcconnell As a test, could you try running without appId and password (clearing it from both the bot and emulator)?

**Comment by scottmcconnell** [comment]
@eanders-MS; Interesting. That does work for me if I remove them out. 
I guess it must be picking up the credentials from my local environment variables that I set.

Any idea why it may have stopped working all of a sudden? 
And is there any disadvantage to not having the appid and password written in the emulator. 

Scott

**Comment by eanders-MS** [comment]
My next suggestion would be to put the credentials back, and double-check to ensure the emulator's credentials match the bot's.

The theory I'm floating is this: the emulator's credentials for the bot may have been inadvertently changed. This can kind of accident can happen if you're testing more than one bot with MSA credentials on localhost. The emulator's browser-like bot endpoint UI is nice and simple, but makes it difficult to manage multiple localhost bot connections. We have a new UI design for this in the works, but in the meantime if you need to manage more than one localhost bot connection in the emulator, what I do is add a differentiating query parameter for each, like this:

`http://localhost:3978/api/messages?bot1`
`http://localhost:3978/api/messages?bot2`
etc.

**Comment by AndrewALatham** [comment]
Hi Eric
Many thanks for the email
You are absolutely correct – this is operator error on my part and I hadn’t selected a message.
As a first time user I expected the message to be displayed in the details section as the conversation went along.
I wonder if there is a way you could prompt a user to select a message, or provide an option to display the json automatically as the conversation proceeds

Thanks again for your help
Andy


Andy Latham
Chief Technology Officer

phone: +44 161 876 4498
email: andy.latham@k3btg.com<mailto:andy.latham@k3btg.com>

K3btg.com

**Comment by eanders-MS** [comment]
@scottmcconnell When your bot is running locally, there is no material disadvantage to running without credentials. You should do what is most convenient. There are a few scenarios there you won't want to provide credentials:
- You haven't registered your bot at botframework.com and therefore don't have credentials yet.
- You're working offline (MSA authentication requires internet connectivity).

It is handy to run with credentials locally in order to verify your bot can successfully communicate bidirectionally when configured for authentication.

**Comment by eanders-MS** [comment]
@scottmcconnell going to go ahead and close this now. If you're still having problems, at-mention me or open a new issue. Cheers.

**Comment by scottmcconnell** [comment]
Thanks for your support. All good for now.
