### ISSUE TITLE
UI looks too much like Visual Studio Code

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotFramework-Emulator#662]
The new version of the emulator looks a lot like VS Code. When I'm using both at the same time, it's a bit jarring because they are not immediately distinguishable. If it's going to be a standalone app rather than an extension for VS Code (which I think was a good decision), it should be themed as a standalone app.  

I've heard similar comments from other developers, but I've also heard from some who like the similarity, so I wanted to get this out there for discussion.

**Comment by tonyanziano** [comment]
Hi @navzam,

We are currently aware of the visual similarities between VS Code and the new Emulator. The decision to imitate their style was intentional. We have also heard comments from both sides, but the overall attitude seems to be positive towards the new design.
