### ISSUE TITLE
Emulator not respecting proxy settings

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-Emulator#67]
Emulator should use host proxy settings if set. Reference issue: https://github.com/Microsoft/BotBuilder/issues/2049

**Comment by eanders-MS** [comment]
A new emulator build is out with experimental support for host proxy settings (v3.5.25).

**Comment by spulci** [comment]
Here I am to report my test to you. Our proxy is under authentication and your fix seems not to support proxy with authentication.
Infact Bot Emulator now gives a new error (407-unauthenticated):

-> POST Refresh access token failed with status code: 407 

Btw this is a workaround for the problem:

1.  Use fiddler as a tunnel for authenticated proxy. Mark "Automatically Authenticate" option under "Rules" menu
2. Start the channel emulator and authenticate to your local bot obtaining a 202 conversation update :)

Please observe that your bot need to contact MS server to negotiate JWT. So you can now experience the same issue under a proxy server. To avoid this I strongly advice to use, under node.js, global-tunnel module (npm install global-tunnel) together with Fiddler running with the previous option. Remember to add this few lines of code to your bot to enable global-tunnel pointing to Fiddler proxy:

`var globalTunnel = require('global-tunnel');
 
process.env.http_proxy = 'http://127.0.0.1:8888';
process.env.https_proxy = 'http://127.0.0.1:8888';
globalTunnel.initialize();`

5. You're now be able to have a full conversation with your bot using the channel emulator even under an authenticated proxy server.
