### ISSUE TITLE
Local QnA bot wont load into Bot Framework Emulator C#

### ISSUE THREAD

**Issue by Fulljames1** [Microsoft/BotFramework-Emulator#673]
I have entered appID, appPassword, SubscriptionKey, knowledgebaseID, and azureWebBasedStorage in myweb.config file.
My code runs correctly and return the address: http://localhost:3984 which I have entered as http://localhost:3984/api/messages.
I have installed the Microsoft.Bot.Builder NuGet in visual studio
But my bit will still not load into the Bot framework emulator.

Any help would be much appropriated!
![capture](https://user-images.githubusercontent.com/25401495/42320744-5ad8eb1e-804e-11e8-8aa6-e0d982b7914e.PNG)
![capture1](https://user-images.githubusercontent.com/25401495/42320745-5aed707a-804e-11e8-8a58-a1f435fa3c80.PNG)

**Comment by Zerryth** [comment]
Hi @Fulljames1! 

I saw your question on StackOverflow as well, and answered there, so it may benefit the SO community as a whole :)

https://stackoverflow.com/questions/51186403/cannot-link-bot-to-bot-framework-emulator?answertab=votes#tab-top

**Comment by Zerryth** [comment]
Closing GitHub issue to continue conversation in SO

**Comment by Fulljames1** [comment]
@Zerryth This issue is still not resolved, same issue applied to a C# basic bot with no code edits (only add app ID, password, and AzureWebJobsStorage). No text is ever shown in the log.
