### ISSUE TITLE
Support new chatdown features in Emulator

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#675]
Conversation update, multi-user handling are now supported in chatdown v1.0.6. 

We should add support for those constructs in the V4 Emulator so the transcript will render correctly

**Comment by tonyanziano** [comment]
Needs design on what do display in the case of multi-user which is currently unsupported in webchat.

**Comment by tonyanziano** [comment]
This depends on 2 PRs that are outstanding to enable the `role` property on activities in DirectLineJS & Webchat.

https://github.com/Microsoft/BotFramework-DirectLineJS/pull/79
https://github.com/Microsoft/BotFramework-WebChat/pull/1053

**Comment by compulim** [comment]
Both PR are merged, but we are hitting another problem, mentioned in Web Chat bug [#1110](https://github.com/Microsoft/BotFramework-WebChat/issues/1110).

**Comment by compulim** [comment]
This is going to be fixed in Chatdown [#377](https://github.com/Microsoft/botbuilder-tools/issues/377).

**Comment by nagarajkotha** [comment]
I am unable to view anything in transcript file using BotEmulator v4 generated using chatdown 1.0.5
