### ISSUE TITLE
Improved prompt for endpoint URL entry

### ISSUE THREAD

**Issue by emadelwany** [Microsoft/BotFramework-Emulator#677]
Revise "Enter a URL for your bot's endpoint" message to give a hint about the expected URL format.

How about "Enter a URL for your bot's endpoint (example: http://localhost:3978/api/messages)"

![image](https://user-images.githubusercontent.com/1061017/42466511-fd94fd80-8363-11e8-82ea-b697f3f517b9.png)

**Comment by tonyanziano** [comment]
Addressed in #761
