### ISSUE TITLE
v3 authentication tutorial not working with AAD v2 in the v3 Emulator

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotFramework-Emulator#678]
**repo steps**:

1. Follow the instructions in the [v3 Authentication tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0).
  - When creating the AAD v2 application, use the following scopes: **openid**, **Mail.Read**, **profile**, and **User.Read**.
  - When you set up the OAuth connection settings for your bot channels registration service, set scopes to **openid Mail.Read profile User.Read**.
  - To verify that your settings are correct, click **Test connection** near the top of the page before clicking **Save**.
1. Clone the **Microsoft/BotBuilder** repo and open **CSharp\Samples\Microsoft.Bot.Builder.Samples.sln** per the instructions.
  1. Set **Microsoft.Bot.Sample.AadV2Bot.csproj** as your startup project.
  1. Update the project's Web.config file.
  1. Build the project and fix any build errors. (I'm trying to get Chris to fix these in the repo.)
  1. Run the project.

**issues**:

* Open the **v4** Emulator, connect to your bot, type `me`, and click **Sign in** on the OAuth card.
  - Get a `Sorry, my bot code is having an issue.` message.
* Open the **v3** Emulator, and connect to your bot.
  - Type `me` and click  **Sign in** on the OAuth card.
  - If you get a `Sorry, my bot code is having an issue.` message, delete your user profile, end the conversation, reconnect to the bot, and type `me` and click  **Sign in** on the OAuth card again.
 - Well, today I'm still getting a `Sorry, my bot code is having an issue.`, but last week I was able to begin authentication. However,...
    * Singing in with my PIN generated one type of error in the resulting browser page.
    * Singing in with my password and two-factor authentication resulted in a different error.

**related**:

- https://github.com/Microsoft/BotBuilder/issues/4830
- https://github.com/Microsoft/BotBuilder/issues/4811
- https://github.com/Microsoft/BotBuilder/issues/4768
- https://github.com/Microsoft/BotBuilder/issues/4709

and possibly more.

**Comment by JonathanFingold** [comment]
Figured out how to get this (failing) behavior to repo in the v4 Emulator:

1. Before launching the Emulator:
  - Open your **AppData\Roaming\botframework-emulator** folder.
  - Delete the **Cookies** and **Cookies-journal** files.
1. Launch the Emulator, connect to the bot, and type in `me`.
1. Click **Sign in** on the OAuth card.
1. Enter a Microsoft alias, which should get the sign in page to redirect you to "your company's sign in page".
1. Choose to sign in via a PIN or smartcard.
1. If you are me, watch helplessly as the credentials selection page flashes by.
1. End up on an "An error occurred/Microsoft IT" page.

**Comment by JasonSowers** [comment]
>* Open the **v4** Emulator, connect to your bot, type `me`, and click **Sign in** on the OAuth card.
>   - Get a `Sorry, my bot code is having an issue.` message.
>* Open the **v3** Emulator, and connect to your bot.
>   - Type `me` and click  **Sign in** on the OAuth card.
>   - If you get a `Sorry, my bot code is having an issue.` message, delete your user profile, end the conversation, reconnect to the bot, and type `me` and click  **Sign in** on the OAuth card again.


In order for the "me" command to work the follow permissions must be enabled on your AAD application:
* `User.ReadBasic.All` for AAdv2
* `Read all users' basic profiles` for AADv1

**Comment by JonathanFingold** [comment]
Some very small amount of progress (still working on the AAD v2 sample).

1. Update the project's index.html:
   ```html
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>Bot Authentication Sample</title>
        <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
    </head>
    <body>
        <p>Bot Authentication Sample for AAD v2</p>
        <div id="bot" />
        <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
        <script>
            BotChat.App({
                directLine: { secret: '<insert-your-directline-secret-here>', webSocket: false },
                user: { id: 'user' },
                bot: { id: 'botid' },
                resize: 'detect'
            }, document.getElementById("bot"));
        </script>
    </body>
    </html>
   ```
1. Run you bot.
1. Copy the URL from the page that's launched, and open it in a private window in the browser of your choice.
1. Enter `me`, click **Sign in** on the resulting OAuth card, and authenticate yourself.
1. I got the following error at the end of this step. I have my tenant ID currently set to `Microsoft.com`.
   ![signinerror-chrome](https://user-images.githubusercontent.com/35047199/42598064-dd694662-850f-11e8-8171-c7161b27621e.png)

**Comment by JonathanFingold** [comment]
Looks like something else changed overnight. When I open my bot channel registration in the Azure Portal, go to settings / OAuth connection settings, and click **test connection**, the connection fails similarly to the above. Researching. :|

**Comment by JonathanFingold** [comment]
FWIW, I got the connection working again, but am still not able to get the OAuth card working. Trying some other...things.

**Comment by JonathanFingold** [comment]
@JasonSowers , @mingweiw found the problem and was able to fix it. Short form, it wasn't an Emulator bug. Longer form, to use auth with a bot running locally, you need an HTTPS endpoint set for your bot on the Azure Portal. Closing this bug and following up in email.

**Comment by SuperJMN** [comment]
@JonathanFingold could you please, post a screenshot of the Azure configuration page where you need to set the https endpoint? I'm facing the same problem. 
Thank you!

**Comment by JonathanFingold** [comment]
@SuperJMN , here's a screenshot for you. Note that the **Messaging endpoint** needs to use HTTPS.

![authcapture](https://user-images.githubusercontent.com/35047199/43727234-3cbbc356-9956-11e8-9640-2bdf701b1f58.PNG)
