### ISSUE TITLE
Not able to log into any OAuth site outside of main Azure AD

### ISSUE THREAD

**Issue by ravensorb** [Microsoft/BotFramework-Emulator#687]
I have setup an OAuth connection for Azure AD and Visual Studio Services. The Azure AD one works perfectly inside the Emulator.  The VSTS one however does not -- all I get is a blank screen.  I have tried both a Generic OAuth Connection and the OOTB one for Visual Studio services and both result in the same experience.  Is there any what to troubleshoot this?

**Comment by JasonSowers** [comment]
@ravensorb can you please post this in the [SDK repository](https://github.com/Microsoft/BotBuilder/issues/new) since it is not directly related to the emulator?  We will address your issue there.

**Comment by ravensorb** [comment]
I am not sure I follow -- it is the emulator that does not seem to be handling loading the webpage for authorization correctly.  Doesn't the emulator handle the UI display of the cards and dialogs?

**Comment by ravensorb** [comment]
I did some more testing and this seem to be only an issue with Visual Studio services.  It seems that the emulator cannot render the Login Page.
