### ISSUE TITLE
Emulator's Edit Menu has an empty menu item 

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotFramework-Emulator#696]
To repro:
- launch the emulator.  I'm running Version 4.0.15-alpha (4.0.15-alpha.33986)
- Click the Edit menu

Results:
- There is an empty menu item after the 'Select All' menu item.  
See screen shot

<img width="507" alt="screen shot 2018-07-19 at 11 44 38 am" src="https://user-images.githubusercontent.com/733559/42955593-da1eaf46-8b4b-11e8-8433-211d2196b595.png">

Expected:
- No blank menu item

**Comment by sgellock** [comment]
I have verified with Bot Framework Emulator (V4 PREVIEW)
version: 4.0.15-alpha
that this issue still exists on macOS

**Comment by justinwilaby** [comment]
Fixed by #921
