### ISSUE TITLE
post /v3/conversations cause an "Cannot read property 'payload' of undefined"  error  (V4 Preview)

### ISSUE THREAD

**Issue by rainmakerho** [Microsoft/BotFramework-Emulator#706]
Hi, 
I post "emulatorserver/v3/conversations" with body  through Fiddler when V3 Emulator is running. 
V3 Emulator will show createConversation 200.
When I change to V4 Emulator, I will get {"code":"InternalError","message":"Cannot read property 'payload' of undefined"} in fiddler. 

The fiddler Request Body is below,
```
 {
  "bot": {
    "id": "405b2580-9170-11e8-bdc0-fda88c496bd5"
  },
  "members": [
    {
      "id": "default-user"
    }
  ],
  "activity": {
    "from": {
      "id": "xxxxRMBot"
    },
    "recipient": {
      "id": "tds"
    },
    "membersAdded": [],
    "membersRemoved": [],
    "reactionsAdded": [],
    "reactionsRemoved": [],
    "attachments": [],
    "entities": []
  }
}

```

**Comment by tonyanziano** [comment]
Hey @rainmakerho,

I tried to `POST` your payload to the `emulator-server/v3/conversations` endpoint on both V3 and V4 and the same error for both of them but a different error than the one you got:

`Cannot read property '1' of null.`

I tracked it down to being a result of the `POST` not having an `Authorization: Bearer <token>` header attached to the request.

I then tried to `POST` the same payload to both V3 and V4 with an `Authorization` header and got a 200 back with the conversation id.

So just out of curiosity, did you have an `Authorization` header with a bearer token attached to either of your `POST` requests? I saw a similar piece of code in the emulator that tries to read a `.payload` property of a decoded bearer token, but the code should detect the token is non-existent before then and throw a 401.

Although, this still doesn't really explain why your `POST` worked on V3 and not V4, but it might help me debug the issue further.

**Comment by rainmakerho** [comment]
@tonyanziano ,
I post it through Fiddler, and not having an Authorization.
My code is below (MessagesController's Post([FromBody]Activity activity)),

```csharp
if(activity.Type == ActivityTypes.Message)
{
	try
	{
		var userId = activity.From.Id;
		var botId = activity.Recipient.Id;
		var emulatorServiceUrl = activity.ServiceUrl;
		var message = new Activity();
		var userAccount = new ChannelAccount(userId);
		var botAccount = new ChannelAccount(botId);
		message.From = userAccount;
		message.Recipient = botAccount;
		message.ServiceUrl = emulatorServiceUrl;
		var members = new List<ChannelAccount>() { userAccount };
		var conversationParams = new ConversationParameters(bot: botAccount, members: members, activity: message);
		var connectorClient = new GssConnectorClient(new Uri(emulatorServiceUrl));
		var replyConversation = await connectorClient.Conversations.CreateConversationAsync(conversationParams);
		message.Conversation = new ConversationAccount(id: replyConversation.Id);
		var replyMessage = message.CreateReply();
		replyMessage.Text = $"my new conversationId:{replyConversation.Id}";
		await connectorClient.Conversations.SendToConversationAsync(replyMessage);
		var response = Request.CreateResponse(HttpStatusCode.OK);
		return response;
	}
	catch(Exception exx)
	{

		throw;
	}
	
}

```
It will get new conversationId on V3, error on V4 .
error code is below,
   at Microsoft.Bot.Connector.Conversations.<CreateConversationWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<CreateConversationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VitalsESPBot.Controllers.MessagesController.<Post>d__0.MoveNext()

Thanks for your help.

**Comment by tonyanziano** [comment]
@rainmakerho , I have looked into this issue, and all you need to do is add an Authorization header to your POST request and it should work in the v4 emulator. The `Authorization` header is something that is required in the v3 DirectLine POST activity schema ([Directline POST schema](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#request)) and so in the Emulator as well.

Here is an example of the request I posted to the Emulator to successfully create a new conversation:

**Request:**
```
POST http://localhost:54089/v3/directline/conversations
Authorization: Bearer iamatoken
```

**Response:**
```
{
    "conversationId": "4cca5ce0-03c2-11e9-9e3b-95e19b0f415e",
    "token": "http://localhost:3978/api/messages",
    "expires_in": 2147483647,
    "streamUrl": ""
}
```

**Comment by rainmakerho** [comment]
@tonyanziano ,
Do I need to give token even if i use Emulator?
Do I need to issue token from botframework.com ? 
Thank you.

**Comment by tonyanziano** [comment]
@rainmakerho , If you are talking to a bot **through the Emulator UI**, you should not need to generate a token because auth will be handled for you by the Emulator. If it's a remote bot that you are talking to, you will of course have to supply the correct MSA App ID and Password.

If you are posting directly to the Emulated endpoint like in your original comment, then you will need to supply a token. If the bot is a local bot, you can just pass in any value for the token, such as:

`Authorization: Bearer someTokenValue` or `Authorization: Bearer imadethisup`

If the bot is remote, you will need to use an actual token issued by the bot service.

**Comment by rainmakerho** [comment]
Hi @tonyanziano ,
I got it.
Thank you for your help.

**Comment by tonyanziano** [comment]
@rainmakerho No problem!
