### ISSUE TITLE
Add Support for Invoking Actions

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Emulator#707]
We need a UX experience that will enable the Emulator to test Actions.  This should provide the ability to read manifest files, expose Actions, allow actions to map to (user specified) entities and entity values.  Once the Actions are known and configured, the Emulator needs to provide a way to invoke the bot using a specified action.

**Comment by tonyanziano** [comment]
Closing this due to lack of detail. Feel free to re-open with more information.
