### ISSUE TITLE
am facing internal server error while testing bot at bot framework locally

### ISSUE THREAD

**Issue by waqasyousafy** [Microsoft/BotFramework-Emulator#708]

**Comment by tonyanziano** [comment]
Hello @waqasyousafy,

Could you please be more specific about the issue you're facing? Is there an error message you are seeing in the log? If so, could you please take a screenshot of the log, or click on the error's log entry and take a screenshot of the inspector panel?

Or open the developer tools using the **Help** menu before trying to talk to your bot, then try again, and take a screenshot of the error in the **Network** tab of the developer tools.

It's hard to diagnose the statement "I'm facing an internal server error while testing my bot."

Thanks

**Comment by stevkan** [comment]
Closing due to lack of response.
