### ISSUE TITLE
latest 4.0.15-alpha nor honoring markdowns [v4]

### ISSUE THREAD

**Issue by oscarcabrero** [Microsoft/BotFramework-Emulator#710]
i am trying latest 4.0 and markdowns are now showing for adaptive cards

**Comment by compulim** [comment]
PR for the fix is in. Will be out on next build.

**Comment by sgellock** [comment]
We need to verify that this is in the daily emulator build

**Comment by compulim** [comment]
Verified it is in nightly build.
