### ISSUE TITLE
[NARRATOR] Behavior of Narrator is confusing in 'My Bot' and 'Help' sections while using Scan or Item mode navigation.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-Emulator#718]
**Actual Result:**
Narrator reads each line of content present in 'My Bot' and 'Help' sections multiple times while using Scan or Item mode navigation.

**Expected Result:**
Narrator should read each line of content present in 'My Bot' and 'Help' sections once only while using Scan or Item mode navigation.

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Start Narrator using Ctrl + Windows Logo Key +Enter.
3. Navigate on 'Welcome' screen.
4. Notice what Narrator reads for content present under 'My Bot' and 'Help' sections

**User Impact:**
Screen Reader dependent users may get confuse due to any repetition of content and this will reduce screen reader's efficiency.

**Test Environment:**
OS: Windows 10
OS Build: 17134.167
OS Version: 1803
Browser: Edge
Tool: Narrator

**Attachment:**
[NARRATOR_BotFrameworkEmulator_MyBots_Help_ScanItemModeNavigation.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2245552/NARRATOR_BotFrameworkEmulator_MyBots_Help_ScanItemModeNavigation.zip)

**Comment by corinagum** [comment]
Closing due to no repro -- accessibility bug fixes in #1096 will be submitted in a PR shortly.
