### ISSUE TITLE
UI becomes unresponsive after adding bot

### ISSUE THREAD

**Issue by nk111** [Microsoft/BotFramework-Emulator#721]
I'm using the latest alpha 4.0.15 on Win 7.

I think i've found a reproducable bug.

When I first started the emulator i created a bot configuration by using my endpoint url as described in the docs. But every time when i try to open a saved bot the whole UI of the emulator gets unresponsive. Sometimes i see a loading indicator, sometimes i don't. The UI gets a grey overlay from time to time. The title bar shows "not responding". I cannot click anywhere.

This was driving me crazy. After hours i decided to open a bot file which was created by the bot builder template directly as part of my visual studio project. And guess what? Everything works smooth and the UI is responsive?!

So i compared the .bot files generated by the emulator and by the project template. I found some differences but nothing critical. At the end i actually made them 100% identical but still the one created by the emulator crashed the UI when opened. 

It turned out it was the directory where i'd saved the bot configuration. The default directory was my documents folder which includes a whole mess of subdirs and files. Somehow this seems to crash the UI because it tries to list everything in the "transcript files" area. I don't know if its just the number of files or maybe permission issues which actually causes the app crash. Let me know if i can provide any further details.

**Comment by nk111** [comment]
After some tests i'm quite sure it's the recursive rendering of the tree view which blocks the UI if the bot config gets stored in a really huge directory.

**Comment by tonyanziano** [comment]
Hey @nk111 ,

You are correct, it is due to the recursive rendering of the file tree view control and this is a known issue currently being tracked here #497.

Any further discussion can be conducted there. Closing this issue.
