### ISSUE TITLE
Un-themed areas that need fixing

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#725]
(split from #518 )

There are a few un-themed areas that need to be fixed so I will consolidate them here:

- File explorer items are always darkly colored
- Drag states on tabs / dragging over the content area to split tabs to other editor screens is darkly colored
- The scrollbar that we use is lightly colored and is barely visible in the light theme
- Active editors should have have the same background color as active tab
- Inspector bars

**Comment by mewa1024** [comment]
Hmm. Here is what VS code does:
<img width="1680" alt="screen shot 2018-08-02 at 11 44 01 am" src="https://user-images.githubusercontent.com/39317542/43604436-9c9d1c02-964a-11e8-89b4-6c38dfefcd80.png">
<img width="1680" alt="screen shot 2018-08-02 at 11 43 19 am" src="https://user-images.githubusercontent.com/39317542/43604437-9cb097b4-964a-11e8-81f6-129885cb1fe3.png">
<img width="1680" alt="screen shot 2018-08-02 at 11 43 06 am" src="https://user-images.githubusercontent.com/39317542/43604438-9cc5da98-964a-11e8-81a9-a994558f1a80.png">

**Comment by tonyanziano** [comment]
More un-themed UI:
- paths of entries in `My Bots` list

**Comment by mewa1024** [comment]
Background color of editors should be as follows:
- light theeme: #FFFFFF 
- dark theme: #212121 
- high contrast: #000000

In other words, the color should be match the background color the tabs in the active state.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/39317542/44674478-7bd41600-a9e2-11e8-859d-fb0dd222902c.png">

**Comment by mewa1024** [comment]
One more:
Inspector bars should use the same color as the active editor. For example, this would be for the light theme:
![image](https://user-images.githubusercontent.com/39317542/44878800-b812ab00-ac5c-11e8-97e1-f7681590c376.png)

specs on Invision: https://microsoft-fuse-design.invisionapp.com/d/#/console/14907902/317399778/preview

**Comment by mewa1024** [comment]
@justinwilaby For the drop targets, let's use each theme's hover color/style.
