### ISSUE TITLE
Emulator is not familiar with the LUIS endpoints outside of North America regions

### ISSUE THREAD

**Issue by gbelenky** [Microsoft/BotFramework-Emulator#730]
If you add a LUIS service, the emulator does not expect a LUIS URL different from https://www.luis.ai and it cannot connect to https://eu.luis.ai and other endpoints mentioned here - https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions.
We need an additional configuration parameter asking for the LUIS URL

**Comment by justinwilaby** [comment]
Which version of the emulator does this pertain to?

**Comment by gbelenky** [comment]
4.0.15-alpha. Thanks!

**Comment by n01d** [comment]
Ran into the same issue yesterday. The emulator expects all LUIS services to run under https://www.luis.ai.

**Comment by justinwilaby** [comment]
Tracking this [here](https://github.com/Microsoft/botbuilder-js/issues/332)
