### ISSUE TITLE
[MAS3.2.1] Focus does not come inside 'New Bot Configuration' pop-up as we open this pop-up.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-Emulator#735]
**Actual Result:**
As we select 'Create a new bot configuration link', focus does not come inside 'New Bot Configuration' dialog-box. It moves to next links present on Welcome page.

**Expected Result:**
As we select 'Create a new bot configuration link', focus does not come inside 'New Bot Configuration' dialog-box (At first interactive element of this dialog-box).

**Repro Steps:**
1. Open the Bot Framework V4 Emulator.
2. Welcome screen will open up.
3. Navigate to 'Create a new bot configuration' link and select it.
4. Notice where keyboard focus goes after this selection.

**User Impact:**
Keyboard dependent users require that all focus changes are as per user expectations otherwise such users may get confuse.

**Test Environment:**
OS: Windows 10
OS Build: 17134.167
OS Version: 1803
Browser: Edge

**Impacted MAS Link:**
[MAS 3.2.1 – On Focus (06)](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a4bbd37d-ee11-485e-b5c8-0539f0ac94b2})

Attachments:
[MAS3.2.1_BotFrameworkEmulator_NewBotConfiguration.zip](https://github.com/Microsoft/BotFramework-Emulator/files/2266066/MAS3.2.1_BotFrameworkEmulator_NewBotConfiguration.zip)

**Comment by tonyanziano** [comment]
No longer repros with new creation modal. Focus goes directly to `X` close icon of modal
