### ISSUE TITLE
Version 4.0.15-alpha not submit LUIS application

### ISSUE THREAD

**Issue by RafaelPNV** [Microsoft/BotFramework-Emulator#738]
I created the azu-cli-bot file and open using a localhost server created in VS2017. When I try to register a LUIS app for my bot, wasn't saved in bot framework. I try to submit several times and all times the LUIS app wasn't saved.

**Comment by vishwacsena** [comment]
@RafaelPNV, can you help clarify if you are trying to add the LUIS app from within the services section in Emulator? 

![image](https://user-images.githubusercontent.com/20918136/43797398-1bdb003e-9a3c-11e8-814f-1ac3d5d78d82.png)

**Comment by n01d** [comment]
Had the same issue. Clicking submit would just close the "Connect to Luis Application" window, but the service wouldn't show up. Restarting the emulator helped though.

**Comment by sgellock** [comment]
PR for a fix has been merged into v4 branch

**Comment by justinwilaby** [comment]
Fixed with #896

**Comment by mewa1024** [comment]
Version windows 4.0.0-preview-.39773

The "Edit configuation" modal is appearing blank:

![image](https://user-images.githubusercontent.com/39317542/45834065-1e6a7680-bcbb-11e8-9e86-4581bb2224d8.png)
