### ISSUE TITLE
[MAS4.3.1] Bot Framework Emulator Application is not able to adapt High Contrast Settings of windows.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-Emulator#749]
**Actual Result:**
When we apply any High Contrast Settings of windows, we observe no change in contrast of content present in Bot Framework Emulator Application.

**Expected Result:**
When we apply any High Contrast Settings of windows, contrast of the content present in Bot Framework Emulator Application should change accordingly.

**Repro Steps**:
1. Open the Bot Framework V4 Emulator.
2. Notice content in this application.
3. Go to Settings-> Ease of Access-> Toggle high contrast On-> Select the contrast mode-> Apply.
4, Go back to the application and look for change in contrast of content.

**User Impact:**
Users with low vision use high contrast settings to access content present in an application or webpage.

**Test Environment:**
OS: Windows 10
OS Build: 17134.167
OS Version: 1803
Browser: Edge

**Impacted MAS Link:**
[MAS 4.3.1 – No Disruption of Accessibility Features (42A)](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={672c8a8b-ed4f-463f-868f-e8131caf9b74})

**Attachment:**
![mas4 3 1_botframeworkemulator_highcontrastmode](https://user-images.githubusercontent.com/41668935/43825060-4bf999ee-9b11-11e8-8166-bffbc5427a33.png)

**Comment by justinwilaby** [comment]
Fixed with #856
