### ISSUE TITLE
Getting error "POST Refresh access token failed with status code: 400 "

### ISSUE THREAD

**Issue by wiseguytamo** [Microsoft/BotFramework-Emulator#75]
Hi.
Why do I keep getting "POST Refresh access token failed with status code: 400 " when I enter my credentials and click connect or when type a message and click send ?

Please I am asking for assistance

**Comment by eanders-MS** [comment]
Hi @wiseguytamo When running your bot on localhost, if you clear credentials from bot and emulator, are they able to communicate?

Here's a helpful auth troubleshooting guide: https://docs.botframework.com/en-us/support/troubleshooting-bot-framework-authentication/

**Comment by eanders-MS** [comment]
@wiseguytamo going to go ahead and close this now. If you're still having problems @mention or open a new issue. Cheers.

**Comment by wiseguytamo** [comment]
Good afternoon Eric.


I must apologize for my late response as I was extremely busy.


Thank you for taking the time to respond to my emails.

I had figured out the cause of the issue and what you had suggested prior to this email was the same solution.


Thank you very much.


One question, I am a C# developer and who like to know where I could get some of the best resources whether it be Texts, Videos, etc that will go a bit deeper in Bot Development.

Thanks again.


Regards,


Ricardo

________________________________
