### ISSUE TITLE
Can't enable microphone in Emulator 3.56

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotFramework-Emulator#757]
Wanted to try the speech to text so I can use Cortana Skills and when I try to do simple test in the emulator, this message popups:

![image](https://user-images.githubusercontent.com/5460795/43975659-5867ca1a-9cac-11e8-964d-238f597d0ab8.png)

**Comment by EricDahlvang** [comment]
Hi @Rykimaruh 

Have the Microsoft App Id and Microsoft App Password for the bot been provided to the emulator? 

![image](https://user-images.githubusercontent.com/11055362/44039885-f692bcf8-9ece-11e8-99c6-828a3c8627ef.png)

These are required for speech.

**Comment by musabukhari** [comment]
I'm facing the same error. I provided the Microsoft App Id and Microsoft App Password. I also have the Speech API enabled. When I click on the mic button, the emulator freezes, and has to be restarted.
