### ISSUE TITLE
LUIS Service can not be saved without subscription key (Version 4.0.15-alpha)

### ISSUE THREAD

**Issue by n01d** [Microsoft/BotFramework-Emulator#763]
When adding a LUIS app to your bot in the Emulator the settings can not be saved ("Submit" button deactivated) without a subscription key although the filed is not marked as required (*).

![image](https://user-images.githubusercontent.com/5029466/44079926-c5ca84d4-9faa-11e8-8124-6e8f68d8f111.png)

Possible solution: Either mark the subscription key as required or change the button behavior.

**Comment by justinwilaby** [comment]
Thank you for the submission. This was a known issue that has been solved in recent weeks. I went ahead and added [test coverage for this issue](https://github.com/Microsoft/BotFramework-Emulator/pull/766/files#diff-91f81856d43d5647126fc1915c76297bR78)
