### ISSUE TITLE
Can't render adaptive cards

### ISSUE THREAD

**Issue by giorigor** [Microsoft/BotFramework-Emulator#765]
I'm having this issue with the latest version (4.0.15 alpha). The adaptive cards work on final channels (Slack, Teams, etc) but the emulator can't render the cards itself.

[Emulator](https://user-images.githubusercontent.com/10777906/43969905-07779842-9ca2-11e8-85ff-4c14957853b0.png) | [Teams](https://user-images.githubusercontent.com/10777906/43969866-e95cc5a8-9ca1-11e8-8e0a-b129c6dce066.png)

```c#
AdaptiveCard card = new AdaptiveCard();
card.Body = new List<AdaptiveElement>()
{
    new AdaptiveTextBlock()
    {
        Text = "Lorem ipsun"
    },
    new AdaptiveDateInput()
    {
        Value = DateTime.Now.ToShortDateString()
    },
    new AdaptiveTimeInput()
    {
        Value = DateTime.Now.ToShortTimeString()
    }
};

var msg = context.MakeMessage();
msg.Attachments.Add(
    new Attachment()
    {
        Content = card,
        ContentType = "application/vnd.microsoft.card.adaptive",
        Name = "Lorem Ipsun"
    }
);

await context.PostAsync(msg);
context.Wait(this.MessageReceived);
```

Issues read: #244 and #286

**Comment by justinwilaby** [comment]
Thank you for the submission. There were a number of issues related to adaptive cards that were closed recently  in the [Botframework-WebChat repo](https://github.com/Microsoft/BotFramework-WebChat/issues?q=is%3Aissue+adaptive+card+is%3Aclosed). We have incorporated most of these changes into the v4 branch which should go out with the next build.

**Comment by justinwilaby** [comment]
Leaving this open until the fix is confirmed.

**Comment by giorigor** [comment]
Thanks @dkonyayev! Now it works.  
I also didn't knew about this "Developer Mode" (pretty much the chrome F12 overlay), so thanks again!  
  
Now related to the issue: is this _"All inputs must have a unique Id"_ restriction valid only for the Emulator? I mean, the cards were rendering on Teams and Slack without this change.  
Should they display the card, even with the missing Ids? Or is the Emulator's _"can't render card"_ message the right approach?
