### ISSUE TITLE
Rev Emulator to pick up new bot configuration manager

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#770]
Pick up the new configuration manager + schema changes. See this [PR](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fbotbuilder-js%2Fpull%2F329&data=04%7C01%7C%7Cf398db39a96d4efcdec608d602f805df%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636699661646122054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=1uTRA4g4Mv36uTbpDZHWV5XEDZkb7cBIP173miJA2c0%3D&reserved=0)

**Comment by mewa1024** [comment]
@vishwacsena @justinwilaby added screens to Invision:
https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15183213

Flow:
1 - User creates a new bot configuration (File menu or text on the Welcome page)
2 - New Bot Config modal opens with encryption turned off
3 - User turns on encryption and a key is generated
4 - User can show/hide key or turn encryption off again
5 - User hits Save and Connect button, which closes the modal and opens the tab for the endpoint
6 - User opens the Bot Explorer nav/sidebar and clicks the gear icon to open the Bot Settings tab
7 - Bot Settings tab allows user to change the bot name and turn encryption on/off

**Comment by darrenj** [comment]
Is this issue to fix the issue where the Emulator no longer works for Bots created using the latest SDK builds? I get HTTP 500 errors and Exceptions: 

Exception thrown: 'Microsoft.Bot.Schema.ErrorResponseException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Bot.Schema.ErrorResponseException' in System.Private.CoreLib.dll

**Comment by justinwilaby** [comment]
@darrenj - This ticket is to move away from the [msbot](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/MSBot) package and use [botframework-config](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botframework-config) in its place. I'm starting on this now so I'll look out for any issues related to the errors you're seeing and fix them if possible.
