### ISSUE TITLE
Change text for File menu options

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#773]
@mewa1024 - can you update this issue with what the menu items should be?

**Comment by mewa1024** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/39317542/44188428-5be34f00-a0d2-11e8-9665-7eac09b9c412.png">

https://microsoft-fuse-design.invisionapp.com/d/#/console/14899362/309814584/preview

**Comment by vishwacsena** [comment]
Thanks @mewa1024. I presume save transcript should be disabled when no bot configuration is loaded and no active live chat session? 

Also close tab is disabled when no tabs are open? 

What's the difference between close window and exit? They both seem like they would do the same thing ..

**Comment by mewa1024** [comment]
@vishwacsena Correct: "Save transcript" and "Close tab" are disabled when no action can occur.
"Close window" closes the instance of Emulator ("New window" allows you to open another instance of the Emulator)" and "Exit" closes Emulator altogether.

**Comment by corinagum** [comment]
@mewa1024 What would you like the submenu for Open Recent... to say if there are no recent bots?
Thank you!

**Comment by mewa1024** [comment]
@corinagum Ah, good catch. Can we use the same menu item but disable it?

**Comment by corinagum** [comment]
@mewa1024 As per offline discussion I'll make it disabled if the menu is empty. Another question, should the Open Recent menu display all recent bots or a certain number? Previously it was only displaying 5. Your menu shows 8. Is there a max that should be listed, like 10? Or just show all of them?

**Comment by mewa1024** [comment]
@corinagum For now, we will show all of them. If it turns out that users want to have a large number of bots (like over 15), then we can consider limiting the number in the list, adding a menu item for Show All, and UI for showing all the Bot files, but we don't have that UI yet.
