### ISSUE TITLE
Hubot receives message but will not reply

### ISSUE THREAD

**Issue by ryanknight09** [Microsoft/BotFramework-Emulator#776]
Hubot running in a docker container will connect to MS Chat Emulator but will not reply with a response. 

- The docker file exposes port 8080
Running docker image: 
<img width="1118" alt="screen shot 2018-08-16 at 1 35 21 pm" src="https://user-images.githubusercontent.com/23562427/44230852-95ab6880-a159-11e8-9b6f-0c0d0d2db735.png">

connected to bot but no reply: 

<img width="1404" alt="screen shot 2018-08-16 at 1 36 55 pm" src="https://user-images.githubusercontent.com/23562427/44230902-b378cd80-a159-11e8-97a7-0d1232dcea07.png">

Question: Do I absolutely have to run tunneling service such as NGROK when running from a docker container? My company network does not allow NGROK due to vulnerability issues. Any work around?

**Comment by sgellock** [comment]
Today we have a requirement to run ngrok.  We don't have an alternate solution at this time.  #714 is used to track an alternative we are considering.
