### ISSUE TITLE
Not clear error message on first run post install

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotFramework-Emulator#798]
Loading the emulator with a bot file shows the following message. 
1. the text is not properly wrapped
2. not clear what the error is and how/what it is related to my bot

Previously I had the Build version.

![image](https://user-images.githubusercontent.com/896149/44759058-b7f39d80-aaec-11e8-907a-ee92a2bcb21f.png)

**Comment by tonyanziano** [comment]
This issue has to do with post-v4 upgrade migration logic. I can look into this one.

**Comment by tonyanziano** [comment]
Addressed in #844

**Comment by justinwilaby** [comment]
Closing this issue since the fix was merged.
