### ISSUE TITLE
Fix Login to Azure popup window borders

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotFramework-Emulator#799]
The login to Azure popup screen has no borders, no way to cancel and close it. When I failed to login, there is no way to close that popup. 

![image](https://user-images.githubusercontent.com/896149/44759125-0739ce00-aaed-11e8-836a-d5b9235c5098.png)

![image](https://user-images.githubusercontent.com/896149/44759154-2e909b00-aaed-11e8-98e4-bcee55e57181.png)

**Comment by vishwacsena** [comment]
@mewa1024 - design input?

**Comment by mewa1024** [comment]
@vishwacsena @justinwilaby Can we do something similar to the Teams sign in modal? Thin border around enter dialog, minimal header with text like "Sign in with Azure", and close button (no minimize or maximize buttons needed):

![teams-sign-in](https://user-images.githubusercontent.com/39317542/45065164-8179cd80-b06c-11e8-9eaa-66d590437975.PNG)

**Comment by vishwacsena** [comment]
Lowering to P1 - 

- The E2E scenario works
- Engineering challenges with implementing the required design.
