### ISSUE TITLE
Recipient.name 

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotFramework-Emulator#80]
Recipient.name does not passes from new simulator. In old version we had I'd and name. Moreover name contains bot name and it is mandatory for us to get routing to which bot we got request.

**Comment by eanders-MS** [comment]
Hi @vovanb, We have a new UX in the works that will allow you to name your bot, and that bot name will be assigned to the `receipient.name` field on outgoing messages. The implementation of this new UI is still a ways off, so in the meantime what we can do is set `recipient.name` to 'Bot'. Will this work for your needs?

**Comment by vovanb** [comment]
Sure 
This will fine. When the patch will be avaliable?

**Comment by eanders-MS** [comment]
Aiming for a release Thursday afternoon PST (1/26)

**Comment by eanders-MS** [comment]
Didn't quite get it out the door today. New target: tomorrow morning.

**Comment by eanders-MS** [comment]
Hi @vovanb, Emulator build 3.5.25 is out. Please give it a try and let us know if the interim solution works or not. Cheers.
