### ISSUE TITLE
The Login to Azure popup window remain 'active' / visible after closing the emulator app

### ISSUE THREAD

**Issue by yochay** [Microsoft/BotFramework-Emulator#800]
The Login to Azure popup window remain 'active' / visible after closing the emulator app

Scenario
1. Open with a bot file
2. try to login to Azure
3. failed to login to Azure - cant close the login window #799 
4. I close the app, as due to step 3 nothing else to do
5. the login to Azure window remain visible an on top of all other windows on my desktop
6. Due to step 3, I force to exit the emulator via Task Manager

**Comment by justinwilaby** [comment]
fixed in #829
