### ISSUE TITLE
Conversation -> send system activity should be disabled when no bot is active

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#801]
Right now, the menu is always enabled. We should have this disabled when no bot is active. 

![image](https://user-images.githubusercontent.com/20918136/44802346-52e18b80-ab70-11e8-9da6-6bf1fe95f740.png)

**Comment by corinagum** [comment]
@mewa1024 
Do we want to implement this so that when Conversation > Send System Activity is disabled, the submenu with various commands is shown, but is disabled? Or should the submenu listing conversationUpdate etc not show at all when Send System Activity is disabled?

**Comment by mewa1024** [comment]
@corinagum Let's allow Send System Activity to expand the submenu, but the submenu items are grayed out. Like this example from Visual Studio Code (where "Open Recent  >" is in the place of "Send System Activity >":
<img width="464" alt="image" src="https://user-images.githubusercontent.com/39317542/48153449-153d6500-e27b-11e8-9cd2-e7f3300b6c73.png">
