### ISSUE TITLE
Emulator not creating/opening Bot files

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#805]
Emulator Build: 4.0.204 (nightly)

Opening existing or creating a new Bot file doesn't work in the Emulator.  This error is shown in the emulator

![image](https://user-images.githubusercontent.com/33519520/44863058-fd8ea280-ac73-11e8-878c-9bdb83ee31c1.png)

And Developer tools shows this

![image](https://user-images.githubusercontent.com/33519520/44862967-c7512300-ac73-11e8-8713-8cf0b1eaa374.png)

Example Bot file:
```
{
    "name": "AuthBot",
    "description": "",
    "secretKey": "",
    "services": [
        {
            "appId": "4f8fde3f-48d3-4d8a-a954-393efe39809e",
            "id": "cded37c0-83f2-11e8-ac6d-b7172cd24b28",
            "type": "endpoint",
            "appPassword": "REDACTED",
            "endpoint": "http://localhost:55697/api/messages",
            "name": "authsample"
        }
    ]
}
```

**Comment by justinwilaby** [comment]
@darrenj - I'm unable to repro this. Creating a new bot and opening and existing bot file worked as expected without errors using your example botfile. It's possible that another change fixed your issue. 

Please download the latest nightly and try this again. If it still persists, I'll contact you personally to diagnose.

**Comment by hilvarenbeek** [comment]
I had the same problem while my .bot file contained a line commented out using //
Removing the line fixed it for me.
See also https://github.com/Microsoft/BotFramework-Emulator/issues/1166
