### ISSUE TITLE
Sign in to Azure fails

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotFramework-Emulator#809]
Build: 4.0.218-nightly 

Sign in to Azure fails with "Something went wrong" error message. If you dismiss the message and try to click on the + button to add a service, nothing happens.

**Comment by mewa1024** [comment]
Also happened with 4.0.0-preview.38774.exe. 
1 - installed Emulator
2 - clicked on File > Sign in. Got the modal, and clicked on the Sign in with Azure button:
![screenshot 73](https://user-images.githubusercontent.com/39317542/45114685-7e312100-b102-11e8-9dd4-9ea81c094ee9.png)

3 - saw sign in window flash briefly: 
![screenshot 74](https://user-images.githubusercontent.com/39317542/45114748-ade02900-b102-11e8-98a9-93f63a529642.png)

4 - got this error message:
![screenshot 75](https://user-images.githubusercontent.com/39317542/45114768-bb95ae80-b102-11e8-9e4c-45977322408e.png)

**Comment by justinwilaby** [comment]
@Kaiqb @mewa1024  - Are you able to provide screenshots of your chrome dev tools console? I'm able to login just fine.

**Comment by justinwilaby** [comment]
This can be reproduced when 2fa is required for the particular login.

**Comment by justinwilaby** [comment]
Fixed with #924

**Comment by stofte** [comment]
I'm on 4.0.0-preview.40052 and I'm not able to login with either of my accounts (one is a "Personal" and the other "Work").

Using personal account:

Request Id: 86b6d78f-3930-4041-9031-9aa72e822001
Correlation Id: 8e070b79-16ea-406f-aa43-06682a5bf812
Timestamp: 2018-10-01T17:42:57Z
Message: AADSTS50020: User account 'blah' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application '4f28e5eb-6b7f-49e6-ac0e-f992b622da57' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

I'd provide the same error message for my work account, but now the window instantly closes so unable to.
