### ISSUE TITLE
Train and Publish

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotFramework-Emulator#810]
Build: 4.0.218-nightly 

The train and publish links in the Inspector window do nothing for LUIS and QnA. 
For LUIS, the "Recognizer Result" "Raw Response" is blank. For QnA, if you are using the dark theme, you can't read the message in the pane.

**Comment by justinwilaby** [comment]
@Kaiqb  -  Can you please include repro steps and a screenshot of your dev tools console?

**Comment by justinwilaby** [comment]
This is likely fixed with #847  @Kaiqb - Can you confirm?

**Comment by justinwilaby** [comment]
@vishwacsena  - Train and publish do not appear to have a progress indicator associated with the API calls that are made. I recall there being an open ticked to poll the luis API's for progress on the training  process. Until this is completed, it does appear that the Train and Publish buttons do nothing when in fact they are executing long running processes.

**Comment by vishwacsena** [comment]
@justinwilaby - Emulator V4 preview we shipped at //BUILD 2018 had a progress spinner for train and publish as well. See [here](https://www.youtube.com/watch?time_continue=2004&v=MfBPmonJExk)
