### ISSUE TITLE
Emulator: Chat editor, "Restart conversation" button

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/BotFramework-Emulator#814]
We need a refresh button (V3 had it) next to the URL to avoid opening new tabs.

**Comment by vishwacsena** [comment]
@Kaiqb - we have the start over button in the live chat session. 
@mewa1024 - do we have any updates to the design here for release? 

approved. backlog.

**Comment by mewa1024** [comment]
We had this design for Build but it didn't make it into the preview release. Looks basically like this:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/39317542/45703735-044d5e80-bb2a-11e8-9379-afb4c3888eb7.png">

**Comment by mewa1024** [comment]
Comps of the conversation editor have been updated to show all themes.

Light theme: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322684766/preview](url)
Dark theme: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322684765/preview](url)
High contrast: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322684764/preview](url)
