### ISSUE TITLE
View menu text scrub

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#820]
If the explorer is collapsed, it stays collapsed when you click on the “Explorer” menu option. If it is expanded, it stays expanded. It’s not clear what this option is supposed to do.
 
 
![image](https://user-images.githubusercontent.com/20918136/44948661-83c2fa00-add6-11e8-9f02-9786365e51fb.png)

**Comment by mewa1024** [comment]
Please remove **View > Explorer** and **View > Bot Settings**. Also, please change "Actual size" to "Reset Zoom" for consistency with VS Code. 

![image](https://user-images.githubusercontent.com/39317542/45048426-bff19700-b030-11e8-8c0a-139cad4437cc.png)
