### ISSUE TITLE
Add a feature to have random user IDs for each conversation

### ISSUE THREAD

**Issue by blueelvis** [Microsoft/BotFramework-Emulator#821]
Hello,

Right now, the only way to change the user ID is by manually editing the `server.json` which is very inefficient. While testing out the bot, I like to see the conversation flow for a new user. Just ending the conversation doesn't work.

Any chance this could be added? I am using the latest release for v3.

-Pranav

**Comment by vishwacsena** [comment]
@blueelvis - there are no plans to add new functionality to v3. We will evaluate supporting this in v4.

**Comment by sgellock** [comment]
dup of #298
