### ISSUE TITLE
Mentions not working with V4 anymore?

### ISSUE THREAD

**Issue by eTomate** [Microsoft/BotFramework-Emulator#822]
Hi there,
I'm using the BotFramwork V4 Preview with the Emulator V4 Preview.
I remember being able to get something filled into the mentions list with V3, when I adressed the bot with @foobot in the emulator. I didn't find any resources or hints in the source code of the emulator, that this is somehow possible - was this removed? Is there no way to get a mention anymore?

**Comment by dipesh-wadhwa** [comment]
Facing same issue in Bot Emulator version 4.2.1.
Please correct me If I am wrong. I am assuming we don't need to do any settings in Bot Emulator to support mention (@).

**Comment by cwhitten** [comment]
Channel support for channel-specific mentions is something we are considering down the road in future releases.
