### ISSUE TITLE
Emulator: add Endpoint modal should include section for ABS credentials

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#824]
User need to be able to add ABS credentials (*Azure BotId, Azure Directory ID, etc.). Screenshot from build 4.0.256-nightly, using "Bot Explorer" pane, Endpoints group, add button:
![image](https://user-images.githubusercontent.com/39317542/45050671-bf5bff00-b036-11e8-9825-c025cd7d4d86.png)
 
Designs on Invision:
complete flow: 
https://microsoft-fuse-design.invisionapp.com/d/#/projects/prototypes/15256213

Screens of the modal:
https://microsoft-fuse-design.invisionapp.com/d/#/console/15256213/317176504/preview
![image](https://user-images.githubusercontent.com/39317542/45051423-e87d8f00-b038-11e8-855d-5b0b7e7f3f29.png)

https://microsoft-fuse-design.invisionapp.com/d/#/console/15256213/317176502/preview
![image](https://user-images.githubusercontent.com/39317542/45051453-f6331480-b038-11e8-96b6-85e3bc6c97c6.png)

**Comment by mewa1024** [comment]
@justinwilaby Just documenting what we discussed offline: 
-	we are not adding the callouts but will revisit post-Ignite
-	This is the behavior for the Endpoints URL field:
1.	When the modal first appears, the field is not selected and has the placeholder text “http://hostname/api/messages”
2.	When the user starts typing, the placeholder text disappears. When they pause in typing for .5 seconds, this warning text appears below the field: “Remember to include route if necessary: “/api/messages”. The message persists until the text field is no longer in focus
3.	When the user clicks out of the field, we validate that the field isn’t empty. If the field is empty, the text field appears in the the error state and an error message saying “This field cannot be empty”, which replaces the warning.

**Comment by justinwilaby** [comment]
Completed
