### ISSUE TITLE
Emulator UI: Bot Setting modal should disable key field when not checked

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#832]
**Version windows 4.0.0-preview-.39773 (released 9/20 ~3AM)**

In the Bot Settings modal, when encryption is not selected, the section below the checkbox should be disabled and grayed out and the placeholder text should appear. It looks like this:
 
![image](https://user-images.githubusercontent.com/39317542/45834644-908f8b00-bcbc-11e8-85e1-0b2b67ad48ce.png)

but it should look like this:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/39317542/45834969-8cb03880-bcbd-11e8-9f1e-0e5a57b26b43.png">

Screen is here: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/320119845/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/320119845/preview)
Comp of encryption flow is here: [https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15183213](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15183213)

Please note that we are changing the field label of "Key" to "Secret" and "Generate new key" to "Generate new password".

**Comment by mewa1024** [comment]
Also, please don't use ellipsis so users can select into the overflow text to view it.

**Comment by mewa1024** [comment]
Updated designs for the Bot Settings modal:
Encryption off: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/315673917/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/315673917/preview)
Encryption on: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/320119845/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/320119845/preview)

**Comment by mewa1024** [comment]
Updated comp to change the field label of "Key" to "Secret" and "Generate new key" to "Generate new password".

**Comment by tonyanziano** [comment]
This is done.
