### ISSUE TITLE
Emulator UI: status bar is the wrong color and has asterisk symbol

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#834]
Build 4.0.262-nightly

Status bar at the bottom of app has an * and is the wrong color. In light theme:
![image](https://user-images.githubusercontent.com/39317542/45129639-d8010d80-b139-11e8-8b3c-23e2c1948dd8.png)

Dark theme:
![image](https://user-images.githubusercontent.com/39317542/45129666-05e65200-b13a-11e8-86e2-070f63207cea.png)

Should be blue #007acc for all themes. (Was correct in Build version.)

**Comment by tonyanziano** [comment]
Addressed in #915
