### ISSUE TITLE
Conversation ID contains "|livechat" string...

### ISSUE THREAD

**Issue by v-ducvo** [Microsoft/BotFramework-Emulator#836]
**This issue was reported in an email. Moving it here so the issue can be tracked.**
-----
Can you double check if this is intended behavior where the conversation ID has the string “|livechat” appended to it? I’m using the latest nightly build (v4.0.285) of the emulator…

I’m trying to display the conversation ID in a table and the “|livechat” string is throwing my columns off…It’s not an expected value for an ID...currently the ID format is: "GUID|channel"....expected ID value: "GUID"

My question is, is this a valid format for the conversation ID to have the channel name attached to it? Or, is this a bug?

Thank you.

**Comment by sgellock** [comment]
we were not able to repo this.  please reactivate if you are able to repo in the currently released build
