### ISSUE TITLE
Emulator hitting my localhost url even when i open the "production" endpoint

### ISSUE THREAD

**Issue by swagatmishra2007** [Microsoft/BotFramework-Emulator#845]
Repro steps -
1) install emulator (version - 4.0.323)
2) open a bot file downloaded from an azure abs web app bot. 
3) the endpoints tab shows both developement and production. However, on clicking the production endpoint, the emulator tries to hit localhost (and fails)

It should hit my ***.azurewebsites.net endpoint.

**Comment by tonyanziano** [comment]
Swagat and I verified that this was due to a `null` `id` field inside of the endpoint service object in the `.bot` file

**Comment by justinwilaby** [comment]
Is this related to the emulator code or the new [botbuilder-config](https://github.com/Microsoft/botbuilder-js/tree/master/libraries/botframework-config) library that was implemented?
