### ISSUE TITLE
I can't edit the endpoint after edit once, the only way is to restart it if I want to update endpoint

### ISSUE THREAD

**Issue by zongbingwang** [Microsoft/BotFramework-Emulator#849]
After open emulator(V4 PREVIEW), I can get the menu (edit setting, open in emulator, remove) first time. it doesn't show my change to uri and name, and also I can't get the menu when I click right mouse button.

**Comment by justinwilaby** [comment]
Are you able to open the dev tools (ctrl + shift + i) and look in the console for uncaught errors? This would help in diagnosing the issue.
