### ISSUE TITLE
Emulator startup to create unique from id

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotFramework-Emulator#853]
today we have a hardcoded value we use for from.id.  to enable per-emulator OAuth testing, let's add the ability to generate a unique from id and use that value going forward.

**Comment by darrenj** [comment]
Do we know if this is common? They should use the channel property on the activity? Perhaps - it can be a configurable option if we think this will break things?

**Comment by justinwilaby** [comment]
This is probably not that common and if it is the case, we should direct users to use the channel property instead.

**Comment by sgellock** [comment]
I wouldn't block on this.  if there's a .chat file that has default-user it's a simple search and replace, once we teach the customer where we store that value.

**Comment by sgellock** [comment]
PR merged into v4 branch.
