### ISSUE TITLE
File -> close tab is not right

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#867]
With no bot configurations open, File -> close tab does nothing. 

I believe this actually functions as 'close bot' but is named as 'closed tab' which is misleading. 

Tagging this as P0 since this is in Ring 0 UI and is part of core emulator functionality.

**Comment by mewa1024** [comment]
@vishwacsena "Close tab" should close the active tab. If no tabs are open, it should be disabled.
There is no "Close bot"--do we need it?

Related question: should we add "New Window" and "Close Window" to the File menu to allow users to test different bots side-by-side? Seems useful for comparing production versus test bots that are different in more ways than just a local and remote endpoint. That was in the original [wireframe](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14899362/309814584/preview) but it got cut for Build--I can't remember why.

**Comment by mewa1024** [comment]
Ignore my comment above for now and just change the behavior: With no tabs open, the "Close Tab" should be disabled.

**Comment by vishwacsena** [comment]
Moving to backlog based on design assessment.

**Comment by corinagum** [comment]
Resolved with PR #1081
