### ISSUE TITLE
Cannot enter a secret to open an encrypted bot file

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#868]
If you attempt to open an encrypted bot file, emulator throws the enter your secret modal immediately without any help/ guidance on where to find the secret from. 

We should consider adding a link to a topic in emulator readme that will explain where to get the secret from. 

1. If you created your bot using Azure bot service, you can find your bot file secret under app settings for your bot in the [Azure portal](https://portal.azure.com).
2. If users encrypted their bot file using MSBOT, we don't have any key recovery mechanisms in place right now but this would be advanced users. 

We need to nail the ABS path though since all bot files are encrypted by default in the ABS flow.

**Comment by mewa1024** [comment]
Use aka.ms/bot-framework-bot-file-encryption as the link.

**Comment by mewa1024** [comment]
@vishwacsena What about these?
![new bot config modal](https://user-images.githubusercontent.com/39317542/45644679-2932ca80-ba73-11e8-8665-b14888e2a308.png)
![new bot config modal2](https://user-images.githubusercontent.com/39317542/45644704-3485f600-ba73-11e8-8f2a-628072b6dad0.png)
![new bot config modal3](https://user-images.githubusercontent.com/39317542/45644715-38197d00-ba73-11e8-80a8-7fcd86fb619c.png)

Link to README about msbot will describe encryption through the CLI, yes?

**Comment by mewa1024** [comment]
New flow is on Invision: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15183213/315673905/preview](url)

**Comment by vishwacsena** [comment]
People are hitting this often and has come up in the bug bash as well. Bumping up to P0.

**Comment by mewa1024** [comment]
"Submit" button is stuck in disabled state. Repro:
(1) open encrypted .bot file
(2) modal opens
(3) enter secret into the field
(4) "Submit" button stays disabled (tried clicking out of the field, hitting Enter, and toggling Show/Hide--nothing enabled the button)

![image](https://user-images.githubusercontent.com/39317542/45833821-8076ac00-bcba-11e8-897c-bab6257a0a93.png)

(There also polish changes to this modal that I field as #908 before I noticed this behavior.)

**Comment by vishwacsena** [comment]
all the downloadable versions at https://github.com/Microsoft/BotFramework-Emulator/releases <https://github.com/Microsoft/BotFramework-Emulator/releases>   (up to 4.0.0-preview-2.39744 <https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.0.0-preview-2.39744>

**Comment by justinwilaby** [comment]
Fixed with #909
