### ISSUE TITLE
CLI arguments to specify endpoint, appid and password

### ISSUE THREAD

**Issue by edteke** [Microsoft/BotFramework-Emulator#87]
My bot web application project in Visual Studio has as start action running an external program: the emulator app. It would be nice to have the option to set the endpoint url and other settings from command line arguments: 

![image](https://cloud.githubusercontent.com/assets/5659816/22374448/398ab32e-e474-11e6-835d-ce8bf3e3cf6b.png)

**Comment by eanders-MS** [comment]
Great idea, thanks for logging it here. I will add it to the backlog.

**Comment by gareththackeray** [comment]
@eanders-MS while you're adding command line args it would also be great if you could specify the port that the HTTP server listens on.

**Comment by eanders-MS** [comment]
@gareththackeray That seems reasonable, thanks.  This feature was recently prioritized up. I should be able to get to it in the next few weeks.

**Comment by vishwacsena** [comment]
@tonyanziano - I believe this should be possible in V4 with protocol activation? If so, can you update this issue with details and resolve?

**Comment by tonyanziano** [comment]
Yes, this will be possible once we push out the next release of v4 (v4.0.16-alpha). I'll update this once it is out.

**Comment by sgellock** [comment]
Let's update this ticket to include the protocol and then we can close it.

**Comment by tonyanziano** [comment]
The protocol to start a livechat session inside of the emulator with a specified endpoint is as follows:


**Protocol:**

`bfemulator://domain.action[?param_n[&param_n+1]*]`

**NOTE:** Parameters **must be** URL encoded.

- **domain:** `livechat`
- **action:** `open`
- **params:** any combination of the following endpoint properties:
  - **endpoint:** URL to use for your bot's endpoint
  - **appId:** Microsoft App ID for your bot's endpoint
  - **appPassword:** Microsoft App password for your bot's endpoint

**Example**

Connecting to a local bot running on **http://localhost:3500** with MSA App ID **id123** and MSA App password **pw123**.

`bfemulator://livechat.open?endpoint=http%3A%2F%2Flocalhost%3A3500&appId=id123&appPassword=pw123`

(Notice how `http://localhost:3500` was encoded to `http%3A%2F%2Flocalhost%3A3500`)
