### ISSUE TITLE
'Reset' for encryption key is not the right word. 

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#870]
![image](https://user-images.githubusercontent.com/20918136/45569598-d2c85080-b814-11e8-951a-8e56aa65e2c4.png)

'Reset' is not the right word here. What we are actually doing is to re-generate a new key. So something like 'Renew' or something similar would be a better word.

**Comment by mewa1024** [comment]
Change to "Generate new key". Adding this to bug #832.

**Comment by sgellock** [comment]
comment to change wording added to #832
