### ISSUE TITLE
Emulator should provide a user-friendly error when .bot file is invalid

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/BotFramework-Emulator#874]
Now, when .bot files are invalid, the user selects the .bot file and the emulator:

1) Does not load the file and stays in the start page as if nothing happened
2) Does not provide a user friendly error message

The Emulator **should**:

- Provide a helpful error to the user such as, at the very least, a generic "The bot file provided is invalid, please contact bot framework tools support at this URL <github repo URL>" or similar.

For this specific issue, Tom already addded support for default cognitive services. Otherwise, when we ship new features, and they flow into our .bot files, users will get failures everywhere until they upgrade the emulator.

**Comment by vishwacsena** [comment]
@carlosscastro - can you attach the invalid bot file here for repro?

**Comment by carlosscastro** [comment]
@vishwacsena We fixed the file to identify the issue so we don't have it ready. Vishwac and I just talked in person, we are going to try to repro creating a bot in ibiza.

**Comment by vishwacsena** [comment]
The flow through ABS portal worked for me with the latest emulator. 

For the generic issue with invalid bot file, let's look at adding it to bot configuration library so emulator can rely on that.

**Comment by sgellock** [comment]
Only known remaining issue is the LUIS version info, which is being tracked with a separate issue
