### ISSUE TITLE
Wrong value displayed in chat header for endpoints

### ISSUE THREAD

**Issue by willportnoy** [Microsoft/BotFramework-Emulator#877]
![image](https://user-images.githubusercontent.com/17912714/45571391-e37bc500-b81a-11e8-9a5b-2100c03c6aec.png)

**Comment by vishwacsena** [comment]
@willportnoy - can you attach your bot file?

**Comment by willportnoy** [comment]
@vishwacsena are there secrets in my bot file?

**Comment by vishwacsena** [comment]
@justinwilaby; @tonyanziano I have a repro for this. Will email you the .bot file.
