### ISSUE TITLE
Suggestion for setting up ngrok could be more obvious

### ISSUE THREAD

**Issue by ToddN** [Microsoft/BotFramework-Emulator#878]
When I flipped from development to production and tried to talk to the bot I get 
"Error: The bot is remote, but the service URL is localhost. Without tunneling software you will not receive replies.
Connecting to bots hosted remotely
Edit ngrok settings"
Both the "Connectign bots hosted remotely" and the "Edit ngrok settings" were underlined.  But it wasnt' clear to me that I should click on "Edit ngrok settings."  

It would help if it said "Without tunneling software you will not receive replies. Configure ngrok".

**Comment by justinwilaby** [comment]
We should look into using https://www.npmjs.com/package/ngrok so users do not have the currently required step of downloading and configuring ngrok manually

**Comment by vishwacsena** [comment]
We should revisit the text to make it more actionable and possibly include a link to settings so users can configure ngrok.

**Comment by mewa1024** [comment]
What was the change to the text?
