### ISSUE TITLE
ConversationDelete system message seems to be sending HTTP DELETE?

### ISSUE THREAD

**Issue by jameslew** [Microsoft/BotFramework-Emulator#881]
used the emulator to interact with Echo bot and was testing the conversation system messages.  I sent a conversationUpdate with 'remove' user and the output in the emulator says DELETE 501 emulator.remove.  Are we really sending a HTTP DELETE to the bot?

**Comment by jameslew** [comment]
Repro:

1) Load your bot to talk to
2) Conversation menu
3) Send System Activity
4) ConversationUpdate (remove user)

**Comment by tonyanziano** [comment]
Yes we are sending a DELETE. This is the exact same functionality that V3 had for removing a user.

**Comment by justinwilaby** [comment]
HTTP DELETE is correct for removing users since we follow RESTful best practices.

**Comment by sgellock** [comment]
v4 matches v3 behavior.
