### ISSUE TITLE
Speech support in emulator for all bots

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#884]

**Comment by compulim** [comment]
Talked to @vishwacsena offline. The behavior is correct:

- Flighted bots
   - Emulator (connected to bots with app ID and password)
   - Embed (which include "Test in Web Chat" blade)
   - ~CDN~
   - ~NPM~
- Provide your own Cognitive Services Speech key
   - ~Emulator~ (no way to provide key)
   - ~Embed~ (no way to provide key)
   - CDN
   - NPM

Post-Ignite, we will create a better story about speech token, which is more likely:

- Everyone
   - Emulator
   - Test in Web Chat
   - Embed (a way to provide key)
   - CDN (as of today: a way to provide key)
   - NPM (as of today: a way to provide key)
