### ISSUE TITLE
Emulator notifications panel should show a message when there are no notifications to display

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#886]
Right now, we show a blank panel. 

can we finalize the copy and hand over to Tony for implementation?

**Comment by mewa1024** [comment]
"No new notifications." Design in Invision: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14909104/320419756/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14909104/320419756/preview)

**Comment by tonyanziano** [comment]
Addressed in #967
