### ISSUE TITLE
EMULATOR: Remove  "Toggle Developer Tools" items from the "Help" menu

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#888]
There are two items and the second one doesn't seem to do anything.

Screenshot from Mac build 4.0.316-alpha2, (but this also appears in Windows 4.0.474-nightly):
![image](https://user-images.githubusercontent.com/39317542/45645084-46b46400-ba74-11e8-8b47-f5d1c2576017.png)

**Comment by justinwilaby** [comment]
The inspector dev tools toggle is used when an inspector is present in the extensions panel.

**Comment by mewa1024** [comment]
@vishwacsena @justinwilaby Can we reopen this and move to backlog? (1) It's not obvious what it does, so it seems like an advanced feature, and (2) having to navigate back to the Help menu isn't the greatest UI for a toggle. If it is a useful feature that is used frequently, a keyboard shortcut would be better.

**Comment by justinwilaby** [comment]
@mewa1024 - debugging the emulator internals is probably not something that is necessary often. When it is necessary, there are other ways to connect a debugger which does't involve explicit menu options. I vote to remove both menu items entirely.

**Comment by mewa1024** [comment]
@vishwacsena v4.2?

**Comment by vishwacsena** [comment]
The fix here is to remove the dev tools menu.

**Comment by corinagum** [comment]
Resolved with PR #1081
