### ISSUE TITLE
Emulator: design polish

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#895]
**Version**
 Mac: Emulator_OSX_v4.0.0-preview.40025_40380

Issues:
- **Start Over** and **Save Transcript As...** should be buttons (moved from #892)
- Fuzzy icons (moved from #892 )
- for high contrast, in the sidebars, the borders should be between groups, not below the group name. screenshot:
![image](https://user-images.githubusercontent.com/39317542/46313959-1a253f80-c57e-11e8-8f15-016cb976f615.png)
**Sidebar/nav2 design, high contrast**: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/310014251/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/310014251/preview)
**Layout, high contrast**: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322684764/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322684764/preview)

**Comment by tonyanziano** [comment]
Adding to this:

I noticed if the Emulator window is very small, flexbox styling on our `<GenericDocument>` component (template for Welcome Page and App Settings Page) causes some strange content "scrunching".

![image](https://user-images.githubusercontent.com/3452012/45894476-4fae7980-bd83-11e8-8dbe-c1c8d113e71c.png)

**Comment by corinagum** [comment]
@mewa1024 Can I clarify with you which icons are fuzzy? To me it looks like we're talking about the NavBar (far left) icons, but I want to make sure I'm not missing any.

**Comment by mewa1024** [comment]
@corinagum @vishwacsena Vishwac, which icons were fuzzy for you? Were they the file type icons or the nav bar? (The fuzzy icon comment was from the original bug #892)

**Comment by corinagum** [comment]
@mewa1024 Hi Melanie, I noticed in the old bug (#892) there's a comment saying 'In the lower "Log" section the text looks like links (ie POST and 202) but they aren't links/buttons. Moved to #895'

Should I fix the Log 'links' in appearance? I believe there aren't specs for the log section, please let me know if I'm wrong!
