### ISSUE TITLE
Replacing JSON quotes with slanted quotes 

### ISSUE THREAD

**Issue by diberry** [Microsoft/BotFramework-Emulator#897]
The bot emulator 4.0.501-nightly version.

If I print something out via dc.context.sendActitive({"text":"author of hrf-546234?"}), the bot emulator replaces the quotes with slanted quotes {“text”:“author of hrf-546234?”}

Is there a setting to turn this replacement off?

**Comment by compulim** [comment]
Markdown-It engine in Web Chat will automatically convert standard quotes in smart quotes.

https://github.com/Microsoft/BotFramework-WebChat/issues/1102

To skip the Markdown engine, when you send the activity, set `textFormat` to `plain`. More information can be found in this article, https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#activity-object.
