### ISSUE TITLE
Transcript Explorer is locking whole directory

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/BotFramework-Emulator#900]
When emulator is started it is locking whole directory tree based on where .bot config file is stored. That means if it is in project directory, it is unable to do anything with node_modules because they are locked by emulator!

**Comment by justinwilaby** [comment]
This is expected behavior. Each directory is being watched for changes and thus is locked by the OS. It's always best not to have transcripts or the bot file in a project directory

**Comment by diberry** [comment]
@justinwilaby Is the idea that anything you need to edit should be done through emulator?
