### ISSUE TITLE
Emulator: Transcripts not saved in "transcripts" folder do not appear in side nav

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#906]
Build: 4.0.0-preview-2.39744

Saving a conversation to a transcript does not appear in the Resources tab unless you save it to a folder named "transcripts". Saving transcripts to "transcripts" folder should be the default. Also, the Resources Settings icon is hidden. Should be a gear on the Resources tab.

Repro:
(1) open bot conversation.
(2) click "Save Transcript As". File browser appears:
![image](https://user-images.githubusercontent.com/39317542/45798465-d453a780-bc5e-11e8-933f-0c1f7d3dd169.png)
(3) Resource tab doesn't show saved transcript:
![image](https://user-images.githubusercontent.com/39317542/45798505-fd743800-bc5e-11e8-9af1-d420f4dd3636.png)
(4) Open bot settings by clicking on the icon. Icon is missing and default locations are blank:
![image](https://user-images.githubusercontent.com/39317542/45798613-5e9c0b80-bc5f-11e8-830c-6b5ea326a1c3.png)

Design for Resource settings:
[https://microsoft-fuse-design.invisionapp.com/d/main#/console/15012340/317169771/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15012340/317169771/preview )

**Comment by justinwilaby** [comment]
@mewa1024  - Great catch and AWESOME repro steps!

**Comment by justinwilaby** [comment]
Fixed with #913

**Comment by mewa1024** [comment]
Behavior as fixed:
1. User opens a bot file and connects to endpoint.
2. User hits "Save transcript...", which opens the file browser to the local folder. User saves .transcript file here.
3. User opens "Transcript" pane and it is blank.
4. User has to click on the settings (gear icon) to change the transcript folder location for the transcript they just saved to appear in this pane.

I think we'd discussed changing the behavior so that the location of the first transcript that is saved is the default location for the Transcripts folder. Can we do that? Also, can we make the Resource settings modal 600 px? The file path gets cut off.

Screenshots of the current behavior below:

![screen shot 2018-10-01 at 9 47 56 am](https://user-images.githubusercontent.com/39317542/46303448-b9d3d500-c560-11e8-93b4-480639e2368a.png)
![screen shot 2018-10-01 at 9 48 02 am](https://user-images.githubusercontent.com/39317542/46303452-bd675c00-c560-11e8-943b-c6db675c6941.png)
![screen shot 2018-10-01 at 9 48 05 am](https://user-images.githubusercontent.com/39317542/46303462-c5bf9700-c560-11e8-949a-410b28a5dff4.png)
![screen shot 2018-10-01 at 9 48 29 am](https://user-images.githubusercontent.com/39317542/46303466-c8ba8780-c560-11e8-97d8-230aae6568a1.png)
![screen shot 2018-10-01 at 9 49 32 am](https://user-images.githubusercontent.com/39317542/46303476-cc4e0e80-c560-11e8-8a9c-6b830c76990b.png)
![screen shot 2018-10-01 at 9 50 13 am](https://user-images.githubusercontent.com/39317542/46303483-cf48ff00-c560-11e8-95ce-abe699b8fa7b.png)
![screen shot 2018-10-01 at 9 50 48 am](https://user-images.githubusercontent.com/39317542/46303488-d3751c80-c560-11e8-9fb4-64847d60c0bc.png)
![screen shot 2018-10-01 at 9 50 53 am](https://user-images.githubusercontent.com/39317542/46303490-d6700d00-c560-11e8-9142-39143da7db18.png)
![screen shot 2018-10-01 at 9 50 59 am](https://user-images.githubusercontent.com/39317542/46303493-d96afd80-c560-11e8-99d0-fee4722af636.png)
