### ISSUE TITLE
Emulator: "Sign in with Azure" sign in flow does not appear with File > Sign in

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#911]
**Windows build 4.0.0-preview-.39773**

Attempting to sign with Azure with **File > Sign in** or the link on the Welcome page opens the intro modal screen (that tells you about signing in) but not the subsequent modals for actually signing in to Azure. However, signing in via adding a service from the services pane does open the sign in flow.

**Repro steps for File > Sign in (or using the link the Welcome page):** 
(1) cleared cookies
![screenshot 178](https://user-images.githubusercontent.com/39317542/45842253-f84fd100-bcd0-11e8-91f4-545f41e755f8.png)

(2) opened Emulator
![screenshot 179](https://user-images.githubusercontent.com/39317542/45842261-0271cf80-bcd1-11e8-88e7-685c4c8e9964.png)

(3) clicked on **File >Sign in with Azure** and the intro modal opened:
![screenshot 181](https://user-images.githubusercontent.com/39317542/45842293-259c7f00-bcd1-11e8-8b19-951c54444846.png)

(4) Clicking the primary button in the intro modal closed the modal, but then nothing happened:
![screenshot 183](https://user-images.githubusercontent.com/39317542/45842363-609eb280-bcd1-11e8-8ddd-51a34e1fa851.png)

**Repro step for signing in through the services pane:**

(1) open a bot

(2) open the Bot Explorer pane, next to the Services group, click the + button to add a service:
![screenshot 187](https://user-images.githubusercontent.com/39317542/45842952-0a327380-bcd3-11e8-9a8b-367e1e987159.png)

(3) modal appears asking if you'd like to sign in to azure:
![screenshot 188](https://user-images.githubusercontent.com/39317542/45842983-23d3bb00-bcd3-11e8-984c-201347856ce5.png)

(4) sign in flow starts:
![screenshot 189](https://user-images.githubusercontent.com/39317542/45843023-4534a700-bcd3-11e8-99cb-96b83ab2153d.png)
![screenshot 190](https://user-images.githubusercontent.com/39317542/45843032-4bc31e80-bcd3-11e8-97a7-ed4dc3af571e.png)
![screenshot 191](https://user-images.githubusercontent.com/39317542/45843036-51206900-bcd3-11e8-85d6-fdbbe8e10fb0.png)
![screenshot 192](https://user-images.githubusercontent.com/39317542/45843044-55e51d00-bcd3-11e8-93c6-9528d516ad32.png)
![screenshot 193](https://user-images.githubusercontent.com/39317542/45843047-58e00d80-bcd3-11e8-8ac5-71e214b35718.png)
![screenshot 195](https://user-images.githubusercontent.com/39317542/45843054-5e3d5800-bcd3-11e8-9c17-246bbd309388.png)
![screenshot 196](https://user-images.githubusercontent.com/39317542/45843063-61d0df00-bcd3-11e8-9ba5-c9148e730b98.png)
![screenshot 197](https://user-images.githubusercontent.com/39317542/45843092-7319eb80-bcd3-11e8-99c2-4ec5e5c6e757.png)

(Not sure why sign in failed, was looking in the Microsoft tenant? I was using a non-Microsoft Azure account.)

**Comment by justinwilaby** [comment]
#913  fixes this as well [here](https://github.com/Microsoft/BotFramework-Emulator/pull/913/files#diff-5277a5288b57ac6ba87e0d94f7cdba05)

**Comment by justinwilaby** [comment]
fixed with #913
