### ISSUE TITLE
Couldn't open a transcript file from the file menu

### ISSUE THREAD

**Issue by muges01** [Microsoft/BotFramework-Emulator#922]
Hi guys,

I'm getting the following error when i try to open a transcript file using the File > Open Transcript..

> "Error creating a new conversation in transcript mode: Error: Error while feeding transcript on disk to conversation: Unexpected token <?> in JSON at position 0."

However, the same transcript file is loaded correctly if i open directly from the transcript folder by double clicking on it.

My Bot Framework Emulator version: **4.0.0-preview.39916**

Please advice me, if this is a bug or I'm doing something wrong.

**Comment by tonyanziano** [comment]
Hey @muges01 ,

Is there any way you could share the transcript with us so that we can try to reproduce the issue and diagnose what's going on?

**Comment by muges01** [comment]
Hi 

This is the transcript.

`[
  {
    "conversation": {
      "id": "g0WFa33GqGxS5CyOmO4SJ6FuVSQ="
    },
    "id": "1",
    "recipient": {
      "id": "2q+DFNKOqsqky+3VlYQ22QBSUfw=",
      "name": "testbot",
      "role": "bot"
    },
    "from": {
      "id": "g0WFa33GqGxS5CyOmO4SJ6FuVSQ="
    },
    "timestamp": "2018-09-22T11:28:04.100Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "2q+DFNKOqsqky+3VlYQ22QBSUfw=",
        "name": "testbot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "g0WFa33GqGxS5CyOmO4SJ6FuVSQ="
    },
    "id": "2",
    "recipient": {
      "id": "2q+DFNKOqsqky+3VlYQ22QBSUfw=",
      "name": "testbot",
      "role": "bot"
    },
    "from": {
      "id": "MP62PdyK3TJmYra86l6g0NflEyM=",
      "name": "muges",
      "role": "user"
    },
    "text": "hi",
    "timestamp": "2018-09-22T11:28:06.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "g0WFa33GqGxS5CyOmO4SJ6FuVSQ="
    },
    "id": "3",
    "recipient": {
      "id": "MP62PdyK3TJmYra86l6g0NflEyM=",
      "name": "muges",
      "role": "user"
    },
    "from": {
      "id": "2q+DFNKOqsqky+3VlYQ22QBSUfw=",
      "name": "testbot",
      "role": "bot"
    },
    "text": "Hello, i'm the sai bot. How can i help you?",
    "timestamp": "2018-09-22T11:28:08.100Z",
    "type": "message",
    "channelId": "chatdown"
  }
]`

**Comment by justinwilaby** [comment]
This error is likely due to the presence of a BOM in the json you're trying to open. This happens when the json is created using a powershell terminal which is the default terminal in VSCode and Visual Studio. Removing the BOM should do the trick.

**Comment by justinwilaby** [comment]
Using the above transcript, I am unable to repro this error. Adding a BOM to the file *does* repro this error. The fix is to remove the BOM from the json

**Comment by muges01** [comment]
How do i remove the BOM from the json. 

This json file was generated using 

> chatdown "{file path}" > {new transcript file path}
