### ISSUE TITLE
Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by NKZ82** [Microsoft/BotFramework-Emulator#931]
I used chatdown **v1.0.9-20** to convert a very simple .chat file into a .transcript file.

I got the following error when I open the .transcript file in Bot Framework Emulator (**4.0.0-preview.40025**)
_Error creating a new conversation in transcript mode: Error: Error while feeding transcript on disk to conversation: Cannot read property 'role' of undefined_

I don't know if it's related to **chatdown** or **Bot Framework Emulator**.

![image](https://user-images.githubusercontent.com/6066754/46121087-2442e900-c1e0-11e8-9c9b-9432b0ef1d56.png)

Here the .chat file:
```
user=vishwac
bot=cafebot

user: hi
bot: Hello, I'm the contoso cafe bot. How can I help you?
```

Here the .transcript file generated by chatdown:
```
[
  {
    "conversation": {
      "id": "zH4ddZX/tW5AO1SKWmRinDick9M="
    },
    "id": "1",
    "timestamp": "2018-09-27T02:20:18.100Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
        "name": "cafebot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "zH4ddZX/tW5AO1SKWmRinDick9M="
    },
    "id": "2",
    "recipient": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "from": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "text": "hi",
    "timestamp": "2018-09-27T02:20:20.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "zH4ddZX/tW5AO1SKWmRinDick9M="
    },
    "id": "3",
    "recipient": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "from": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "text": "Hello, I'm the contoso cafe bot. How can I help you?",
    "timestamp": "2018-09-27T02:20:22.100Z",
    "type": "message",
    "channelId": "chatdown"
  }
]
```

**Comment by justinwilaby** [comment]
This is a known issue with chatdown. Updating to 1.0.10 fixes this problem. As a workaround, the emulator uses this version under the hood and can convert .chat files into transcripts and feed them into the chat window automatically. To do this: 

1. open a bot file in the emulator
2. click on the resources icon
![image](https://user-images.githubusercontent.com/2652885/46159781-fab4ac80-c235-11e8-992c-1167dc252941.png)
3. Click on the cogwheel to open the settings dialog and browse to the location of the directory that your chat files are in.
![image](https://user-images.githubusercontent.com/2652885/46159857-30599580-c236-11e8-9fb9-fcc7e442cf3a.png)
4. Click OK 
5. you should now see your chat files in the scripts pane. Clicking on the chat will convert it to a transcript and display it in the chat window
![image](https://user-images.githubusercontent.com/2652885/46159978-7282d700-c236-11e8-86f1-008b8fcb8253.png)

**Comment by sorgina13** [comment]
My Bot Emulator didn't let me click the resources icon . I downloaded version 4.1.0 and now it shows 'choose a different location' under transcripts and chats but when I click nothing happens. I still can't open the transcript files! Please help?

**Comment by nicojdejong** [comment]
@sorgina13 - 'I have the same problem. it says you dont have any chat files in . ' After I open a .bot file though it starts working. I can then close the .bot file and it continuous to work.

**Comment by paulfitz72** [comment]
I get the original error with version 4.5.2 of the emulator and the new chatbot cli with bf chatdown

**Comment by tonyanziano** [comment]
Thanks @paulfitz72 for reporting this. I'll try this version combination out.

**Comment by tonyanziano** [comment]
@paulfitz72 I was unable to reproduce this with `botframework-cli@4.5.4` and both version 4.5.2 of the Emulator, and the newest nightly build.

**test.chat**

```
user=Tony
bot=MrBot

user: Hey bot!
bot: Hello Tony!
```

**generated test.transcript**

```
[
  {
    "conversation": {
      "id": "8g3mrSOCs+ReSF5moEvcCuHIXFA="
    },
    "id": "1",
    "recipient": {
      "id": "s1KG+2yGBuF6atkrwxuBbNQFj7g=",
      "name": "MrBot",
      "role": "bot"
    },
    "from": {
      "id": "yPqMtPiPeEhc5+BFOsDUOAJrxbs=",
      "name": "Tony",
      "role": "user"
    },
    "timestamp": "2019-10-09T22:26:47.100Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "s1KG+2yGBuF6atkrwxuBbNQFj7g=",
        "name": "MrBot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "8g3mrSOCs+ReSF5moEvcCuHIXFA="
    },
    "id": "2",
    "recipient": {
      "id": "s1KG+2yGBuF6atkrwxuBbNQFj7g=",
      "name": "MrBot",
      "role": "bot"
    },
    "from": {
      "id": "yPqMtPiPeEhc5+BFOsDUOAJrxbs=",
      "name": "Tony",
      "role": "user"
    },
    "text": "Hey bot!",
    "timestamp": "2019-10-09T22:26:49.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "8g3mrSOCs+ReSF5moEvcCuHIXFA="
    },
    "id": "3",
    "recipient": {
      "id": "yPqMtPiPeEhc5+BFOsDUOAJrxbs=",
      "name": "Tony",
      "role": "user"
    },
    "from": {
      "id": "s1KG+2yGBuF6atkrwxuBbNQFj7g=",
      "name": "MrBot",
      "role": "bot"
    },
    "text": "Hello Tony!",
    "timestamp": "2019-10-09T22:26:51.100Z",
    "type": "message",
    "channelId": "chatdown"
  }
]
```
