### ISSUE TITLE
Emulator - add support for enumerating/ adding blob, cosmos db storage providers

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#934]
Bot file supports keeping track of blob and cosmos db storage providers are service configurations. 

Emulator does not support this today - both through the Login flow as well as the non-login manual mode. 

Filing this ticket to track the work to add support in emulator for storage providers.

**Comment by mewa1024** [comment]
Required fields in the msbot connect blob:
- friendly name (defaults to serviceName)
- Azure Tenant id (either GUID or xxx.onmicrosoft.com)
- Azure Subscription Id
- Azure resource group name
- Azure service name
- Blob storage connection string
- blob container name

**Comment by mewa1024** [comment]
@justinwilaby Hi Justin, a few corrections to text.
In the link to the Azure portal, 
- please exclude the word "the" from the link.
- Please remove the words "Azure Storage" altogether, so the text should be "the **Azure portal**." with "Azure portal" as the linked text.
- Please add a period to the end of the sentence

Please use semibold for all the links (the accessibility people require a font weight change for links in text, so this should be the style throughout the Emulator:

![image](https://user-images.githubusercontent.com/39317542/49673631-efdf7a80-fa23-11e8-8ea5-f120f489463b.png)

should look more like this (minus the pink annotations):
![image](https://user-images.githubusercontent.com/39317542/49673895-f1f60900-fa24-11e8-99b4-301ecf9471af.png)

**Comment by mewa1024** [comment]
@justinwilaby plus the deep link to the service doesn't work and then context menu doesn't appear.

**Comment by tonyanziano** [comment]
Addressed in #1164
