### ISSUE TITLE
Emulator - add support for app insights service configuration

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#935]
Bot file supports keeping track of app insights service configuration. 

Emulator does not provide any affordance at all to manage this today (both through the azure login flow as well as through manual mode). 

Filing this ticket to track the work for emulator to support app insights service configuration.

**Comment by mewa1024** [comment]
@vishwacsena 
Can you confirm that this is the right flow? Using the QnA Maker/LUIS/Dispatch flow as a model:

Modals for adding a Service X when:
(A) user has signed into Azure, and user has a Service X service **- user picks from a list**
(C) user has not signed into Azure - **gets modal to sign in or connect manually**
(D) user adds app by entering required fields - **modal with fields to enter manually**

And these are the fields required (according to the [doc for msbot connect appinsights](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/add-services.md#connecting-to-azure-appinsights-service)):
- Name (defaults to serviceName)
- Azure Tenant id (either GUID or xxx.onmicrosoft.com)
- Azure Subscription Id
- Azure resource group name
- Azure service name
- App Insights Instrumentation Key
- (OPTIONAL) App Insights Application Id

Comps of the modals are here:
https://microsoft-fuse-design.invisionapp.com/d/#/projects/prototypes/14863139 (look in App Insights section)

Other questions:
- the LUIS, QnA, and Dispatch flows had links to create those services and learn more. Do we want to do the same for App Insights and storage? Might be necessary for Azure resources that are not specifically bot-related.
- Also, Azure App Insights is being rebranded as Azure Monitor. Do we care? https://docs.microsoft.com/en-us/azure/azure-monitor/azure-monitor-rebrand

**Comment by vishwacsena** [comment]
@mewa1024 - this is great and yes following along the patterns established by the current flows for LUIS, QnA and dispatch is the right model for other service types. Yes, we should have pointers to doc pages for the respective services. We can have it be application insights for now and update the copy later if needed.

**Comment by mewa1024** [comment]
@vishwacsena Cool. Assigning to Justin.

**Comment by mewa1024** [comment]
@justinwilaby I updated the designs with the links:
Link: https://aka.ms/bot-framework-emulator-create-appinsights
Link: https://aka.ms/bot-framework-emulator-appinsights-docs
Link: https://aka.ms/bot-framework-emulator-appinsights-keys

Updates to the designs are on Invision and also copied below:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/39317542/48733959-e3bc8600-ebf8-11e8-8d59-60487f6d8981.png">

<img width="843" alt="image" src="https://user-images.githubusercontent.com/39317542/48734047-2a11e500-ebf9-11e8-99ea-b92376292f90.png">

<img width="757" alt="image" src="https://user-images.githubusercontent.com/39317542/48734195-9856a780-ebf9-11e8-9167-e74d7ef8f375.png">

**Comment by mewa1024** [comment]
@justinwilaby I have found a few typos in the comps and just corrected them. Sorry about this:

- changed the wording in the Azure picker modal from "Select a resource below to your resource's information in your bot file or connect to an Application Insights resource manually" to "Select a resource below or connect to an Application Insights resource manually."

- changed the wording in the Azure picker modal from "Create a new Application Insights service." to "Create a new Application Insights resource."

<img width="873" alt="image" src="https://user-images.githubusercontent.com/39317542/48744270-740bc280-ec1b-11e8-9cd4-9b46d8df2365.png">



- changed the wording in the not-signed-in-yet modal from "Alternatively, you can connect to an Azure Application Insights resource manually with the app ID, version, and authoring key" to "Alternatively, you can connect to an Azure Application Insights resource manually. "

<img width="810" alt="image" src="https://user-images.githubusercontent.com/39317542/48744291-8423a200-ec1b-11e8-81f0-9af8d5c87070.png">

**Comment by mewa1024** [comment]
@justinwilaby similar issues as #934.
In the link to the Azure portal,
-    please exclude the word "the" from the link.
-   Please remove the words "App Insights " altogether, so the text should be "the Azure portal." with "Azure portal" as the linked text.
-    Please add a period to the end of the sentence

Please use semibold for all the links (the accessibility people require a font weight change for links in text, so this should be the style throughout the Emulator.

Also, the deep link to App Insights is not working.

**Comment by mewa1024** [comment]
@justinwilaby One more thing, the modal is looking for "Azure Subscription Key" instead of "Azure Subscription ID". This means the modal is showing the field as blank, even though the .bot file has an entry for "subscriptionId":

![image](https://user-images.githubusercontent.com/39317542/49677893-fb3ba180-fa35-11e8-9e0f-c56feaf26382.png)

**Comment by tonyanziano** [comment]
Addressed in #1160
