### ISSUE TITLE
Emulator - add support for generic service configuration

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#936]
Bot file supports keeping track of a generic service that the bot depends on. 

Emulator today does not support adding/ managing generic service type. 

Filing this ticket to track the work to add this capability to Emulator.

**Comment by mewa1024** [comment]
@vishwacsena 
Design of the flow is in the "Generic 11.26" section on Invision: 
[Services flow](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/14863139) 

Unassigning myself. Let me know if there are changes.

**Comment by mewa1024** [comment]
@justinwilaby 

1. The key-value pair table does not let me type in it. Tried this on both Mac and Windows. Windows screenshot here:

![image](https://user-images.githubusercontent.com/39317542/49674983-975eac00-fa28-11e8-9443-8d2f4ae1f2a9.png)

The field is selected, but I can't type.

2. "Key" and "Value" should be column headers so "Value" should be left-aligned to "Add a value (optional)".
