### ISSUE TITLE
Add Service is missing a bunch of services

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Emulator#943]
## Version
What version of the Emulator are you using.

## Describe the bug
When I click Add Service, it shows this:
![image](https://user-images.githubusercontent.com/17789481/46260437-b544e900-c49a-11e8-9800-a8756184bacb.png)

## Expected behavior
I expected this list:
* appinsights  connect to Azure AppInsights
* blob         connect to Azure Blob storage
* bot          connect to Azure Bot Service
* cosmosdb     connect to Azure CosmosDB
* dispatch     connect to a Dispatch model
* file         connect to file to the bot
* generic      connect to generic service configuration
* luis         connect to a LUIS application
* qna          connect to QNA a service

[bug]

**Comment by vishwacsena** [comment]
Remaining services are tracked via #934 #935 #936
