### ISSUE TITLE
Emulator: Transcripts not saved in "transcripts" folder do not automatically appear in side nav

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#944]
### Moved from #906 "Emulator: Transcripts not saved in "transcripts" folder do not appear in side nav"

**Version**
Mac: Emulator_OSX_v4.0.0-preview.40025_40380

Behavior as fixed is still a little confusing, as user has to change Resource settings for transcript to appear in sidebar.

**Changes:**
- empty state for transcripts: "No transcripts were found in **transcripts\*<default location for transcripts is a "transcripts" folder in .bot file location>." plus text below that says "Choose a different location".
- empty state for chat files: "No chat files were found in **dialogs\resources\**\*<default location for chat files>." plus text below that says "Choose a different location".
- not empty state: the chat/transcripts are listed, and the text "Choose a different location" always appears.
- user clicks "Choose a different location" and "Resource settings" modal appears.
- remove gear icon from "Resource" sidebar name, since the modal is accessed through the link instead.
- change group name "Scripts" to "Chat files" to match Chatdown docs (and per #962)

![resources revised - 01](https://user-images.githubusercontent.com/39317542/47051166-f1916e00-d157-11e8-8a2b-03137ab409a6.png)
![resources revised - 02](https://user-images.githubusercontent.com/39317542/47051179-feae5d00-d157-11e8-8aa2-2f4f17fbc135.png)
![resources revised - 03](https://user-images.githubusercontent.com/39317542/46977452-2383d100-d081-11e8-8f66-5384102d76b5.png)
![resources revised - 04](https://user-images.githubusercontent.com/39317542/46977460-27175800-d081-11e8-8d7c-673aa4eb0450.png)
![resources revised - 05](https://user-images.githubusercontent.com/39317542/46977465-2aaadf00-d081-11e8-8110-6108f3b73f75.png)

updated specs on Invision: [https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15012340](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/15012340)

Repro steps of old experience:
1. User opens a bot file and connects to endpoint.
2. User hits "Save transcript...", which opens the file browser to the local folder. User saves .transcript file here.
3. User opens "Transcript" pane and it is blank.
4. User has to click on the settings (gear icon) to change the transcript folder location for the transcript they just saved to appear in this pane.

Screenshots of the current behavior below:

![screen shot 2018-10-01 at 9 47 56 am](https://user-images.githubusercontent.com/39317542/46303448-b9d3d500-c560-11e8-93b4-480639e2368a.png)
![screen shot 2018-10-01 at 9 48 02 am](https://user-images.githubusercontent.com/39317542/46303452-bd675c00-c560-11e8-943b-c6db675c6941.png)
![screen shot 2018-10-01 at 9 48 05 am](https://user-images.githubusercontent.com/39317542/46303462-c5bf9700-c560-11e8-949a-410b28a5dff4.png)
![screen shot 2018-10-01 at 9 48 29 am](https://user-images.githubusercontent.com/39317542/46303466-c8ba8780-c560-11e8-97d8-230aae6568a1.png)
![screen shot 2018-10-01 at 9 49 32 am](https://user-images.githubusercontent.com/39317542/46303476-cc4e0e80-c560-11e8-8a9c-6b830c76990b.png)
![screen shot 2018-10-01 at 9 50 13 am](https://user-images.githubusercontent.com/39317542/46303483-cf48ff00-c560-11e8-95ce-abe699b8fa7b.png)
![screen shot 2018-10-01 at 9 50 48 am](https://user-images.githubusercontent.com/39317542/46303488-d3751c80-c560-11e8-9fb4-64847d60c0bc.png)
![screen shot 2018-10-01 at 9 50 53 am](https://user-images.githubusercontent.com/39317542/46303490-d6700d00-c560-11e8-9142-39143da7db18.png)
![screen shot 2018-10-01 at 9 50 59 am](https://user-images.githubusercontent.com/39317542/46303493-d96afd80-c560-11e8-99d0-fee4722af636.png)

**Comment by mewa1024** [comment]
@vishwacsena change to 4.1? (I'll create new designs)

**Comment by mewa1024** [comment]
@vishwacsena Changing the flow as we discussed:
- empty state: "No chat files/transcripts were found in <default location, starting with location of .bot file>." plus text below that says "Choose a different location".
- not empty state: the chat/transcripts are listed, and the text "Choose a different location" always appears.
- user clicks "Choose a different location" and "Resource settings" modal appears.

![resources revised - 01](https://user-images.githubusercontent.com/39317542/46977438-1c5cc300-d081-11e8-8777-c7ba4ace8808.png)
![resources revised - 02](https://user-images.githubusercontent.com/39317542/46977444-1ff04a00-d081-11e8-8e79-7578219e125c.png)
![resources revised - 03](https://user-images.githubusercontent.com/39317542/46977452-2383d100-d081-11e8-8f66-5384102d76b5.png)
![resources revised - 04](https://user-images.githubusercontent.com/39317542/46977460-27175800-d081-11e8-8d7c-673aa4eb0450.png)
![resources revised - 05](https://user-images.githubusercontent.com/39317542/46977465-2aaadf00-d081-11e8-8110-6108f3b73f75.png)

**Comment by mewa1024** [comment]
@vishwacsena Is the wording "Choose a different location" for the chat files acceptable? We're actually searching multiple /resource folders...

**Comment by vishwacsena** [comment]
@mewa1024 this looks good to me. I like "Choose a different location" works.
