### ISSUE TITLE
Emulator: LUIS inspector is blank

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#946]
## Version
Mac: Emulator_OSX_v4.0.0-preview.40025_40380

## Describe the bug
LUIS inspector is not appearing.

## To Reproduce
1. Open a bot that is connected to LUIS.
2. Say something to the bot.
3. Click on the LUIS trace log item.
4. The LUIS inspector is blank, except for the Train and Publish buttons.

The deep link to the LUIS app from the sidebar is working, so it doesn't seem like a problem with the bot file. (You can see this in the screenshot below.)

## Expected behavior
LUIS inspector should show the JSON from LUIS plus the reassign intent control

## Screenshots
<img width="2560" alt="screen shot 2018-10-01 at 11 33 51 am 3" src="https://user-images.githubusercontent.com/39317542/46308480-9e6fc680-c56e-11e8-8898-39a5974f346f.png">

**Comment by justinwilaby** [comment]
fixed with #965
