### ISSUE TITLE
Emulator: modal design pass

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#949]
## Version
Mac: Emulator_OSX_v4.0.0-preview.40025_40380

## Describe the bug
Some modals do not follow design. For example the "New bot configuration" modal does not have the correct padding. Should be 24px on the left, top, and right, and 32px on the bottom. The space above the buttons should be 48px. 
**Design specs:** [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322428901/inspect](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/322428901/inspect)

## Screenshots
Incorrect modal:
![screen shot 2018-10-01 at 11 26 07 am](https://user-images.githubusercontent.com/39317542/46361352-3bd80280-c622-11e8-9659-3b2884f2e1f1.png)

[bug]

**Comment by justinwilaby** [comment]
This defect will also involve removing ui-fabrics Dialog component in favor of our own so we have more control over the design.

**Comment by justinwilaby** [comment]
This is ready for design review
