### ISSUE TITLE
Emulator - Edit > Select All menu item should be removed

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#950]
## Describe the bug
Moved from [VSO bug 24807](https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/24807)
"Select all" seems to select everything on the screen but otherwise does nothing. Let's remove the menu item.
Updated design spec: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/315600750/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/315600750/preview)

## To Reproduce
1. Go to 'Edit' > 'Select All menu' item.

[bug]

**Comment by justinwilaby** [comment]
Fixed by #966
