### ISSUE TITLE
Emulator: "Sign in with Azure" not working

### ISSUE THREAD

**Issue by dragonraelms** [Microsoft/BotFramework-Emulator#958]
## Version
Version 4.0.0-preview.40025

## Describe the bug
When using the "Sign in with Azure" option a window opens titled "Sign in to your account" but it remains white. You're also unable to close the window without using the taskbar in windows 10

## To Reproduce
Steps to reproduce the behaviour:
1. open the emulator
2. open the "welcome tab
3. click "sign in with your Azure Account
4.  in the popup that opens click the blue "sign in with Azure" button

You can also replicate this by adding a service
1. on services click the plus button
2. choose any service
3. click Sign in with Azure

## Expected behaviour
After clicking the "Sign in with Azure" button, I would expect a login prompt to appear asking me to enter my login credentials for Azure

## Screenshots

![image](https://user-images.githubusercontent.com/27970213/46538032-c5016a80-c8aa-11e8-9a6d-cd5514ea7075.png)

[bug]

**Comment by habuso** [comment]
Hi, yes I still have the same issue and a similar case was suddenly closed: 
https://github.com/Microsoft/BotFramework-Emulator/issues/861

The error appears also without using TFA.

**Comment by dividor** [comment]
Sign in with Azure doesn't work for me either. In my case, I am using MFA and get the attached error on confirming the code texted to me (works for all other services, just not in bot emulator).

<img width="247" alt="screen shot 2018-10-07 at 11 10 50 am" src="https://user-images.githubusercontent.com/8402586/46583267-fc465780-ca21-11e8-9ee7-1ba70734c8aa.png">

**Comment by justinwilaby** [comment]
This is a know issue and has been fixed with #924. MFA should work once nightly builds are re-established.
