### ISSUE TITLE
Locale changes in the emulator aren't set on messages sent to Bot

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#960]
## Version
4.0.0-preview.40025

## Describe the bug
The Emulator has a Locale setting in Emulator Settings. It seems to default system locale which is fine but setting to another locale (e.g. zh-hans) doesn't adjust what the emulator sends which is key for multi-language testing.

![image](https://user-images.githubusercontent.com/33519520/46576108-a917ca80-c977-11e8-8249-2436e6c33d79.png)

![image](https://user-images.githubusercontent.com/33519520/46576124-f85dfb00-c977-11e8-9aec-e6c268b27bb3.png)

## To Reproduce
1. Go to Emulator Settings
2. Change local to zh-hans (or any other locale)
3. Send a message to Bot and review Inspector to see that the locale hasn't changed.

## Expected behavior
Locale property on Activities is set to whatever is set in Emulator Settings.

[bug]

**Comment by justinwilaby** [comment]
Thank you for the submission. I do see a problem related to this defect and am working on a fix.

**Comment by justinwilaby** [comment]
Fixed with #960

**Comment by igor17400** [comment]
Hi there, I'm facing a similar issue in Mac Bot Framework Emulator version 4.7. I have configured for the chatbot to send messages in "pt-br", but in the emulator keeps reading the messages as locale: "en-us".

Is this a Mac version problem?

**Comment by tonyanziano** [comment]
@igor17400 can you please take a screenshot of your Emulator settings page and also post the activity payload in which you see an incorrect value for the locale?

The Emulator should correctly pass along the locale you have defined in the Emulator settings page:

![image](https://user-images.githubusercontent.com/3452012/76545269-b5defe80-6446-11ea-9265-bd878325b878.png)

![image](https://user-images.githubusercontent.com/3452012/76545330-d1e2a000-6446-11ea-88ce-7d9b4af6813f.png)

You can see that the Web Chat timestamps are now in Portugese
