### ISSUE TITLE
"Scripts" in Emulator should be called "Chats" or at the very least indicate that "Scripts" mean .chat files

### ISSUE THREAD

**Issue by Andrea-Orimoto** [Microsoft/BotFramework-Emulator#962]
## Version
4.0.0-preview.40025

## Describe the bug
The emulator UX references Scripts and Transcripts in the Resources tab, but while the term "Transcripts" is consistent, the term "Scripts" is not. It is not clear that "Scripts" refers to .chat files.

Please make it clear by either renaming it, or by providing a hint about .chat files

## To Reproduce
1. open the Resources tab
2. Click on the gear icon
3. In the resulting dialog you'll see "Locations for scripts"

## Expected behavior
1. It should say "Location for .chat files" or at least something like "Location for scripts (.chat files)"
2. Why is the word "Locations" plural? you're requested to provide a location, not many

[bug]

**Comment by mewa1024** [comment]
Addressed in #944
