### ISSUE TITLE
Remove 'reset' secret from emulator for 4.1

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#964]
See #871 

For 4.1, let's just drop the ability to be able to reset/ renew the secret from the emulator. Customers can be pointed to and use msbot cli.

**Comment by corinagum** [comment]
In progress

**Comment by mewa1024** [comment]
@vishwacsena This change effects the [Getting Started](https://github.com/Microsoft/BotFramework-Emulator/wiki/Getting-Started) doc too. We should remove: 

Choose 'Encrypt keys stored in Bot Configuration' if you would like your .bot file to be encrypted. This is recommended especially if you have keys and other sensitive information in your bot file. CAUTION: If you choose this option, Emulator will encrypt the .bot file and give you a key. You need to keep this key in a secure place (e.g. Azure Key Vault). See here to learn more about bot file encryption.

and update the screenshots and replace with a reference to the MsBot CLI. (We are not adding the reference to msbot cli to the modal.)

**Comment by corinagum** [comment]
Clarification after discussion with Vishwac: We are only removing the single button that says "Generate new secret key" from the bot creating dialog and settings editor.
