### ISSUE TITLE
Emulator: deep link to LUIS app after sign-in is inconsistent

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#973]
## Version
4.0.0-preview.40025

## Describe the bug
When I'm signed out of LUIS, a deep link to a LUIS app behaves differently. It lands on the home page, and after I sign in, it sometimes goes to My Apps or the Welcome page instead of the LUIS app.

## To Reproduce
1. Go to https://www.luis.ai/home.
2. Click on Sign in. Follow Sign in flow.
3. Sign out, but don't close browser.
4. Open Emulator.
5. Click on a LUIS app in Bot Explorer.
![screenshot 57](https://user-images.githubusercontent.com/39317542/46769014-2eb0b880-cc9f-11e8-9dce-989f2a40fcab.png)

6. A browser opens to luis.ai:
![screenshot 58](https://user-images.githubusercontent.com/39317542/46769027-3c663e00-cc9f-11e8-8e66-a382785c6aa0.png)

![screenshot 59](https://user-images.githubusercontent.com/39317542/46769038-46883c80-cc9f-11e8-8056-14eb8d2d8a9d.png)

7. Click on Sign in. Sign in screen appears.
![screenshot 60](https://user-images.githubusercontent.com/39317542/46769041-4b4cf080-cc9f-11e8-95ed-31ba4c5336dd.png)

8. You are signed in:
![screenshot 61](https://user-images.githubusercontent.com/39317542/46769128-9d8e1180-cc9f-11e8-931e-406e7ac8bbe8.png)

9. You are navigated to "My Apps" page, instead of the LUIS app in your bot.
![screenshot 62](https://user-images.githubusercontent.com/39317542/46769186-ca422900-cc9f-11e8-9943-143d93c3905b.png)
![screenshot 63](https://user-images.githubusercontent.com/39317542/46769192-cdd5b000-cc9f-11e8-91aa-6cfa37d27ab6.png)

## Expected behavior
You should land on the main page of the LUIS app that is listed in the Emulator. That happens if you are logged out and close your browser:

![screenshot 64](https://user-images.githubusercontent.com/39317542/46769259-12614b80-cca0-11e8-88f8-34f927004359.png)
![screenshot 65](https://user-images.githubusercontent.com/39317542/46769260-12614b80-cca0-11e8-84be-fd4010ea2d6f.png)
![screenshot 66](https://user-images.githubusercontent.com/39317542/46769261-12614b80-cca0-11e8-94fa-c39e3e08c3be.png)
![screenshot 67](https://user-images.githubusercontent.com/39317542/46769263-12f9e200-cca0-11e8-9fc4-2adc8ffe5079.png)
![screenshot 68](https://user-images.githubusercontent.com/39317542/46769264-12f9e200-cca0-11e8-86c8-fd0eb10da1e6.png)
![screenshot 69](https://user-images.githubusercontent.com/39317542/46769265-12f9e200-cca0-11e8-95d5-fa9dd0609caf.png)
![screenshot 70](https://user-images.githubusercontent.com/39317542/46769268-12f9e200-cca0-11e8-9523-e6ed12da8799.png)
![screenshot 71](https://user-images.githubusercontent.com/39317542/46769269-12f9e200-cca0-11e8-9ff5-07062f671d04.png)
![screenshot 72](https://user-images.githubusercontent.com/39317542/46769270-13927880-cca0-11e8-9082-a2916ce6b81a.png)
![screenshot 73](https://user-images.githubusercontent.com/39317542/46769271-13927880-cca0-11e8-97df-803e2056528e.png)
![screenshot 74](https://user-images.githubusercontent.com/39317542/46769272-13927880-cca0-11e8-81e3-b17ed36d4545.png)
![screenshot 75](https://user-images.githubusercontent.com/39317542/46769274-13927880-cca0-11e8-8125-54b18c1606f5.png)
![screenshot 76](https://user-images.githubusercontent.com/39317542/46769275-13927880-cca0-11e8-9c19-e3a4ff3ad853.png)
![screenshot 77](https://user-images.githubusercontent.com/39317542/46769276-13927880-cca0-11e8-8281-2359a12df477.png)

[bug]

**Comment by justinwilaby** [comment]
This is a known luis.ai issue. The emulator does not change the link structure based on the user's login. The luis portal handles the redirects and does not forward the user to the proper page after a successful login. This is why the user lands on the home page after logging in.

**Comment by justinwilaby** [comment]
To summarize, luis.ai is broken which requires the user to have logged in previously before the emulator links will work. There is nothing we can do on our end to workaround this issue and a defect should probably be raised on the luis side.

**Comment by mewa1024** [comment]
@justinwilaby Is this being tracked in the LUIS teams VSO?

**Comment by justinwilaby** [comment]
@mewa1024 - Not that I'm aware of. Do we have access to that project?
