### ISSUE TITLE
Sign out should sign me out and not remember me if I don't explicitly ask to be remembered

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/BotFramework-Emulator#976]
Steps:

- Sign in to Azure
- Do NOT choose "keep me signed in"
- Sign out
- Sign in again: my credentials are remembered and I'm automatically signed in, which I don't want. 

The "keep me signed in" checkbox is ignored and assumed always true perhaps?

**Comment by justinwilaby** [comment]
Thank for opening this discussion. 

The purpose of remember me is not to control whether or not the user is prompted for credentials the login tool. Its purpose is to prevent the user from having to login again if the emulator is closed and reopened at a later time. To implement what you describe, we would need two checkboxes, one to remember credentials in the sign in tool and another to remember the user's azure login at the emulator. The two are mutually exclusive and we currently implement only the latter.

**Comment by carlosscastro** [comment]
The current state doesn't feel right because if I sign in with my work account by mistake, then I sign out with the intention of signing in with my personal account, I cannot - the emulator simply chooses to sign me in to an account that i did not ask to be remembered and I don't want to sign in to.

I got frustrated because of this and I imagined our users might feel equally frustrated. Whether it meets the bar to get it fixed or not, I'm not sure! Lets dicuss in standup :)

**Comment by carlosscastro** [comment]
If we leave the checkboxes as they are, but sign out reprompts for which account you want to sign in, I would be fine with that. That is a correct behavior, and seems easy enough to fix.

**Comment by justinwilaby** [comment]
Yes, setting the `prompt=consent` seems to work. I can implement this

**Comment by carlosscastro** [comment]
@justinwilaby Sure! However when I find these things, I can help fix them too, no need for you to jump in, we can help :) I file it as issue so we get to discuss what the right thing is 👍

**Comment by justinwilaby** [comment]
Fixed with #977

**Comment by carlosscastro** [comment]
Reopening since our fix for this unfortunately was not what we need. We need to figure out what to do (probably will take a bit) and do it (probably a few lines of code, jsut hard to know which!).

**Comment by carlosscastro** [comment]
after we make ours a first party app, we may be able to have consent work and re-apply
