### ISSUE TITLE
Double Welcome Message after February 2nd update...

### ISSUE THREAD

**Issue by EmilioMeira** [Microsoft/BotFramework-Emulator#98]
Hi guys,

Great project, congrats! However, after the latest update I started to receive double welcome messages. I have a portion of code that send an initial message. Until yesterday, it was just sending ONE message upon ConversationUpdate. Now, for some reason it's generating TWO ConversationUpdates and generating two messages. 

Nothing has changed on the code, the only change was the update of the Emulator. 

Here's the code:

            else if (activity.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels

                ConnectorClient WelcomeConnector = new ConnectorClient(new Uri(activity.ServiceUrl));
                string WelcomeMessageString = "Hello, how can I help you? I'm here to provide some basic self-help in case " +
                    "you want to troubleshoot or setup something. In case I'm not THAT helpful (I'm just a humble BOT after all) " +
                    "you can always reach out to #it-support-team on Slack. ;) ";
                Activity WelcomeMessage = activity.CreateReply(WelcomeMessageString);
                WelcomeConnector.Conversations.ReplyToActivityAsync(WelcomeMessage);

            }

Here's the stack on the emulator:

[15:11:06] <- POST 200 Reply[message] Hello, how can I help you? I'm here to provide som... 
[15:11:10] <- POST 200 Reply[message] Hello, how can I help you? I'm here to provide som... 
[15:11:19] -> POST 200 [conversationUpdate] 
[15:11:19] -> POST 200 [conversationUpdate]

Thanks a lot,

Emilio Meira

**Comment by eanders-MS** [comment]
Hi @EmilioMeira This change was made in preparation for group conversation support. Previously, we sent a single `ConversationUpdate` with both bot and user in the `MembersAdded` list. Now we're sending them as separate `ConversationUpdate` activities. In a group conversation, users can come and go. Whenever this happens, your bot will receive corresponding `ConversationUpdate` activities.

To filter out your bot from the `ConversationUpdate.MembersAdded`:
```C#
case ActivityTypes.ConversationUpdate:
    IConversationUpdateActivity update = activity;
    var client = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials());
    if (update.MembersAdded != null && update.MembersAdded.Any())
    {
        foreach (var newMember in update.MembersAdded)
        {
            if (newMember.Id != activity.Recipient.Id)
            {
                var reply = activity.CreateReply();
                reply.Text = $"Welcome {newMember.Name}!";
                await client.Conversations.ReplyToActivityAsync(reply);
            }
        }
    }
    break;
```

**Comment by EmilioMeira** [comment]
@eanders-MS , I'm really sorry for the delay to respond! It worked like a charm, thanks a lot for the help.
