### ISSUE TITLE
Emulator doesn't set locale on conversationUpdate event

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-Emulator#980]
## Version
4.0.41221

## Describe the bug
the conversationUpdate message event sent by the Emulator doesn't set the Locale property. This then means any introduction message logic defaults to English rather than the desired language (set in the emulator)

## To Reproduce
1. Change locale in emulator to say zh-cn
2. Start a conversation with the Bot and observe that the incoming conversationUpdate event has locale set to Null

## Expected behavior
Locale populated on all messages/events sent from emulator

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/46900465-80716280-ce9a-11e8-8f32-5cedcdda47e9.png)

[bug]

**Comment by justinwilaby** [comment]
Fixed by #987
