### ISSUE TITLE
Emulator: Services pane should show help text whether or not services exist

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#981]
## Version
Mac - 4.0.0-preview-one-off
Windows: - 4.0.41221

## Describe the bug
Help text below the list of services should appear when services exist (not just when there are no services.)

## To Reproduce
1. Open a bot file.
2. Open the Services pane.
3. If your bot file has services, it will look like this:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/39317542/46900768-6add4800-ce5c-11e8-896c-3219d069f46c.png">

## Expected behavior
It should show this help text (which currently only appears when there are no services):
![image](https://user-images.githubusercontent.com/39317542/46900783-b09a1080-ce5c-11e8-82b9-2695a7ff7ac2.png)

There are extra spaces before the links and there is a period missing after "learn more about using services".

## Additional context
Design is on Invision: [https://microsoft-fuse-design.invisionapp.com/d/main#/console/15012340/317169752/preview](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15012340/317169752/preview)

![image](https://user-images.githubusercontent.com/39317542/46900796-0078d780-ce5d-11e8-899b-27fb58b269c9.png)

[bug]

**Comment by justinwilaby** [comment]
Fixed with #984
