### ISSUE TITLE
Emulator - service context menu, change wording from "Remove this service" to "Disconnect this service"

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#982]
## Describe the bug
We should change the wording of the context menu to remove a service from "Forget this service" to "Disconnect this service" to match the MsBot CLI command. 

## To Reproduce
1. Open a bot
2. Open a service pane
3. Right-click on a service:
![image](https://user-images.githubusercontent.com/39317542/46900993-2f447d00-ce60-11e8-9c0c-70ce94e42634.png) 
[bug]

**Comment by mewa1024** [comment]
@vishwacsena 4.1? "Forget" kind of implies that we're remembering your service out of convenience rather than because your bot depends on it. This wording is leftover from the Build version where the bot was not dependent on the .bot file.

**Comment by justinwilaby** [comment]
Fixed with #984
