### ISSUE TITLE
Emulator: Welcome screen, "My Bots" list needs a context menu

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#986]
## Describe the bug
The "My Bots" list on the Welcome page needs a context menu to allow users to move the file, open the file location, and forget the bot. (#505 Migrate v3 endpoints to v4 bots needs this feature--when we create .bot files for every v3 endpoint, we will be saving them in one location, so users will need to be able to find them and move them.)

## Screenshot of context menu
<img width="512" alt="image" src="https://user-images.githubusercontent.com/39317542/46972699-f8df4b80-d073-11e8-9f7f-e2288a389a4c.png">

**Comment by mewa1024** [comment]
@justinwilaby Can we open the file browser similar to a "Save As..." but with the text "Move to" instead?

**Comment by justinwilaby** [comment]
@mewa1024 - I can, yes. This will be the directory chooser used in the resources settings dialog with the text "Move to" in place of "Open"

**Comment by justinwilaby** [comment]
fixed with #992
