### ISSUE TITLE
v4.1 Emulator docs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#989]
We will add new docs under the Emulator Wiki section for the following topics - 
- V3 to V4 migration
	- One bot file per V3 bot configuration
	- Move created bot files to desired location
- Chat files and transcripts
	- What they are
	- Entry points
	- Settings
	- Save as transcript 
- Azure login flow
	- Login + stay signed in
	- Logout
	- Listing/ adding connected services through Azure login
- Service configuration
	- LUIS
	- QnA
	- Dispatch
	- Other service types
- Inspectors
	- LUIS - refine, train and publish
	- QnA Maker - refine, train and publish

**Comment by mewa1024** [comment]
Also edit Getting Started section since we are removing the encryption UI from the Emulator (#964 )

**Comment by vishwacsena** [comment]
Updated doc content is posted to the wiki - https://github.com/Microsoft/BotFramework-Emulator/wiki
