### ISSUE TITLE
Sending Conversation/conversationUpdate (user added) appears to make multiple calls. 

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/BotFramework-Emulator#991]
## Version
Bot Framework Emulator (V4 PREVIEW)
version: 4.0.0-preview.4025

## Describe the bug
Using the send activity ConversationUpdate add member seems to make 8 calls.
Remove member seems to make no calls. Same for other activity types.

Sending these activities would be very useful for bot developers.

## To Reproduce
1) got to top menu "Conversation"
2) sub menu "conversationUpdate" "user added"
3) observe main window - and see activities arriving in a test bot.

## Expected behavior
The appropriate activity exchanges (2 for member added for example.)

**Comment by justinwilaby** [comment]
I saw this today while testing other bits and it seems there is an issue with a middleware in the emulator or possibly with webchat somewhere. I'll investigate and determine risk and impact.
