### ISSUE TITLE
UI for 2FA

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-Emulator#997]
@mewa1024 has the design ready
@corinagum is going to implement
@justinwilaby is also coming to help for pair programming

**Comment by mewa1024** [comment]
[Spec for the "Select a certificate" modal:](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14863139/325383796/preview)
[Flow is here (look for the 2FA section](https://microsoft-fuse-design.invisionapp.com/d/main#/projects/prototypes/14863139)

**Comment by corinagum** [comment]
Test-writing in progress. :)
