### ISSUE TITLE
Remove <button> in <button> for selectable activity

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-Emulator#998]
This issue is required to fix in order to repro #750.

React is giving warning on "`<button>` nested inside `<button>`" is not a good DOM.

We need to revert the accessibility fix (that converted `<div onClick>` to `<button>`), and then use `tabIndex={ 0 }` instead.

After this one is fixed, we will look at #750.

Our long term plan is to redo the UX for select activity, so it don't have "`onClick` inside `onClick`". The reason is the discoverability of the button that is nested inside the the bigger `onClick`.

**Comment by compulim** [comment]
Tracking bug at Microsoft/BotFramework-WebChat#1205.

**Comment by corinagum** [comment]
in progress

**Comment by compulim** [comment]
Fixed in Microsoft/BotFramework-WebChat#1215.
