### ISSUE TITLE
Emulator - wrong font is appearing where Segoe UI Semibold used to be

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/BotFramework-Emulator#999]
## Version
version: 4.0.50000 - screens below are from Mac

## Describe the bug
With the latest version, it looks like the semibold font is being replaced by a serif font, and sometimes also appears at the wrong size.

## Screenshots
![image](https://user-images.githubusercontent.com/39317542/47107827-30c6ca00-d1ff-11e8-9d51-14e2b281ddbd.png)

## Additional context
Design specs are on Invision:
[Welcome page, light](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15205961/316621301/preview)
[Welcome page, dark](https://microsoft-fuse-design.invisionapp.com/d/main#/console/15205961/317594187/preview)
[Type styles](https://microsoft-fuse-design.invisionapp.com/d/main#/console/14907902/310002580/preview)

[bug]

**Comment by justinwilaby** [comment]
This is fixed with #994
